In [187]:
import xlrd
import pandas as pd
import pprint

## SNAP 2019

In [398]:
book = xlrd.open_workbook('SNAP/FY19.xls')

In [399]:
for sheet in book.sheets():
    print (sheet.name)

NERO
MARO
SERO
MWRO
SWRO
MPRO
WRO
US Summary

### NERO

In [400]:
sheet = book.sheet_by_name('NERO')

In [401]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 PUBLIC - Supplemental Nutrition Assistance Program', '', '', '', '', '07/01/2020']
1 ['SNAP Monthly State Participation and Benefit Summary - Public Data, Fiscal Year 2019', '', '', '', '', '']
2 [' ', '', '', '', '', '']
3 ['', '', '', '', '', '']
4 [' ', 'Total 1/', '', '', '', '']
5 ['Fiscal Year and Month', 'Participation 1/', '', 'Cost', 'Cost Per', '']
6 ['', 'Household', 'Persons', '', 'Household', 'Persons']
7 ['Connecticut', '', '', '', '', '']
8 ['Oct 2018', 217619.0, 376447.0, 50630409.0, 232.6562, 134.4955]
9 ['Nov 2018', 216134.0, 374230.0, 50141937.0, 231.9947, 133.987]
10 ['Dec 2018', 215283.0, 372079.0, 49717875.0, 230.9419, 133.6218]
11 ['Jan 2019 /2', 215132.0, 371393.0, 96027525.0, 446.3656, 258.5604]
12 ['Feb 2019 /2', 19891.0, 39270.0, 1894161.0, 95.227, 48.2343]
13 ['Mar 2019', 213248.0, 366453.0, 48298979.0, 226.4921, 131.8013]
14 ['Apr 2019', 212331.0, 364182.0, 47900307.0, 225.5926, 131.5285]
15 ['May 2019', 212602.0, 364456.0, 47981032.0, 225.6848, 131.6511]
16 ['Jun 2019', 212355.0, 363578.0, 47921516.0, 225.667, 131.8053]
17 ['Jul 2019', 212611.0, 364092.0, 48021204.0, 225.8642, 131.893]
18 ['Aug 2019', 213062.0, 364704.0, 48102772.0, 225.7689, 131.8954]
19 ['Sep 2019', 212861.0, 364474.0, 48080883.0, 225.8792, 131.9186]
20 ['Total', 197760.75, 340446.5, 584718600.0, 246.39140833333335, 143.125425]
21 ['', '', '', '', '', '']
22 ['Maine', '', '', '', '', '']
23 ['Oct 2018', 86368.0, 159320.0, 17383023.0, 201.2669, 109.1076]
24 ['Nov 2018', 85990.0, 158401.0, 17238325.0, 200.4689, 108.8271]
25 ['Dec 2018', 85243.0, 157026.0, 17087989.0, 200.4621, 108.8227]
26 ['Jan 2019 /2', 85308.0, 157160.0, 32575311.0, 381.8553, 207.2748]
27 ['Feb 2019 /2', 5313.0, 10078.0, 1148278.0, 216.1261, 113.9391]
28 ['Mar 2019', 84826.0, 155564.0, 16803461.0, 198.0933, 108.0164]
29 ['Apr 2019', 85139.0, 155769.0, 16954141.0, 199.1348, 108.8416]
30 ['May 2019', 85445.0, 156166.0, 17046903.0, 199.5073, 109.1589]
31 ['Jun 2019', 85564.0, 156232.0, 16926406.0, 197.8216, 108.3415]
32 ['Jul 2019', 85292.0, 155749.0, 16927388.0, 198.464, 108.6838]
33 ['Aug 2019', 85862.0, 156079.0, 16888414.0, 196.6925, 108.2043]
34 ['Sep 2019', 85996.0, 155648.0, 16650888.0, 193.624, 106.9778]
35 ['Total', 78862.1667, 144432.6667, 203630527.0, 215.17555833333333, 117.48873333333333]
36 ['', '', '', '', '', '']
37 ['Massachusetts', '', '', '', '', '']
38 ['Oct 2018', 451379.0, 768374.0, 97290212.0, 215.54, 126.6183]
39 ['Nov 2018', 451033.0, 767420.0, 96374866.0, 213.6759, 125.5829]
40 ['Dec 2018', 448876.0, 762672.0, 95654353.0, 213.0975, 125.42]
41 ['Jan 2019 /2', 447729.0, 759254.0, 182023690.0, 406.5488, 239.7402]
42 ['Feb 2019 /2', 49078.0, 83104.0, 8982276.0, 183.0204, 108.0848]
43 ['Mar 2019', 446236.0, 754623.0, 92767066.0, 207.8879, 122.9317]
44 ['Apr 2019', 445664.0, 752757.0, 92116494.0, 206.6949, 122.3722]
45 ['May 2019', 446143.0, 752862.0, 92548407.0, 207.4411, 122.9288]
46 ['Jun 2019', 447612.0, 754843.0, 92589386.0, 206.8519, 122.6605]
47 ['Jul 2019', 450879.0, 759398.0, 93155637.0, 206.609, 122.6704]
48 ['Aug 2019', 453658.0, 762684.0, 94138216.0, 207.5092, 123.4302]
49 ['Sep 2019', 455252.0, 764203.0, 93507863.0, 205.398, 122.36]
50 ['Total', 416128.25, 703516.1667, 1131148466.0, 226.52240833333335, 133.9875]
51 ['', '', '', '', '', '']
52 ['New Hampshire', '', '', '', '', '']
53 ['Oct 2018', 40944.0, 79727.0, 8122185.0, 198.373, 101.875]
54 ['Nov 2018', 40803.0, 79137.0, 8015584.0, 196.4459, 101.2874]
55 ['Dec 2018', 40376.0, 78053.0, 7960721.0, 197.1647, 101.9912]
56 ['Jan 2019 /2', 40708.0, 78653.0, 15326545.0, 376.4996, 194.8628]
57 ['Feb 2019 /2', 2880.0, 5614.0, 494774.0, 171.7965, 88.1322]
58 ['Mar 2019', 39972.0, 76762.0, 7758137.0, 194.0893, 101.0674]
59 ['Apr 2019', 39760.0, 76113.0, 7731320.0, 194.4497, 101.5769]
60 ['May 2019', 39479.0, 75411.0, 7636791.0, 193.4393, 101.2689]
61 ['Jun 2019', 39015.0, 74354.0, 7516813.0, 192.6647, 101.0949]
62 ['Jul 2019', 38754.0, 73837.0, 7435786.0, 191.8714, 100.7054]
63 ['Aug 2019', 38777.0, 73775.0, 7454121.0, 192.2305, 101.0386]
64 ['Sep 2019', 38747.0, 73506.0, 7436414.0, 191.9223, 101.1674]
65 ['Total', 36684.5833, 70411.8333, 92889191.0, 211.00869166666666, 109.93558333333333]
66 ['', '', '', '', '', '']
67 ['New York', '', '', '', '', '']
68 ['Oct 2018', 1536243.0, 2727462.0, 373759666.0, 243.2946, 137.0357]
69 ['Nov 2018', 1527245.0, 2706697.0, 369873312.0, 242.1834, 136.6512]
70 ['Dec 2018', 1527054.0, 2702602.0, 369977403.0, 242.2818, 136.8967]
71 ['Jan 2019 /2', 1531428.0, 2705107.0, 703444905.0, 459.3392, 260.0433]
72 ['Feb 2019 /2', 1526845.0, 2690578.0, 26916871.0, 17.6291, 10.0041]
73 ['Mar 2019', 1522410.0, 2681717.0, 362010122.0, 237.7875, 134.9919]
74 ['Apr 2019', 1514547.0, 2662511.0, 359045704.0, 237.0647, 134.8523]
75 ['May 2019', 1505591.0, 2642450.0, 358120510.0, 237.8604, 135.5259]
76 ['Jun 2019', 1496844.0, 2623177.0, 355193679.0, 237.2951, 135.4059]
77 ['Jul 2019', 1492844.0, 2613091.0, 354891169.0, 237.7282, 135.8128]
78 ['Aug 2019', 1486402.0, 2598826.0, 354587072.0, 238.554, 136.4413]
79 ['Sep 2019', 1481195.0, 2586186.0, 351797553.0, 237.5093, 136.0295]
80 ['Total', 1512387.3333, 2661700.3333, 4339617966.0, 239.11521666666667, 135.86609166666668]
81 ['', '', '', '', '', '']
82 ['Rhode Island', '', '', '', '', '']
83 ['Oct 2018', 93735.0, 157948.0, 21593908.0, 230.3719, 136.7153]
84 ['Nov 2018', 94543.0, 158750.0, 20917736.0, 221.251, 131.7653]
85 ['Dec 2018', 93709.0, 157079.0, 21488652.0, 229.3126, 136.8016]
86 ['Jan 2019 /2', 92394.0, 155099.0, 39037563.0, 422.5119, 251.6945]
87 ['Feb 2019 /2', 9771.0, 20281.0, 1894746.0, 193.9153, 93.4247]
88 ['Mar 2019', 90976.0, 151822.0, 20259048.0, 222.6856, 133.4395]
89 ['Apr 2019', 90212.0, 150288.0, 20063409.0, 222.4029, 133.4997]
90 ['May 2019', 90057.0, 149735.0, 19946267.0, 221.4849, 133.2105]
91 ['Jun 2019', 89668.0, 148929.0, 19785946.0, 220.6578, 132.8549]
92 ['Jul 2019', 89808.0, 148914.0, 19826007.0, 220.7599, 133.1373]
93 ['Aug 2019', 89278.0, 148087.0, 19723052.0, 220.9173, 133.1856]
94 ['Sep 2019', 89192.0, 147857.0, 19687230.0, 220.7287, 133.1505]
95 ['Total', 84445.25, 141232.4167, 244223564.0, 241.0078, 144.10263333333333]
96 ['', '', '', '', '', '']
97 ['Vermont', '', '', '', '', '']
98 ['Oct 2018', 40158.0, 71176.0, 8635017.0, 215.0261, 121.3192]
99 ['Nov 2018', 40223.0, 71400.0, 8615248.0, 214.1871, 120.6617]
100 ['Dec 2018', 40295.0, 71494.0, 8653570.0, 214.7554, 121.0391]
101 ['Jan 2019 /2', 62010.0, 119143.0, 16060274.0, 258.9949, 134.7983]
102 ['Feb 2019 /2', 5609.0, 9920.0, 1058444.0, 188.7046, 106.698]
103 ['Mar 2019', 39748.0, 69854.0, 8424871.0, 211.9571, 120.6069]
104 ['Apr 2019', 39351.0, 68932.0, 8216475.0, 208.7996, 119.1968]
105 ['May 2019', 39081.0, 68257.0, 8244917.0, 210.97, 120.7923]
106 ['Jun 2019', 38836.0, 67606.0, 8171043.0, 210.3987, 120.8627]
107 ['Jul 2019', 38594.0, 67136.0, 8045744.0, 208.4714, 119.8425]
108 ['Aug 2019', 38592.0, 67195.0, 8112482.0, 210.2115, 120.7304]
109 ['Sep 2019', 38579.0, 67209.0, 8010589.0, 207.6412, 119.1892]
110 ['Total', 38423.0, 68276.8333, 100248674.0, 217.42331666666666, 122.35565]
111 ['', '', '', '', '', '']
112 ['Virgin Islands', '', '', '', '', '']
113 ['Oct 2018', 14166.0, 28683.0, 4936176.0, 348.4524, 172.0941]
114 ['Nov 2018', 13384.0, 27069.0, 4270501.0, 319.0751, 157.7635]
115 ['Dec 2018', 12603.0, 25662.0, 4040818.0, 320.6235, 157.4631]
116 ['Jan 2019 /2', 11964.0, 24527.0, 7539447.0, 630.1778, 307.3938]
117 ['Feb 2019 /2', 822.0, 1726.0, 193425.0, 235.3102, 112.0655]
118 ['Mar 2019', 10450.0, 21387.0, 3553182.0, 340.0174, 166.1375]
119 ['Apr 2019', 9862.0, 20381.0, 3307427.0, 335.3708, 162.2799]
120 ['May 2019', 10118.0, 20934.0, 3363794.0, 332.4564, 160.6857]
121 ['Jun 2019', 10194.0, 21099.0, 3398399.0, 333.3725, 161.0692]
122 ['Jul 2019', 10339.0, 21370.0, 3449351.0, 333.6252, 161.4109]
123 ['Aug 2019', 10395.0, 21511.0, 3478700.0, 334.6513, 161.7173]
124 ['Sep 2019', 10439.0, 21623.0, 3508023.0, 336.0497, 162.2357]
125 ['Total', 10394.6667, 21331.0, 45039243.0, 361.0765333333333, 175.95379166666666]
126 ['', '', '', '', '', '']
127 ['NERO', '', '', '', '', '']
128 ['Oct 2018', 2480612.0, 4369137.0, 582350596.0, 234.7609, 133.2873]
129 ['Nov 2018', 2469355.0, 4343104.0, 575447509.0, 233.0356, 132.4968]
130 ['Dec 2018', 2463439.0, 4326667.0, 574581381.0, 233.2436, 132.8]
131 ['Jan 2019 /2', 2486673.0, 4370336.0, 1092035260.0, 439.1552, 249.8744]
132 ['Feb 2019 /2', 1620209.0, 2860571.0, 42582975.0, 26.2824, 14.8862]
133 ['Mar 2019', 2447866.0, 4278182.0, 559874866.0, 228.7196, 130.8675]
134 ['Apr 2019', 2436866.0, 4250933.0, 555335277.0, 227.8891, 130.6384]
135 ['May 2019', 2428516.0, 4230271.0, 554888621.0, 228.4888, 131.1709]
136 ['Jun 2019', 2420088.0, 4209818.0, 551503188.0, 227.8856, 131.004]
137 ['Jul 2019', 2419121.0, 4203587.0, 551752286.0, 228.0797, 131.2575]
138 ['Aug 2019', 2416026.0, 4192861.0, 552484829.0, 228.675, 131.768]
139 ['Sep 2019', 2412261.0, 4180706.0, 548679443.0, 227.4544, 131.2409]
140 ['Total', 2375086.0, 4151347.75, 6741516231.0, 236.53586666666666, 135.32786666666667]
141 ['', '', '', '', '', '']
142 ['Footnotes:', '', '', '', '', '']
143 ['1. "Total Participation" (Households and Persons) excludes the counts of participation for Disaster Supplements and Replacements. The participation data reflected in those categories are a subset of the "Regular Ongoing" participation category.', '', '', '', '', '']
144 ["2. Due to the partial Federal government shutdown, most of the February 2019 SNAP benefits were issued early in the month of January 2019.  This was done to ensure SNAP recipients would receive their February 2019 benefits in a timely manner.  As a result, January 2019's benefits will show a significant increase over the previous month and February 2019's benefits will show significantly less than January 2019.", '', '', '', '', '']

In [402]:
snap_data_2019 = {}
for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [x for x in range(7, sheet.nrows, 15)]:
        #for the rows that have the state names
        state = row[0]
        if state == 'NERO':
            break
        else:
            continue         
    if i in [x for x in range(20, sheet.nrows, 15)]:
        
        snap_data_2019[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

In [403]:
pprint.pprint(snap_data_2019)

{'Connecticut': {'cost_by_household': 246.39140833333335,
                 'cost_by_individual': 143.125425,
                 'household_participation': 197760.75,
                 'individual_participation': 340446.5,
                 'total_cost': 584718600.0},
 'Maine': {'cost_by_household': 215.17555833333333,
           'cost_by_individual': 117.48873333333333,
           'household_participation': 78862.1667,
           'individual_participation': 144432.6667,
           'total_cost': 203630527.0},
 'Massachusetts': {'cost_by_household': 226.52240833333335,
                   'cost_by_individual': 133.9875,
                   'household_participation': 416128.25,
                   'individual_participation': 703516.1667,
                   'total_cost': 1131148466.0},
 'New Hampshire': {'cost_by_household': 211.00869166666666,
                   'cost_by_individual': 109.93558333333333,
                   'household_participation': 36684.5833,
                   'individual_participation': 70411.8333,
                   'total_cost': 92889191.0},
 'New York': {'cost_by_household': 239.11521666666667,
              'cost_by_individual': 135.86609166666668,
              'household_participation': 1512387.3333,
              'individual_participation': 2661700.3333,
              'total_cost': 4339617966.0},
 'Rhode Island': {'cost_by_household': 241.0078,
                  'cost_by_individual': 144.10263333333333,
                  'household_participation': 84445.25,
                  'individual_participation': 141232.4167,
                  'total_cost': 244223564.0},
 'Vermont': {'cost_by_household': 217.42331666666666,
             'cost_by_individual': 122.35565,
             'household_participation': 38423.0,
             'individual_participation': 68276.8333,
             'total_cost': 100248674.0},
 'Virgin Islands': {'cost_by_household': 361.0765333333333,
                    'cost_by_individual': 175.95379166666666,
                    'household_participation': 10394.6667,
                    'individual_participation': 21331.0,
                    'total_cost': 45039243.0}}

### MARO

In [404]:
sheet = book.sheet_by_name('MARO')

In [405]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 PUBLIC - Supplemental Nutrition Assistance Program', '', '', '', '', '07/01/2020']
1 ['SNAP Monthly State Participation and Benefit Summary - Public Data, Fiscal Year 2019', '', '', '', '', '']
2 [' ', '', '', '', '', '']
3 ['', '', '', '', '', '']
4 [' ', 'Total 1/', '', '', '', '']
5 ['Fiscal Year and Month', 'Participation 1/', '', 'Cost', 'Cost Per', '']
6 ['', 'Household', 'Persons', '', 'Household', 'Persons']
7 ['Delaware', '', '', '', '', '']
8 ['Oct 2018', 66592.0, 136252.0, 15919691.0, 239.0631, 116.8401]
9 ['Nov 2018', 66006.0, 135049.0, 15833430.0, 239.8786, 117.2421]
10 ['Dec 2018', 65572.0, 134116.0, 15366657.0, 234.3478, 114.5774]
11 ['Jan 2019 /2', 67688.0, 138562.0, 29724419.0, 439.1387, 214.5207]
12 ['Feb 2019 /2', 4591.0, 9847.0, 1058418.0, 230.5419, 107.4863]
13 ['Mar 2019', 63714.0, 130125.0, 14834373.0, 232.8275, 114.0009]
14 ['Apr 2019', 62920.0, 128321.0, 14553838.0, 231.307, 113.4174]
15 ['May 2019', 62535.0, 127545.0, 14483248.0, 231.6023, 113.554]
16 ['Jun 2019', 61742.0, 125758.0, 14314398.0, 231.8421, 113.8249]
17 ['Jul 2019', 60991.0, 124488.0, 14062844.0, 230.5724, 112.9655]
18 ['Aug 2019', 61275.0, 125239.0, 14243888.0, 232.4584, 113.7336]
19 ['Sep 2019', 59840.0, 122139.0, 13743381.0, 229.6688, 112.5225]
20 ['Total', 58622.1667, 119786.75, 178138585.0, 253.22984166666666, 123.92758333333333]
21 ['', '', '', '', '', '']
22 ['District of Columbia', '', '', '', '', '']
23 ['Oct 2018', 67986.0, 119885.0, 15249635.0, 224.3055, 127.2022]
24 ['Nov 2018', 67629.0, 113646.0, 15141978.0, 223.8977, 133.2381]
25 ['Dec 2018', 67028.0, 111266.0, 15008526.0, 223.9143, 134.8887]
26 ['Jan 2019 /2', 65819.0, 109580.0, 27064549.0, 411.1966, 246.9844]
27 ['Feb 2019 /2', 59489.0, 99991.0, 13618339.0, 228.922, 136.1956]
28 ['Mar 2019', 6196.0, 10249.0, 1790034.0, 288.9015, 174.6545]
29 ['Apr 2019', 64035.0, 106298.0, 13931081.0, 217.5542, 131.0568]
30 ['May 2019', 64060.0, 106340.0, 14257641.0, 222.567, 134.076]
31 ['Jun 2019', 64202.0, 106575.0, 13880687.0, 216.2033, 130.2434]
32 ['Jul 2019', 64691.0, 109146.0, 14051870.0, 217.2152, 128.7438]
33 ['Aug 2019', 65330.0, 110383.0, 13903720.0, 212.8229, 125.9589]
34 ['Sep 2019', 65410.0, 111402.0, 14180853.0, 216.7995, 127.2944]
35 ['Total', 60156.25, 101230.0833, 172078913.0, 238.37771666666666, 141.6566]
36 ['', '', '', '', '', '']
37 ['Maryland', '', '', '', '', '']
38 ['Oct 2018', 341809.0, 637966.0, 76063984.0, 222.5336, 119.2289]
39 ['Nov 2018', 339964.0, 633655.0, 75280214.0, 221.4358, 118.8032]
40 ['Dec 2018', 337043.0, 626738.0, 83749092.0, 248.4819, 133.627]
41 ['Jan 2019 /2', 337895.0, 627002.0, 137276660.0, 406.2702, 218.9413]
42 ['Feb 2019 /2', 16327.0, 30774.0, 8885916.0, 544.2467, 288.7475]
43 ['Mar 2019', 333753.0, 616315.0, 72482928.0, 217.1754, 117.607]
44 ['Apr 2019', 332146.0, 612581.0, 70829362.0, 213.2477, 115.6245]
45 ['May 2019', 331601.0, 611598.0, 70722782.0, 213.2767, 115.6361]
46 ['Jun 2019', 330887.0, 610677.0, 70642858.0, 213.4954, 115.6796]
47 ['Jul 2019', 331092.0, 610523.0, 70581258.0, 213.1772, 115.6079]
48 ['Aug 2019', 333459.0, 615096.0, 71368280.0, 214.0242, 116.0279]
49 ['Sep 2019', 332027.0, 612399.0, 70766332.0, 213.1343, 115.5559]
50 ['Total', 308166.9167, 570443.6667, 878649666.0, 237.601125, 128.35764166666667]
51 ['', '', '', '', '', '']
52 ['New Jersey', '', '', '', '', '']
53 ['Oct 2018', 366108.0, 731983.0, 82681979.0, 225.8404, 112.9561]
54 ['Nov 2018', 363398.0, 725753.0, 81844482.0, 225.22, 112.7718]
55 ['Dec 2018', 361021.0, 721400.0, 81019453.0, 224.4176, 112.3086]
56 ['Jan 2019 /2', 363628.0, 728496.0, 153478098.0, 422.0745, 210.678]
57 ['Feb 2019 /2', 15504.0, 30804.0, 3390934.0, 218.7135, 110.081]
58 ['Mar 2019', 353257.0, 703228.0, 77637945.0, 219.7775, 110.4022]
59 ['Apr 2019', 350174.0, 695964.0, 79319308.0, 226.514, 113.9704]
60 ['May 2019', 350208.0, 695525.0, 79447283.0, 226.8574, 114.2264]
61 ['Jun 2019', 349069.0, 692664.0, 79053572.0, 226.4698, 114.1298]
62 ['Jul 2019', 347341.0, 690006.0, 78664779.0, 226.4771, 114.0059]
63 ['Aug 2019', 347963.0, 690789.0, 78934003.0, 226.846, 114.2664]
64 ['Sep 2019', 344237.0, 682918.0, 78086860.0, 226.8404, 114.343]
65 ['Total', 325992.3333, 649127.5, 953558696.0, 243.75795833333333, 122.41543333333334]
66 ['', '', '', '', '', '']
67 ['Pennsylvania', '', '', '', '', '']
68 ['Oct 2018', 953070.0, 1791564.0, 213898255.0, 224.4308, 119.3919]
69 ['Nov 2018', 949366.0, 1780497.0, 211527962.0, 222.8097, 118.8028]
70 ['Dec 2018', 945533.0, 1769604.0, 210931556.0, 223.0822, 119.197]
71 ['Jan 2019 /2', 945432.0, 1768620.0, 408749990.0, 432.342, 231.1124]
72 ['Feb 2019 /2', 93193.0, 196429.0, 12061046.0, 129.4201, 61.4016]
73 ['Mar 2019', 939194.0, 1748715.0, 207129488.0, 220.5396, 118.4467]
74 ['Apr 2019', 938729.0, 1747214.0, 205014079.0, 218.3954, 117.3377]
75 ['May 2019', 937782.0, 1741489.0, 218072554.0, 232.5408, 125.2219]
76 ['Jun 2019', 938895.0, 1741026.0, 211652374.0, 225.4271, 121.5676]
77 ['Jul 2019', 941757.0, 1746086.0, 204147534.0, 216.773, 116.9172]
78 ['Aug 2019', 947660.0, 1755663.0, 207288802.0, 218.7375, 118.0687]
79 ['Sep 2019', 943248.0, 1744769.0, 203222944.0, 215.4502, 116.4756]
80 ['Total', 872821.5833, 1627639.6667, 2513696584.0, 239.997175, 128.69845833333332]
81 ['', '', '', '', '', '']
82 ['Puerto Rico', '', '', '', '', '']
83 [' No data found.', '', '', '', '', '']
84 ['Virginia', '', '', '', '', '']
85 ['Oct 2018', 345364.0, 715559.0, 85529568.0, 247.6505, 119.5283]
86 ['Nov 2018', 345334.0, 716022.0, 82548894.0, 239.0407, 115.2882]
87 ['Dec 2018', 344002.0, 711323.0, 82662078.0, 240.2953, 116.2089]
88 ['Jan 2019 /2', 344477.0, 709491.0, 161264927.0, 468.1443, 227.2966]
89 ['Feb 2019 /2', 49677.0, 102350.0, 11995411.0, 241.4681, 117.1999]
90 ['Mar 2019', 343426.0, 704973.0, 83328226.0, 242.6381, 118.2006]
91 ['Apr 2019', 342330.0, 701304.0, 82382972.0, 240.6537, 117.4711]
92 ['May 2019', 341866.0, 700353.0, 82609842.0, 241.6439, 117.9546]
93 ['Jun 2019', 341854.0, 700418.0, 82841080.0, 242.3288, 118.2738]
94 ['Jul 2019', 341153.0, 698607.0, 82140202.0, 240.7723, 117.5771]
95 ['Aug 2019', 341570.0, 699837.0, 82725764.0, 242.1927, 118.2072]
96 ['Sep 2019', 341208.0, 698350.0, 82351202.0, 241.3519, 117.9225]
97 ['Total', 318521.75, 654882.25, 1002380166.0, 262.2479666666667, 127.55221666666667]
98 ['', '', '', '', '', '']
99 ['West Virginia', '', '', '', '', '']
100 ['Oct 2018', 162244.0, 311863.0, 34366157.0, 211.8177, 110.1963]
101 ['Nov 2018', 161116.0, 309086.0, 33755454.0, 209.5103, 109.2106]
102 ['Dec 2018', 159867.0, 305468.0, 33455614.0, 209.2715, 109.5225]
103 ['Jan 2019 /2', 163826.0, 314042.0, 63407313.0, 387.0406, 201.9071]
104 ['Feb 2019 /2', 10927.0, 22907.0, 3589182.0, 328.4691, 156.6849]
105 ['Mar 2019', 159568.0, 303538.0, 32744189.0, 205.2052, 107.8751]
106 ['Apr 2019', 158856.0, 302044.0, 32506593.0, 204.6293, 107.622]
107 ['May 2019', 159008.0, 302274.0, 32463803.0, 204.1646, 107.3986]
108 ['Jun 2019', 159975.0, 304345.0, 32595506.0, 203.7537, 107.1005]
109 ['Jul 2019', 159699.0, 303102.0, 32797125.0, 205.3684, 108.2049]
110 ['Aug 2019', 160602.0, 305640.0, 33073144.0, 205.9323, 108.2095]
111 ['Sep 2019', 161612.0, 307638.0, 33145870.0, 205.0954, 107.7431]
112 ['Total', 148108.3333, 282662.25, 397899950.0, 223.87889166666668, 117.30724166666667]
113 ['', '', '', '', '', '']
114 ['MARO', '', '', '', '', '']
115 ['Oct 2018', 2303173.0, 4445072.0, 523709269.0, 227.386, 117.8179]
116 ['Nov 2018', 2292813.0, 4413708.0, 515932414.0, 225.0216, 116.8932]
117 ['Dec 2018', 2280066.0, 4379915.0, 522192976.0, 229.0254, 119.2245]
118 ['Jan 2019 /2', 2288765.0, 4395793.0, 980965956.0, 428.6006, 223.1602]
119 ['Feb 2019 /2', 249708.0, 493102.0, 54599246.0, 218.6524, 110.7261]
120 ['Mar 2019', 2199108.0, 4217143.0, 489947183.0, 222.7936, 116.1799]
121 ['Apr 2019', 2249190.0, 4293726.0, 498537233.0, 221.6519, 116.1083]
122 ['May 2019', 2247060.0, 4285124.0, 512057153.0, 227.8787, 119.4965]
123 ['Jun 2019', 2246624.0, 4281463.0, 504980475.0, 224.773, 117.9458]
124 ['Jul 2019', 2246724.0, 4281958.0, 496445612.0, 220.9642, 115.9389]
125 ['Aug 2019', 2257859.0, 4302647.0, 501537601.0, 222.1297, 116.5649]
126 ['Sep 2019', 2247582.0, 4279615.0, 495497442.0, 220.458, 115.7808]
127 ['Total', 2092389.3333, 4005772.1667, 6096402560.0, 242.800675, 126.825375]
128 ['', '', '', '', '', '']
129 ['Footnotes:', '', '', '', '', '']
130 ['1. "Total Participation" (Households and Persons) excludes the counts of participation for Disaster Supplements and Replacements. The participation data reflected in those categories are a subset of the "Regular Ongoing" participation category.', '', '', '', '', '']
131 ["2. Due to the partial Federal government shutdown, most of the February 2019 SNAP benefits were issued early in the month of January 2019.  This was done to ensure SNAP recipients would receive their February 2019 benefits in a timely manner.  As a result, January 2019's benefits will show a significant increase over the previous month and February 2019's benefits will show significantly less than January 2019.", '', '', '', '', '']

In [406]:

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,84,99,114,129]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MARO':
            break
        else:
            continue       
    if i in [20,35,50,65,80,97,112]:
        
        snap_data_2019[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

In [407]:
pprint.pprint(snap_data_2019)

{'Connecticut': {'cost_by_household': 246.39140833333335,
                 'cost_by_individual': 143.125425,
                 'household_participation': 197760.75,
                 'individual_participation': 340446.5,
                 'total_cost': 584718600.0},
 'Delaware': {'cost_by_household': 253.22984166666666,
              'cost_by_individual': 123.92758333333333,
              'household_participation': 58622.1667,
              'individual_participation': 119786.75,
              'total_cost': 178138585.0},
 'District of Columbia': {'cost_by_household': 238.37771666666666,
                          'cost_by_individual': 141.6566,
                          'household_participation': 60156.25,
                          'individual_participation': 101230.0833,
                          'total_cost': 172078913.0},
 'Maine': {'cost_by_household': 215.17555833333333,
           'cost_by_individual': 117.48873333333333,
           'household_participation': 78862.1667,
           'individual_participation': 144432.6667,
           'total_cost': 203630527.0},
 'Maryland': {'cost_by_household': 237.601125,
              'cost_by_individual': 128.35764166666667,
              'household_participation': 308166.9167,
              'individual_participation': 570443.6667,
              'total_cost': 878649666.0},
 'Massachusetts': {'cost_by_household': 226.52240833333335,
                   'cost_by_individual': 133.9875,
                   'household_participation': 416128.25,
                   'individual_participation': 703516.1667,
                   'total_cost': 1131148466.0},
 'New Hampshire': {'cost_by_household': 211.00869166666666,
                   'cost_by_individual': 109.93558333333333,
                   'household_participation': 36684.5833,
                   'individual_participation': 70411.8333,
                   'total_cost': 92889191.0},
 'New Jersey': {'cost_by_household': 243.75795833333333,
                'cost_by_individual': 122.41543333333334,
                'household_participation': 325992.3333,
                'individual_participation': 649127.5,
                'total_cost': 953558696.0},
 'New York': {'cost_by_household': 239.11521666666667,
              'cost_by_individual': 135.86609166666668,
              'household_participation': 1512387.3333,
              'individual_participation': 2661700.3333,
              'total_cost': 4339617966.0},
 'Pennsylvania': {'cost_by_household': 239.997175,
                  'cost_by_individual': 128.69845833333332,
                  'household_participation': 872821.5833,
                  'individual_participation': 1627639.6667,
                  'total_cost': 2513696584.0},
 'Rhode Island': {'cost_by_household': 241.0078,
                  'cost_by_individual': 144.10263333333333,
                  'household_participation': 84445.25,
                  'individual_participation': 141232.4167,
                  'total_cost': 244223564.0},
 'Vermont': {'cost_by_household': 217.42331666666666,
             'cost_by_individual': 122.35565,
             'household_participation': 38423.0,
             'individual_participation': 68276.8333,
             'total_cost': 100248674.0},
 'Virgin Islands': {'cost_by_household': 361.0765333333333,
                    'cost_by_individual': 175.95379166666666,
                    'household_participation': 10394.6667,
                    'individual_participation': 21331.0,
                    'total_cost': 45039243.0},
 'Virginia': {'cost_by_household': 262.2479666666667,
              'cost_by_individual': 127.55221666666667,
              'household_participation': 318521.75,
              'individual_participation': 654882.25,
              'total_cost': 1002380166.0},
 'West Virginia': {'cost_by_household': 223.87889166666668,
                   'cost_by_individual': 117.30724166666667,
                   'household_participation': 148108.3333,
                   'individual_participation': 282662.25,
                   'total_cost': 397899950.0}}

### SERO

In [408]:
sheet = book.sheet_by_name('SERO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 PUBLIC - Supplemental Nutrition Assistance Program', '', '', '', '', '07/01/2020']
1 ['SNAP Monthly State Participation and Benefit Summary - Public Data, Fiscal Year 2019', '', '', '', '', '']
2 [' ', '', '', '', '', '']
3 ['', '', '', '', '', '']
4 [' ', 'Total 1/', '', '', '', '']
5 ['Fiscal Year and Month', 'Participation 1/', '', 'Cost', 'Cost Per', '']
6 ['', 'Household', 'Persons', '', 'Household', 'Persons']
7 ['Alabama', '', '', '', '', '']
8 ['Oct 2018', 352543.0, 748755.0, 90640836.0, 257.1058, 121.0554]
9 ['Nov 2018', 350510.0, 743517.0, 88391600.0, 252.18, 118.8831]
10 ['Dec 2018', 348807.0, 739258.0, 88413840.0, 253.475, 119.5981]
11 ['Jan 2019 /2', 346977.0, 734098.0, 163797737.0, 472.0709, 223.1279]
12 ['Feb 2019 /2', 1663.0, 3926.0, 7478420.0, 4496.9453, 1904.8446]
13 ['Mar 2019', 342619.0, 723596.0, 85184474.0, 248.6274, 117.7238]
14 ['Apr 2019', 339982.0, 717163.0, 84031740.0, 247.1653, 117.1724]
15 ['May 2019', 339642.0, 716989.0, 84389364.0, 248.4656, 117.6997]
16 ['Jun 2019', 339857.0, 717564.0, 84618427.0, 248.9824, 117.9246]
17 ['Jul 2019', 340639.0, 718523.0, 84716418.0, 248.6985, 117.9036]
18 ['Aug 2019', 341995.0, 721299.0, 85367868.0, 249.6173, 118.353]
19 ['Sep 2019', 341373.0, 719827.0, 85034162.0, 249.0946, 118.1314]
20 ['Total', 315550.5833, 667042.9167, 1032064886.0, 272.5566416666667, 128.93534166666666]
21 ['', '', '', '', '', '']
22 ['Florida', '', '', '', '', '']
23 ['Oct 2018', 1606761.0, 2996302.0, 363289185.0, 226.1003, 121.2459]
24 ['Nov 2018', 1644826.0, 3073877.0, 369998096.0, 224.9466, 120.3685]
25 ['Dec 2018', 1585037.0, 2944370.0, 348529002.0, 219.887, 118.3713]
26 ['Jan 2019 /2', 1559702.0, 2888654.0, 608867822.0, 390.3745, 210.7791]
27 ['Feb 2019 /2', 214313.0, 473190.0, 56338014.0, 262.8773, 119.06]
28 ['Mar 2019', 1509558.0, 2780799.0, 325661693.0, 215.7331, 117.1108]
29 ['Apr 2019', 1499980.0, 2765663.0, 324369732.0, 216.2494, 117.2846]
30 ['May 2019', 1507038.0, 2779400.0, 327033066.0, 217.0039, 117.6632]
31 ['Jun 2019', 1513284.0, 2789098.0, 328579542.0, 217.1301, 117.8085]
32 ['Jul 2019', 1509953.0, 2779754.0, 328952112.0, 217.8559, 118.3386]
33 ['Aug 2019', 1507501.0, 2770280.0, 327743409.0, 217.4084, 118.307]
34 ['Sep 2019', 1500656.0, 2755509.0, 326024572.0, 217.2547, 118.3174]
35 ['Total', 1429884.0833, 2649741.3333, 4035386245.0, 235.18143333333333, 126.911325]
36 ['', '', '', '', '', '']
37 ['Georgia', '', '', '', '', '']
38 ['Oct 2018', 683336.0, 1485060.0, 190681055.0, 279.0444, 128.3996]
39 ['Nov 2018', 721447.0, 1582313.0, 206270431.0, 285.9121, 130.3601]
40 ['Dec 2018', 671855.0, 1453914.0, 181205366.0, 269.709, 124.6328]
41 ['Jan 2019 /2', 670279.0, 1452314.0, 323117028.0, 482.0635, 222.4843]
42 ['Feb 2019 /2', 133634.0, 319224.0, 30402760.0, 227.5077, 95.2396]
43 ['Mar 2019', 655516.0, 1414322.0, 173281627.0, 264.3439, 122.5192]
44 ['Apr 2019', 647278.0, 1397447.0, 169081690.0, 261.2196, 120.9933]
45 ['May 2019', 644207.0, 1390665.0, 171007285.0, 265.4539, 122.968]
46 ['Jun 2019', 642604.0, 1385857.0, 168987279.0, 262.9727, 121.937]
47 ['Jul 2019', 632180.0, 1365770.0, 165572233.0, 261.9068, 121.23]
48 ['Aug 2019', 636701.0, 1372252.0, 168097109.0, 264.0126, 122.4973]
49 ['Sep 2019', 637959.0, 1372965.0, 167397378.0, 262.3952, 121.924]
50 ['Total', 614749.6667, 1332675.25, 2115101241.0, 286.7157916666667, 132.25910833333333]
51 ['', '', '', '', '', '']
52 ['Kentucky', '', '', '', '', '']
53 ['Oct 2018', 261676.0, 577565.0, 66221973.0, 253.0686, 114.6572]
54 ['Nov 2018', 258169.0, 568814.0, 64806291.0, 251.0227, 113.9323]
55 ['Dec 2018', 257469.0, 566810.0, 63766617.0, 247.6672, 112.5009]
56 ['Jan 2019 /2', 258445.0, 566900.0, 118232631.0, 457.477, 208.5599]
57 ['Feb 2019 /2', 31058.0, 75734.0, 8112220.0, 261.1958, 107.1146]
58 ['Mar 2019', 244916.0, 539847.0, 62032927.0, 253.2825, 114.9083]
59 ['Apr 2019', 241584.0, 533922.0, 60288579.0, 249.5553, 112.9165]
60 ['May 2019', 238679.0, 529143.0, 60200588.0, 252.2241, 113.77]
61 ['Jun 2019', 237323.0, 527256.0, 60053460.0, 253.0453, 113.8981]
62 ['Jul 2019', 233270.0, 518431.0, 59260656.0, 254.0432, 114.3077]
63 ['Aug 2019', 231839.0, 515693.0, 58690321.0, 253.1512, 113.8086]
64 ['Sep 2019', 227556.0, 506778.0, 57631484.0, 253.2629, 113.7214]
65 ['Total', 226832.0, 502241.0833, 739297747.0, 271.6025333333333, 122.66648333333333]
66 ['', '', '', '', '', '']
67 ['Mississippi', '', '', '', '', '']
68 ['Oct 2018', 220993.0, 477166.0, 53796407.0, 243.4304, 112.7415]
69 ['Nov 2018', 219510.0, 473171.0, 53122830.0, 242.0064, 112.2698]
70 ['Dec 2018', 217632.0, 468186.0, 52309394.0, 240.3571, 111.7278]
71 ['Jan 2019 /2', 215458.0, 463284.0, 95210876.0, 441.8999, 205.513]
72 ['Feb 2019 /2', 20353.0, 47674.0, 5615007.0, 275.881, 117.7792]
73 ['Mar 2019', 209975.0, 449821.0, 49340055.0, 234.9806, 109.6882]
74 ['Apr 2019', 207566.0, 443868.0, 49191245.0, 236.9909, 110.824]
75 ['May 2019', 207248.0, 444005.0, 49151036.0, 237.1605, 110.6993]
76 ['Jun 2019', 208080.0, 446617.0, 49445672.0, 237.6282, 110.7116]
77 ['Jul 2019', 208202.0, 446420.0, 49607362.0, 238.2655, 111.1226]
78 ['Aug 2019', 208615.0, 446880.0, 49665349.0, 238.0718, 111.138]
79 ['Sep 2019', 207204.0, 443382.0, 49324894.0, 238.0499, 111.2469]
80 ['Total', 195903.0, 420872.8333, 605780127.0, 257.68710833333336, 119.9452]
81 ['', '', '', '', '', '']
82 ['North Carolina', '', '', '', '', '']
83 ['Oct 2018', 787918.0, 1691351.0, 221760632.0, 281.4514, 131.1145]
84 ['Nov 2018', 665684.0, 1393700.0, 165703900.0, 248.9228, 118.895]
85 ['Dec 2018', 637265.0, 1326080.0, 153880128.0, 241.4696, 116.0414]
86 ['Jan 2019 /2', 637206.0, 1322868.0, 301747623.0, 473.548, 228.1011]
87 ['Feb 2019 /2', 49845.0, 110659.0, 9235512.0, 185.2846, 83.4592]
88 ['Mar 2019', 634567.0, 1308432.0, 148511913.0, 234.0366, 113.5037]
89 ['Apr 2019', 619367.0, 1278787.0, 143762312.0, 232.1117, 112.4208]
90 ['May 2019', 611574.0, 1263343.0, 142410507.0, 232.859, 112.7251]
91 ['Jun 2019', 613520.0, 1268103.0, 143138454.0, 233.3069, 112.876]
92 ['Jul 2019', 604527.0, 1248711.0, 143122497.0, 236.7512, 114.6162]
93 ['Aug 2019', 609333.0, 1266496.0, 144961717.0, 237.9023, 114.4589]
94 ['Sep 2019', 610088.0, 1262554.0, 145421615.0, 238.3617, 115.1805]
95 ['Total', 590074.5, 1228423.6667, 1863656810.0, 263.195125, 126.42603333333334]
96 ['', '', '', '', '', '']
97 ['South Carolina', '', '', '', '', '']
98 ['Oct 2018', 290170.0, 623283.0, 77881486.0, 268.3995, 124.9537]
99 ['Nov 2018', 288695.0, 621075.0, 74809162.0, 259.1287, 120.4511]
100 ['Dec 2018', 286913.0, 617516.0, 73357946.0, 255.6801, 118.7952]
101 ['Jan 2019 /2', 284053.0, 611652.0, 129736138.0, 456.7322, 212.1078]
102 ['Feb 2019 /2', 40435.0, 96732.0, 11667281.0, 288.5441, 120.6145]
103 ['Mar 2019', 276962.0, 595551.0, 69686266.0, 251.6095, 117.0114]
104 ['Apr 2019', 275630.0, 590881.0, 68886660.0, 249.9244, 116.583]
105 ['May 2019', 275498.0, 590201.0, 69239203.0, 251.3238, 117.3146]
106 ['Jun 2019', 275645.0, 590472.0, 69764318.0, 253.0948, 118.1501]
107 ['Jul 2019', 275478.0, 590847.0, 69751763.0, 253.2027, 118.0538]
108 ['Aug 2019', 274552.0, 590285.0, 69998234.0, 254.9544, 118.5838]
109 ['Sep 2019', 272457.0, 586163.0, 69874294.0, 256.4599, 119.2063]
110 ['Total', 259707.3333, 558721.5, 854652751.0, 274.23585833333334, 127.47149166666667]
111 ['', '', '', '', '', '']
112 ['Tennessee', '', '', '', '', '']
113 ['Oct 2018', 448713.0, 938986.0, 113491397.0, 252.9265, 120.8659]
114 ['Nov 2018', 440858.0, 922468.0, 111962458.0, 253.9649, 121.3727]
115 ['Dec 2018', 437519.0, 913571.0, 110098760.0, 251.6434, 120.5147]
116 ['Jan 2019 /2', 447425.0, 933981.0, 213255740.0, 476.629, 228.3298]
117 ['Feb 2019 /2', 23311.0, 46795.0, 8484045.0, 363.9503, 181.3024]
118 ['Mar 2019', 441016.0, 913919.0, 110588115.0, 250.7576, 121.0043]
119 ['Apr 2019', 428677.0, 889691.0, 106493826.0, 248.4244, 119.6975]
120 ['May 2019', 426846.0, 891135.0, 107033243.0, 250.7538, 120.1089]
121 ['Jun 2019', 424144.0, 884811.0, 106136332.0, 250.2366, 119.9537]
122 ['Jul 2019', 425845.0, 889405.0, 106924493.0, 251.0878, 120.2203]
123 ['Aug 2019', 423073.0, 884025.0, 107699508.0, 254.5648, 121.8286]
124 ['Sep 2019', 420066.0, 876772.0, 105080205.0, 250.1517, 119.849]
125 ['Total', 398957.75, 832129.9167, 1307248122.0, 273.0548333333333, 130.91386666666668]
126 ['', '', '', '', '', '']
127 ['SERO', '', '', '', '', '']
128 ['Oct 2018', 4652110.0, 9538468.0, 1177762971.0, 253.1675, 123.4751]
129 ['Nov 2018', 4589699.0, 9378935.0, 1135064768.0, 247.307, 121.0228]
130 ['Dec 2018', 4442497.0, 9029705.0, 1071561053.0, 241.2069, 118.6707]
131 ['Jan 2019 /2', 4419545.0, 8973751.0, 1953965595.0, 442.1192, 217.7423]
132 ['Feb 2019 /2', 514612.0, 1173934.0, 137333259.0, 266.8676, 116.9855]
133 ['Mar 2019', 4315129.0, 8726287.0, 1024287070.0, 237.3711, 117.3795]
134 ['Apr 2019', 4260064.0, 8617422.0, 1006105784.0, 236.1715, 116.7525]
135 ['May 2019', 4250732.0, 8604881.0, 1010464292.0, 237.7154, 117.4292]
136 ['Jun 2019', 4254457.0, 8609778.0, 1010723484.0, 237.5682, 117.3925]
137 ['Jul 2019', 4230094.0, 8557861.0, 1007907534.0, 238.2707, 117.7756]
138 ['Aug 2019', 4233609.0, 8567210.0, 1012223515.0, 239.0923, 118.1509]
139 ['Sep 2019', 4217359.0, 8523950.0, 1005788604.0, 238.4878, 117.9956]
140 ['Total', 4031658.9167, 8191848.5, 12553187929.0, 259.47110833333335, 127.69999166666666]
141 ['', '', '', '', '', '']
142 ['Footnotes:', '', '', '', '', '']
143 ['1. "Total Participation" (Households and Persons) excludes the counts of participation for Disaster Supplements and Replacements. The participation data reflected in those categories are a subset of the "Regular Ongoing" participation category.', '', '', '', '', '']
144 ["2. Due to the partial Federal government shutdown, most of the February 2019 SNAP benefits were issued early in the month of January 2019.  This was done to ensure SNAP recipients would receive their February 2019 benefits in a timely manner.  As a result, January 2019's benefits will show a significant increase over the previous month and February 2019's benefits will show significantly less than January 2019.", '', '', '', '', '']

In [409]:
for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SERO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data_2019[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

In [410]:
pprint.pprint(snap_data_2019)

{'Alabama': {'cost_by_household': 272.5566416666667,
             'cost_by_individual': 128.93534166666666,
             'household_participation': 315550.5833,
             'individual_participation': 667042.9167,
             'total_cost': 1032064886.0},
 'Connecticut': {'cost_by_household': 246.39140833333335,
                 'cost_by_individual': 143.125425,
                 'household_participation': 197760.75,
                 'individual_participation': 340446.5,
                 'total_cost': 584718600.0},
 'Delaware': {'cost_by_household': 253.22984166666666,
              'cost_by_individual': 123.92758333333333,
              'household_participation': 58622.1667,
              'individual_participation': 119786.75,
              'total_cost': 178138585.0},
 'District of Columbia': {'cost_by_household': 238.37771666666666,
                          'cost_by_individual': 141.6566,
                          'household_participation': 60156.25,
                          'individual_participation': 101230.0833,
                          'total_cost': 172078913.0},
 'Florida': {'cost_by_household': 235.18143333333333,
             'cost_by_individual': 126.911325,
             'household_participation': 1429884.0833,
             'individual_participation': 2649741.3333,
             'total_cost': 4035386245.0},
 'Georgia': {'cost_by_household': 286.7157916666667,
             'cost_by_individual': 132.25910833333333,
             'household_participation': 614749.6667,
             'individual_participation': 1332675.25,
             'total_cost': 2115101241.0},
 'Kentucky': {'cost_by_household': 271.6025333333333,
              'cost_by_individual': 122.66648333333333,
              'household_participation': 226832.0,
              'individual_participation': 502241.0833,
              'total_cost': 739297747.0},
 'Maine': {'cost_by_household': 215.17555833333333,
           'cost_by_individual': 117.48873333333333,
           'household_participation': 78862.1667,
           'individual_participation': 144432.6667,
           'total_cost': 203630527.0},
 'Maryland': {'cost_by_household': 237.601125,
              'cost_by_individual': 128.35764166666667,
              'household_participation': 308166.9167,
              'individual_participation': 570443.6667,
              'total_cost': 878649666.0},
 'Massachusetts': {'cost_by_household': 226.52240833333335,
                   'cost_by_individual': 133.9875,
                   'household_participation': 416128.25,
                   'individual_participation': 703516.1667,
                   'total_cost': 1131148466.0},
 'Mississippi': {'cost_by_household': 257.68710833333336,
                 'cost_by_individual': 119.9452,
                 'household_participation': 195903.0,
                 'individual_participation': 420872.8333,
                 'total_cost': 605780127.0},
 'New Hampshire': {'cost_by_household': 211.00869166666666,
                   'cost_by_individual': 109.93558333333333,
                   'household_participation': 36684.5833,
                   'individual_participation': 70411.8333,
                   'total_cost': 92889191.0},
 'New Jersey': {'cost_by_household': 243.75795833333333,
                'cost_by_individual': 122.41543333333334,
                'household_participation': 325992.3333,
                'individual_participation': 649127.5,
                'total_cost': 953558696.0},
 'New York': {'cost_by_household': 239.11521666666667,
              'cost_by_individual': 135.86609166666668,
              'household_participation': 1512387.3333,
              'individual_participation': 2661700.3333,
              'total_cost': 4339617966.0},
 'North Carolina': {'cost_by_household': 263.195125,
                    'cost_by_individual': 126.42603333333334,
                    'household_participation': 590074.5,
                    'individual_participation': 1228423.6667,
                    'total_cost': 1863656810.0},
 'Pennsylvania': {'cost_by_household': 239.997175,
                  'cost_by_individual': 128.69845833333332,
                  'household_participation': 872821.5833,
                  'individual_participation': 1627639.6667,
                  'total_cost': 2513696584.0},
 'Rhode Island': {'cost_by_household': 241.0078,
                  'cost_by_individual': 144.10263333333333,
                  'household_participation': 84445.25,
                  'individual_participation': 141232.4167,
                  'total_cost': 244223564.0},
 'South Carolina': {'cost_by_household': 274.23585833333334,
                    'cost_by_individual': 127.47149166666667,
                    'household_participation': 259707.3333,
                    'individual_participation': 558721.5,
                    'total_cost': 854652751.0},
 'Tennessee': {'cost_by_household': 273.0548333333333,
               'cost_by_individual': 130.91386666666668,
               'household_participation': 398957.75,
               'individual_participation': 832129.9167,
               'total_cost': 1307248122.0},
 'Vermont': {'cost_by_household': 217.42331666666666,
             'cost_by_individual': 122.35565,
             'household_participation': 38423.0,
             'individual_participation': 68276.8333,
             'total_cost': 100248674.0},
 'Virgin Islands': {'cost_by_household': 361.0765333333333,
                    'cost_by_individual': 175.95379166666666,
                    'household_participation': 10394.6667,
                    'individual_participation': 21331.0,
                    'total_cost': 45039243.0},
 'Virginia': {'cost_by_household': 262.2479666666667,
              'cost_by_individual': 127.55221666666667,
              'household_participation': 318521.75,
              'individual_participation': 654882.25,
              'total_cost': 1002380166.0},
 'West Virginia': {'cost_by_household': 223.87889166666668,
                   'cost_by_individual': 117.30724166666667,
                   'household_participation': 148108.3333,
                   'individual_participation': 282662.25,
                   'total_cost': 397899950.0}}

### MWRO

In [411]:
sheet = book.sheet_by_name('MWRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 PUBLIC - Supplemental Nutrition Assistance Program', '', '', '', '', '07/01/2020']
1 ['SNAP Monthly State Participation and Benefit Summary - Public Data, Fiscal Year 2019', '', '', '', '', '']
2 [' ', '', '', '', '', '']
3 ['', '', '', '', '', '']
4 [' ', 'Total 1/', '', '', '', '']
5 ['Fiscal Year and Month', 'Participation 1/', '', 'Cost', 'Cost Per', '']
6 ['', 'Household', 'Persons', '', 'Household', 'Persons']
7 ['Illinois', '', '', '', '', '']
8 ['Oct 2018', 885620.0, 1783389.0, 228902676.0, 258.466, 128.3526]
9 ['Nov 2018', 873669.0, 1759510.0, 221428465.0, 253.4466, 125.8467]
10 ['Dec 2018', 883840.0, 1777509.0, 222272631.0, 251.4851, 125.0473]
11 ['Jan 2019 /2', 907953.0, 1826750.0, 422282439.0, 465.0928, 231.166]
12 ['Feb 2019 /2', 64915.0, 141914.0, 18120032.0, 279.1347, 127.6832]
13 ['Mar 2019', 875089.0, 1757209.0, 220254421.0, 251.6937, 125.3433]
14 ['Apr 2019', 864878.0, 1737117.0, 214468054.0, 247.9749, 123.4621]
15 ['May 2019', 885370.0, 1780778.0, 220362230.0, 248.8928, 123.7449]
16 ['Jun 2019', 882852.0, 1771527.0, 217608678.0, 246.4838, 122.8368]
17 ['Jul 2019', 889348.0, 1782949.0, 220378853.0, 247.7982, 123.6036]
18 ['Aug 2019', 892071.0, 1783530.0, 221401220.0, 248.1879, 124.1365]
19 ['Sep 2019', 886924.0, 1770574.0, 218556181.0, 246.4204, 123.438]
20 ['Total', 816044.0833, 1639396.3333, 2646035880.0, 270.2096583333333, 134.50255]
21 ['', '', '', '', '', '']
22 ['Indiana', '', '', '', '', '']
23 ['Oct 2018', 269024.0, 599613.0, 71227071.0, 264.761, 118.7884]
24 ['Nov 2018', 265027.0, 590807.0, 69424440.0, 261.9523, 117.5078]
25 ['Dec 2018', 263014.0, 584631.0, 68622608.0, 260.9086, 117.3776]
26 ['Jan 2019 /2', 270851.0, 603782.0, 133297371.0, 492.1428, 220.7707]
27 ['Feb 2019 /2', 18695.0, 44078.0, 34711618.0, 1856.7327, 787.5044]
28 ['Mar 2019', 263930.0, 586395.0, 38415892.0, 145.5533, 65.512]
29 ['Apr 2019', 254030.0, 566081.0, 67677767.0, 266.4164, 119.5549]
30 ['May 2019', 257025.0, 570171.0, 67305365.0, 261.8631, 118.0442]
31 ['Jun 2019', 252565.0, 559775.0, 66890426.0, 264.8444, 119.4952]
32 ['Jul 2019', 231554.0, 519230.0, 67012384.0, 289.4028, 129.0611]
33 ['Aug 2019', 254886.0, 565743.0, 67845773.0, 266.1809, 119.9233]
34 ['Sep 2019', 259037.0, 574304.0, 67214160.0, 259.4771, 117.0359]
35 ['Total', 238303.1667, 530384.1667, 819644875.0, 286.6254, 128.78163333333333]
36 ['', '', '', '', '', '']
37 ['Iowa', '', '', '', '', '']
38 ['Oct 2018', 159549.0, 332595.0, 37472225.0, 234.8634, 112.6662]
39 ['Nov 2018', 158362.0, 329869.0, 36976712.0, 233.4949, 112.0951]
40 ['Dec 2018', 157716.0, 327915.0, 36667073.0, 232.488, 111.8188]
41 ['Jan 2019 /2', 158181.0, 327902.0, 70915744.0, 448.3202, 216.2712]
42 ['Feb 2019 /2', 12752.0, 28798.0, 2373639.0, 186.1386, 82.4237]
43 ['Mar 2019', 154548.0, 320036.0, 35249902.0, 228.0838, 110.1436]
44 ['Apr 2019', 153470.0, 317878.0, 35227578.0, 229.5405, 110.8211]
45 ['May 2019', 152351.0, 315622.0, 35048324.0, 230.0498, 111.0453]
46 ['Jun 2019', 151910.0, 314300.0, 34982659.0, 230.2854, 111.3034]
47 ['Jul 2019', 150822.0, 311638.0, 34845741.0, 231.0388, 111.8148]
48 ['Aug 2019', 150920.0, 312501.0, 35044205.0, 232.2038, 112.1411]
49 ['Sep 2019', 149444.0, 309126.0, 34511416.0, 230.9321, 111.6419]
50 ['Total', 142502.0833, 295681.6667, 429315218.0, 251.05785833333334, 120.9959]
51 ['', '', '', '', '', '']
52 ['Michigan', '', '', '', '', '']
53 ['Oct 2018', 652916.0, 1217499.0, 148976674.0, 228.1713, 122.3629]
54 ['Nov 2018', 646153.0, 1204984.0, 146219816.0, 226.2929, 121.3459]
55 ['Dec 2018', 642827.0, 1198801.0, 146444480.0, 227.8132, 122.1591]
56 ['Jan 2019 /2', 1233970.0, 2301979.0, 274804770.0, 222.6997, 119.3776]
57 ['Feb 2019 /2', 56328.0, 107779.0, 11504607.0, 204.2431, 106.7426]
58 ['Mar 2019', 633266.0, 1182623.0, 141883082.0, 224.0497, 119.9732]
59 ['Apr 2019', 628885.0, 1175365.0, 140297888.0, 223.0899, 119.3654]
60 ['May 2019', 624064.0, 1167928.0, 138965664.0, 222.6785, 118.9848]
61 ['Jun 2019', 620166.0, 1162808.0, 137810967.0, 222.2163, 118.5157]
62 ['Jul 2019', 617618.0, 1160246.0, 139562751.0, 225.9694, 120.2872]
63 ['Aug 2019', 614381.0, 1155683.0, 139426791.0, 226.9386, 120.6445]
64 ['Sep 2019', 609812.0, 1147972.0, 135532854.0, 222.2535, 118.0629]
65 ['Total', 631698.8333, 1181972.25, 1701430344.0, 224.451675, 119.95701666666666]
66 ['', '', '', '', '', '']
67 ['Minnesota', '', '', '', '', '']
68 ['Oct 2018', 211897.0, 422573.0, 43844243.0, 206.913, 103.7554]
69 ['Nov 2018', 210009.0, 418183.0, 43243747.0, 205.9138, 103.4087]
70 ['Dec 2018', 208354.0, 413125.0, 42707295.0, 204.9747, 103.3762]
71 ['Jan 2019 /2', 211448.0, 418348.0, 78396698.0, 370.7611, 187.3959]
72 ['Feb 2019 /2', 34852.0, 78770.0, 7923155.0, 227.3372, 100.5859]
73 ['Mar 2019', 207210.0, 406302.0, 42130516.0, 203.3228, 103.6926]
74 ['Apr 2019', 207153.0, 405566.0, 42087241.0, 203.1698, 103.7741]
75 ['May 2019', 207303.0, 405773.0, 42089964.0, 203.036, 103.7279]
76 ['Jun 2019', 206345.0, 403555.0, 41973723.0, 203.4153, 104.0099]
77 ['Jul 2019', 206968.0, 404059.0, 41878214.0, 202.3415, 103.6438]
78 ['Aug 2019', 207053.0, 404212.0, 41718582.0, 201.4875, 103.2097]
79 ['Sep 2019', 205610.0, 400877.0, 41471381.0, 201.6992, 103.4516]
80 ['Total', 193683.5, 381778.5833, 509464759.0, 219.19986666666668, 111.20424166666666]
81 ['', '', '', '', '', '']
82 ['Ohio', '', '', '', '', '']
83 ['Oct 2018', 695524.0, 1400704.0, 171541212.0, 246.6359, 122.4679]
84 ['Nov 2018', 677046.0, 1358228.0, 170377569.0, 251.6484, 125.4411]
85 ['Dec 2018', 697541.0, 1406880.0, 171838544.0, 246.349, 122.1416]
86 ['Jan 2019 /2', 693828.0, 1401304.0, 321843023.0, 463.8657, 229.6739]
87 ['Feb 2019 /2', 28776.0, 61255.0, 89635095.0, 3114.9255, 1463.3107]
88 ['Mar 2019', 684163.0, 1376068.0, 91635593.0, 133.9382, 66.5923]
89 ['Apr 2019', 688024.0, 1385222.0, 166487299.0, 241.9789, 120.1882]
90 ['May 2019', 685221.0, 1378556.0, 166976233.0, 243.6823, 121.124]
91 ['Jun 2019', 685377.0, 1379247.0, 169734604.0, 247.6514, 123.0632]
92 ['Jul 2019', 683135.0, 1375056.0, 166120562.0, 243.1738, 120.81]
93 ['Aug 2019', 682571.0, 1375316.0, 167784003.0, 245.8118, 121.9967]
94 ['Sep 2019', 684844.0, 1381245.0, 166523707.0, 243.1557, 120.5606]
95 ['Total', 632170.8333, 1273256.75, 2020497444.0, 266.34380833333336, 132.23945833333335]
96 ['', '', '', '', '', '']
97 ['Wisconsin', '', '', '', '', '']
98 ['Oct 2018', 322619.0, 634562.0, 66498750.0, 206.1216, 104.7947]
99 ['Nov 2018', 320633.0, 629450.0, 65640481.0, 204.7215, 104.2823]
100 ['Dec 2018', 319229.0, 625435.0, 65283848.0, 204.5048, 104.3815]
101 ['Jan 2019 /2', 320854.0, 629141.0, 121564431.0, 378.8777, 193.2229]
102 ['Feb 2019 /2', 32385.0, 71428.0, 6902386.0, 213.1353, 96.6342]
103 ['Mar 2019', 313467.0, 615344.0, 63798302.0, 203.5248, 103.6791]
104 ['Apr 2019', 312579.0, 613035.0, 63923345.0, 204.503, 104.2736]
105 ['May 2019', 311695.0, 611038.0, 63479672.0, 203.6596, 103.8883]
106 ['Jun 2019', 311811.0, 610698.0, 63640850.0, 204.1007, 104.21]
107 ['Jul 2019', 311836.0, 609826.0, 68236008.0, 218.8202, 111.8942]
108 ['Aug 2019', 311915.0, 610078.0, 65614207.0, 210.3593, 107.5505]
109 ['Sep 2019', 311625.0, 607844.0, 63790781.0, 204.7037, 104.946]
110 ['Total', 291720.6667, 572323.25, 778373061.0, 222.35113333333334, 113.33529166666666]
111 ['', '', '', '', '', '']
112 ['MWRO', '', '', '', '', '']
113 ['Oct 2018', 3197149.0, 6390935.0, 768462851.0, 240.3588, 120.2426]
114 ['Nov 2018', 3150899.0, 6291031.0, 753311230.0, 239.0782, 119.7437]
115 ['Dec 2018', 3172521.0, 6334296.0, 753836479.0, 237.6143, 119.0087]
116 ['Jan 2019 /2', 3797085.0, 7509206.0, 1423104476.0, 374.7887, 189.5146]
117 ['Feb 2019 /2', 248703.0, 534022.0, 171170532.0, 688.2528, 320.5309]
118 ['Mar 2019', 3131673.0, 6243977.0, 633367708.0, 202.2458, 101.4366]
119 ['Apr 2019', 3109019.0, 6200264.0, 730169172.0, 234.8552, 117.7642]
120 ['May 2019', 3123029.0, 6229866.0, 734227452.0, 235.1011, 117.8561]
121 ['Jun 2019', 3111026.0, 6201910.0, 732641907.0, 235.4985, 118.1317]
122 ['Jul 2019', 3091281.0, 6163004.0, 738034513.0, 238.7471, 119.7524]
123 ['Aug 2019', 3113797.0, 6207063.0, 738834781.0, 237.2778, 119.0313]
124 ['Sep 2019', 3107296.0, 6191942.0, 727600480.0, 234.1587, 117.5076]
125 ['Total', 2946123.1667, 5874793.0, 8904761581.0, 251.87795, 126.313125]
126 ['', '', '', '', '', '']
127 ['Footnotes:', '', '', '', '', '']
128 ['1. "Total Participation" (Households and Persons) excludes the counts of participation for Disaster Supplements and Replacements. The participation data reflected in those categories are a subset of the "Regular Ongoing" participation category.', '', '', '', '', '']
129 ["2. Due to the partial Federal government shutdown, most of the February 2019 SNAP benefits were issued early in the month of January 2019.  This was done to ensure SNAP recipients would receive their February 2019 benefits in a timely manner.  As a result, January 2019's benefits will show a significant increase over the previous month and February 2019's benefits will show significantly less than January 2019.", '', '', '', '', '']

In [412]:
for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MWRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data_2019[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

In [413]:
pprint.pprint(snap_data_2019)

{'Alabama': {'cost_by_household': 272.5566416666667,
             'cost_by_individual': 128.93534166666666,
             'household_participation': 315550.5833,
             'individual_participation': 667042.9167,
             'total_cost': 1032064886.0},
 'Connecticut': {'cost_by_household': 246.39140833333335,
                 'cost_by_individual': 143.125425,
                 'household_participation': 197760.75,
                 'individual_participation': 340446.5,
                 'total_cost': 584718600.0},
 'Delaware': {'cost_by_household': 253.22984166666666,
              'cost_by_individual': 123.92758333333333,
              'household_participation': 58622.1667,
              'individual_participation': 119786.75,
              'total_cost': 178138585.0},
 'District of Columbia': {'cost_by_household': 238.37771666666666,
                          'cost_by_individual': 141.6566,
                          'household_participation': 60156.25,
                          'individual_participation': 101230.0833,
                          'total_cost': 172078913.0},
 'Florida': {'cost_by_household': 235.18143333333333,
             'cost_by_individual': 126.911325,
             'household_participation': 1429884.0833,
             'individual_participation': 2649741.3333,
             'total_cost': 4035386245.0},
 'Georgia': {'cost_by_household': 286.7157916666667,
             'cost_by_individual': 132.25910833333333,
             'household_participation': 614749.6667,
             'individual_participation': 1332675.25,
             'total_cost': 2115101241.0},
 'Illinois': {'cost_by_household': 270.2096583333333,
              'cost_by_individual': 134.50255,
              'household_participation': 816044.0833,
              'individual_participation': 1639396.3333,
              'total_cost': 2646035880.0},
 'Indiana': {'cost_by_household': 286.6254,
             'cost_by_individual': 128.78163333333333,
             'household_participation': 238303.1667,
             'individual_participation': 530384.1667,
             'total_cost': 819644875.0},
 'Iowa': {'cost_by_household': 251.05785833333334,
          'cost_by_individual': 120.9959,
          'household_participation': 142502.0833,
          'individual_participation': 295681.6667,
          'total_cost': 429315218.0},
 'Kentucky': {'cost_by_household': 271.6025333333333,
              'cost_by_individual': 122.66648333333333,
              'household_participation': 226832.0,
              'individual_participation': 502241.0833,
              'total_cost': 739297747.0},
 'Maine': {'cost_by_household': 215.17555833333333,
           'cost_by_individual': 117.48873333333333,
           'household_participation': 78862.1667,
           'individual_participation': 144432.6667,
           'total_cost': 203630527.0},
 'Maryland': {'cost_by_household': 237.601125,
              'cost_by_individual': 128.35764166666667,
              'household_participation': 308166.9167,
              'individual_participation': 570443.6667,
              'total_cost': 878649666.0},
 'Massachusetts': {'cost_by_household': 226.52240833333335,
                   'cost_by_individual': 133.9875,
                   'household_participation': 416128.25,
                   'individual_participation': 703516.1667,
                   'total_cost': 1131148466.0},
 'Michigan': {'cost_by_household': 224.451675,
              'cost_by_individual': 119.95701666666666,
              'household_participation': 631698.8333,
              'individual_participation': 1181972.25,
              'total_cost': 1701430344.0},
 'Minnesota': {'cost_by_household': 219.19986666666668,
               'cost_by_individual': 111.20424166666666,
               'household_participation': 193683.5,
               'individual_participation': 381778.5833,
               'total_cost': 509464759.0},
 'Mississippi': {'cost_by_household': 257.68710833333336,
                 'cost_by_individual': 119.9452,
                 'household_participation': 195903.0,
                 'individual_participation': 420872.8333,
                 'total_cost': 605780127.0},
 'New Hampshire': {'cost_by_household': 211.00869166666666,
                   'cost_by_individual': 109.93558333333333,
                   'household_participation': 36684.5833,
                   'individual_participation': 70411.8333,
                   'total_cost': 92889191.0},
 'New Jersey': {'cost_by_household': 243.75795833333333,
                'cost_by_individual': 122.41543333333334,
                'household_participation': 325992.3333,
                'individual_participation': 649127.5,
                'total_cost': 953558696.0},
 'New York': {'cost_by_household': 239.11521666666667,
              'cost_by_individual': 135.86609166666668,
              'household_participation': 1512387.3333,
              'individual_participation': 2661700.3333,
              'total_cost': 4339617966.0},
 'North Carolina': {'cost_by_household': 263.195125,
                    'cost_by_individual': 126.42603333333334,
                    'household_participation': 590074.5,
                    'individual_participation': 1228423.6667,
                    'total_cost': 1863656810.0},
 'Ohio': {'cost_by_household': 266.34380833333336,
          'cost_by_individual': 132.23945833333335,
          'household_participation': 632170.8333,
          'individual_participation': 1273256.75,
          'total_cost': 2020497444.0},
 'Pennsylvania': {'cost_by_household': 239.997175,
                  'cost_by_individual': 128.69845833333332,
                  'household_participation': 872821.5833,
                  'individual_participation': 1627639.6667,
                  'total_cost': 2513696584.0},
 'Rhode Island': {'cost_by_household': 241.0078,
                  'cost_by_individual': 144.10263333333333,
                  'household_participation': 84445.25,
                  'individual_participation': 141232.4167,
                  'total_cost': 244223564.0},
 'South Carolina': {'cost_by_household': 274.23585833333334,
                    'cost_by_individual': 127.47149166666667,
                    'household_participation': 259707.3333,
                    'individual_participation': 558721.5,
                    'total_cost': 854652751.0},
 'Tennessee': {'cost_by_household': 273.0548333333333,
               'cost_by_individual': 130.91386666666668,
               'household_participation': 398957.75,
               'individual_participation': 832129.9167,
               'total_cost': 1307248122.0},
 'Vermont': {'cost_by_household': 217.42331666666666,
             'cost_by_individual': 122.35565,
             'household_participation': 38423.0,
             'individual_participation': 68276.8333,
             'total_cost': 100248674.0},
 'Virgin Islands': {'cost_by_household': 361.0765333333333,
                    'cost_by_individual': 175.95379166666666,
                    'household_participation': 10394.6667,
                    'individual_participation': 21331.0,
                    'total_cost': 45039243.0},
 'Virginia': {'cost_by_household': 262.2479666666667,
              'cost_by_individual': 127.55221666666667,
              'household_participation': 318521.75,
              'individual_participation': 654882.25,
              'total_cost': 1002380166.0},
 'West Virginia': {'cost_by_household': 223.87889166666668,
                   'cost_by_individual': 117.30724166666667,
                   'household_participation': 148108.3333,
                   'individual_participation': 282662.25,
                   'total_cost': 397899950.0},
 'Wisconsin': {'cost_by_household': 222.35113333333334,
               'cost_by_individual': 113.33529166666666,
               'household_participation': 291720.6667,
               'individual_participation': 572323.25,
               'total_cost': 778373061.0}}

### SWRO

In [414]:
sheet = book.sheet_by_name('SWRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 PUBLIC - Supplemental Nutrition Assistance Program', '', '', '', '', '07/01/2020']
1 ['SNAP Monthly State Participation and Benefit Summary - Public Data, Fiscal Year 2019', '', '', '', '', '']
2 [' ', '', '', '', '', '']
3 ['', '', '', '', '', '']
4 [' ', 'Total 1/', '', '', '', '']
5 ['Fiscal Year and Month', 'Participation 1/', '', 'Cost', 'Cost Per', '']
6 ['', 'Household', 'Persons', '', 'Household', 'Persons']
7 ['Arizona', '', '', '', '', '']
8 ['Oct 2018', 386130.0, 834518.0, 100656542.0, 260.6804, 120.6164]
9 ['Nov 2018', 381440.0, 823176.0, 98897848.0, 259.275, 120.1418]
10 ['Dec 2018', 378525.0, 813790.0, 97746608.0, 258.2303, 120.1128]
11 ['Jan 2019 /2', 381800.0, 815689.0, 182138762.0, 477.0528, 223.2944]
12 ['Feb 2019 /2', 29081.0, 62271.0, 6925223.0, 238.1357, 111.211]
13 ['Mar 2019', 367418.0, 779723.0, 92956039.0, 252.9981, 119.2167]
14 ['Apr 2019', 362808.0, 769805.0, 92094926.0, 253.8393, 119.6341]
15 ['May 2019', 363819.0, 773157.0, 92665456.0, 254.7021, 119.8533]
16 ['Jun 2019', 368339.0, 783815.0, 94309681.0, 256.0404, 120.3214]
17 ['Jul 2019', 371735.0, 790722.0, 95736659.0, 257.5401, 121.075]
18 ['Aug 2019', 374946.0, 797795.0, 96298934.0, 256.8341, 120.7064]
19 ['Sep 2019', 375236.0, 798130.0, 96285536.0, 256.5999, 120.6389]
20 ['Total', 345106.4167, 736882.5833, 1146712214.0, 276.89821666666666, 129.68056666666666]
21 ['', '', '', '', '', '']
22 ['Arkansas', '', '', '', '', '']
23 ['Oct 2018', 161515.0, 363186.0, 39894829.0, 247.0039, 109.8468]
24 ['Nov 2018', 162693.0, 365559.0, 39594063.0, 243.3667, 108.311]
25 ['Dec 2018', 161926.0, 363631.0, 39319914.0, 242.8264, 108.1314]
26 ['Jan 2019 /2', 161030.0, 360533.0, 73798041.0, 458.2875, 204.6915]
27 ['Feb 2019 /2', 162097.0, 363301.0, 3949309.0, 24.3639, 10.8706]
28 ['Mar 2019', 160976.0, 358305.0, 37515841.0, 233.0524, 104.7036]
29 ['Apr 2019', 156621.0, 347080.0, 36991559.0, 236.1852, 106.5793]
30 ['May 2019', 155508.0, 344512.0, 37197884.0, 239.2024, 107.9727]
31 ['Jun 2019', 155869.0, 345284.0, 37797646.0, 242.4962, 109.4683]
32 ['Jul 2019', 156744.0, 346819.0, 37723420.0, 240.669, 108.7698]
33 ['Aug 2019', 157688.0, 349592.0, 38213951.0, 242.339, 109.3101]
34 ['Sep 2019', 158103.0, 351199.0, 38337148.0, 242.4821, 109.1608]
35 ['Total', 159230.8333, 354916.75, 460333605.0, 240.91523333333333, 108.084875]
36 ['', '', '', '', '', '']
37 ['Louisiana', '', '', '', '', '']
38 ['Oct 2018', 391248.0, 838611.0, 105959669.0, 270.8248, 126.3514]
39 ['Nov 2018', 389175.0, 835613.0, 105158533.0, 270.2089, 125.846]
40 ['Dec 2018', 386735.0, 829177.0, 104953782.0, 271.3842, 126.5758]
41 ['Jan 2019 /2', 378562.0, 811065.0, 189149760.0, 499.6533, 233.2116]
42 ['Feb 2019 /2', 42546.0, 95008.0, 12346124.0, 290.183, 129.9483]
43 ['Mar 2019', 375788.0, 808037.0, 100319291.0, 266.9571, 124.1519]
44 ['Apr 2019', 369236.0, 794152.0, 96906155.0, 262.4505, 122.0247]
45 ['May 2019', 369692.0, 795810.0, 98844915.0, 267.371, 124.2067]
46 ['Jun 2019', 369465.0, 795990.0, 99413782.0, 269.075, 124.8933]
47 ['Jul 2019', 367554.0, 791070.0, 100690473.0, 273.9474, 127.2839]
48 ['Aug 2019', 372335.0, 801655.0, 101203279.0, 271.8071, 126.2429]
49 ['Sep 2019', 371381.0, 798536.0, 99712175.0, 268.4902, 124.8687]
50 ['Total', 348643.0833, 749560.3333, 1214657938.0, 290.32985, 135.04115833333333]
51 ['', '', '', '', '', '']
52 ['New Mexico', '', '', '', '', '']
53 ['Oct 2018', 221495.0, 454244.0, 53784104.0, 242.8231, 118.4036]
54 ['Nov 2018', 221696.0, 453405.0, 53434672.0, 241.0268, 117.852]
55 ['Dec 2018', 220823.0, 450576.0, 53110280.0, 240.5106, 117.872]
56 ['Jan 2019 /2', 220728.0, 450546.0, 101796675.0, 461.1861, 225.9407]
57 ['Feb 2019 /2', 22378.0, 44864.0, 3394399.0, 151.6846, 75.6597]
58 ['Mar 2019', 218344.0, 444255.0, 52180221.0, 238.9817, 117.4556]
59 ['Apr 2019', 218674.0, 444329.0, 52083626.0, 238.1793, 117.2186]
60 ['May 2019', 219429.0, 444815.0, 52116722.0, 237.5106, 117.1649]
61 ['Jun 2019', 220196.0, 446392.0, 52408048.0, 238.0064, 117.4036]
62 ['Jul 2019', 221356.0, 447874.0, 52736224.0, 238.2417, 117.7479]
63 ['Aug 2019', 222799.0, 450221.0, 52770916.0, 236.8544, 117.2111]
64 ['Sep 2019', 223019.0, 450410.0, 53091969.0, 238.0603, 117.8748]
65 ['Total', 204244.75, 415160.9167, 632907856.0, 258.230975, 127.04066666666667]
66 ['', '', '', '', '', '']
67 ['Oklahoma', '', '', '', '', '']
68 ['Oct 2018', 269359.0, 581701.0, 70153702.0, 260.4468, 120.601]
69 ['Nov 2018', 269159.0, 580244.0, 69885274.0, 259.6431, 120.4412]
70 ['Dec 2018', 267396.0, 575272.0, 69269564.0, 259.0524, 120.4118]
71 ['Jan 2019 /2', 267704.0, 575769.0, 129258491.0, 482.8411, 224.4971]
72 ['Feb 2019 /2', 28648.0, 63182.0, 6502418.0, 226.9763, 102.9157]
73 ['Mar 2019', 264312.0, 565817.0, 66883548.0, 253.0477, 118.207]
74 ['Apr 2019', 264417.0, 565900.0, 66790676.0, 252.596, 118.0256]
75 ['May 2019', 264953.0, 566892.0, 67177734.0, 253.5459, 118.5018]
76 ['Jun 2019', 267505.0, 571467.0, 67814152.0, 253.5061, 118.6668]
77 ['Jul 2019', 268444.0, 573259.0, 67865677.0, 252.8113, 118.3857]
78 ['Aug 2019', 268949.0, 583042.0, 69223904.0, 257.3867, 118.7288]
79 ['Sep 2019', 271229.0, 578189.0, 68721154.0, 253.3695, 118.8559]
80 ['Total', 247672.9167, 531727.8333, 819546294.0, 275.7488583333333, 128.44075833333332]
81 ['', '', '', '', '', '']
82 ['Texas', '', '', '', '', '']
83 ['Oct 2018', 1544007.0, 3610340.0, 427590925.0, 276.9359, 118.4351]
84 ['Nov 2018', 1515143.0, 3544393.0, 407984497.0, 269.2713, 115.107]
85 ['Dec 2018', 1495103.0, 3496398.0, 406779520.0, 272.0746, 116.3425]
86 ['Jan 2019 /2', 1522293.0, 3544410.0, 740141128.0, 486.2015, 208.8193]
87 ['Feb 2019 /2', 248741.0, 667967.0, 65636444.0, 263.8746, 98.263]
88 ['Mar 2019', 1438380.0, 3342252.0, 385070489.0, 267.7112, 115.2129]
89 ['Apr 2019', 1430437.0, 3322131.0, 385446164.0, 269.4604, 116.0238]
90 ['May 2019', 1415354.0, 3291843.0, 382248624.0, 270.0728, 116.1199]
91 ['Jun 2019', 1434522.0, 3339430.0, 390851623.0, 272.4612, 117.0414]
92 ['Jul 2019', 1445259.0, 3364115.0, 394606675.0, 273.0353, 117.2988]
93 ['Aug 2019', 1449989.0, 3376727.0, 392058273.0, 270.3871, 116.106]
94 ['Sep 2019', 1439988.0, 3346851.0, 388698434.0, 269.9317, 116.1386]
95 ['Total', 1364934.6667, 3187238.0833, 4767112796.0, 291.0464583333333, 124.64064166666667]
96 ['', '', '', '', '', '']
97 ['Utah', '', '', '', '', '']
98 ['Oct 2018', 74606.0, 178812.0, 20480886.0, 274.5206, 114.5387]
99 ['Nov 2018', 73999.0, 177209.0, 20172293.0, 272.6022, 113.8333]
100 ['Dec 2018', 72886.0, 174187.0, 19757324.0, 271.0716, 113.4259]
101 ['Jan 2019 /2', 73644.0, 175327.0, 35208929.0, 478.0964, 200.8186]
102 ['Feb 2019 /2', 13928.0, 37924.0, 3926908.0, 281.9434, 103.5468]
103 ['Mar 2019', 72835.0, 172787.0, 19677197.0, 270.1613, 113.8812]
104 ['Apr 2019', 72173.0, 170989.0, 19349743.0, 268.1022, 113.1637]
105 ['May 2019', 72426.0, 170880.0, 19405451.0, 267.9349, 113.5619]
106 ['Jun 2019', 72013.0, 169541.0, 19207276.0, 266.7196, 113.2899]
107 ['Jul 2019', 71836.0, 168361.0, 19142582.0, 266.4762, 113.6996]
108 ['Aug 2019', 72372.0, 168772.0, 19321245.0, 266.9713, 114.4813]
109 ['Sep 2019', 70918.0, 165162.0, 18902998.0, 266.5473, 114.4513]
110 ['Total', 67803.0, 160829.25, 234552832.0, 288.27735, 121.53305]
111 ['', '', '', '', '', '']
112 ['SWRO', '', '', '', '', '']
113 ['Oct 2018', 3048360.0, 6861412.0, 818520657.0, 268.5118, 119.2933]
114 ['Nov 2018', 3013305.0, 6779599.0, 795127180.0, 263.8721, 117.2823]
115 ['Dec 2018', 2983394.0, 6703031.0, 790936992.0, 265.1132, 117.9969]
116 ['Jan 2019 /2', 3005761.0, 6733339.0, 1451491786.0, 482.9033, 215.5679]
117 ['Feb 2019 /2', 547419.0, 1334517.0, 102680825.0, 187.5726, 76.9423]
118 ['Mar 2019', 2898053.0, 6471176.0, 754602626.0, 260.3826, 116.6098]
119 ['Apr 2019', 2874366.0, 6414386.0, 749662849.0, 260.8098, 116.8721]
120 ['May 2019', 2861181.0, 6387909.0, 749656786.0, 262.0096, 117.3556]
121 ['Jun 2019', 2887909.0, 6451919.0, 761802208.0, 263.7902, 118.0737]
122 ['Jul 2019', 2902928.0, 6482220.0, 768501710.0, 264.7333, 118.5553]
123 ['Aug 2019', 2919078.0, 6527804.0, 769090502.0, 263.4703, 117.8176]
124 ['Sep 2019', 2909874.0, 6488477.0, 763749414.0, 262.4682, 117.7086]
125 ['Total', 2737635.6667, 6136315.75, 9275823535.0, 282.3550666666667, 125.96895833333333]
126 ['', '', '', '', '', '']
127 ['Footnotes:', '', '', '', '', '']
128 ['1. "Total Participation" (Households and Persons) excludes the counts of participation for Disaster Supplements and Replacements. The participation data reflected in those categories are a subset of the "Regular Ongoing" participation category.', '', '', '', '', '']
129 ["2. Due to the partial Federal government shutdown, most of the February 2019 SNAP benefits were issued early in the month of January 2019.  This was done to ensure SNAP recipients would receive their February 2019 benefits in a timely manner.  As a result, January 2019's benefits will show a significant increase over the previous month and February 2019's benefits will show significantly less than January 2019.", '', '', '', '', '']

In [415]:
for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SWRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data_2019[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

In [416]:
pprint.pprint(snap_data_2019)

{'Alabama': {'cost_by_household': 272.5566416666667,
             'cost_by_individual': 128.93534166666666,
             'household_participation': 315550.5833,
             'individual_participation': 667042.9167,
             'total_cost': 1032064886.0},
 'Arizona': {'cost_by_household': 276.89821666666666,
             'cost_by_individual': 129.68056666666666,
             'household_participation': 345106.4167,
             'individual_participation': 736882.5833,
             'total_cost': 1146712214.0},
 'Arkansas': {'cost_by_household': 240.91523333333333,
              'cost_by_individual': 108.084875,
              'household_participation': 159230.8333,
              'individual_participation': 354916.75,
              'total_cost': 460333605.0},
 'Connecticut': {'cost_by_household': 246.39140833333335,
                 'cost_by_individual': 143.125425,
                 'household_participation': 197760.75,
                 'individual_participation': 340446.5,
                 'total_cost': 584718600.0},
 'Delaware': {'cost_by_household': 253.22984166666666,
              'cost_by_individual': 123.92758333333333,
              'household_participation': 58622.1667,
              'individual_participation': 119786.75,
              'total_cost': 178138585.0},
 'District of Columbia': {'cost_by_household': 238.37771666666666,
                          'cost_by_individual': 141.6566,
                          'household_participation': 60156.25,
                          'individual_participation': 101230.0833,
                          'total_cost': 172078913.0},
 'Florida': {'cost_by_household': 235.18143333333333,
             'cost_by_individual': 126.911325,
             'household_participation': 1429884.0833,
             'individual_participation': 2649741.3333,
             'total_cost': 4035386245.0},
 'Georgia': {'cost_by_household': 286.7157916666667,
             'cost_by_individual': 132.25910833333333,
             'household_participation': 614749.6667,
             'individual_participation': 1332675.25,
             'total_cost': 2115101241.0},
 'Illinois': {'cost_by_household': 270.2096583333333,
              'cost_by_individual': 134.50255,
              'household_participation': 816044.0833,
              'individual_participation': 1639396.3333,
              'total_cost': 2646035880.0},
 'Indiana': {'cost_by_household': 286.6254,
             'cost_by_individual': 128.78163333333333,
             'household_participation': 238303.1667,
             'individual_participation': 530384.1667,
             'total_cost': 819644875.0},
 'Iowa': {'cost_by_household': 251.05785833333334,
          'cost_by_individual': 120.9959,
          'household_participation': 142502.0833,
          'individual_participation': 295681.6667,
          'total_cost': 429315218.0},
 'Kentucky': {'cost_by_household': 271.6025333333333,
              'cost_by_individual': 122.66648333333333,
              'household_participation': 226832.0,
              'individual_participation': 502241.0833,
              'total_cost': 739297747.0},
 'Louisiana': {'cost_by_household': 290.32985,
               'cost_by_individual': 135.04115833333333,
               'household_participation': 348643.0833,
               'individual_participation': 749560.3333,
               'total_cost': 1214657938.0},
 'Maine': {'cost_by_household': 215.17555833333333,
           'cost_by_individual': 117.48873333333333,
           'household_participation': 78862.1667,
           'individual_participation': 144432.6667,
           'total_cost': 203630527.0},
 'Maryland': {'cost_by_household': 237.601125,
              'cost_by_individual': 128.35764166666667,
              'household_participation': 308166.9167,
              'individual_participation': 570443.6667,
              'total_cost': 878649666.0},
 'Massachusetts': {'cost_by_household': 226.52240833333335,
                   'cost_by_individual': 133.9875,
                   'household_participation': 416128.25,
                   'individual_participation': 703516.1667,
                   'total_cost': 1131148466.0},
 'Michigan': {'cost_by_household': 224.451675,
              'cost_by_individual': 119.95701666666666,
              'household_participation': 631698.8333,
              'individual_participation': 1181972.25,
              'total_cost': 1701430344.0},
 'Minnesota': {'cost_by_household': 219.19986666666668,
               'cost_by_individual': 111.20424166666666,
               'household_participation': 193683.5,
               'individual_participation': 381778.5833,
               'total_cost': 509464759.0},
 'Mississippi': {'cost_by_household': 257.68710833333336,
                 'cost_by_individual': 119.9452,
                 'household_participation': 195903.0,
                 'individual_participation': 420872.8333,
                 'total_cost': 605780127.0},
 'New Hampshire': {'cost_by_household': 211.00869166666666,
                   'cost_by_individual': 109.93558333333333,
                   'household_participation': 36684.5833,
                   'individual_participation': 70411.8333,
                   'total_cost': 92889191.0},
 'New Jersey': {'cost_by_household': 243.75795833333333,
                'cost_by_individual': 122.41543333333334,
                'household_participation': 325992.3333,
                'individual_participation': 649127.5,
                'total_cost': 953558696.0},
 'New Mexico': {'cost_by_household': 258.230975,
                'cost_by_individual': 127.04066666666667,
                'household_participation': 204244.75,
                'individual_participation': 415160.9167,
                'total_cost': 632907856.0},
 'New York': {'cost_by_household': 239.11521666666667,
              'cost_by_individual': 135.86609166666668,
              'household_participation': 1512387.3333,
              'individual_participation': 2661700.3333,
              'total_cost': 4339617966.0},
 'North Carolina': {'cost_by_household': 263.195125,
                    'cost_by_individual': 126.42603333333334,
                    'household_participation': 590074.5,
                    'individual_participation': 1228423.6667,
                    'total_cost': 1863656810.0},
 'Ohio': {'cost_by_household': 266.34380833333336,
          'cost_by_individual': 132.23945833333335,
          'household_participation': 632170.8333,
          'individual_participation': 1273256.75,
          'total_cost': 2020497444.0},
 'Oklahoma': {'cost_by_household': 275.7488583333333,
              'cost_by_individual': 128.44075833333332,
              'household_participation': 247672.9167,
              'individual_participation': 531727.8333,
              'total_cost': 819546294.0},
 'Pennsylvania': {'cost_by_household': 239.997175,
                  'cost_by_individual': 128.69845833333332,
                  'household_participation': 872821.5833,
                  'individual_participation': 1627639.6667,
                  'total_cost': 2513696584.0},
 'Rhode Island': {'cost_by_household': 241.0078,
                  'cost_by_individual': 144.10263333333333,
                  'household_participation': 84445.25,
                  'individual_participation': 141232.4167,
                  'total_cost': 244223564.0},
 'South Carolina': {'cost_by_household': 274.23585833333334,
                    'cost_by_individual': 127.47149166666667,
                    'household_participation': 259707.3333,
                    'individual_participation': 558721.5,
                    'total_cost': 854652751.0},
 'Tennessee': {'cost_by_household': 273.0548333333333,
               'cost_by_individual': 130.91386666666668,
               'household_participation': 398957.75,
               'individual_participation': 832129.9167,
               'total_cost': 1307248122.0},
 'Texas': {'cost_by_household': 291.0464583333333,
           'cost_by_individual': 124.64064166666667,
           'household_participation': 1364934.6667,
           'individual_participation': 3187238.0833,
           'total_cost': 4767112796.0},
 'Utah': {'cost_by_household': 288.27735,
          'cost_by_individual': 121.53305,
          'household_participation': 67803.0,
          'individual_participation': 160829.25,
          'total_cost': 234552832.0},
 'Vermont': {'cost_by_household': 217.42331666666666,
             'cost_by_individual': 122.35565,
             'household_participation': 38423.0,
             'individual_participation': 68276.8333,
             'total_cost': 100248674.0},
 'Virgin Islands': {'cost_by_household': 361.0765333333333,
                    'cost_by_individual': 175.95379166666666,
                    'household_participation': 10394.6667,
                    'individual_participation': 21331.0,
                    'total_cost': 45039243.0},
 'Virginia': {'cost_by_household': 262.2479666666667,
              'cost_by_individual': 127.55221666666667,
              'household_participation': 318521.75,
              'individual_participation': 654882.25,
              'total_cost': 1002380166.0},
 'West Virginia': {'cost_by_household': 223.87889166666668,
                   'cost_by_individual': 117.30724166666667,
                   'household_participation': 148108.3333,
                   'individual_participation': 282662.25,
                   'total_cost': 397899950.0},
 'Wisconsin': {'cost_by_household': 222.35113333333334,
               'cost_by_individual': 113.33529166666666,
               'household_participation': 291720.6667,
               'individual_participation': 572323.25,
               'total_cost': 778373061.0}}

### MPRO

In [417]:
sheet = book.sheet_by_name('MPRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 PUBLIC - Supplemental Nutrition Assistance Program', '', '', '', '', '07/01/2020']
1 ['SNAP Monthly State Participation and Benefit Summary - Public Data, Fiscal Year 2019', '', '', '', '', '']
2 [' ', '', '', '', '', '']
3 ['', '', '', '', '', '']
4 [' ', 'Total 1/', '', '', '', '']
5 ['Fiscal Year and Month', 'Participation 1/', '', 'Cost', 'Cost Per', '']
6 ['', 'Household', 'Persons', '', 'Household', 'Persons']
7 ['Colorado', '', '', '', '', '']
8 ['Oct 2018', 226581.0, 461659.0, 54137256.0, 238.9311, 117.2668]
9 ['Nov 2018', 227958.0, 462062.0, 54295937.0, 238.184, 117.5079]
10 ['Dec 2018', 226803.0, 456585.0, 54203856.0, 238.9909, 118.7158]
11 ['Jan 2019 /2', 227731.0, 456786.0, 101867828.0, 447.3165, 223.01]
12 ['Feb 2019 /2', 14711.0, 31018.0, 5563741.0, 378.2028, 179.3714]
13 ['Mar 2019', 227236.0, 452616.0, 53800677.0, 236.7612, 118.8661]
14 ['Apr 2019', 224890.0, 447801.0, 53085578.0, 236.0513, 118.5473]
15 ['May 2019', 224148.0, 446093.0, 52915128.0, 236.0723, 118.6191]
16 ['Jun 2019', 223919.0, 445289.0, 52779262.0, 235.7069, 118.5281]
17 ['Jul 2019', 224136.0, 444626.0, 52626797.0, 234.7985, 118.3619]
18 ['Aug 2019', 222430.0, 440612.0, 52125498.0, 234.3456, 118.3025]
19 ['Sep 2019', 222430.0, 438326.0, 51598193.0, 231.975, 117.7165]
20 ['Total', 207747.75, 415289.4167, 638999751.0, 256.32036666666664, 128.22378333333333]
21 ['', '', '', '', '', '']
22 ['Kansas', '', '', '', '', '']
23 ['Oct 2018', 98652.0, 211005.0, 23452255.0, 237.7271, 111.1455]
24 ['Nov 2018', 97745.0, 208579.0, 23086957.0, 236.1958, 110.6869]
25 ['Dec 2018', 96432.0, 205387.0, 22716873.0, 235.574, 110.6052]
26 ['Jan 2019 /2', 95855.0, 203960.0, 43313931.0, 451.8693, 212.3648]
27 ['Feb 2019 /2', 5046.0, 10754.0, 1172149.0, 232.2927, 108.9966]
28 ['Mar 2019', 93169.0, 197577.0, 21397016.0, 229.6581, 108.2971]
29 ['Apr 2019', 92922.0, 196818.0, 21432230.0, 230.6475, 108.8936]
30 ['May 2019', 92383.0, 195859.0, 21378223.0, 231.4086, 109.1511]
31 ['Jun 2019', 92763.0, 197142.0, 21622498.0, 233.094, 109.6798]
32 ['Jul 2019', 93953.0, 198962.0, 21939111.0, 233.5116, 110.2678]
33 ['Aug 2019', 93754.0, 199622.0, 22030281.0, 234.9796, 110.36]
34 ['Sep 2019', 93217.0, 198285.0, 21781024.0, 233.6594, 109.8471]
35 ['Total', 87157.5833, 185329.1667, 265322548.0, 253.680875, 119.30239166666667]
36 ['', '', '', '', '', '']
37 ['Missouri', '', '', '', '', '']
38 ['Oct 2018', 331701.0, 713151.0, 86043707.0, 259.4014, 120.6529]
39 ['Nov 2018', 328660.0, 705803.0, 83619242.0, 254.4248, 118.4739]
40 ['Dec 2018', 327740.0, 703365.0, 84269256.0, 257.1223, 119.8087]
41 ['Jan 2019 /2', 333455.0, 713331.0, 166324116.0, 498.7903, 233.1654]
42 ['Feb 2019 /2', 21323.0, 49363.0, 2982562.0, 139.8753, 60.421]
43 ['Mar 2019', 327403.0, 696214.0, 83134673.0, 253.9215, 119.4097]
44 ['Apr 2019', 321512.0, 684676.0, 80848241.0, 251.4626, 118.0825]
45 ['May 2019', 320724.0, 682794.0, 82368936.0, 256.8219, 120.6351]
46 ['Jun 2019', 320683.0, 682299.0, 81624467.0, 254.5332, 119.6315]
47 ['Jul 2019', 319101.0, 678768.0, 81758033.0, 256.2137, 120.4506]
48 ['Aug 2019', 320592.0, 683574.0, 81922929.0, 255.5364, 119.845]
49 ['Sep 2019', 318316.0, 678716.0, 81315979.0, 255.4568, 119.8085]
50 ['Total', 299267.5, 639337.8333, 996212141.0, 277.40291666666667, 129.84946666666667]
51 ['', '', '', '', '', '']
52 ['Montana', '', '', '', '', '']
53 ['Oct 2018', 53574.0, 109420.0, 12559554.0, 234.4338, 114.783]
54 ['Nov 2018', 53237.0, 108616.0, 12293668.0, 230.9234, 113.1847]
55 ['Dec 2018', 52971.0, 107818.0, 12280382.0, 231.8322, 113.8992]
56 ['Jan 2019 /2', 52996.0, 107850.0, 23526655.0, 443.9327, 218.1424]
57 ['Feb 2019 /2', 5293.0, 11053.0, 920657.0, 173.9386, 83.2948]
58 ['Mar 2019', 53147.0, 107957.0, 12337853.0, 232.1458, 114.2849]
59 ['Apr 2019', 52998.0, 107433.0, 12294294.0, 231.9766, 114.4368]
60 ['May 2019', 52906.0, 106957.0, 12239268.0, 231.3399, 114.4317]
61 ['Jun 2019', 52915.0, 106820.0, 12201667.0, 230.5899, 114.2264]
62 ['Jul 2019', 52666.0, 106298.0, 12094520.0, 229.6457, 113.7794]
63 ['Aug 2019', 52523.0, 106146.0, 12098315.0, 230.3432, 113.9781]
64 ['Sep 2019', 52460.0, 106053.0, 12097351.0, 230.6014, 114.0689]
65 ['Total', 48973.8333, 99368.4167, 146944184.0, 250.0386, 123.2318]
66 ['', '', '', '', '', '']
67 ['Nebraska', '', '', '', '', '']
68 ['Oct 2018', 74203.0, 163999.0, 18567195.0, 250.2216, 113.2153]
69 ['Nov 2018', 73788.0, 162964.0, 18441417.0, 249.9243, 113.1625]
70 ['Dec 2018', 73432.0, 161713.0, 18220057.0, 248.1215, 112.6691]
71 ['Jan 2019 /2', 73760.0, 162343.0, 35824672.0, 485.6924, 220.6727]
72 ['Feb 2019 /2', 6000.0, 13198.0, 782298.0, 130.383, 59.274]
73 ['Mar 2019', 74425.0, 163384.0, 21402988.0, 287.5779, 130.9981]
74 ['Apr 2019', 73927.0, 162585.0, 19033103.0, 257.4581, 117.0656]
75 ['May 2019', 72947.0, 159963.0, 18005858.0, 246.8348, 112.5626]
76 ['Jun 2019', 73007.0, 160206.0, 18175095.0, 248.95, 113.4483]
77 ['Jul 2019', 72832.0, 159662.0, 17931740.0, 246.2069, 112.3106]
78 ['Aug 2019', 72272.0, 158755.0, 17997687.0, 249.0271, 113.3677]
79 ['Sep 2019', 71121.0, 156439.0, 17578681.0, 247.1658, 112.3676]
80 ['Total', 67642.8333, 148767.5833, 221960791.0, 273.4470416666667, 124.33308333333333]
81 ['', '', '', '', '', '']
82 ['North Dakota', '', '', '', '', '']
83 ['Oct 2018', 24326.0, 50503.0, 6028804.0, 247.8338, 119.3752]
84 ['Nov 2018', 24167.0, 50048.0, 5880246.0, 243.3172, 117.4921]
85 ['Dec 2018', 23906.0, 49586.0, 5801040.0, 242.6604, 116.9895]
86 ['Jan 2019 /2', 23904.0, 49813.0, 10558889.0, 441.7206, 211.9705]
87 ['Feb 2019 /2', 3256.0, 7638.0, 813161.0, 249.7423, 106.4626]
88 ['Mar 2019', 23479.0, 48422.0, 5628923.0, 239.7429, 116.2472]
89 ['Apr 2019', 23329.0, 48096.0, 5649719.0, 242.1758, 117.4675]
90 ['May 2019', 23307.0, 48095.0, 5664383.0, 243.0336, 117.7749]
91 ['Jun 2019', 23188.0, 47783.0, 5633252.0, 242.9382, 117.8924]
92 ['Jul 2019', 23110.0, 47645.0, 5602410.0, 242.4236, 117.5865]
93 ['Aug 2019', 23206.0, 48043.0, 5633084.0, 242.7426, 117.2509]
94 ['Sep 2019', 23192.0, 48070.0, 5591907.0, 241.1136, 116.3284]
95 ['Total', 21864.1667, 45311.8333, 68485818.0, 261.027625, 125.95278333333333]
96 ['', '', '', '', '', '']
97 ['South Dakota', '', '', '', '', '']
98 ['Oct 2018', 38687.0, 82566.0, 10387332.0, 268.4967, 125.8064]
99 ['Nov 2018', 38579.0, 81999.0, 10263556.0, 266.04, 125.1668]
100 ['Dec 2018', 38358.0, 81528.0, 10260752.0, 267.4997, 125.8556]
101 ['Jan 2019 /2', 38618.0, 82164.0, 19566639.0, 506.6715, 238.1413]
102 ['Feb 2019 /2', 3653.0, 8068.0, 936099.0, 256.2549, 116.0262]
103 ['Mar 2019', 38047.0, 81412.0, 10194620.0, 267.9481, 125.2226]
104 ['Apr 2019', 37849.0, 80939.0, 10088731.0, 266.5521, 124.6461]
105 ['May 2019', 37870.0, 80967.0, 10174421.0, 268.667, 125.6613]
106 ['Jun 2019', 37819.0, 80962.0, 10156186.0, 268.5472, 125.4439]
107 ['Jul 2019', 37610.0, 80314.0, 10062411.0, 267.5462, 125.2884]
108 ['Aug 2019', 37605.0, 80139.0, 10016772.0, 266.3681, 124.9925]
109 ['Sep 2019', 37323.0, 79186.0, 9888153.0, 264.9346, 124.8725]
110 ['Total', 35168.1667, 75020.3333, 121995672.0, 289.07694166666664, 135.51400833333332]
111 ['', '', '', '', '', '']
112 ['Wyoming', '', '', '', '', '']
113 ['Oct 2018', 12278.0, 27448.0, 3164054.0, 257.7011, 115.2745]
114 ['Nov 2018', 12187.0, 27262.0, 3119729.0, 255.9883, 114.4351]
115 ['Dec 2018', 12208.0, 27257.0, 3129666.0, 256.3619, 114.8206]
116 ['Jan 2019 /2', 12528.0, 28009.0, 6046790.0, 482.662, 215.8874]
117 ['Feb 2019 /2', 837.0, 1803.0, 332118.0, 396.7957, 184.203]
118 ['Mar 2019', 11873.0, 26472.0, 3046745.0, 256.6112, 115.0931]
119 ['Apr 2019', 11703.0, 26025.0, 2997337.0, 256.117, 115.1715]
120 ['May 2019', 11631.0, 25789.0, 2959808.0, 254.4758, 114.7702]
121 ['Jun 2019', 11585.0, 25838.0, 2953115.0, 254.9085, 114.2935]
122 ['Jul 2019', 11492.0, 25527.0, 2872545.0, 249.9604, 112.5297]
123 ['Aug 2019', 11429.0, 25349.0, 2870386.0, 251.1494, 113.2347]
124 ['Sep 2019', 11194.0, 24928.0, 2784822.0, 248.7781, 111.7146]
125 ['Total', 10912.0833, 24308.9167, 36277115.0, 277.04085833333335, 124.36148333333334]
126 ['', '', '', '', '', '']
127 ['MPRO', '', '', '', '', '']
128 ['Oct 2018', 860002.0, 1819751.0, 214340157.0, 249.2322, 117.7854]
129 ['Nov 2018', 856321.0, 1807333.0, 211000752.0, 246.4038, 116.747]
130 ['Dec 2018', 851850.0, 1793239.0, 210881882.0, 247.5575, 117.5983]
131 ['Jan 2019 /2', 858847.0, 1804256.0, 407029520.0, 473.9255, 225.5941]
132 ['Feb 2019 /2', 60119.0, 132895.0, 13502785.0, 224.601, 101.6049]
133 ['Mar 2019', 848779.0, 1774054.0, 210943495.0, 248.5258, 118.9048]
134 ['Apr 2019', 839130.0, 1754373.0, 205429233.0, 244.8122, 117.0955]
135 ['May 2019', 835916.0, 1746517.0, 205706025.0, 246.0846, 117.7807]
136 ['Jun 2019', 835879.0, 1746339.0, 205145542.0, 245.4249, 117.4718]
137 ['Jul 2019', 834900.0, 1741802.0, 204887567.0, 245.4037, 117.6297]
138 ['Aug 2019', 833811.0, 1742240.0, 204694952.0, 245.4932, 117.4895]
139 ['Sep 2019', 829253.0, 1730003.0, 202636110.0, 244.3598, 117.1305]
140 ['Total', 778733.9167, 1632733.5, 2496198020.0, 267.1214083333333, 127.40383333333334]
141 ['', '', '', '', '', '']
142 ['Footnotes:', '', '', '', '', '']
143 ['1. "Total Participation" (Households and Persons) excludes the counts of participation for Disaster Supplements and Replacements. The participation data reflected in those categories are a subset of the "Regular Ongoing" participation category.', '', '', '', '', '']
144 ["2. Due to the partial Federal government shutdown, most of the February 2019 SNAP benefits were issued early in the month of January 2019.  This was done to ensure SNAP recipients would receive their February 2019 benefits in a timely manner.  As a result, January 2019's benefits will show a significant increase over the previous month and February 2019's benefits will show significantly less than January 2019.", '', '', '', '', '']

In [418]:
for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MPRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data_2019[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

In [419]:
pprint.pprint(snap_data_2019)

{'Alabama': {'cost_by_household': 272.5566416666667,
             'cost_by_individual': 128.93534166666666,
             'household_participation': 315550.5833,
             'individual_participation': 667042.9167,
             'total_cost': 1032064886.0},
 'Arizona': {'cost_by_household': 276.89821666666666,
             'cost_by_individual': 129.68056666666666,
             'household_participation': 345106.4167,
             'individual_participation': 736882.5833,
             'total_cost': 1146712214.0},
 'Arkansas': {'cost_by_household': 240.91523333333333,
              'cost_by_individual': 108.084875,
              'household_participation': 159230.8333,
              'individual_participation': 354916.75,
              'total_cost': 460333605.0},
 'Colorado': {'cost_by_household': 256.32036666666664,
              'cost_by_individual': 128.22378333333333,
              'household_participation': 207747.75,
              'individual_participation': 415289.4167,
              'total_cost': 638999751.0},
 'Connecticut': {'cost_by_household': 246.39140833333335,
                 'cost_by_individual': 143.125425,
                 'household_participation': 197760.75,
                 'individual_participation': 340446.5,
                 'total_cost': 584718600.0},
 'Delaware': {'cost_by_household': 253.22984166666666,
              'cost_by_individual': 123.92758333333333,
              'household_participation': 58622.1667,
              'individual_participation': 119786.75,
              'total_cost': 178138585.0},
 'District of Columbia': {'cost_by_household': 238.37771666666666,
                          'cost_by_individual': 141.6566,
                          'household_participation': 60156.25,
                          'individual_participation': 101230.0833,
                          'total_cost': 172078913.0},
 'Florida': {'cost_by_household': 235.18143333333333,
             'cost_by_individual': 126.911325,
             'household_participation': 1429884.0833,
             'individual_participation': 2649741.3333,
             'total_cost': 4035386245.0},
 'Georgia': {'cost_by_household': 286.7157916666667,
             'cost_by_individual': 132.25910833333333,
             'household_participation': 614749.6667,
             'individual_participation': 1332675.25,
             'total_cost': 2115101241.0},
 'Illinois': {'cost_by_household': 270.2096583333333,
              'cost_by_individual': 134.50255,
              'household_participation': 816044.0833,
              'individual_participation': 1639396.3333,
              'total_cost': 2646035880.0},
 'Indiana': {'cost_by_household': 286.6254,
             'cost_by_individual': 128.78163333333333,
             'household_participation': 238303.1667,
             'individual_participation': 530384.1667,
             'total_cost': 819644875.0},
 'Iowa': {'cost_by_household': 251.05785833333334,
          'cost_by_individual': 120.9959,
          'household_participation': 142502.0833,
          'individual_participation': 295681.6667,
          'total_cost': 429315218.0},
 'Kansas': {'cost_by_household': 253.680875,
            'cost_by_individual': 119.30239166666667,
            'household_participation': 87157.5833,
            'individual_participation': 185329.1667,
            'total_cost': 265322548.0},
 'Kentucky': {'cost_by_household': 271.6025333333333,
              'cost_by_individual': 122.66648333333333,
              'household_participation': 226832.0,
              'individual_participation': 502241.0833,
              'total_cost': 739297747.0},
 'Louisiana': {'cost_by_household': 290.32985,
               'cost_by_individual': 135.04115833333333,
               'household_participation': 348643.0833,
               'individual_participation': 749560.3333,
               'total_cost': 1214657938.0},
 'Maine': {'cost_by_household': 215.17555833333333,
           'cost_by_individual': 117.48873333333333,
           'household_participation': 78862.1667,
           'individual_participation': 144432.6667,
           'total_cost': 203630527.0},
 'Maryland': {'cost_by_household': 237.601125,
              'cost_by_individual': 128.35764166666667,
              'household_participation': 308166.9167,
              'individual_participation': 570443.6667,
              'total_cost': 878649666.0},
 'Massachusetts': {'cost_by_household': 226.52240833333335,
                   'cost_by_individual': 133.9875,
                   'household_participation': 416128.25,
                   'individual_participation': 703516.1667,
                   'total_cost': 1131148466.0},
 'Michigan': {'cost_by_household': 224.451675,
              'cost_by_individual': 119.95701666666666,
              'household_participation': 631698.8333,
              'individual_participation': 1181972.25,
              'total_cost': 1701430344.0},
 'Minnesota': {'cost_by_household': 219.19986666666668,
               'cost_by_individual': 111.20424166666666,
               'household_participation': 193683.5,
               'individual_participation': 381778.5833,
               'total_cost': 509464759.0},
 'Mississippi': {'cost_by_household': 257.68710833333336,
                 'cost_by_individual': 119.9452,
                 'household_participation': 195903.0,
                 'individual_participation': 420872.8333,
                 'total_cost': 605780127.0},
 'Missouri': {'cost_by_household': 277.40291666666667,
              'cost_by_individual': 129.84946666666667,
              'household_participation': 299267.5,
              'individual_participation': 639337.8333,
              'total_cost': 996212141.0},
 'Montana': {'cost_by_household': 250.0386,
             'cost_by_individual': 123.2318,
             'household_participation': 48973.8333,
             'individual_participation': 99368.4167,
             'total_cost': 146944184.0},
 'Nebraska': {'cost_by_household': 273.4470416666667,
              'cost_by_individual': 124.33308333333333,
              'household_participation': 67642.8333,
              'individual_participation': 148767.5833,
              'total_cost': 221960791.0},
 'New Hampshire': {'cost_by_household': 211.00869166666666,
                   'cost_by_individual': 109.93558333333333,
                   'household_participation': 36684.5833,
                   'individual_participation': 70411.8333,
                   'total_cost': 92889191.0},
 'New Jersey': {'cost_by_household': 243.75795833333333,
                'cost_by_individual': 122.41543333333334,
                'household_participation': 325992.3333,
                'individual_participation': 649127.5,
                'total_cost': 953558696.0},
 'New Mexico': {'cost_by_household': 258.230975,
                'cost_by_individual': 127.04066666666667,
                'household_participation': 204244.75,
                'individual_participation': 415160.9167,
                'total_cost': 632907856.0},
 'New York': {'cost_by_household': 239.11521666666667,
              'cost_by_individual': 135.86609166666668,
              'household_participation': 1512387.3333,
              'individual_participation': 2661700.3333,
              'total_cost': 4339617966.0},
 'North Carolina': {'cost_by_household': 263.195125,
                    'cost_by_individual': 126.42603333333334,
                    'household_participation': 590074.5,
                    'individual_participation': 1228423.6667,
                    'total_cost': 1863656810.0},
 'North Dakota': {'cost_by_household': 261.027625,
                  'cost_by_individual': 125.95278333333333,
                  'household_participation': 21864.1667,
                  'individual_participation': 45311.8333,
                  'total_cost': 68485818.0},
 'Ohio': {'cost_by_household': 266.34380833333336,
          'cost_by_individual': 132.23945833333335,
          'household_participation': 632170.8333,
          'individual_participation': 1273256.75,
          'total_cost': 2020497444.0},
 'Oklahoma': {'cost_by_household': 275.7488583333333,
              'cost_by_individual': 128.44075833333332,
              'household_participation': 247672.9167,
              'individual_participation': 531727.8333,
              'total_cost': 819546294.0},
 'Pennsylvania': {'cost_by_household': 239.997175,
                  'cost_by_individual': 128.69845833333332,
                  'household_participation': 872821.5833,
                  'individual_participation': 1627639.6667,
                  'total_cost': 2513696584.0},
 'Rhode Island': {'cost_by_household': 241.0078,
                  'cost_by_individual': 144.10263333333333,
                  'household_participation': 84445.25,
                  'individual_participation': 141232.4167,
                  'total_cost': 244223564.0},
 'South Carolina': {'cost_by_household': 274.23585833333334,
                    'cost_by_individual': 127.47149166666667,
                    'household_participation': 259707.3333,
                    'individual_participation': 558721.5,
                    'total_cost': 854652751.0},
 'South Dakota': {'cost_by_household': 289.07694166666664,
                  'cost_by_individual': 135.51400833333332,
                  'household_participation': 35168.1667,
                  'individual_participation': 75020.3333,
                  'total_cost': 121995672.0},
 'Tennessee': {'cost_by_household': 273.0548333333333,
               'cost_by_individual': 130.91386666666668,
               'household_participation': 398957.75,
               'individual_participation': 832129.9167,
               'total_cost': 1307248122.0},
 'Texas': {'cost_by_household': 291.0464583333333,
           'cost_by_individual': 124.64064166666667,
           'household_participation': 1364934.6667,
           'individual_participation': 3187238.0833,
           'total_cost': 4767112796.0},
 'Utah': {'cost_by_household': 288.27735,
          'cost_by_individual': 121.53305,
          'household_participation': 67803.0,
          'individual_participation': 160829.25,
          'total_cost': 234552832.0},
 'Vermont': {'cost_by_household': 217.42331666666666,
             'cost_by_individual': 122.35565,
             'household_participation': 38423.0,
             'individual_participation': 68276.8333,
             'total_cost': 100248674.0},
 'Virgin Islands': {'cost_by_household': 361.0765333333333,
                    'cost_by_individual': 175.95379166666666,
                    'household_participation': 10394.6667,
                    'individual_participation': 21331.0,
                    'total_cost': 45039243.0},
 'Virginia': {'cost_by_household': 262.2479666666667,
              'cost_by_individual': 127.55221666666667,
              'household_participation': 318521.75,
              'individual_participation': 654882.25,
              'total_cost': 1002380166.0},
 'West Virginia': {'cost_by_household': 223.87889166666668,
                   'cost_by_individual': 117.30724166666667,
                   'household_participation': 148108.3333,
                   'individual_participation': 282662.25,
                   'total_cost': 397899950.0},
 'Wisconsin': {'cost_by_household': 222.35113333333334,
               'cost_by_individual': 113.33529166666666,
               'household_participation': 291720.6667,
               'individual_participation': 572323.25,
               'total_cost': 778373061.0},
 'Wyoming': {'cost_by_household': 277.04085833333335,
             'cost_by_individual': 124.36148333333334,
             'household_participation': 10912.0833,
             'individual_participation': 24308.9167,
             'total_cost': 36277115.0}}

### WRO

In [420]:
sheet = book.sheet_by_name('WRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 PUBLIC - Supplemental Nutrition Assistance Program', '', '', '', '', '07/01/2020']
1 ['SNAP Monthly State Participation and Benefit Summary - Public Data, Fiscal Year 2019', '', '', '', '', '']
2 [' ', '', '', '', '', '']
3 ['', '', '', '', '', '']
4 [' ', 'Total 1/', '', '', '', '']
5 ['Fiscal Year and Month', 'Participation 1/', '', 'Cost', 'Cost Per', '']
6 ['', 'Household', 'Persons', '', 'Household', 'Persons']
7 ['Alaska', '', '', '', '', '']
8 ['Oct 2018', 32487.0, 71775.0, 12145236.0, 373.8491, 169.2126]
9 ['Nov 2018', 37781.0, 83956.0, 13954208.0, 369.3446, 166.2086]
10 ['Dec 2018', 37928.0, 84575.0, 14174180.0, 373.7128, 167.593]
11 ['Jan 2019 /2', 38796.0, 86305.0, 26171765.0, 674.5996, 303.2474]
12 ['Feb 2019 /2', 6167.0, 14683.0, 2305103.0, 373.7803, 156.9913]
13 ['Mar 2019', 38972.0, 86284.0, 14439030.0, 370.4975, 167.3431]
14 ['Apr 2019', 39433.0, 87526.0, 14676186.0, 372.1803, 167.678]
15 ['May 2019', 39133.0, 86836.0, 14588239.0, 372.7861, 167.9976]
16 ['Jun 2019', 39241.0, 87307.0, 14748405.0, 375.8417, 168.9258]
17 ['Jul 2019', 38892.0, 86605.0, 14818525.0, 381.0173, 171.1047]
18 ['Aug 2019', 38756.0, 86185.0, 14664325.0, 378.3756, 170.1494]
19 ['Sep 2019', 38335.0, 85147.0, 14406470.0, 375.8046, 169.1953]
20 ['Total', 35493.4167, 78932.0, 171091672.0, 401.6981333333333, 180.631925]
21 ['', '', '', '', '', '']
22 ['American Samoa', '', '', '', '', '']
23 [' No data found.', '', '', '', '', '']
24 ['California', '', '', '', '', '']
25 ['Oct 2018', 1911644.0, 3830650.0, 515551201.0, 269.69, 134.5858]
26 ['Nov 2018', 1894575.0, 3795514.0, 509059032.0, 268.693, 134.1212]
27 ['Dec 2018', 1886632.0, 3773446.0, 507802535.0, 269.1582, 134.5726]
28 ['Jan 2019 /2', 1890447.0, 3727456.0, 924312088.0, 488.9384, 247.974]
29 ['Feb 2019 /2', 303030.0, 606095.0, 72917188.0, 240.627, 120.3065]
30 ['Mar 2019', 1848931.0, 3677090.0, 496090357.0, 268.312, 134.9138]
31 ['Apr 2019', 1824382.0, 3623654.0, 479428789.0, 262.7897, 132.3053]
32 ['May 2019', 1837803.0, 3636313.0, 481111532.0, 261.7862, 132.3075]
33 ['Jun 2019', 1970778.0, 3775793.0, 490367375.0, 248.8192, 129.8714]
34 ['Jul 2019', 2053345.0, 3914962.0, 498732955.0, 242.888, 127.3915]
35 ['Aug 2019', 2100790.0, 3987750.0, 502360546.0, 239.1293, 125.9759]
36 ['Sep 2019', 2118467.0, 4004917.0, 499547701.0, 235.8062, 124.7336]
37 ['Total', 1803402.0, 3529470.0, 5977281299.0, 276.20395833333333, 141.127925]
38 ['', '', '', '', '', '']
39 ['Guam', '', '', '', '', '']
40 ['Oct 2018', 15624.0, 45010.0, 8508948.0, 544.6075, 189.0457]
41 ['Nov 2018', 15533.0, 44621.0, 8480592.0, 545.9726, 190.0583]
42 ['Dec 2018', 15631.0, 44936.0, 8498550.0, 543.6984, 189.1256]
43 ['Jan 2019 /2', 15637.0, 44909.0, 16251446.0, 1039.2944, 361.875]
44 ['Feb 2019 /2', 1413.0, 4159.0, 521135.0, 368.8146, 125.303]
45 ['Mar 2019', 15412.0, 44098.0, 8264969.0, 536.2684, 187.4228]
46 ['Apr 2019', 15543.0, 44376.0, 8269399.0, 532.0336, 186.3485]
47 ['May 2019', 15430.0, 44170.0, 8238219.0, 533.9092, 186.5116]
48 ['Jun 2019', 15335.0, 43740.0, 8202025.0, 534.8565, 187.5177]
49 ['Jul 2019', 15387.0, 43673.0, 8534636.0, 554.6654, 195.4213]
50 ['Aug 2019', 15411.0, 43698.0, 8197980.0, 531.9564, 187.6054]
51 ['Sep 2019', 15446.0, 43773.0, 8180001.0, 529.587, 186.8732]
52 ['Total', 14316.8333, 40930.25, 100147900.0, 582.926275, 203.89951666666667]
53 ['', '', '', '', '', '']
54 ['Hawaii', '', '', '', '', '']
55 ['Oct 2018', 82806.0, 161354.0, 38670932.0, 467.0064, 239.6652]
56 ['Nov 2018', 82343.0, 160334.0, 38355871.0, 465.8061, 239.2248]
57 ['Dec 2018', 82149.0, 159653.0, 38251646.0, 465.6374, 239.5924]
58 ['Jan 2019 /2', 81833.0, 158949.0, 72910898.0, 890.9718, 458.7062]
59 ['Feb 2019 /2', 5547.0, 7377.0, 2606185.0, 469.8368, 353.2852]
60 ['Mar 2019', 80421.0, 155902.0, 37009071.0, 460.1916, 237.3868]
61 ['Apr 2019', 79929.0, 154526.0, 36679061.0, 458.8955, 237.365]
62 ['May 2019', 79934.0, 154618.0, 36772095.0, 460.0307, 237.8254]
63 ['Jun 2019', 79702.0, 154161.0, 36716649.0, 460.6741, 238.1708]
64 ['Jul 2019', 83361.0, 162260.0, 36745036.0, 440.7941, 226.4578]
65 ['Aug 2019', 79813.0, 154642.0, 36844724.0, 461.6381, 238.2582]
66 ['Sep 2019', 79998.0, 155293.0, 36869240.0, 460.877, 237.4173]
67 ['Total', 74819.6667, 144922.4167, 448431408.0, 499.45804166666665, 257.85716666666667]
68 ['', '', '', '', '', '']
69 ['Idaho', '', '', '', '', '']
70 ['Oct 2018', 66828.0, 148779.0, 16259104.0, 243.2978, 109.2836]
71 ['Nov 2018', 66955.0, 148842.0, 16317017.0, 243.7012, 109.6264]
72 ['Dec 2018', 67155.0, 149309.0, 16520691.0, 246.0084, 110.6477]
73 ['Jan 2019 /2', 67554.0, 150376.0, 31060627.0, 459.7896, 206.5531]
74 ['Feb 2019 /2', 8134.0, 20752.0, 1810183.0, 222.5452, 87.2293]
75 ['Mar 2019', 67038.0, 148378.0, 16266664.0, 242.6484, 109.6299]
76 ['Apr 2019', 66547.0, 146903.0, 16153804.0, 242.7428, 109.9624]
77 ['May 2019', 66052.0, 145542.0, 15989550.0, 242.0752, 109.8621]
78 ['Jun 2019', 65349.0, 143910.0, 15751353.0, 241.0343, 109.4528]
79 ['Jul 2019', 64960.0, 142933.0, 15647216.0, 240.8746, 109.4724]
80 ['Aug 2019', 65235.0, 143236.0, 15612444.0, 239.3262, 108.998]
81 ['Sep 2019', 64868.0, 142105.0, 15529580.0, 239.4028, 109.2824]
82 ['Total', 61389.5833, 135922.0833, 192918233.0, 261.87699166666664, 118.27746666666667]
83 ['', '', '', '', '', '']
84 ['Nevada', '', '', '', '', '']
85 ['Oct 2018', 227448.0, 434898.0, 51071837.0, 224.5429, 117.4341]
86 ['Nov 2018', 225371.0, 430141.0, 50304762.0, 223.2087, 116.9495]
87 ['Dec 2018', 224523.0, 427773.0, 49882429.0, 222.1707, 116.6096]
88 ['Jan 2019 /2', 223565.0, 425264.0, 93253674.0, 417.1211, 219.2842]
89 ['Feb 2019 /2', 21911.0, 41853.0, 4893121.0, 223.318, 116.9121]
90 ['Mar 2019', 220731.0, 418397.0, 48499885.0, 219.7239, 115.9183]
91 ['Apr 2019', 221242.0, 419347.0, 48624847.0, 219.7813, 115.9537]
92 ['May 2019', 220650.0, 418308.0, 48009985.0, 217.5843, 114.7719]
93 ['Jun 2019', 221312.0, 419602.0, 48478247.0, 219.0493, 115.5339]
94 ['Jul 2019', 221819.0, 420743.0, 48550569.0, 218.8747, 115.3925]
95 ['Aug 2019', 222412.0, 421481.0, 47814489.0, 214.9816, 113.444]
96 ['Sep 2019', 222216.0, 421015.0, 48168041.0, 216.7623, 114.4093]
97 ['Total', 206100.0, 391568.5, 587551886.0, 237.567475, 125.04238333333333]
98 ['', '', '', '', '', '']
99 ['Oregon', '', '', '', '', '']
100 ['Oct 2018', 354999.0, 612249.0, 74887753.0, 210.952, 122.3158]
101 ['Nov 2018', 353939.0, 610070.0, 74655111.0, 210.9265, 122.3714]
102 ['Dec 2018', 354725.0, 607328.0, 74572803.0, 210.2271, 122.7883]
103 ['Jan 2019 /2', 353560.0, 607135.0, 144663799.0, 409.1634, 238.2729]
104 ['Feb 2019 /2', 41143.0, 71869.0, 3318740.0, 80.6635, 46.1776]
105 ['Mar 2019', 349604.0, 597775.0, 73510339.0, 210.2674, 122.9733]
106 ['Apr 2019', 349537.0, 596165.0, 73408033.0, 210.0151, 123.1338]
107 ['May 2019', 349737.0, 595284.0, 73308464.0, 209.6103, 123.1487]
108 ['Jun 2019', 349024.0, 593129.0, 73389891.0, 210.2718, 123.7334]
109 ['Jul 2019', 348528.0, 591697.0, 72979725.0, 209.3942, 123.3397]
110 ['Aug 2019', 348362.0, 590317.0, 72944675.0, 209.3933, 123.5687]
111 ['Sep 2019', 345676.0, 586111.0, 72550317.0, 209.8795, 123.7826]
112 ['Total', 324902.8333, 554927.4167, 884189650.0, 226.7831, 132.778575]
113 ['', '', '', '', '', '']
114 ['Washington', '', '', '', '', '']
115 ['Oct 2018', 489477.0, 845789.0, 102277702.0, 208.953, 120.9258]
116 ['Nov 2018', 488863.0, 843905.0, 101860596.0, 208.3623, 120.7015]
117 ['Dec 2018', 488059.0, 842115.0, 101991706.0, 208.9741, 121.1138]
118 ['Jan 2019 /2', 910221.0, 1640632.0, 191582941.0, 210.4796, 116.7739]
119 ['Feb 2019 /2', 67828.0, 126444.0, 9124228.0, 134.5201, 72.1602]
120 ['Mar 2019', 480950.0, 826184.0, 99448023.0, 206.7741, 120.3703]
121 ['Apr 2019', 479207.0, 818771.0, 98435040.0, 205.4124, 120.2229]
122 ['May 2019', 478607.0, 815496.0, 98620758.0, 206.0579, 120.9335]
123 ['Jun 2019', 476592.0, 813948.0, 97768288.0, 205.1404, 120.1161]
124 ['Jul 2019', 475598.0, 809551.0, 97391261.0, 204.7764, 120.3028]
125 ['Aug 2019', 475838.0, 810037.0, 96970957.0, 203.7899, 119.7118]
126 ['Sep 2019', 473056.0, 804663.0, 96908809.0, 204.8569, 120.434]
127 ['Total', 482024.6667, 833127.9167, 1192380309.0, 206.14095833333334, 119.26743333333333]
128 ['', '', '', '', '', '']
129 ['Commonwealth of Northern Mariana Islands', '', '', '', '', '']
130 [' No data found.', '', '', '', '', '']
131 ['WRO', '', '', '', '', '']
132 ['Oct 2018', 3181313.0, 6150504.0, 819372713.0, 257.558, 133.2204]
133 ['Nov 2018', 3165360.0, 6117383.0, 812987189.0, 256.8388, 132.8979]
134 ['Dec 2018', 3156802.0, 6089135.0, 811694540.0, 257.1256, 133.3021]
135 ['Jan 2019 /2', 3581613.0, 6841026.0, 1500207238.0, 418.8636, 219.2956]
136 ['Feb 2019 /2', 455173.0, 893232.0, 97495883.0, 214.1952, 109.1496]
137 ['Mar 2019', 3102059.0, 5954108.0, 793528338.0, 255.807, 133.2741]
138 ['Apr 2019', 3075820.0, 5891268.0, 775675159.0, 252.1848, 131.6652]
139 ['May 2019', 3087346.0, 5896567.0, 776638842.0, 251.5555, 131.7103]
140 ['Jun 2019', 3217333.0, 6031590.0, 785422233.0, 244.1221, 130.2181]
141 ['Jul 2019', 3301890.0, 6172424.0, 793399923.0, 240.2866, 128.5394]
142 ['Aug 2019', 3346617.0, 6237346.0, 795410140.0, 237.6759, 127.5238]
143 ['Sep 2019', 3358062.0, 6243024.0, 792160159.0, 235.898, 126.8873]
144 ['Total', 3002449.0, 5709800.5833, 9553992357.0, 265.17220833333334, 139.4385]
145 ['', '', '', '', '', '']
146 ['Footnotes:', '', '', '', '', '']
147 ['1. "Total Participation" (Households and Persons) excludes the counts of participation for Disaster Supplements and Replacements. The participation data reflected in those categories are a subset of the "Regular Ongoing" participation category.', '', '', '', '', '']
148 ["2. Due to the partial Federal government shutdown, most of the February 2019 SNAP benefits were issued early in the month of January 2019.  This was done to ensure SNAP recipients would receive their February 2019 benefits in a timely manner.  As a result, January 2019's benefits will show a significant increase over the previous month and February 2019's benefits will show significantly less than January 2019.", '', '', '', '', '']

In [421]:
for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,24,39,54,69,84,99,114,129,131]:
        #for the rows that have the state names
        state = row[0]
        if state == 'WRO':
            break
        else:
            continue       
    if i in [20,23,37,52,67,82,97,112,127,130,144]:
        
        snap_data_2019[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

In [422]:
pprint.pprint(snap_data_2019)

{'Alabama': {'cost_by_household': 272.5566416666667,
             'cost_by_individual': 128.93534166666666,
             'household_participation': 315550.5833,
             'individual_participation': 667042.9167,
             'total_cost': 1032064886.0},
 'Alaska': {'cost_by_household': 401.6981333333333,
            'cost_by_individual': 180.631925,
            'household_participation': 35493.4167,
            'individual_participation': 78932.0,
            'total_cost': 171091672.0},
 'American Samoa': {'cost_by_household': '',
                    'cost_by_individual': '',
                    'household_participation': '',
                    'individual_participation': '',
                    'total_cost': ''},
 'Arizona': {'cost_by_household': 276.89821666666666,
             'cost_by_individual': 129.68056666666666,
             'household_participation': 345106.4167,
             'individual_participation': 736882.5833,
             'total_cost': 1146712214.0},
 'Arkansas': {'cost_by_household': 240.91523333333333,
              'cost_by_individual': 108.084875,
              'household_participation': 159230.8333,
              'individual_participation': 354916.75,
              'total_cost': 460333605.0},
 'California': {'cost_by_household': 276.20395833333333,
                'cost_by_individual': 141.127925,
                'household_participation': 1803402.0,
                'individual_participation': 3529470.0,
                'total_cost': 5977281299.0},
 'Colorado': {'cost_by_household': 256.32036666666664,
              'cost_by_individual': 128.22378333333333,
              'household_participation': 207747.75,
              'individual_participation': 415289.4167,
              'total_cost': 638999751.0},
 'Commonwealth of Northern Mariana Islands': {'cost_by_household': '',
                                              'cost_by_individual': '',
                                              'household_participation': '',
                                              'individual_participation': '',
                                              'total_cost': ''},
 'Connecticut': {'cost_by_household': 246.39140833333335,
                 'cost_by_individual': 143.125425,
                 'household_participation': 197760.75,
                 'individual_participation': 340446.5,
                 'total_cost': 584718600.0},
 'Delaware': {'cost_by_household': 253.22984166666666,
              'cost_by_individual': 123.92758333333333,
              'household_participation': 58622.1667,
              'individual_participation': 119786.75,
              'total_cost': 178138585.0},
 'District of Columbia': {'cost_by_household': 238.37771666666666,
                          'cost_by_individual': 141.6566,
                          'household_participation': 60156.25,
                          'individual_participation': 101230.0833,
                          'total_cost': 172078913.0},
 'Florida': {'cost_by_household': 235.18143333333333,
             'cost_by_individual': 126.911325,
             'household_participation': 1429884.0833,
             'individual_participation': 2649741.3333,
             'total_cost': 4035386245.0},
 'Georgia': {'cost_by_household': 286.7157916666667,
             'cost_by_individual': 132.25910833333333,
             'household_participation': 614749.6667,
             'individual_participation': 1332675.25,
             'total_cost': 2115101241.0},
 'Guam': {'cost_by_household': 582.926275,
          'cost_by_individual': 203.89951666666667,
          'household_participation': 14316.8333,
          'individual_participation': 40930.25,
          'total_cost': 100147900.0},
 'Hawaii': {'cost_by_household': 499.45804166666665,
            'cost_by_individual': 257.85716666666667,
            'household_participation': 74819.6667,
            'individual_participation': 144922.4167,
            'total_cost': 448431408.0},
 'Idaho': {'cost_by_household': 261.87699166666664,
           'cost_by_individual': 118.27746666666667,
           'household_participation': 61389.5833,
           'individual_participation': 135922.0833,
           'total_cost': 192918233.0},
 'Illinois': {'cost_by_household': 270.2096583333333,
              'cost_by_individual': 134.50255,
              'household_participation': 816044.0833,
              'individual_participation': 1639396.3333,
              'total_cost': 2646035880.0},
 'Indiana': {'cost_by_household': 286.6254,
             'cost_by_individual': 128.78163333333333,
             'household_participation': 238303.1667,
             'individual_participation': 530384.1667,
             'total_cost': 819644875.0},
 'Iowa': {'cost_by_household': 251.05785833333334,
          'cost_by_individual': 120.9959,
          'household_participation': 142502.0833,
          'individual_participation': 295681.6667,
          'total_cost': 429315218.0},
 'Kansas': {'cost_by_household': 253.680875,
            'cost_by_individual': 119.30239166666667,
            'household_participation': 87157.5833,
            'individual_participation': 185329.1667,
            'total_cost': 265322548.0},
 'Kentucky': {'cost_by_household': 271.6025333333333,
              'cost_by_individual': 122.66648333333333,
              'household_participation': 226832.0,
              'individual_participation': 502241.0833,
              'total_cost': 739297747.0},
 'Louisiana': {'cost_by_household': 290.32985,
               'cost_by_individual': 135.04115833333333,
               'household_participation': 348643.0833,
               'individual_participation': 749560.3333,
               'total_cost': 1214657938.0},
 'Maine': {'cost_by_household': 215.17555833333333,
           'cost_by_individual': 117.48873333333333,
           'household_participation': 78862.1667,
           'individual_participation': 144432.6667,
           'total_cost': 203630527.0},
 'Maryland': {'cost_by_household': 237.601125,
              'cost_by_individual': 128.35764166666667,
              'household_participation': 308166.9167,
              'individual_participation': 570443.6667,
              'total_cost': 878649666.0},
 'Massachusetts': {'cost_by_household': 226.52240833333335,
                   'cost_by_individual': 133.9875,
                   'household_participation': 416128.25,
                   'individual_participation': 703516.1667,
                   'total_cost': 1131148466.0},
 'Michigan': {'cost_by_household': 224.451675,
              'cost_by_individual': 119.95701666666666,
              'household_participation': 631698.8333,
              'individual_participation': 1181972.25,
              'total_cost': 1701430344.0},
 'Minnesota': {'cost_by_household': 219.19986666666668,
               'cost_by_individual': 111.20424166666666,
               'household_participation': 193683.5,
               'individual_participation': 381778.5833,
               'total_cost': 509464759.0},
 'Mississippi': {'cost_by_household': 257.68710833333336,
                 'cost_by_individual': 119.9452,
                 'household_participation': 195903.0,
                 'individual_participation': 420872.8333,
                 'total_cost': 605780127.0},
 'Missouri': {'cost_by_household': 277.40291666666667,
              'cost_by_individual': 129.84946666666667,
              'household_participation': 299267.5,
              'individual_participation': 639337.8333,
              'total_cost': 996212141.0},
 'Montana': {'cost_by_household': 250.0386,
             'cost_by_individual': 123.2318,
             'household_participation': 48973.8333,
             'individual_participation': 99368.4167,
             'total_cost': 146944184.0},
 'Nebraska': {'cost_by_household': 273.4470416666667,
              'cost_by_individual': 124.33308333333333,
              'household_participation': 67642.8333,
              'individual_participation': 148767.5833,
              'total_cost': 221960791.0},
 'Nevada': {'cost_by_household': 237.567475,
            'cost_by_individual': 125.04238333333333,
            'household_participation': 206100.0,
            'individual_participation': 391568.5,
            'total_cost': 587551886.0},
 'New Hampshire': {'cost_by_household': 211.00869166666666,
                   'cost_by_individual': 109.93558333333333,
                   'household_participation': 36684.5833,
                   'individual_participation': 70411.8333,
                   'total_cost': 92889191.0},
 'New Jersey': {'cost_by_household': 243.75795833333333,
                'cost_by_individual': 122.41543333333334,
                'household_participation': 325992.3333,
                'individual_participation': 649127.5,
                'total_cost': 953558696.0},
 'New Mexico': {'cost_by_household': 258.230975,
                'cost_by_individual': 127.04066666666667,
                'household_participation': 204244.75,
                'individual_participation': 415160.9167,
                'total_cost': 632907856.0},
 'New York': {'cost_by_household': 239.11521666666667,
              'cost_by_individual': 135.86609166666668,
              'household_participation': 1512387.3333,
              'individual_participation': 2661700.3333,
              'total_cost': 4339617966.0},
 'North Carolina': {'cost_by_household': 263.195125,
                    'cost_by_individual': 126.42603333333334,
                    'household_participation': 590074.5,
                    'individual_participation': 1228423.6667,
                    'total_cost': 1863656810.0},
 'North Dakota': {'cost_by_household': 261.027625,
                  'cost_by_individual': 125.95278333333333,
                  'household_participation': 21864.1667,
                  'individual_participation': 45311.8333,
                  'total_cost': 68485818.0},
 'Ohio': {'cost_by_household': 266.34380833333336,
          'cost_by_individual': 132.23945833333335,
          'household_participation': 632170.8333,
          'individual_participation': 1273256.75,
          'total_cost': 2020497444.0},
 'Oklahoma': {'cost_by_household': 275.7488583333333,
              'cost_by_individual': 128.44075833333332,
              'household_participation': 247672.9167,
              'individual_participation': 531727.8333,
              'total_cost': 819546294.0},
 'Oregon': {'cost_by_household': 226.7831,
            'cost_by_individual': 132.778575,
            'household_participation': 324902.8333,
            'individual_participation': 554927.4167,
            'total_cost': 884189650.0},
 'Pennsylvania': {'cost_by_household': 239.997175,
                  'cost_by_individual': 128.69845833333332,
                  'household_participation': 872821.5833,
                  'individual_participation': 1627639.6667,
                  'total_cost': 2513696584.0},
 'Rhode Island': {'cost_by_household': 241.0078,
                  'cost_by_individual': 144.10263333333333,
                  'household_participation': 84445.25,
                  'individual_participation': 141232.4167,
                  'total_cost': 244223564.0},
 'South Carolina': {'cost_by_household': 274.23585833333334,
                    'cost_by_individual': 127.47149166666667,
                    'household_participation': 259707.3333,
                    'individual_participation': 558721.5,
                    'total_cost': 854652751.0},
 'South Dakota': {'cost_by_household': 289.07694166666664,
                  'cost_by_individual': 135.51400833333332,
                  'household_participation': 35168.1667,
                  'individual_participation': 75020.3333,
                  'total_cost': 121995672.0},
 'Tennessee': {'cost_by_household': 273.0548333333333,
               'cost_by_individual': 130.91386666666668,
               'household_participation': 398957.75,
               'individual_participation': 832129.9167,
               'total_cost': 1307248122.0},
 'Texas': {'cost_by_household': 291.0464583333333,
           'cost_by_individual': 124.64064166666667,
           'household_participation': 1364934.6667,
           'individual_participation': 3187238.0833,
           'total_cost': 4767112796.0},
 'Utah': {'cost_by_household': 288.27735,
          'cost_by_individual': 121.53305,
          'household_participation': 67803.0,
          'individual_participation': 160829.25,
          'total_cost': 234552832.0},
 'Vermont': {'cost_by_household': 217.42331666666666,
             'cost_by_individual': 122.35565,
             'household_participation': 38423.0,
             'individual_participation': 68276.8333,
             'total_cost': 100248674.0},
 'Virgin Islands': {'cost_by_household': 361.0765333333333,
                    'cost_by_individual': 175.95379166666666,
                    'household_participation': 10394.6667,
                    'individual_participation': 21331.0,
                    'total_cost': 45039243.0},
 'Virginia': {'cost_by_household': 262.2479666666667,
              'cost_by_individual': 127.55221666666667,
              'household_participation': 318521.75,
              'individual_participation': 654882.25,
              'total_cost': 1002380166.0},
 'Washington': {'cost_by_household': 206.14095833333334,
                'cost_by_individual': 119.26743333333333,
                'household_participation': 482024.6667,
                'individual_participation': 833127.9167,
                'total_cost': 1192380309.0},
 'West Virginia': {'cost_by_household': 223.87889166666668,
                   'cost_by_individual': 117.30724166666667,
                   'household_participation': 148108.3333,
                   'individual_participation': 282662.25,
                   'total_cost': 397899950.0},
 'Wisconsin': {'cost_by_household': 222.35113333333334,
               'cost_by_individual': 113.33529166666666,
               'household_participation': 291720.6667,
               'individual_participation': 572323.25,
               'total_cost': 778373061.0},
 'Wyoming': {'cost_by_household': 277.04085833333335,
             'cost_by_individual': 124.36148333333334,
             'household_participation': 10912.0833,
             'individual_participation': 24308.9167,
             'total_cost': 36277115.0}}

In [423]:
snap_data_2019 = pd.DataFrame.from_dict(snap_data_2019, orient = "index")

In [424]:
pd.DataFrame.to_csv(snap_data_2019,'SNAP/SNAP DFs/snap_2019_df.csv')

# 2018

In [425]:
book = xlrd.open_workbook('SNAP/FY18.xls')

In [426]:
snap_data = {}

########################
#                      #
# NERO                 #
#                      #
########################

sheet = book.sheet_by_name('NERO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [x for x in range(7, sheet.nrows, 15)]:
        #for the rows that have the state names
        state = row[0]
        if state == 'NERO':
            break
        else:
            continue         
    if i in [x for x in range(20, sheet.nrows, 15)]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# MARO                 #
#                      #
########################

sheet = book.sheet_by_name('MARO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,84,99,114,129]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MARO':
            break
        else:
            continue       
    if i in [20,35,50,65,80,97,112]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# SERO                 #
#                      #
########################

sheet = book.sheet_by_name('SERO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SERO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# MWRO                 #
#                      #
########################

sheet = book.sheet_by_name('MWRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MWRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# SWRO                 #
#                      #
########################

sheet = book.sheet_by_name('SWRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SWRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# MPRO                 #
#                      #
########################
sheet = book.sheet_by_name('MPRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MPRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }


########################
#                      #
# WRO                  #
#                      #
########################
sheet = book.sheet_by_name('WRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'WRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

In [427]:
pprint.pprint(snap_data)

{'Alabama': {'cost_by_household': 251.0096,
             'cost_by_individual': 117.885175,
             'household_participation': 360067.0,
             'individual_participation': 766680.5833,
             'total_cost': 1084563290.0},
 'Alaska': {'cost_by_household': 385.3609833333333,
            'cost_by_individual': 169.71675833333333,
            'household_participation': 40515.5,
            'individual_participation': 91995.0,
            'total_cost': 187357117.0},
 'American Samoa': {'cost_by_household': 268.3873,
                    'cost_by_individual': 133.4658,
                    'household_participation': 1927173.0,
                    'individual_participation': 3875364.0,
                    'total_cost': 517228663.0},
 'Arizona': {'cost_by_household': 260.2019666666667,
             'cost_by_individual': 119.26839166666667,
             'household_participation': 387657.1667,
             'individual_participation': 845732.5,
             'total_cost': 1210429898.0},
 'Arkansas': {'cost_by_household': 243.01446666666666,
              'cost_by_individual': 107.50238333333333,
              'household_participation': 164761.3333,
              'individual_participation': 372451.1667,
              'total_cost': 480472657.0},
 'Colorado': {'cost_by_household': 251.289725,
              'cost_by_individual': 123.86530833333333,
              'household_participation': 221726.4167,
              'individual_participation': 449823.8333,
              'total_cost': 668610833.0},
 'Connecticut': {'cost_by_household': 229.55705,
                 'cost_by_individual': 132.30961666666667,
                 'household_participation': 223244.4167,
                 'individual_participation': 387328.8333,
                 'total_cost': 614967955.0},
 'Delaware': {'cost_by_household': 239.347275,
              'cost_by_individual': 116.95328333333333,
              'household_participation': 68554.1667,
              'individual_participation': 140297.5,
              'total_cost': 196899033.0},
 'District of Columbia': {'cost_by_household': 228.05636666666666,
                          'cost_by_individual': 139.85119166666667,
                          'household_participation': 68854.8333,
                          'individual_participation': 112282.0833,
                          'total_cost': 188433398.0},
 'Florida': {'cost_by_household': 274.80201666666665,
             'cost_by_individual': 143.483475,
             'household_participation': 1747853.0833,
             'individual_participation': 3347518.3333,
             'total_cost': 5763762595.0},
 'Georgia': {'cost_by_household': 269.9028416666667,
             'cost_by_individual': 125.11295,
             'household_participation': 721490.5833,
             'individual_participation': 1556452.4167,
             'total_cost': 2336788286.0},
 'Illinois': {'cost_by_household': 251.55155833333333,
              'cost_by_individual': 126.77674166666667,
              'household_participation': 920271.4167,
              'individual_participation': 1826010.9167,
              'total_cost': 2777948512.0},
 'Indiana': {'cost_by_household': 262.5375916666667,
             'cost_by_individual': 117.16471666666666,
             'household_participation': 275367.9167,
             'individual_participation': 617032.4167,
             'total_cost': 867533147.0},
 'Iowa': {'cost_by_household': 225.22549166666667,
          'cost_by_individual': 107.66554166666667,
          'household_participation': 165116.0,
          'individual_participation': 345406.0833,
          'total_cost': 446259982.0},
 'Kansas': {'cost_by_household': 241.13031666666666,
            'cost_by_individual': 112.509025,
            'household_participation': 101445.8333,
            'individual_participation': 217419.5833,
            'total_cost': 293539988.0},
 'Kentucky': {'cost_by_household': 249.03678333333335,
              'cost_by_individual': 115.658975,
              'household_participation': 285763.3333,
              'individual_participation': 615305.3333,
              'total_cost': 853986982.0},
 'Louisiana': {'cost_by_household': 268.00539166666664,
               'cost_by_individual': 124.6454,
               'household_participation': 403387.9167,
               'individual_participation': 867341.5833,
               'total_cost': 1297321641.0},
 'Maine': {'cost_by_household': 204.119325,
           'cost_by_individual': 108.33466666666666,
           'household_participation': 89089.0833,
           'individual_participation': 167857.6667,
           'total_cost': 218217647.0},
 'Maryland': {'cost_by_household': 220.51230833333332,
              'cost_by_individual': 117.314025,
              'household_participation': 343933.4167,
              'individual_participation': 646483.25,
              'total_cost': 910098604.0},
 'Massachusetts': {'cost_by_household': 214.14164166666666,
                   'cost_by_individual': 125.35366666666667,
                   'household_participation': 451071.5833,
                   'individual_participation': 770565.5,
                   'total_cost': 1159118509.0},
 'Michigan': {'cost_by_household': 230.75480833333333,
              'cost_by_individual': 123.130725,
              'household_participation': 684001.0833,
              'individual_participation': 1281861.5,
              'total_cost': 1894038446.0},
 'Minnesota': {'cost_by_household': 213.545025,
               'cost_by_individual': 105.75714166666667,
               'household_participation': 212453.25,
               'individual_participation': 428986.0,
               'total_cost': 544420005.0},
 'Mississippi': {'cost_by_household': 244.314025,
                 'cost_by_individual': 112.09701666666666,
                 'household_participation': 231847.3333,
                 'individual_participation': 505308.3333,
                 'total_cost': 679722657.0},
 'Missouri': {'cost_by_household': 258.36544166666664,
              'cost_by_individual': 120.072875,
              'household_participation': 342323.3333,
              'individual_participation': 736590.3333,
              'total_cost': 1061334229.0},
 'Montana': {'cost_by_household': 235.59559166666668,
             'cost_by_individual': 114.55320833333333,
             'household_participation': 56024.5833,
             'individual_participation': 115222.8333,
             'total_cost': 158389738.0},
 'Nebraska': {'cost_by_household': 249.83940833333332,
              'cost_by_individual': 112.48096666666666,
              'household_participation': 76451.1667,
              'individual_participation': 169811.0833,
              'total_cost': 229206174.0},
 'New Hampshire': {'cost_by_household': 194.43469166666668,
                   'cost_by_individual': 97.75325,
                   'household_participation': 43489.25,
                   'individual_participation': 86501.6667,
                   'total_cost': 101469828.0},
 'New Jersey': {'cost_by_household': 222.45783333333333,
                'cost_by_individual': 110.99238333333334,
                'household_participation': 379343.1667,
                'individual_participation': 760303.1667,
                'total_cost': 1012654300.0},
 'New Mexico': {'cost_by_household': 241.451925,
                'cost_by_individual': 116.606575,
                'household_participation': 220341.25,
                'individual_participation': 456250.5833,
                'total_cost': 638421821.0},
 'New York': {'cost_by_household': 240.969425,
              'cost_by_individual': 134.89410833333332,
              'household_participation': 1565541.25,
              'individual_participation': 2796620.1667,
              'total_cost': 4526970965.0},
 'North Carolina': {'cost_by_household': 248.65138333333334,
                    'cost_by_individual': 118.94595,
                    'household_participation': 643153.4167,
                    'individual_participation': 1344484.5,
                    'total_cost': 1919051873.0},
 'North Dakota': {'cost_by_household': 250.58640833333334,
                  'cost_by_individual': 119.39335833333334,
                  'household_participation': 25071.5833,
                  'individual_participation': 52621.0,
                  'total_cost': 75391175.0},
 'Ohio': {'cost_by_household': 243.91645833333334,
          'cost_by_individual': 121.84509166666666,
          'household_participation': 710023.5,
          'individual_participation': 1421365.5833,
          'total_cost': 2078237006.0},
 'Oklahoma': {'cost_by_household': 258.225,
              'cost_by_individual': 118.59863333333334,
              'household_participation': 268710.5833,
              'individual_participation': 585064.0,
              'total_cost': 832653493.0},
 'Pennsylvania': {'cost_by_household': 225.85478333333333,
                  'cost_by_individual': 118.781825,
                  'household_participation': 956434.5,
                  'individual_participation': 1818588.8333,
                  'total_cost': 2592183684.0},
 'Rhode Island': {'cost_by_household': 229.28045,
                  'cost_by_individual': 135.85664166666666,
                  'household_participation': 94204.8333,
                  'individual_participation': 158986.1667,
                  'total_cost': 259191919.0},
 'South Carolina': {'cost_by_household': 255.5071,
                    'cost_by_individual': 119.52275,
                    'household_participation': 307859.1667,
                    'individual_participation': 658119.0833,
                    'total_cost': 943922431.0},
 'South Dakota': {'cost_by_household': 273.36775,
                  'cost_by_individual': 124.99799166666666,
                  'household_participation': 39968.3333,
                  'individual_participation': 87409.8333,
                  'total_cost': 131112641.0},
 'Tennessee': {'cost_by_household': 251.920875,
               'cost_by_individual': 122.30298333333333,
               'household_participation': 471342.0833,
               'individual_participation': 970875.0,
               'total_cost': 1424890904.0},
 'Texas': {'cost_by_household': 281.42833333333334,
           'cost_by_individual': 118.204625,
           'household_participation': 1636052.25,
           'individual_participation': 3895206.8333,
           'total_cost': 5525177455.0},
 'Total': {'cost_by_household': 207.9993,
           'cost_by_individual': 120.2062,
           'household_participation': 492935.0,
           'individual_participation': 852952.0,
           'total_cost': 102530156.0},
 'Utah': {'cost_by_household': 276.94126666666665,
          'cost_by_individual': 113.93709166666666,
          'household_participation': 77795.0833,
          'individual_participation': 189092.6667,
          'total_cost': 258536027.0},
 'Vermont': {'cost_by_household': 217.38886666666667,
             'cost_by_individual': 121.80125,
             'household_participation': 40933.5833,
             'individual_participation': 73057.5833,
             'total_cost': 106782062.0},
 'Virgin Islands': {'cost_by_household': 480.9207916666667,
                    'cost_by_individual': 220.65313333333333,
                    'household_participation': 15064.0833,
                    'individual_participation': 32832.6667,
                    'total_cost': 86935571.0},
 'Virginia': {'cost_by_household': 248.784925,
              'cost_by_individual': 119.05405,
              'household_participation': 352312.6667,
              'individual_participation': 736220.9167,
              'total_cost': 1051800978.0},
 'West Virginia': {'cost_by_household': 221.86425833333334,
                   'cost_by_individual': 114.300775,
                   'household_participation': 165378.4167,
                   'individual_participation': 321008.8333,
                   'total_cost': 440298715.0},
 'Wisconsin': {'cost_by_household': 206.782775,
               'cost_by_individual': 104.26576666666666,
               'household_participation': 329203.0,
               'individual_participation': 652884.5833,
               'total_cost': 816882114.0},
 'Wyoming': {'cost_by_household': 260.96956666666665,
             'cost_by_individual': 115.5701,
             'household_participation': 12988.8333,
             'individual_participation': 29330.1667,
             'total_cost': 40676283.0}}

In [428]:
snap_data_2018 = pd.DataFrame.from_dict(snap_data, orient = "index")

In [429]:
pd.DataFrame.to_csv(snap_data_2018,'SNAP/SNAP DFs/snap_2018_df.csv')

# 2017

In [430]:
book = xlrd.open_workbook('SNAP/FY17.xls')

In [431]:
snap_data = {}

########################
#                      #
# NERO                 #
#                      #
########################

sheet = book.sheet_by_name('NERO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [x for x in range(7, sheet.nrows, 15)]:
        #for the rows that have the state names
        state = row[0]
        if state == 'NERO':
            break
        else:
            continue         
    if i in [x for x in range(20, sheet.nrows, 15)]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# MARO                 #
#                      #
########################

sheet = book.sheet_by_name('MARO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,84,99,114,129]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MARO':
            break
        else:
            continue       
    if i in [20,35,50,65,80,97,112]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# SERO                 #
#                      #
########################

sheet = book.sheet_by_name('SERO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SERO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# MWRO                 #
#                      #
########################

sheet = book.sheet_by_name('MWRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MWRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# SWRO                 #
#                      #
########################

sheet = book.sheet_by_name('SWRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SWRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# MPRO                 #
#                      #
########################
sheet = book.sheet_by_name('MPRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MPRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }


########################
#                      #
# WRO                  #
#                      #
########################
sheet = book.sheet_by_name('WRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'WRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

In [432]:
snap_data_2017 = pd.DataFrame.from_dict(snap_data, orient = "index")

In [433]:
pd.DataFrame.to_csv(snap_data_2017,'SNAP/SNAP DFs/snap_2017_df.csv')

# 2016

In [434]:
book = xlrd.open_workbook('SNAP/FY16.xls')

In [435]:
snap_data = {}

########################
#                      #
# NERO                 #
#                      #
########################

sheet = book.sheet_by_name('NERO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [x for x in range(7, sheet.nrows, 15)]:
        #for the rows that have the state names
        state = row[0]
        if state == 'NERO':
            break
        else:
            continue         
    if i in [x for x in range(20, sheet.nrows, 15)]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# MARO                 #
#                      #
########################

sheet = book.sheet_by_name('MARO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,84,99,114,129]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MARO':
            break
        else:
            continue       
    if i in [20,35,50,65,80,97,112]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# SERO                 #
#                      #
########################

sheet = book.sheet_by_name('SERO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SERO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# MWRO                 #
#                      #
########################

sheet = book.sheet_by_name('MWRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MWRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# SWRO                 #
#                      #
########################

sheet = book.sheet_by_name('SWRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SWRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# MPRO                 #
#                      #
########################
sheet = book.sheet_by_name('MPRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MPRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }


########################
#                      #
# WRO                  #
#                      #
########################
sheet = book.sheet_by_name('WRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'WRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

In [436]:
snap_data_2016 = pd.DataFrame.from_dict(snap_data, orient = "index")

In [437]:
pd.DataFrame.to_csv(snap_data_2016,'SNAP/SNAP DFs/snap_2016_df.csv')

# 2015

In [438]:
book = xlrd.open_workbook('SNAP/FY15.xls')

In [439]:
snap_data = {}

########################
#                      #
# NERO                 #
#                      #
########################

sheet = book.sheet_by_name('NERO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [x for x in range(7, sheet.nrows, 15)]:
        #for the rows that have the state names
        state = row[0]
        if state == 'NERO':
            break
        else:
            continue         
    if i in [x for x in range(20, sheet.nrows, 15)]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# MARO                 #
#                      #
########################

sheet = book.sheet_by_name('MARO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,84,99,114,129]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MARO':
            break
        else:
            continue       
    if i in [20,35,50,65,80,97,112]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# SERO                 #
#                      #
########################

sheet = book.sheet_by_name('SERO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SERO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# MWRO                 #
#                      #
########################

sheet = book.sheet_by_name('MWRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MWRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# SWRO                 #
#                      #
########################

sheet = book.sheet_by_name('SWRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SWRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

########################
#                      #
# MPRO                 #
#                      #
########################
sheet = book.sheet_by_name('MPRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MPRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }


########################
#                      #
# WRO                  #
#                      #
########################
sheet = book.sheet_by_name('WRO')

for i in range(7, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [7,22,37,52,67,82,97,112,127,142]:
        #for the rows that have the state names
        state = row[0]
        if state == 'WRO':
            break
        else:
            continue       
    if i in [20, 35, 50, 65, 80, 95, 110, 125]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[3],
        'cost_by_household' : row[4],
        'cost_by_individual': row[5],
        }

In [440]:
snap_data_2015 = pd.DataFrame.from_dict(snap_data, orient = "index")

In [441]:
pd.DataFrame.to_csv(snap_data_2015,'SNAP/SNAP DFs/snap_2015_df.csv')

# 2014 *NOTE FORMAT CHANGES

In [442]:
book = xlrd.open_workbook('SNAP/FY14.xls')

In [443]:
sheet = book.sheet_by_name('NERO')

In [444]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '11/06/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2014', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Connecticut', '', '', '', '', '']
6 ['Oct 2013', 239908.0, 436283.0, 252.531, 138.8645, 60584199.0]
7 ['Nov 2013', 236117.0, 429190.0, 242.7713, 133.5596, 57322425.0]
8 ['Dec 2013', 240909.0, 437131.0, 235.963, 130.0425, 56845599.0]
9 ['Jan 2014', 241877.0, 438848.0, 235.6142, 129.862, 56989662.0]
10 ['Feb 2014', 240671.0, 435832.0, 237.7199, 131.2714, 57212289.0]
11 ['Mar 2014', 243040.0, 438438.0, 239.8063, 132.9322, 58282520.0]
12 ['Apr 2014', 243128.0, 438338.0, 240.2715, 133.2687, 58416734.0]
13 ['May 2014', 244294.0, 439405.0, 241.6258, 134.3356, 59027724.0]
14 ['Jun 2014', 244885.0, 440132.0, 236.1381, 131.3848, 57826672.0]
15 ['Jul 2014', 246068.0, 441782.0, 236.2252, 131.575, 58127456.0]
16 ['Aug 2014', 246341.0, 441645.0, 238.4971, 133.029, 58751610.0]
17 ['Sep 2014', 248547.0, 445682.0, 233.5525, 130.2471, 58048782.0]
18 ['Total', 242982.0833, 438558.8333, 239.1931, 132.5242, 697435672.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Maine', '', '', '', '', '']
22 ['Oct 2013', 127274.0, 241371.0, 235.9028, 124.3906, 30024295.0]
23 ['Nov 2013', 125728.0, 237780.0, 218.115, 115.33, 27423157.0]
24 ['Dec 2013', 124599.0, 235842.0, 219.6493, 116.0442, 27368088.0]
25 ['Jan 2014', 124143.0, 235771.0, 218.3356, 114.9626, 27104841.0]
26 ['Feb 2014', 123212.0, 233609.0, 218.7426, 115.3711, 26951717.0]
27 ['Mar 2014', 122601.0, 232610.0, 220.9385, 116.4493, 27087276.0]
28 ['Apr 2014', 121190.0, 229516.0, 219.5914, 115.9496, 26612278.0]
29 ['May 2014', 131784.0, 228069.0, 202.0178, 116.7309, 26622710.0]
30 ['Jun 2014', 119336.0, 225815.0, 219.1446, 115.8109, 26151837.0]
31 ['Jul 2014', 120960.0, 227666.0, 212.8894, 113.1091, 25751106.0]
32 ['Aug 2014', 116558.0, 221263.0, 219.5334, 115.6469, 25588379.0]
33 ['Sep 2014', 114900.0, 217115.0, 216.4041, 114.5238, 24864829.0]
34 ['Total', 122690.4167, 230535.5833, 218.4024, 116.2331, 321550513.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Massachusetts', '', '', '', '', '']
38 ['Oct 2013', 501212.0, 889565.0, 233.3421, 131.4731, 116953866.0]
39 ['Nov 2013', 499467.0, 885920.0, 218.2968, 123.0721, 109032044.0]
40 ['Dec 2013', 494376.0, 876992.0, 216.6184, 122.1117, 107090952.0]
41 ['Jan 2014', 493650.0, 874104.0, 215.2165, 121.5435, 106241640.0]
42 ['Feb 2014', 490931.0, 869489.0, 213.0014, 120.2649, 104568993.0]
43 ['Mar 2014', 491487.0, 867968.0, 216.0968, 122.3648, 106208765.0]
44 ['Apr 2014', 489466.0, 863113.0, 217.1077, 123.1204, 106266859.0]
45 ['May 2014', 486807.0, 857127.0, 216.8308, 123.1495, 105554773.0]
46 ['Jun 2014', 485281.0, 853866.0, 215.3198, 122.3735, 104490600.0]
47 ['Jul 2014', 484041.0, 850697.0, 214.8161, 122.229, 103979823.0]
48 ['Aug 2014', 481507.0, 845395.0, 214.6166, 122.238, 103339385.0]
49 ['Sep 2014', 470248.0, 826707.0, 211.0584, 120.0544, 99249788.0]
50 ['Total', 489039.4167, 863411.9167, 216.918, 122.8631, 1272977488.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['New Hampshire', '', '', '', '', '']
54 ['Oct 2013', 54837.0, 114919.0, 240.5242, 114.7732, 13189626.0]
55 ['Nov 2013', 54114.0, 113534.0, 222.9165, 106.2492, 12062902.0]
56 ['Dec 2013', 53913.0, 112922.0, 221.3371, 105.6743, 11932948.0]
57 ['Jan 2014', 54266.0, 113349.0, 218.5826, 104.6467, 11861602.0]
58 ['Feb 2014', 54008.0, 112773.0, 220.3257, 105.516, 11899353.0]
59 ['Mar 2014', 53985.0, 112504.0, 220.5053, 105.8094, 11903976.0]
60 ['Apr 2014', 53841.0, 112081.0, 219.1106, 105.2554, 11797132.0]
61 ['May 2014', 53509.0, 111375.0, 217.3442, 104.4209, 11629873.0]
62 ['Jun 2014', 53133.0, 110574.0, 214.7672, 103.1999, 11411226.0]
63 ['Jul 2014', 52561.0, 109236.0, 211.7355, 101.8806, 11129027.0]
64 ['Aug 2014', 52340.0, 108768.0, 210.4358, 101.2633, 11014211.0]
65 ['Sep 2014', 52201.0, 108381.0, 208.5544, 100.4489, 10886748.0]
66 ['Total', 53559.0, 111701.3333, 218.9464, 104.9813, 140718624.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['New York', '', '', '', '', '']
70 ['Oct 2013', 1712225.0, 3170323.0, 270.9407, 146.3294, 463911383.0]
71 ['Nov 2013', 1778279.0, 3243156.0, 284.4541, 155.9711, 505838731.0]
72 ['Dec 2013', 1708904.0, 3158376.0, 252.209, 136.4628, 431000956.0]
73 ['Jan 2014', 1708608.0, 3148532.0, 249.9249, 135.6263, 427023612.0]
74 ['Feb 2014', 1688379.0, 3114414.0, 249.9978, 135.5282, 422091040.0]
75 ['Mar 2014', 1688839.0, 3109524.0, 251.2238, 136.4442, 424276496.0]
76 ['Apr 2014', 1687248.0, 3103477.0, 251.5549, 136.7613, 424435469.0]
77 ['May 2014', 1688619.0, 3101888.0, 251.4884, 136.9063, 424668075.0]
78 ['Jun 2014', 1686095.0, 3094747.0, 250.8483, 136.6684, 422954102.0]
79 ['Jul 2014', 1683609.0, 3088298.0, 250.4396, 136.529, 421642288.0]
80 ['Aug 2014', 1677427.0, 3075125.0, 249.0636, 135.8598, 417785933.0]
81 ['Sep 2014', 1674479.0, 3066686.0, 247.9159, 135.3676, 415130008.0]
82 ['Total', 1698559.25, 3122878.8333, 255.1554, 138.7811, 5200758093.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Rhode Island', '', '', '', '', '']
86 ['Oct 2013', 101542.0, 180860.0, 248.609, 139.579, 25244254.0]
87 ['Nov 2013', 101040.0, 179742.0, 231.8476, 130.3306, 23425881.0]
88 ['Dec 2013', 101011.0, 179336.0, 229.963, 129.5267, 23228793.0]
89 ['Jan 2014', 101085.0, 179736.0, 228.8865, 128.7276, 23136990.0]
90 ['Feb 2014', 101047.0, 179420.0, 229.5853, 129.2995, 23198909.0]
91 ['Mar 2014', 101570.0, 179824.0, 230.3502, 130.1087, 23396666.0]
92 ['Apr 2014', 101072.0, 178483.0, 229.3011, 129.8494, 23175919.0]
93 ['May 2014', 101119.0, 178110.0, 229.1782, 130.1121, 23174271.0]
94 ['Jun 2014', 101094.0, 177697.0, 228.956, 130.2559, 23146074.0]
95 ['Jul 2014', 100290.0, 176146.0, 227.0301, 129.2613, 22768853.0]
96 ['Aug 2014', 100399.0, 176110.0, 227.5554, 129.7277, 22846337.0]
97 ['Sep 2014', 100758.0, 176750.0, 229.2656, 130.695, 23100340.0]
98 ['Total', 101002.25, 178517.8333, 230.8887, 130.6327, 279843287.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['Vermont', '', '', '', '', '']
102 ['Oct 2013', 52664.0, 100276.0, 239.9381, 126.0132, 12636101.0]
103 ['Nov 2013', 52323.0, 99405.0, 221.823, 116.7592, 11606447.0]
104 ['Dec 2013', 51891.0, 98607.0, 219.3288, 115.4197, 11381191.0]
105 ['Jan 2014', 51687.0, 98190.0, 221.2235, 116.4516, 11434378.0]
106 ['Feb 2014', 48213.0, 93397.0, 220.9252, 114.0451, 10651468.0]
107 ['Mar 2014', 47849.0, 92335.0, 222.2663, 115.1808, 10635219.0]
108 ['Apr 2014', 47343.0, 91107.0, 221.973, 115.3464, 10508867.0]
109 ['May 2014', 46856.0, 90009.0, 222.2565, 115.7001, 10414049.0]
110 ['Jun 2014', 46504.0, 89144.0, 222.2947, 115.9651, 10337592.0]
111 ['Jul 2014', 46023.0, 88207.0, 222.5949, 116.1414, 10244486.0]
112 ['Aug 2014', 45832.0, 87794.0, 223.9565, 116.9143, 10264373.0]
113 ['Sep 2014', 45711.0, 87525.0, 223.3665, 116.6559, 10210305.0]
114 ['Total', 48574.6667, 92999.6667, 223.581, 116.7786, 130324476.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['NERO', '', '', '', '', '']
118 ['Oct 2013', 2789662.0, 5133597.0, 259.0076, 140.748, 722543724.0]
119 ['Nov 2013', 2847068.0, 5188727.0, 262.2739, 143.9104, 746711587.0]
120 ['Dec 2013', 2775603.0, 5099206.0, 240.9741, 131.1672, 668848527.0]
121 ['Jan 2014', 2775316.0, 5088530.0, 239.1773, 130.4488, 663792725.0]
122 ['Feb 2014', 2746461.0, 5038934.0, 239.0617, 130.3001, 656573769.0]
123 ['Mar 2014', 2749371.0, 5033203.0, 240.7063, 131.485, 661790918.0]
124 ['Apr 2014', 2743288.0, 5016115.0, 241.0295, 131.8178, 661213258.0]
125 ['May 2014', 2752988.0, 5005983.0, 240.136, 132.0603, 661091475.0]
126 ['Jun 2014', 2736328.0, 4991975.0, 239.8536, 131.4746, 656318103.0]
127 ['Jul 2014', 2733552.0, 4982032.0, 239.1186, 131.2001, 653643039.0]
128 ['Aug 2014', 2720404.0, 4956100.0, 238.7845, 131.0688, 649590228.0]
129 ['Sep 2014', 2706844.0, 4928846.0, 236.9885, 130.1503, 641490800.0]
130 ['Total', 2756407.0833, 5038604.0, 243.1791, 133.033, 8043608153.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
134 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [445]:
snap_data = {}

########################
#                      #
# NERO                 #
#                      #
########################

for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117]:
        #for the rows that have the state names
        state = row[0]
        if state == 'NERO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [446]:
########################
#                      #
# MARO                 #
#                      #
########################

sheet = book.sheet_by_name('MARO')

In [447]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '11/06/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2014', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Delaware', '', '', '', '', '']
6 ['Oct 2013', 73662.0, 155762.0, 268.021, 126.7508, 19742961.0]
7 ['Nov 2013', 71828.0, 151800.0, 248.7221, 117.6891, 17865211.0]
8 ['Dec 2013', 72163.0, 152106.0, 251.5277, 119.3312, 18150990.0]
9 ['Jan 2014', 71102.0, 150018.0, 256.6434, 121.6378, 18247858.0]
10 ['Feb 2014', 69831.0, 147318.0, 262.179, 124.2769, 18308223.0]
11 ['Mar 2014', 69597.0, 146647.0, 258.9714, 122.9049, 18023633.0]
12 ['Apr 2014', 71073.0, 149158.0, 256.8411, 122.3835, 18254471.0]
13 ['May 2014', 71201.0, 149362.0, 255.9395, 122.0066, 18223149.0]
14 ['Jun 2014', 71648.0, 150029.0, 253.8539, 121.2307, 18188125.0]
15 ['Jul 2014', 72072.0, 151222.0, 257.1773, 122.57, 18535280.0]
16 ['Aug 2014', 71268.0, 149416.0, 255.0837, 121.6691, 18179307.0]
17 ['Sep 2014', 71451.0, 149950.0, 260.7885, 124.2654, 18633597.0]
18 ['Total', 71408.0, 150232.3333, 257.1523, 122.2289, 220352805.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['District of Columbia', '', '', '', '', '']
22 ['Oct 2013', 82468.0, 146278.0, 245.4492, 138.3783, 20241704.0]
23 ['Nov 2013', 81898.0, 145357.0, 228.952, 128.9976, 18750710.0]
24 ['Dec 2013', 80617.0, 143213.0, 228.8362, 128.8157, 18448085.0]
25 ['Jan 2014', 79975.0, 141969.0, 228.0126, 128.4457, 18235306.0]
26 ['Feb 2014', 79310.0, 140828.0, 229.2164, 129.0877, 18179156.0]
27 ['Mar 2014', 78815.0, 139844.0, 229.3183, 129.242, 18073722.0]
28 ['Apr 2014', 78867.0, 140024.0, 230.3433, 129.7383, 18166482.0]
29 ['May 2014', 79568.0, 141209.0, 229.5582, 129.3507, 18265489.0]
30 ['Jun 2014', 79910.0, 141992.0, 229.7017, 129.2711, 18355464.0]
31 ['Jul 2014', 80629.0, 143240.0, 230.1026, 129.5235, 18552946.0]
32 ['Aug 2014', 80825.0, 143761.0, 229.9779, 129.2977, 18587967.0]
33 ['Sep 2014', 81441.0, 144768.0, 230.1913, 129.4969, 18747010.0]
34 ['Total', 80360.25, 142706.9167, 230.8397, 129.9891, 222604041.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Maryland', '', '', '', '', '']
38 ['Oct 2013', 408103.0, 800022.0, 249.7896, 127.4213, 101939881.0]
39 ['Nov 2013', 406022.0, 794933.0, 232.5401, 118.7728, 94416391.0]
40 ['Dec 2013', 402761.0, 788442.0, 231.5171, 118.2662, 93246047.0]
41 ['Jan 2014', 401137.0, 783592.0, 228.709, 117.0809, 91743660.0]
42 ['Feb 2014', 400323.0, 781927.0, 231.8932, 118.7223, 92832163.0]
43 ['Mar 2014', 400738.0, 781441.0, 232.4394, 119.1994, 93147281.0]
44 ['Apr 2014', 402864.0, 784864.0, 232.9005, 119.5458, 93827229.0]
45 ['May 2014', 403554.0, 785557.0, 233.3771, 119.8898, 94180263.0]
46 ['Jun 2014', 405458.0, 788806.0, 233.3323, 119.9363, 94606446.0]
47 ['Jul 2014', 405601.0, 788843.0, 232.7837, 119.6909, 94417290.0]
48 ['Aug 2014', 404832.0, 787477.0, 233.6756, 120.1297, 94599359.0]
49 ['Sep 2014', 403983.0, 785263.0, 233.1283, 119.9342, 94179864.0]
50 ['Total', 403781.3333, 787597.25, 233.8592, 119.8938, 1133135874.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['New Jersey', '', '', '', '', '']
54 ['Oct 2013', 441538.0, 892606.0, 263.6406, 130.4129, 116407342.0]
55 ['Nov 2013', 429060.0, 864490.0, 244.2757, 121.2379, 104808928.0]
56 ['Dec 2013', 435372.0, 877177.0, 244.3835, 121.2956, 106397728.0]
57 ['Jan 2014', 435842.0, 877149.0, 240.7927, 119.6462, 104947572.0]
58 ['Feb 2014', 425301.0, 856916.0, 243.3305, 120.7688, 103488718.0]
59 ['Mar 2014', 443106.0, 891684.0, 244.0072, 121.2549, 108121068.0]
60 ['Apr 2014', 446829.0, 897138.0, 244.5603, 121.8058, 109276646.0]
61 ['May 2014', 435799.0, 872510.0, 244.5726, 122.1585, 106584515.0]
62 ['Jun 2014', 445255.0, 891560.0, 244.1642, 121.9383, 108715337.0]
63 ['Jul 2014', 448086.0, 897065.0, 243.0016, 121.3799, 108885622.0]
64 ['Aug 2014', 437595.0, 876183.0, 240.5439, 120.1356, 105260812.0]
65 ['Sep 2014', 452551.0, 906735.0, 238.192, 118.8815, 107794025.0]
66 ['Total', 439694.5, 883434.4167, 244.6184, 121.7491, 1290688313.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Pennsylvania', '', '', '', '', '']
70 ['Oct 2013', 888107.0, 1807510.0, 258.312, 126.9197, 229408706.0]
71 ['Nov 2013', 888346.0, 1802935.0, 239.2683, 117.8928, 212553011.0]
72 ['Dec 2013', 882304.0, 1788668.0, 239.7139, 118.2447, 211500547.0]
73 ['Jan 2014', 880107.0, 1782330.0, 239.8569, 118.4403, 211099733.0]
74 ['Feb 2014', 876245.0, 1772367.0, 238.6077, 117.9659, 209078829.0]
75 ['Mar 2014', 883788.0, 1785622.0, 239.9191, 118.7472, 212037628.0]
76 ['Apr 2014', 888020.0, 1790623.0, 239.7769, 118.9121, 212926708.0]
77 ['May 2014', 893127.0, 1799956.0, 240.3733, 119.2718, 214683910.0]
78 ['Jun 2014', 891630.0, 1794330.0, 239.8794, 119.1998, 213883701.0]
79 ['Jul 2014', 898623.0, 1806495.0, 239.7273, 119.25, 215424499.0]
80 ['Aug 2014', 903257.0, 1812819.0, 238.9008, 119.0349, 215788790.0]
81 ['Sep 2014', 903148.0, 1810197.0, 238.3567, 118.9215, 215271383.0]
82 ['Total', 889725.1667, 1796154.3333, 241.0536, 119.4059, 2573657445.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Puerto Rico', '', '', '', '', '']
86 [' No data found.', '', '', '', '', '']
87 ['', '', '', '', '', '']
88 ['', '', '', '', '', '']
89 ['Virginia', '', '', '', '', '']
90 ['Oct 2013', 459380.0, 945067.0, 262.0545, 127.38, 120382606.0]
91 ['Nov 2013', 456627.0, 940065.0, 242.6068, 117.8438, 110780802.0]
92 ['Dec 2013', 454235.0, 935642.0, 242.572, 117.7637, 110184707.0]
93 ['Jan 2014', 451425.0, 930264.0, 240.3951, 116.6555, 108520371.0]
94 ['Feb 2014', 449407.0, 926704.0, 242.2431, 117.4763, 108865740.0]
95 ['Mar 2014', 447162.0, 922065.0, 243.0537, 117.8706, 108684373.0]
96 ['Apr 2014', 444740.0, 918852.0, 243.6869, 117.9486, 108377314.0]
97 ['May 2014', 440967.0, 913672.0, 244.0249, 117.7741, 107606923.0]
98 ['Jun 2014', 437101.0, 908370.0, 244.1393, 117.478, 106713518.0]
99 ['Jul 2014', 431772.0, 901498.0, 244.1255, 116.9238, 105406573.0]
100 ['Aug 2014', 427438.0, 895829.0, 244.3837, 116.6058, 104458884.0]
101 ['Sep 2014', 423025.0, 888797.0, 244.1932, 116.2243, 103299820.0]
102 ['Total', 443606.5833, 918902.0833, 244.8269, 118.1919, 1303281631.0]
103 ['', '', '', '', '', '']
104 ['', '', '', '', '', '']
105 ['Virgin Islands', '', '', '', '', '']
106 ['Oct 2013', 12626.0, 28488.0, 391.4033, 173.4716, 4941858.0]
107 ['Nov 2013', 12604.0, 28357.0, 363.8447, 161.7202, 4585899.0]
108 ['Dec 2013', 12555.0, 28217.0, 363.2632, 161.632, 4560770.0]
109 ['Jan 2014', 12395.0, 27792.0, 366.0726, 163.2653, 4537470.0]
110 ['Feb 2014', 12212.0, 27258.0, 366.2942, 164.1054, 4473185.0]
111 ['Mar 2014', 12292.0, 27410.0, 367.2735, 164.7036, 4514526.0]
112 ['Apr 2014', 12315.0, 27482.0, 366.195, 164.0962, 4509691.0]
113 ['May 2014', 12402.0, 27595.0, 365.8866, 164.4402, 4537726.0]
114 ['Jun 2014', 12541.0, 27781.0, 366.2398, 165.3293, 4593013.0]
115 ['Jul 2014', 12614.0, 27901.0, 366.0708, 165.5001, 4617617.0]
116 ['Aug 2014', 12641.0, 27938.0, 367.5895, 166.3218, 4646699.0]
117 ['Sep 2014', 12538.0, 27668.0, 365.3696, 165.5705, 4581004.0]
118 ['Total', 12477.9167, 27823.9167, 367.9798, 165.0243, 55099458.0]
119 ['', '', '', '', '', '']
120 ['', '', '', '', '', '']
121 ['West Virginia', '', '', '', '', '']
122 ['Oct 2013', 170548.0, 356349.0, 242.8711, 116.2377, 41421172.0]
123 ['Nov 2013', 170791.0, 356038.0, 225.3722, 108.1108, 38491550.0]
124 ['Dec 2013', 170842.0, 354760.0, 225.2218, 108.4602, 38477337.0]
125 ['Jan 2014', 171381.0, 353507.0, 224.7546, 108.9615, 38518669.0]
126 ['Feb 2014', 175372.0, 362133.0, 223.7495, 108.3563, 39239390.0]
127 ['Mar 2014', 176566.0, 362392.0, 222.8167, 108.5616, 39341855.0]
128 ['Apr 2014', 177764.0, 364798.0, 223.7897, 109.0515, 39781751.0]
129 ['May 2014', 177426.0, 362759.0, 224.8992, 109.9986, 39902971.0]
130 ['Jun 2014', 180055.0, 368825.0, 222.515, 108.6286, 40064936.0]
131 ['Jul 2014', 180588.0, 369840.0, 222.2147, 108.5045, 40129305.0]
132 ['Aug 2014', 180160.0, 369360.0, 224.4704, 109.4883, 40440582.0]
133 ['Sep 2014', 180851.0, 369249.0, 222.9718, 109.2073, 40324682.0]
134 ['Total', 176028.6667, 362500.8333, 225.4056, 109.4559, 476134200.0]
135 ['', '', '', '', '', '']
136 ['', '', '', '', '', '']
137 ['MARO', '', '', '', '', '']
138 ['Oct 2013', 2536432.0, 5132082.0, 258.0342, 127.5284, 654486230.0]
139 ['Nov 2013', 2517176.0, 5083975.0, 239.2572, 118.4609, 602252502.0]
140 ['Dec 2013', 2510849.0, 5068225.0, 239.3478, 118.5753, 600966211.0]
141 ['Jan 2014', 2503364.0, 5046621.0, 238.02, 118.0692, 595850639.0]
142 ['Feb 2014', 2488001.0, 5015451.0, 238.9329, 118.5268, 594465404.0]
143 ['Mar 2014', 2512064.0, 5057105.0, 239.6213, 119.0294, 601944086.0]
144 ['Apr 2014', 2522472.0, 5072939.0, 239.8918, 119.284, 605120292.0]
145 ['May 2014', 2514044.0, 5052620.0, 240.2444, 119.539, 603984946.0]
146 ['Jun 2014', 2523598.0, 5071693.0, 239.7848, 119.3133, 605120540.0]
147 ['Jul 2014', 2529985.0, 5086104.0, 239.5149, 119.1421, 605969132.0]
148 ['Aug 2014', 2518016.0, 5062783.0, 239.0622, 118.8995, 601962400.0]
149 ['Sep 2014', 2528988.0, 5082627.0, 238.3686, 118.6063, 602831385.0]
150 ['Total', 2517082.4167, 5069352.0833, 240.8527, 119.5905, 7274953767.0]
151 ['', '', '', '', '', '']
152 ['', '', '', '', '', '']
153 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
154 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [448]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,89,105,121,137]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MARO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,87,102,118,134,150]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [449]:
########################
#                      #
# SERO                 #
#                      #
########################

sheet = book.sheet_by_name('SERO')

In [450]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '11/06/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2014', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Alabama', '', '', '', '', '']
6 ['Oct 2013', 424675.0, 915230.0, 281.8086, 130.7618, 119677081.0]
7 ['Nov 2013', 422903.0, 911698.0, 260.8884, 121.0165, 110330496.0]
8 ['Dec 2013', 421365.0, 908168.0, 260.7867, 120.9978, 109886367.0]
9 ['Jan 2014', 417456.0, 898898.0, 257.4748, 119.5735, 107484399.0]
10 ['Feb 2014', 417559.0, 898745.0, 259.188, 120.4193, 108226285.0]
11 ['Mar 2014', 417531.0, 897818.0, 259.8153, 120.8273, 108480939.0]
12 ['Apr 2014', 416914.0, 896185.0, 259.3499, 120.6521, 108126612.0]
13 ['May 2014', 418029.0, 898301.0, 261.242, 121.5703, 109206721.0]
14 ['Jun 2014', 418539.0, 899097.0, 260.0106, 121.0376, 108824566.0]
15 ['Jul 2014', 419050.0, 899307.0, 260.647, 121.4536, 109224109.0]
16 ['Aug 2014', 419974.0, 900886.0, 260.5899, 121.4815, 109440990.0]
17 ['Sep 2014', 420629.0, 900545.0, 259.6706, 121.2877, 109224997.0]
18 ['Total', 419552.0, 902073.1667, 261.8137, 121.7689, 1318133562.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Florida', '', '', '', '', '']
22 ['Oct 2013', 1932006.0, 3565296.0, 257.9799, 139.7973, 498418725.0]
23 ['Nov 2013', 1912768.0, 3536728.0, 241.324, 130.5152, 461596796.0]
24 ['Dec 2013', 1905774.0, 3522173.0, 240.4363, 130.095, 458217157.0]
25 ['Jan 2014', 1894943.0, 3493264.0, 238.9964, 129.6451, 452884539.0]
26 ['Feb 2014', 1879048.0, 3461816.0, 238.2473, 129.3188, 447678063.0]
27 ['Mar 2014', 1883340.0, 3451122.0, 236.5266, 129.0769, 445460028.0]
28 ['Apr 2014', 1889608.0, 3454704.0, 234.9309, 128.4994, 443927378.0]
29 ['May 2014', 1909113.0, 3487797.0, 233.773, 127.9602, 446299143.0]
30 ['Jun 2014', 1930106.0, 3526356.0, 232.187, 127.0846, 448145599.0]
31 ['Jul 2014', 1944048.0, 3555983.0, 232.678, 127.2046, 452337236.0]
32 ['Aug 2014', 1973852.0, 3612131.0, 231.6999, 126.6126, 457341403.0]
33 ['Sep 2014', 1993762.0, 3648365.0, 230.9844, 126.2286, 460527934.0]
34 ['Total', 1920697.3333, 3526311.25, 237.45, 129.3333, 5472834001.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Georgia', '', '', '', '', '']
38 ['Oct 2013', 874241.0, 1883966.0, 297.3605, 137.988, 259964778.0]
39 ['Nov 2013', 940662.0, 2123806.0, 246.7776, 109.3011, 232134272.0]
40 ['Dec 2013', 916996.0, 2075085.0, 250.9163, 110.8819, 230089269.0]
41 ['Jan 2014', 794714.0, 1727545.0, 280.8415, 129.1941, 223188696.0]
42 ['Feb 2014', 900583.0, 2044233.0, 248.3061, 109.3908, 223620229.0]
43 ['Mar 2014', 896220.0, 2034383.0, 259.5234, 114.3295, 232590033.0]
44 ['Apr 2014', 901362.0, 2044251.0, 259.6302, 114.4775, 234020813.0]
45 ['May 2014', 856636.0, 1847395.0, 274.0586, 127.0808, 234768478.0]
46 ['Jun 2014', 872005.0, 1877788.0, 273.6859, 127.0939, 238655493.0]
47 ['Jul 2014', 874132.0, 1882484.0, 273.7858, 127.1325, 239324963.0]
48 ['Aug 2014', 878717.0, 1889570.0, 273.5814, 127.2251, 240400668.0]
49 ['Sep 2014', 879110.0, 1881761.0, 271.9753, 127.0598, 239096184.0]
50 ['Total', 882114.8333, 1942688.9167, 267.1472, 121.3033, 2827853876.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Kentucky', '', '', '', '', '']
54 ['Oct 2013', 414737.0, 856784.0, 261.0795, 126.3788, 108279325.0]
55 ['Nov 2013', 408474.0, 845094.0, 241.8366, 116.8911, 98783965.0]
56 ['Dec 2013', 406074.0, 840047.0, 241.1122, 116.5523, 97909409.0]
57 ['Jan 2014', 402249.0, 832518.0, 238.8848, 115.4223, 96091175.0]
58 ['Feb 2014', 398545.0, 825684.0, 241.8705, 116.7472, 96396264.0]
59 ['Mar 2014', 400366.0, 828244.0, 242.707, 117.3224, 97171614.0]
60 ['Apr 2014', 398160.0, 824254.0, 242.9726, 117.3691, 96741977.0]
61 ['May 2014', 396523.0, 822231.0, 244.1833, 117.758, 96824304.0]
62 ['Jun 2014', 395929.0, 822619.0, 244.5269, 117.6916, 96815309.0]
63 ['Jul 2014', 391879.0, 816024.0, 244.5006, 117.4165, 95814664.0]
64 ['Aug 2014', 389287.0, 812783.0, 245.1532, 117.4175, 95434972.0]
65 ['Sep 2014', 388258.0, 810628.0, 243.9794, 116.8563, 94726970.0]
66 ['Total', 399206.75, 828075.8333, 244.441, 117.8425, 1170989948.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Mississippi', '', '', '', '', '']
70 ['Oct 2013', 308251.0, 671463.0, 271.1273, 124.4674, 83575260.0]
71 ['Nov 2013', 307230.0, 669599.0, 250.017, 114.7145, 76812715.0]
72 ['Dec 2013', 305042.0, 664936.0, 249.9518, 114.6664, 76245787.0]
73 ['Jan 2014', 303023.0, 660320.0, 247.6471, 113.646, 75042753.0]
74 ['Feb 2014', 301741.0, 657672.0, 249.6583, 114.5436, 75332151.0]
75 ['Mar 2014', 300309.0, 653779.0, 249.4425, 114.5797, 74909827.0]
76 ['Apr 2014', 299299.0, 650774.0, 249.7837, 114.8786, 74760007.0]
77 ['May 2014', 299694.0, 650853.0, 252.4344, 116.2368, 75653090.0]
78 ['Jun 2014', 299728.0, 650144.0, 249.9092, 115.2126, 74904778.0]
79 ['Jul 2014', 299969.0, 649948.0, 250.4997, 115.6126, 75142146.0]
80 ['Aug 2014', 301099.0, 652057.0, 250.2037, 115.5361, 75336097.0]
81 ['Sep 2014', 301036.0, 650911.0, 250.0395, 115.6393, 75270893.0]
82 ['Total', 302201.75, 656871.3333, 251.7594, 115.825, 912985504.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['North Carolina', '', '', '', '', '']
86 ['Oct 2013', 767471.0, 1591292.0, 284.6939, 137.3062, 218494332.0]
87 ['Nov 2013', 761917.0, 1578293.0, 257.5186, 124.3165, 196207817.0]
88 ['Dec 2013', 762873.0, 1583150.0, 256.3749, 123.5395, 195581487.0]
89 ['Jan 2014', 760487.0, 1573226.0, 255.6884, 123.5981, 194447702.0]
90 ['Feb 2014', 758531.0, 1566955.0, 261.5735, 126.6224, 198411602.0]
91 ['Mar 2014', 671771.0, 1386020.0, 290.9371, 141.0103, 195443075.0]
92 ['Apr 2014', 773962.0, 1602564.0, 253.2271, 122.2966, 195988160.0]
93 ['May 2014', 708076.0, 1467250.0, 279.0218, 134.6523, 197568630.0]
94 ['Jun 2014', 786074.0, 1629073.0, 251.968, 121.5817, 198065466.0]
95 ['Jul 2014', 784863.0, 1628467.0, 251.7273, 121.3236, 197571429.0]
96 ['Aug 2014', 785883.0, 1631689.0, 252.1291, 121.4349, 198143964.0]
97 ['Sep 2014', 811347.0, 1670130.0, 243.6046, 118.3428, 197647837.0]
98 ['Total', 761104.5833, 1575675.75, 260.9772, 126.0608, 2383571501.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['South Carolina', '', '', '', '', '']
102 ['Oct 2013', 415840.0, 874016.0, 276.3676, 131.4904, 114924712.0]
103 ['Nov 2013', 411082.0, 864774.0, 256.2147, 121.7951, 105325237.0]
104 ['Dec 2013', 406631.0, 855898.0, 254.9129, 121.1073, 103655500.0]
105 ['Jan 2014', 400329.0, 843141.0, 252.4893, 119.8836, 101078807.0]
106 ['Feb 2014', 395261.0, 832734.0, 289.3672, 137.3495, 114375564.0]
107 ['Mar 2014', 396463.0, 834569.0, 253.217, 120.291, 100391164.0]
108 ['Apr 2014', 388398.0, 820495.0, 255.8941, 121.1327, 99388762.0]
109 ['May 2014', 386862.0, 818094.0, 256.7093, 121.3932, 99311086.0]
110 ['Jun 2014', 386822.0, 818960.0, 256.6124, 121.2066, 99263338.0]
111 ['Jul 2014', 384844.0, 816523.0, 257.7415, 121.4788, 99190256.0]
112 ['Aug 2014', 385532.0, 818211.0, 258.4305, 121.7696, 99633225.0]
113 ['Sep 2014', 384438.0, 816717.0, 257.9313, 121.4112, 99158609.0]
114 ['Total', 395208.5, 834511.0, 260.5579, 123.3952, 1235696260.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['Tennessee', '', '', '', '', '']
118 ['Oct 2013', 666321.0, 1346102.0, 267.1628, 132.2457, 178016185.0]
119 ['Nov 2013', 657277.0, 1327376.0, 250.7323, 124.1552, 164800586.0]
120 ['Dec 2013', 653995.0, 1318529.0, 247.8826, 122.9506, 162113996.0]
121 ['Jan 2014', 658373.0, 1329164.0, 246.5773, 122.1368, 162339832.0]
122 ['Feb 2014', 647275.0, 1307038.0, 247.5639, 122.5993, 160241894.0]
123 ['Mar 2014', 652653.0, 1316813.0, 247.7651, 122.8, 161704620.0]
124 ['Apr 2014', 649594.0, 1311887.0, 248.2092, 122.9033, 161235219.0]
125 ['May 2014', 647064.0, 1305837.0, 249.3611, 123.5626, 161352600.0]
126 ['Jun 2014', 645413.0, 1302428.0, 247.9744, 122.8827, 160045908.0]
127 ['Jul 2014', 647283.0, 1307290.0, 249.5921, 123.5814, 161556712.0]
128 ['Aug 2014', 641294.0, 1295020.0, 250.5215, 124.0583, 160657921.0]
129 ['Sep 2014', 636468.0, 1282580.0, 248.0146, 123.0749, 157853359.0]
130 ['Total', 650250.8333, 1312505.3333, 250.1495, 123.9309, 1951918832.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['SERO', '', '', '', '', '']
134 ['Oct 2013', 5803542.0, 11704149.0, 272.4802, 135.1102, 1581350398.0]
135 ['Nov 2013', 5822313.0, 11857368.0, 248.3535, 121.9488, 1445991884.0]
136 ['Dec 2013', 5778750.0, 11767986.0, 248.0985, 121.8304, 1433698972.0]
137 ['Jan 2014', 5631574.0, 11358076.0, 250.8283, 124.3659, 1412557903.0]
138 ['Feb 2014', 5698543.0, 11594877.0, 249.9379, 122.8372, 1424282052.0]
139 ['Mar 2014', 5618653.0, 11402748.0, 252.0446, 124.1939, 1416151300.0]
140 ['Apr 2014', 5717297.0, 11605114.0, 247.3527, 121.8591, 1414188928.0]
141 ['May 2014', 5621997.0, 11297758.0, 252.7543, 125.7758, 1420984052.0]
142 ['Jun 2014', 5734616.0, 11526465.0, 248.4422, 123.6043, 1424720457.0]
143 ['Jul 2014', 5746068.0, 11556026.0, 248.8939, 123.7589, 1430161515.0]
144 ['Aug 2014', 5775638.0, 11612347.0, 248.6979, 123.695, 1436389240.0]
145 ['Sep 2014', 5815048.0, 11661637.0, 246.5168, 122.925, 1433506783.0]
146 ['Total', 5730336.5833, 11578712.5833, 251.2066, 124.3229, 17273983484.0]
147 ['', '', '', '', '', '']
148 ['', '', '', '', '', '']
149 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
150 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [451]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117, 133]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SERO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114, 130,146]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [452]:
########################
#                      #
# MWRO                 #
#                      #
########################

sheet = book.sheet_by_name('MWRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '11/06/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2014', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Illinois', '', '', '', '', '']
6 ['Oct 2013', 1018933.0, 2027483.0, 281.0688, 141.2541, 286390322.0]
7 ['Nov 2013', 1007753.0, 2001372.0, 259.3691, 130.6004, 261380018.0]
8 ['Dec 2013', 1013617.0, 2016940.0, 259.7489, 130.5373, 263285934.0]
9 ['Jan 2014', 1006420.0, 1999327.0, 262.4234, 132.0985, 264108109.0]
10 ['Feb 2014', 996277.0, 1975705.0, 260.6239, 131.4232, 259653550.0]
11 ['Mar 2014', 1015021.0, 2012035.0, 262.0811, 132.2133, 266017791.0]
12 ['Apr 2014', 1015826.0, 2006258.0, 260.993, 132.1482, 265123451.0]
13 ['May 2014', 1025636.0, 2020820.0, 261.2512, 132.594, 267948680.0]
14 ['Jun 2014', 1030544.0, 2026028.0, 257.8954, 131.1791, 265772538.0]
15 ['Jul 2014', 1039095.0, 2033995.0, 258.2098, 131.9101, 268304503.0]
16 ['Aug 2014', 1039852.0, 2029888.0, 256.5632, 131.4298, 266787777.0]
17 ['Sep 2014', 1044824.0, 2033787.0, 256.251, 131.6447, 267737190.0]
18 ['Total', 1021149.8333, 2015303.1667, 261.3483, 132.4247, 3202509863.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Indiana', '', '', '', '', '']
22 ['Oct 2013', 418649.0, 926155.0, 290.1645, 131.1628, 121477058.0]
23 ['Nov 2013', 414892.0, 917743.0, 268.8026, 121.5199, 111524060.0]
24 ['Dec 2013', 411046.0, 908732.0, 267.7781, 121.1238, 110069110.0]
25 ['Jan 2014', 406364.0, 898362.0, 265.3173, 120.0133, 107815386.0]
26 ['Feb 2014', 405169.0, 896095.0, 266.6415, 120.5619, 108034878.0]
27 ['Mar 2014', 405171.0, 894673.0, 267.5717, 121.1753, 108412281.0]
28 ['Apr 2014', 400719.0, 883826.0, 266.9012, 121.0107, 106952377.0]
29 ['May 2014', 400556.0, 882724.0, 269.9174, 122.4811, 108117024.0]
30 ['Jun 2014', 399298.0, 879279.0, 269.1256, 122.2153, 107461303.0]
31 ['Jul 2014', 398768.0, 877617.0, 271.4986, 123.3624, 108264966.0]
32 ['Aug 2014', 398034.0, 875833.0, 268.5293, 122.0367, 106883786.0]
33 ['Sep 2014', 396235.0, 871344.0, 268.6693, 122.1747, 106456174.0]
34 ['Total', 404575.0833, 892698.5833, 270.1329, 122.4255, 1311468403.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Michigan', '', '', '', '', '']
38 ['Oct 2013', 895067.0, 1735759.0, 262.8567, 135.5455, 235274375.0]
39 ['Nov 2013', 883486.0, 1707665.0, 245.8465, 127.1923, 217201903.0]
40 ['Dec 2013', 877409.0, 1692720.0, 245.9974, 127.511, 215840339.0]
41 ['Jan 2014', 874508.0, 1685232.0, 242.8134, 126.0018, 212342237.0]
42 ['Feb 2014', 875150.0, 1686312.0, 245.884, 127.6071, 215185340.0]
43 ['Mar 2014', 874669.0, 1684253.0, 245.499, 127.4929, 214730374.0]
44 ['Apr 2014', 872877.0, 1678883.0, 246.0691, 127.9351, 214788064.0]
45 ['May 2014', 873956.0, 1681322.0, 245.6552, 127.6923, 214691865.0]
46 ['Jun 2014', 868424.0, 1669334.0, 244.8291, 127.3655, 212615488.0]
47 ['Jul 2014', 863485.0, 1656802.0, 243.4325, 126.8711, 210200284.0]
48 ['Aug 2014', 857925.0, 1642746.0, 242.3019, 126.5423, 207876896.0]
49 ['Sep 2014', 853504.0, 1632020.0, 240.6761, 125.8673, 205417983.0]
50 ['Total', 872538.3333, 1679420.6667, 246.0413, 127.8301, 2576165148.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Minnesota', '', '', '', '', '']
54 ['Oct 2013', 276092.0, 556655.0, 231.8054, 114.9718, 63999616.0]
55 ['Nov 2013', 273085.0, 551045.0, 214.0081, 106.0574, 58442396.0]
56 ['Dec 2013', 272361.0, 549612.0, 212.3266, 105.2187, 57829479.0]
57 ['Jan 2014', 271579.0, 548682.0, 211.4728, 104.6719, 57431575.0]
58 ['Feb 2014', 259874.0, 533213.0, 212.4839, 103.5591, 55219049.0]
59 ['Mar 2014', 258457.0, 531552.0, 212.993, 103.5638, 55049531.0]
60 ['Apr 2014', 256112.0, 528763.0, 214.2663, 103.7822, 54876162.0]
61 ['May 2014', 254770.0, 527118.0, 214.2919, 103.5729, 54595156.0]
62 ['Jun 2014', 253031.0, 524072.0, 210.5837, 101.6734, 53284204.0]
63 ['Jul 2014', 251940.0, 522512.0, 213.5332, 102.9594, 53797548.0]
64 ['Aug 2014', 249643.0, 517785.0, 213.4258, 102.9003, 53280253.0]
65 ['Sep 2014', 248300.0, 513911.0, 211.0258, 101.9587, 52397699.0]
66 ['Total', 260437.0, 533743.3333, 214.4481, 104.6387, 670202668.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Ohio', '', '', '', '', '']
70 ['Oct 2013', 881591.0, 1799770.0, 269.2964, 131.9109, 237409312.0]
71 ['Nov 2013', 873996.0, 1787984.0, 250.8089, 122.5995, 219205938.0]
72 ['Dec 2013', 878326.0, 1799993.0, 249.29, 121.6437, 218957858.0]
73 ['Jan 2014', 862730.0, 1775855.0, 249.7297, 121.3215, 215449342.0]
74 ['Feb 2014', 852325.0, 1757718.0, 250.1096, 121.2792, 213174688.0]
75 ['Mar 2014', 851516.0, 1760557.0, 251.7096, 121.7426, 214334769.0]
76 ['Apr 2014', 847031.0, 1750373.0, 252.7386, 122.3039, 214077423.0]
77 ['May 2014', 841476.0, 1735294.0, 253.2177, 122.7899, 213076599.0]
78 ['Jun 2014', 840090.0, 1730818.0, 250.9682, 121.8129, 210835893.0]
79 ['Jul 2014', 835600.0, 1719027.0, 251.4266, 122.2157, 210092037.0]
80 ['Aug 2014', 830191.0, 1706254.0, 250.9777, 122.1151, 208359436.0]
81 ['Sep 2014', 828795.0, 1701979.0, 250.707, 122.0842, 207784672.0]
82 ['Total', 851972.25, 1752135.1667, 252.6254, 122.8386, 2582757967.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Wisconsin', '', '', '', '', '']
86 ['Oct 2013', 421395.0, 856336.0, 238.1367, 117.1849, 100349612.0]
87 ['Nov 2013', 417578.0, 843578.0, 218.1707, 107.9963, 91103304.0]
88 ['Dec 2013', 416018.0, 838946.0, 217.6244, 107.916, 90535666.0]
89 ['Jan 2014', 417871.0, 841484.0, 224.6859, 111.5764, 93889724.0]
90 ['Feb 2014', 419522.0, 842945.0, 217.8882, 108.4399, 91408883.0]
91 ['Mar 2014', 421291.0, 843396.0, 220.0868, 109.9372, 92720599.0]
92 ['Apr 2014', 423345.0, 844841.0, 220.6574, 110.5701, 93414194.0]
93 ['May 2014', 423178.0, 842345.0, 215.277, 108.151, 91100478.0]
94 ['Jun 2014', 423232.0, 840358.0, 219.1438, 110.3681, 92748679.0]
95 ['Jul 2014', 422635.0, 837025.0, 221.0281, 111.6026, 93414194.0]
96 ['Aug 2014', 422983.0, 836165.0, 215.3762, 108.9504, 91100478.0]
97 ['Sep 2014', 420949.0, 830975.0, 216.6416, 109.7447, 91195073.0]
98 ['Total', 420833.0833, 841532.8333, 220.3924, 110.2137, 1112980884.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['MWRO', '', '', '', '', '']
102 ['Oct 2013', 3911727.0, 7902158.0, 267.1199, 132.2297, 1044900295.0]
103 ['Nov 2013', 3870790.0, 7809387.0, 247.7163, 122.7827, 958857619.0]
104 ['Dec 2013', 3868777.0, 7806943.0, 247.2405, 122.5215, 956518386.0]
105 ['Jan 2014', 3839472.0, 7748942.0, 247.6998, 122.7311, 951036373.0]
106 ['Feb 2014', 3808317.0, 7691988.0, 247.531, 122.553, 942676388.0]
107 ['Mar 2014', 3826125.0, 7726466.0, 248.6237, 123.1178, 951265345.0]
108 ['Apr 2014', 3815910.0, 7692944.0, 248.7563, 123.3899, 949231671.0]
109 ['May 2014', 3819572.0, 7689623.0, 248.5959, 123.482, 949529802.0]
110 ['Jun 2014', 3814619.0, 7669889.0, 247.133, 122.9116, 942718105.0]
111 ['Jul 2014', 3811523.0, 7646978.0, 247.6893, 123.4571, 944073532.0]
112 ['Aug 2014', 3798628.0, 7608671.0, 245.9542, 122.7926, 934288626.0]
113 ['Sep 2014', 3792607.0, 7584016.0, 245.4746, 122.7567, 930988791.0]
114 ['Total', 3831505.5833, 7714833.75, 249.1641, 123.7452, 11456084933.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
118 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [453]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MWRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [454]:
########################
#                      #
# SWRO                 #
#                      #
########################

sheet = book.sheet_by_name('SWRO ')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '11/06/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2014', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Arkansas', '', '', '', '', '']
6 ['Oct 2013', 226013.0, 504541.0, 270.7625, 121.2901, 61195850.0]
7 ['Nov 2013', 224279.0, 501124.0, 248.3967, 111.1704, 55710171.0]
8 ['Dec 2013', 222627.0, 496671.0, 248.4135, 111.3485, 55303557.0]
9 ['Jan 2014', 222548.0, 496935.0, 245.9583, 110.1503, 54737523.0]
10 ['Feb 2014', 221008.0, 492663.0, 247.5246, 111.0392, 54704910.0]
11 ['Mar 2014', 220289.0, 488926.0, 247.8122, 111.6535, 54590302.0]
12 ['Apr 2014', 219560.0, 486651.0, 247.4473, 111.6396, 54329531.0]
13 ['May 2014', 220290.0, 488404.0, 248.8271, 112.2311, 54814113.0]
14 ['Jun 2014', 220400.0, 487710.0, 247.99, 112.0686, 54656987.0]
15 ['Jul 2014', 219718.0, 486465.0, 248.3914, 112.1891, 54576063.0]
16 ['Aug 2014', 220315.0, 487174.0, 247.9842, 112.146, 54634638.0]
17 ['Sep 2014', 220307.0, 486312.0, 247.226, 111.9973, 54465623.0]
18 ['Total', 221446.1667, 491964.6667, 249.767, 112.4266, 663719268.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Louisiana', '', '', '', '', '']
22 ['Oct 2013', 412020.0, 909245.0, 289.4527, 131.1641, 119260283.0]
23 ['Nov 2013', 408545.0, 902984.0, 268.4222, 121.4446, 109662560.0]
24 ['Dec 2013', 403022.0, 891260.0, 270.0644, 122.1214, 108841875.0]
25 ['Jan 2014', 396392.0, 876550.0, 265.2038, 119.93, 105124647.0]
26 ['Feb 2014', 396049.0, 877140.0, 268.1145, 121.0599, 106186480.0]
27 ['Mar 2014', 392944.0, 870227.0, 267.7791, 120.9135, 105222195.0]
28 ['Apr 2014', 389247.0, 862432.0, 267.7304, 120.8365, 104213254.0]
29 ['May 2014', 391116.0, 866941.0, 270.4246, 122.0007, 105767398.0]
30 ['Jun 2014', 389894.0, 863320.0, 269.373, 121.6547, 105026912.0]
31 ['Jul 2014', 390812.0, 865798.0, 270.3468, 122.0317, 105654780.0]
32 ['Aug 2014', 394546.0, 873993.0, 271.9926, 122.7854, 107313597.0]
33 ['Sep 2014', 392546.0, 868192.0, 270.1398, 122.1415, 106042292.0]
34 ['Total', 396427.75, 877340.1667, 270.8178, 122.3695, 1288316273.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['New Mexico', '', '', '', '', '']
38 ['Oct 2013', 191998.0, 425559.0, 293.727, 132.5198, 56394999.0]
39 ['Nov 2013', 191826.0, 423913.0, 269.5381, 121.9694, 51704407.0]
40 ['Dec 2013', 191740.0, 423093.0, 267.7618, 121.346, 51340645.0]
41 ['Jan 2014', 191691.0, 422684.0, 262.7708, 119.1689, 50370792.0]
42 ['Feb 2014', 191676.0, 422479.0, 263.8903, 119.7253, 50581433.0]
43 ['Mar 2014', 191669.0, 422377.0, 262.5131, 119.1249, 50315621.0]
44 ['Apr 2014', 191665.0, 422326.0, 265.4178, 120.455, 50871297.0]
45 ['May 2014', 195213.0, 432786.0, 266.3553, 120.1426, 51996014.0]
46 ['Jun 2014', 199791.0, 442600.0, 262.8854, 118.6673, 52522142.0]
47 ['Jul 2014', 200249.0, 443348.0, 271.0636, 122.4325, 54280215.0]
48 ['Aug 2014', 202804.0, 448429.0, 268.5434, 121.4499, 54461679.0]
49 ['Sep 2014', 202778.0, 448328.0, 267.8851, 121.164, 54321209.0]
50 ['Total', 195258.3333, 431493.5, 268.5163, 121.5083, 629160453.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Oklahoma', '', '', '', '', '']
54 ['Oct 2013', 293173.0, 629942.0, 276.9373, 128.8857, 81190532.0]
55 ['Nov 2013', 291499.0, 627722.0, 256.1674, 118.958, 74672536.0]
56 ['Dec 2013', 287701.0, 624567.0, 255.9386, 117.8957, 73633785.0]
57 ['Jan 2014', 285182.0, 620031.0, 252.48, 116.1277, 72002763.0]
58 ['Feb 2014', 279933.0, 605563.0, 255.0086, 117.8826, 71385330.0]
59 ['Mar 2014', 275973.0, 598409.0, 254.3575, 117.3041, 70195800.0]
60 ['Apr 2014', 275751.0, 598336.0, 255.6416, 117.8158, 70493415.0]
61 ['May 2014', 274718.0, 598483.0, 256.3971, 117.6924, 70436911.0]
62 ['Jun 2014', 273989.0, 599302.0, 256.8516, 117.4275, 70374524.0]
63 ['Jul 2014', 272663.0, 598167.0, 257.3862, 117.3246, 70179703.0]
64 ['Aug 2014', 272956.0, 601365.0, 257.6865, 116.9624, 70337075.0]
65 ['Sep 2014', 271728.0, 600021.0, 258.153, 116.9082, 70147391.0]
66 ['Total', 279605.5, 608492.3333, 257.8185, 118.469, 865049765.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Texas', '', '', '', '', '']
70 ['Oct 2013', 1674771.0, 4027808.0, 296.8948, 123.4495, 497230848.0]
71 ['Nov 2013', 1652175.0, 3972686.0, 275.1322, 114.423, 454566522.0]
72 ['Dec 2013', 1629546.0, 3916115.0, 274.2507, 114.1193, 446904194.0]
73 ['Jan 2014', 1614284.0, 3870787.0, 272.5579, 113.6683, 439985871.0]
74 ['Feb 2014', 1596864.0, 3826274.0, 274.6212, 114.6109, 438532682.0]
75 ['Mar 2014', 1591548.0, 3806053.0, 275.007, 114.9976, 437686808.0]
76 ['Apr 2014', 1579373.0, 3777873.0, 274.131, 114.6029, 432955057.0]
77 ['May 2014', 1591707.0, 3810926.0, 274.8638, 114.8022, 437502623.0]
78 ['Jun 2014', 1592988.0, 3812561.0, 274.599, 114.7346, 437432845.0]
79 ['Jul 2014', 1589023.0, 3802668.0, 274.5194, 114.7136, 436217606.0]
80 ['Aug 2014', 1588428.0, 3802188.0, 274.0889, 114.5052, 435370451.0]
81 ['Sep 2014', 1591325.0, 3806160.0, 274.1521, 114.6208, 436265112.0]
82 ['Total', 1607669.3333, 3852674.9167, 276.3136, 115.3019, 5330650619.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['SWRO', '', '', '', '', '']
86 ['Oct 2013', 2797975.0, 6497095.0, 291.3795, 125.4826, 815272512.0]
87 ['Nov 2013', 2768324.0, 6428429.0, 269.5913, 116.0962, 746316196.0]
88 ['Dec 2013', 2734636.0, 6351706.0, 269.1488, 115.8782, 736024056.0]
89 ['Jan 2014', 2710097.0, 6286987.0, 266.4929, 114.8756, 722221596.0]
90 ['Feb 2014', 2685530.0, 6224119.0, 268.6214, 115.9025, 721390835.0]
91 ['Mar 2014', 2672423.0, 6185992.0, 268.6741, 116.0704, 718010726.0]
92 ['Apr 2014', 2655596.0, 6147618.0, 268.4379, 115.9575, 712862554.0]
93 ['May 2014', 2673044.0, 6197540.0, 269.5493, 116.2586, 720517059.0]
94 ['Jun 2014', 2677062.0, 6205493.0, 268.9566, 116.0284, 720013410.0]
95 ['Jul 2014', 2672465.0, 6196446.0, 269.7541, 116.3422, 720908367.0]
96 ['Aug 2014', 2679049.0, 6213149.0, 269.5425, 116.2241, 722117440.0]
97 ['Sep 2014', 2678684.0, 6209013.0, 269.2522, 116.1604, 721241627.0]
98 ['Total', 2700407.0833, 6261965.5833, 270.851, 116.8017, 8776896378.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
102 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [455]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SWRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [456]:
########################
#                      #
# MPRO                 #
#                      #
########################
sheet = book.sheet_by_name('MPRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '11/06/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2014', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Colorado', '', '', '', '', '']
6 ['Oct 2013', 232871.0, 508082.0, 293.8843, 134.697, 68437133.0]
7 ['Nov 2013', 230001.0, 501679.0, 271.3628, 124.4097, 62413714.0]
8 ['Dec 2013', 232145.0, 504612.0, 271.4134, 124.8628, 63007253.0]
9 ['Jan 2014', 232491.0, 503223.0, 269.3856, 124.4572, 62629730.0]
10 ['Feb 2014', 232284.0, 501889.0, 269.939, 124.933, 62702518.0]
11 ['Mar 2014', 235937.0, 508211.0, 274.4303, 127.4043, 64748257.0]
12 ['Apr 2014', 235777.0, 506461.0, 270.5746, 125.9629, 63795278.0]
13 ['May 2014', 237405.0, 509949.0, 270.9222, 126.1269, 64318286.0]
14 ['Jun 2014', 236971.0, 509157.0, 269.8704, 125.6026, 63951460.0]
15 ['Jul 2014', 235586.0, 506625.0, 271.7109, 126.3485, 64011284.0]
16 ['Aug 2014', 233933.0, 501508.0, 269.1275, 125.537, 62957796.0]
17 ['Sep 2014', 233771.0, 500635.0, 268.4866, 125.3695, 62764376.0]
18 ['Total', 234097.6667, 505169.25, 272.5846, 126.3169, 765737085.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Iowa', '', '', '', '', '']
22 ['Oct 2013', 199540.0, 421634.0, 245.6029, 116.2326, 49007606.0]
23 ['Nov 2013', 197118.0, 416270.0, 228.6812, 108.2883, 45077181.0]
24 ['Dec 2013', 196216.0, 413543.0, 226.1173, 107.2871, 44367838.0]
25 ['Jan 2014', 195303.0, 411462.0, 223.8514, 106.2525, 43718849.0]
26 ['Feb 2014', 194411.0, 410210.0, 227.1083, 107.6335, 44152354.0]
27 ['Mar 2014', 193488.0, 408195.0, 227.5331, 107.8527, 44024927.0]
28 ['Apr 2014', 193096.0, 407506.0, 228.3259, 108.1918, 44088816.0]
29 ['May 2014', 192638.0, 406150.0, 228.3119, 108.2889, 43981547.0]
30 ['Jun 2014', 191341.0, 403934.0, 228.6762, 108.3225, 43755133.0]
31 ['Jul 2014', 189665.0, 400241.0, 228.9869, 108.5116, 43430800.0]
32 ['Aug 2014', 189258.0, 399826.0, 229.3149, 108.5464, 43399675.0]
33 ['Sep 2014', 188394.0, 397866.0, 228.6723, 108.2789, 43080487.0]
34 ['Total', 193372.3333, 408069.75, 229.3008, 108.659, 532085213.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Kansas', '', '', '', '', '']
38 ['Oct 2013', 147912.0, 315171.0, 265.9905, 124.8313, 39343193.0]
39 ['Nov 2013', 146090.0, 311672.0, 244.2397, 114.4825, 35680981.0]
40 ['Dec 2013', 143674.0, 307507.0, 243.5895, 113.8103, 34997477.0]
41 ['Jan 2014', 131906.0, 292420.0, 242.6354, 109.449, 32005071.0]
42 ['Feb 2014', 129963.0, 289502.0, 245.9381, 110.4063, 31962847.0]
43 ['Mar 2014', 129236.0, 288331.0, 245.0459, 109.8347, 31668757.0]
44 ['Apr 2014', 128423.0, 286829.0, 246.3587, 110.3031, 31638118.0]
45 ['May 2014', 128115.0, 286915.0, 246.7443, 110.1777, 31611643.0]
46 ['Jun 2014', 127780.0, 286930.0, 247.032, 110.012, 31565747.0]
47 ['Jul 2014', 127179.0, 285537.0, 248.7105, 110.7764, 31630756.0]
48 ['Aug 2014', 127196.0, 286294.0, 249.45, 110.8268, 31729037.0]
49 ['Sep 2014', 126431.0, 284365.0, 248.1699, 110.3384, 31376367.0]
50 ['Total', 132825.4167, 293456.0833, 247.9508, 112.2286, 395209994.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Missouri', '', '', '', '', '']
54 ['Oct 2013', 422033.0, 896475.0, 274.5526, 129.251, 115870269.0]
55 ['Nov 2013', 416921.0, 886405.0, 251.7412, 118.4066, 104956180.0]
56 ['Dec 2013', 413953.0, 881239.0, 247.7426, 116.3746, 102553798.0]
57 ['Jan 2014', 409315.0, 871755.0, 255.0341, 119.7461, 104389284.0]
58 ['Feb 2014', 405982.0, 864887.0, 252.5169, 118.5326, 102517332.0]
59 ['Mar 2014', 405637.0, 862992.0, 251.2565, 118.0995, 101918952.0]
60 ['Apr 2014', 403677.0, 857909.0, 255.411, 120.1801, 103103556.0]
61 ['May 2014', 399844.0, 848469.0, 252.0265, 118.7684, 100771282.0]
62 ['Jun 2014', 395887.0, 839734.0, 252.5674, 119.0712, 99988168.0]
63 ['Jul 2014', 390664.0, 829008.0, 256.7411, 120.9874, 100299506.0]
64 ['Aug 2014', 391679.0, 831214.0, 255.9706, 120.6167, 100258296.0]
65 ['Sep 2014', 391361.0, 830900.0, 255.0535, 120.1324, 99818007.0]
66 ['Total', 403912.75, 858415.5833, 255.0973, 120.0317, 1236444630.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Montana', '', '', '', '', '']
70 ['Oct 2013', 59368.0, 125704.0, 269.619, 127.3368, 16006743.0]
71 ['Nov 2013', 59199.0, 125478.0, 247.9924, 116.9998, 14680900.0]
72 ['Dec 2013', 59105.0, 125487.0, 248.0535, 116.8345, 14661205.0]
73 ['Jan 2014', 59297.0, 125606.0, 245.0354, 115.6781, 14529867.0]
74 ['Feb 2014', 59270.0, 125400.0, 246.123, 116.3294, 14587712.0]
75 ['Mar 2014', 59234.0, 125049.0, 247.2453, 117.1167, 14645328.0]
76 ['Apr 2014', 59196.0, 124803.0, 246.0109, 116.6868, 14562861.0]
77 ['May 2014', 59358.0, 125315.0, 246.8607, 116.9306, 14653160.0]
78 ['Jun 2014', 59280.0, 125010.0, 246.6279, 116.9515, 14620102.0]
79 ['Jul 2014', 58999.0, 124537.0, 246.965, 116.9989, 14570689.0]
80 ['Aug 2014', 58601.0, 123825.0, 244.79, 115.8485, 14344937.0]
81 ['Sep 2014', 58257.0, 122659.0, 245.5677, 116.6326, 14306039.0]
82 ['Total', 59097.0, 124906.0833, 248.4186, 117.5347, 176169543.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Nebraska', '', '', '', '', '']
86 ['Oct 2013', 78608.0, 178056.0, 277.5478, 122.5316, 21817481.0]
87 ['Nov 2013', 78487.0, 177532.0, 261.3429, 115.5399, 20512021.0]
88 ['Dec 2013', 78943.0, 178631.0, 254.8403, 112.6224, 20117858.0]
89 ['Jan 2014', 78831.0, 178333.0, 256.1888, 113.2467, 20195620.0]
90 ['Feb 2014', 77573.0, 175324.0, 255.6496, 113.1135, 19831510.0]
91 ['Mar 2014', 77632.0, 175112.0, 257.117, 113.9871, 19960507.0]
92 ['Apr 2014', 75879.0, 170710.0, 255.085, 113.3829, 19355595.0]
93 ['May 2014', 75731.0, 170160.0, 259.4563, 115.473, 19648885.0]
94 ['Jun 2014', 74755.0, 167713.0, 254.9735, 113.6498, 19060541.0]
95 ['Jul 2014', 74558.0, 167550.0, 259.9439, 115.6723, 19380901.0]
96 ['Aug 2014', 75270.0, 169845.0, 260.1111, 115.2731, 19578566.0]
97 ['Sep 2014', 76756.0, 173398.0, 253.3336, 112.1401, 19444873.0]
98 ['Total', 76918.5833, 173530.3333, 258.8282, 114.7275, 238904358.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['North Dakota', '', '', '', '', '']
102 ['Oct 2013', 25131.0, 54025.0, 271.4601, 126.276, 6822063.0]
103 ['Nov 2013', 24985.0, 53753.0, 251.2248, 116.7721, 6276851.0]
104 ['Dec 2013', 24869.0, 53570.0, 251.4535, 116.7332, 6253397.0]
105 ['Jan 2014', 25063.0, 53943.0, 248.2216, 115.3287, 6221177.0]
106 ['Feb 2014', 25094.0, 54093.0, 250.3902, 116.1572, 6283292.0]
107 ['Mar 2014', 25157.0, 54089.0, 249.9335, 116.245, 6287576.0]
108 ['Apr 2014', 25229.0, 54174.0, 250.9392, 116.8632, 6330945.0]
109 ['May 2014', 25206.0, 54159.0, 250.6156, 116.6384, 6317017.0]
110 ['Jun 2014', 25028.0, 53752.0, 251.4208, 117.0665, 6292561.0]
111 ['Jul 2014', 24843.0, 53252.0, 250.8952, 117.047, 6232989.0]
112 ['Aug 2014', 24794.0, 53194.0, 250.934, 116.9616, 6221657.0]
113 ['Sep 2014', 24735.0, 53034.0, 251.6879, 117.3869, 6225499.0]
114 ['Total', 25011.1667, 53753.1667, 252.4373, 117.4582, 75765024.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['South Dakota', '', '', '', '', '']
118 ['Oct 2013', 44413.0, 101887.0, 303.9874, 132.5095, 13500991.0]
119 ['Nov 2013', 44337.0, 101403.0, 279.5428, 122.2261, 12394090.0]
120 ['Dec 2013', 44271.0, 101355.0, 279.4479, 122.0605, 12371437.0]
121 ['Jan 2014', 44612.0, 102253.0, 278.8844, 121.6746, 12441590.0]
122 ['Feb 2014', 44339.0, 101468.0, 278.019, 121.4874, 12327085.0]
123 ['Mar 2014', 44199.0, 101163.0, 279.8863, 122.2848, 12370696.0]
124 ['Apr 2014', 44140.0, 100971.0, 279.4199, 122.1499, 12333594.0]
125 ['May 2014', 43902.0, 100646.0, 281.6108, 122.8392, 12363279.0]
126 ['Jun 2014', 43798.0, 100534.0, 280.9265, 122.3866, 12304017.0]
127 ['Jul 2014', 43657.0, 100433.0, 281.8983, 122.5378, 12306834.0]
128 ['Aug 2014', 43514.0, 100041.0, 280.8626, 122.1645, 12221457.0]
129 ['Sep 2014', 43285.0, 99101.0, 277.3064, 121.1209, 12003206.0]
130 ['Total', 44038.9167, 100937.9167, 281.8308, 122.9619, 148938276.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['Utah', '', '', '', '', '']
134 ['Oct 2013', 92718.0, 236449.0, 314.8824, 123.4738, 29195268.0]
135 ['Nov 2013', 91147.0, 233041.0, 289.7746, 113.3366, 26412081.0]
136 ['Dec 2013', 90170.0, 230329.0, 287.9029, 112.7092, 25960201.0]
137 ['Jan 2014', 89827.0, 228503.0, 285.6036, 112.2739, 25654916.0]
138 ['Feb 2014', 90369.0, 230108.0, 292.3173, 114.8001, 26416420.0]
139 ['Mar 2014', 91387.0, 231684.0, 290.1749, 114.4585, 26518210.0]
140 ['Apr 2014', 91001.0, 230361.0, 290.6969, 114.8359, 26453709.0]
141 ['May 2014', 90912.0, 229970.0, 290.3042, 114.7634, 26392133.0]
142 ['Jun 2014', 89892.0, 227179.0, 288.469, 114.1437, 25931059.0]
143 ['Jul 2014', 89437.0, 225880.0, 288.9908, 114.4257, 25846469.0]
144 ['Aug 2014', 90150.0, 228203.0, 289.2547, 114.268, 26076309.0]
145 ['Sep 2014', 89831.0, 227229.0, 287.3728, 113.6078, 25814989.0]
146 ['Total', 90570.0833, 229911.3333, 291.369, 114.7804, 316671764.0]
147 ['', '', '', '', '', '']
148 ['', '', '', '', '', '']
149 ['Wyoming', '', '', '', '', '']
150 ['Oct 2013', 16003.0, 37931.0, 292.2277, 123.2902, 4676520.0]
151 ['Nov 2013', 15978.0, 37914.0, 270.6003, 114.0384, 4323652.0]
152 ['Dec 2013', 15887.0, 37659.0, 268.4722, 113.2589, 4265218.0]
153 ['Jan 2014', 15924.0, 37771.0, 266.8583, 112.5057, 4249452.0]
154 ['Feb 2014', 15602.0, 36881.0, 268.5863, 113.6218, 4190484.0]
155 ['Mar 2014', 15660.0, 36830.0, 267.905, 113.9124, 4195392.0]
156 ['Apr 2014', 15467.0, 36376.0, 268.2505, 114.0596, 4149031.0]
157 ['May 2014', 15153.0, 35485.0, 267.2609, 114.1272, 4049805.0]
158 ['Jun 2014', 14771.0, 34434.0, 263.8622, 113.1878, 3897508.0]
159 ['Jul 2014', 14335.0, 33299.0, 265.3533, 114.2328, 3803839.0]
160 ['Aug 2014', 14085.0, 32886.0, 265.9938, 113.9245, 3746522.0]
161 ['Sep 2014', 14128.0, 32986.0, 263.6711, 112.9311, 3725146.0]
162 ['Total', 15249.4167, 35871.0, 269.2593, 114.467, 49272569.0]
163 ['', '', '', '', '', '']
164 ['', '', '', '', '', '']
165 ['MPRO', '', '', '', '', '']
166 ['Oct 2013', 1318597.0, 2875414.0, 276.5646, 126.826, 364677267.0]
167 ['Nov 2013', 1304263.0, 2845147.0, 255.1078, 116.9457, 332727651.0]
168 ['Dec 2013', 1299233.0, 2833932.0, 252.8843, 115.9363, 328555682.0]
169 ['Jan 2014', 1282569.0, 2805269.0, 254.2051, 116.2226, 326035556.0]
170 ['Feb 2014', 1274887.0, 2789762.0, 254.9022, 116.4872, 324971554.0]
171 ['Mar 2014', 1277567.0, 2791656.0, 255.4376, 116.8979, 326338602.0]
172 ['Apr 2014', 1271885.0, 2776100.0, 256.1643, 117.363, 325811503.0]
173 ['May 2014', 1268264.0, 2767218.0, 255.5517, 117.1238, 324107037.0]
174 ['Jun 2014', 1259503.0, 2748377.0, 255.1533, 116.9295, 321366296.0]
175 ['Jul 2014', 1248923.0, 2726362.0, 257.4331, 117.9279, 321514067.0]
176 ['Aug 2014', 1248480.0, 2726836.0, 256.7396, 117.548, 320534252.0]
177 ['Sep 2014', 1246949.0, 2722173.0, 255.4707, 117.0238, 318558989.0]
178 ['Total', 1275093.3333, 2784020.5, 257.1837, 117.7912, 3935198456.0]
179 ['', '', '', '', '', '']
180 ['', '', '', '', '', '']
181 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
182 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [457]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117, 133, 149,165]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MPRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114, 130,146, 162, 178]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [458]:

########################
#                      #
# WRO                  #
#                      #
########################
sheet = book.sheet_by_name('WRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '11/06/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2014', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Alaska', '', '', '', '', '']
6 ['Oct 2013', 33081.0, 75493.0, 387.1158, 169.634, 12806177.0]
7 ['Nov 2013', 37134.0, 87510.0, 378.2508, 160.507, 14045966.0]
8 ['Dec 2013', 36986.0, 87301.0, 383.1465, 162.3241, 14171055.0]
9 ['Jan 2014', 37342.0, 88041.0, 385.0607, 163.3209, 14378938.0]
10 ['Feb 2014', 37497.0, 88742.0, 390.8578, 165.1529, 14655995.0]
11 ['Mar 2014', 38160.0, 90260.0, 394.7232, 166.8806, 15062639.0]
12 ['Apr 2014', 38751.0, 92067.0, 395.2679, 166.3682, 15317025.0]
13 ['May 2014', 38424.0, 91351.0, 392.4418, 165.0686, 15079182.0]
14 ['Jun 2014', 38125.0, 90634.0, 396.9548, 166.9782, 15133901.0]
15 ['Jul 2014', 36622.0, 87266.0, 399.4359, 167.627, 14628142.0]
16 ['Aug 2014', 36347.0, 86814.0, 406.799, 170.3173, 14785922.0]
17 ['Sep 2014', 35497.0, 84357.0, 399.3822, 168.058, 14176871.0]
18 ['Total', 36997.1667, 87486.3333, 392.4666, 165.9705, 174241813.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['American Samoa', '', '', '', '', '']
22 [' No data found.', '', '', '', '', '']
23 ['', '', '', '', '', '']
24 ['', '', '', '', '', '']
25 ['Arizona', '', '', '', '', '']
26 ['Oct 2013', 469089.0, 1093804.0, 293.9002, 126.0421, 137865367.0]
27 ['Nov 2013', 460719.0, 1072133.0, 273.0682, 117.3434, 125807728.0]
28 ['Dec 2013', 451902.0, 1052614.0, 273.0105, 117.2072, 123373977.0]
29 ['Jan 2014', 444039.0, 1072103.0, 271.9696, 112.6432, 120765115.0]
30 ['Feb 2014', 438209.0, 1035650.0, 270.8443, 114.6009, 118686415.0]
31 ['Mar 2014', 440245.0, 1018000.0, 271.0218, 117.2063, 119315990.0]
32 ['Apr 2014', 440798.0, 1016742.0, 270.8002, 117.4026, 119368170.0]
33 ['May 2014', 445131.0, 1024764.0, 270.8452, 117.6481, 120561581.0]
34 ['Jun 2014', 448529.0, 1031316.0, 271.6399, 118.1387, 121838367.0]
35 ['Jul 2014', 450263.0, 1034470.0, 272.3925, 118.5615, 122648280.0]
36 ['Aug 2014', 453175.0, 1040026.0, 271.7009, 118.3894, 123128034.0]
37 ['Sep 2014', 453579.0, 1040099.0, 272.0648, 118.6453, 123402874.0]
38 ['Total', 449639.8333, 1044310.0833, 273.6935, 117.8419, 1476761898.0]
39 ['', '', '', '', '', '']
40 ['', '', '', '', '', '']
41 ['California', '', '', '', '', '']
42 ['Oct 2013', 1961085.0, 4245372.0, 331.5758, 153.1664, 650248342.0]
43 ['Nov 2013', 1966307.0, 4264816.0, 308.9251, 142.4309, 607441620.0]
44 ['Dec 2013', 1985240.0, 4295452.0, 307.4609, 142.1, 610383650.0]
45 ['Jan 2014', 1997428.0, 4308752.0, 306.8039, 142.2265, 612818679.0]
46 ['Feb 2014', 1995827.0, 4311206.0, 307.5757, 142.3889, 613867843.0]
47 ['Mar 2014', 2018357.0, 4336066.0, 305.6992, 142.2972, 617010166.0]
48 ['Apr 2014', 2027773.0, 4349203.0, 304.0462, 141.7586, 616536772.0]
49 ['May 2014', 2038610.0, 4362874.0, 303.2825, 141.7127, 618274705.0]
50 ['Jun 2014', 2049185.0, 4419104.0, 300.9222, 139.5408, 616645342.0]
51 ['Jul 2014', 2057046.0, 4434106.0, 299.9596, 139.1556, 617030705.0]
52 ['Aug 2014', 2067778.0, 4439090.0, 299.1023, 139.3252, 618477138.0]
53 ['Sep 2014', 2066631.0, 4429570.0, 296.4964, 138.3314, 612748723.0]
54 ['Total', 2019272.25, 4349634.25, 305.8645, 141.9944, 7411483685.0]
55 ['', '', '', '', '', '']
56 ['', '', '', '', '', '']
57 ['Guam', '', '', '', '', '']
58 ['Oct 2013', 15363.0, 46305.0, 648.5953, 215.1899, 9964370.0]
59 ['Nov 2013', 16381.0, 48921.0, 570.2712, 190.953, 9341612.0]
60 ['Dec 2013', 16442.0, 49137.0, 568.8398, 190.3426, 9352864.0]
61 ['Jan 2014', 15257.0, 47129.0, 588.6353, 190.558, 8980809.0]
62 ['Feb 2014', 15520.0, 47817.0, 578.7805, 187.8552, 8982674.0]
63 ['Mar 2014', 14658.0, 45332.0, 607.0622, 196.2922, 8898318.0]
64 ['Apr 2014', 15439.0, 47599.0, 573.457, 186.0039, 8853602.0]
65 ['May 2014', 15432.0, 47403.0, 573.5286, 186.7117, 8850694.0]
66 ['Jun 2014', 15405.0, 47253.0, 573.4791, 186.9605, 8834445.0]
67 ['Jul 2014', 15245.0, 46560.0, 573.0597, 187.6352, 8736295.0]
68 ['Aug 2014', 15219.0, 46694.0, 578.4575, 188.537, 8803545.0]
69 ['Sep 2014', 15393.0, 47321.0, 573.9389, 186.696, 8834641.0]
70 ['Total', 15479.5, 47289.25, 583.7498, 191.0827, 108433869.0]
71 ['', '', '', '', '', '']
72 ['', '', '', '', '', '']
73 ['Hawaii', '', '', '', '', '']
74 ['Oct 2013', 99081.0, 194961.0, 445.8961, 226.6086, 44179832.0]
75 ['Nov 2013', 98426.0, 193936.0, 445.3293, 226.0126, 43831978.0]
76 ['Dec 2013', 98807.0, 194550.0, 442.8485, 224.9115, 43756536.0]
77 ['Jan 2014', 98573.0, 193897.0, 440.6423, 224.0129, 43435431.0]
78 ['Feb 2014', 98204.0, 193255.0, 441.5425, 224.3732, 43361235.0]
79 ['Mar 2014', 98745.0, 193930.0, 441.1198, 224.6088, 43558379.0]
80 ['Apr 2014', 98688.0, 193600.0, 440.4714, 224.5312, 43469237.0]
81 ['May 2014', 98860.0, 193933.0, 441.3429, 224.9806, 43631158.0]
82 ['Jun 2014', 99320.0, 194865.0, 439.4339, 223.9734, 43644579.0]
83 ['Jul 2014', 99629.0, 195703.0, 440.2699, 224.1338, 43863653.0]
84 ['Aug 2014', 97629.0, 192117.0, 458.7186, 233.1092, 44784240.0]
85 ['Sep 2014', 99997.0, 196420.0, 438.8302, 223.4075, 43881702.0]
86 ['Total', 98829.9167, 194263.9167, 443.0153, 225.3798, 525397960.0]
87 ['', '', '', '', '', '']
88 ['', '', '', '', '', '']
89 ['Idaho', '', '', '', '', '']
90 ['Oct 2013', 94493.0, 219112.0, 290.3138, 125.1991, 27432619.0]
91 ['Nov 2013', 93146.0, 217219.0, 275.9001, 118.3091, 25698989.0]
92 ['Dec 2013', 92436.0, 216218.0, 273.1499, 116.7751, 25248882.0]
93 ['Jan 2014', 92809.0, 217399.0, 268.8951, 114.793, 24955889.0]
94 ['Feb 2014', 91627.0, 215468.0, 272.0196, 115.6754, 24924338.0]
95 ['Mar 2014', 91006.0, 214339.0, 271.9058, 115.4482, 24745062.0]
96 ['Apr 2014', 89894.0, 212021.0, 272.377, 115.4841, 24485062.0]
97 ['May 2014', 89166.0, 210450.0, 272.8516, 115.6051, 24329090.0]
98 ['Jun 2014', 88128.0, 207896.0, 271.4438, 115.0662, 23921801.0]
99 ['Jul 2014', 86900.0, 205160.0, 270.5895, 114.6141, 23514230.0]
100 ['Aug 2014', 86400.0, 203770.0, 269.9235, 114.4496, 23321392.0]
101 ['Sep 2014', 85929.0, 202318.0, 268.6592, 114.1056, 23085619.0]
102 ['Total', 90161.1667, 211780.8333, 273.2727, 116.34, 295662973.0]
103 ['', '', '', '', '', '']
104 ['', '', '', '', '', '']
105 ['Nevada', '', '', '', '', '']
106 ['Oct 2013', 180639.0, 372377.0, 254.3759, 123.397, 45950209.0]
107 ['Nov 2013', 179516.0, 369352.0, 239.9316, 116.6138, 43071554.0]
108 ['Dec 2013', 180618.0, 370544.0, 238.4462, 116.2282, 43067667.0]
109 ['Jan 2014', 182660.0, 373901.0, 235.929, 115.2572, 43094796.0]
110 ['Feb 2014', 184321.0, 375708.0, 232.918, 114.2687, 42931683.0]
111 ['Mar 2014', 187080.0, 379657.0, 236.3993, 116.4882, 44225576.0]
112 ['Apr 2014', 189665.0, 384136.0, 234.3838, 115.7257, 44454402.0]
113 ['May 2014', 192062.0, 388284.0, 235.8732, 116.6731, 45302279.0]
114 ['Jun 2014', 194082.0, 391816.0, 234.6175, 116.2153, 45535026.0]
115 ['Jul 2014', 196004.0, 395236.0, 234.9016, 116.4915, 46041647.0]
116 ['Aug 2014', 198236.0, 399514.0, 232.9834, 115.6047, 46185696.0]
117 ['Sep 2014', 199985.0, 402937.0, 234.2715, 116.2732, 46850778.0]
118 ['Total', 188739.0, 383621.8333, 236.9724, 116.5886, 536711313.0]
119 ['', '', '', '', '', '']
120 ['', '', '', '', '', '']
121 ['Oregon', '', '', '', '', '']
122 ['Oct 2013', 450242.0, 810191.0, 230.6102, 128.1554, 103830392.0]
123 ['Nov 2013', 447095.0, 805163.0, 214.4749, 119.0947, 95890674.0]
124 ['Dec 2013', 445922.0, 802237.0, 214.6052, 119.2879, 95697195.0]
125 ['Jan 2014', 449073.0, 806740.0, 213.6162, 118.9098, 95929258.0]
126 ['Feb 2014', 448841.0, 804591.0, 216.0447, 120.5205, 96969713.0]
127 ['Mar 2014', 449290.0, 803108.0, 215.797, 120.7253, 96955417.0]
128 ['Apr 2014', 450370.0, 802749.0, 215.8454, 121.0967, 97210284.0]
129 ['May 2014', 450575.0, 802312.0, 215.2151, 120.8639, 96970544.0]
130 ['Jun 2014', 450152.0, 799042.0, 214.4497, 120.8134, 96534974.0]
131 ['Jul 2014', 449468.0, 800211.0, 213.1671, 119.7332, 95811789.0]
132 ['Aug 2014', 448718.0, 798715.0, 212.6728, 119.4796, 95430130.0]
133 ['Sep 2014', 446519.0, 791222.0, 211.9521, 119.6133, 94640635.0]
134 ['Total', 448855.4167, 802190.0833, 215.71, 120.6978, 1161871005.0]
135 ['', '', '', '', '', '']
136 ['', '', '', '', '', '']
137 ['Washington', '', '', '', '', '']
138 ['Oct 2013', 592612.0, 1113644.0, 235.6114, 125.3777, 139626118.0]
139 ['Nov 2013', 586295.0, 1091092.0, 219.0518, 117.7068, 128428968.0]
140 ['Dec 2013', 584570.0, 1082598.0, 220.1444, 118.8713, 128689819.0]
141 ['Jan 2014', 586863.0, 1088502.0, 220.0135, 118.6197, 129117803.0]
142 ['Feb 2014', 586058.0, 1088175.0, 220.1293, 118.5549, 129008511.0]
143 ['Mar 2014', 586285.0, 1112524.0, 221.3688, 116.6583, 129785199.0]
144 ['Apr 2014', 586042.0, 1105343.0, 219.6523, 116.4575, 128725500.0]
145 ['May 2014', 586774.0, 1103493.0, 219.5212, 116.7287, 128809326.0]
146 ['Jun 2014', 585207.0, 1099975.0, 218.447, 116.2178, 127836708.0]
147 ['Jul 2014', 582459.0, 1094228.0, 217.5619, 115.8085, 126720901.0]
148 ['Aug 2014', 580788.0, 1089665.0, 217.1828, 115.7577, 126137168.0]
149 ['Sep 2014', 577301.0, 1077374.0, 215.9356, 115.7071, 124659861.0]
150 ['Total', 585104.5, 1095551.0833, 220.4088, 117.7144, 1547545882.0]
151 ['', '', '', '', '', '']
152 ['', '', '', '', '', '']
153 ['Outlying Areas', '', '', '', '', '']
154 [' No data found.', '', '', '', '', '']
155 ['', '', '', '', '', '']
156 ['', '', '', '', '', '']
157 ['WRO', '', '', '', '', '']
158 ['Oct 2013', 3895685.0, 8171259.0, 300.8209, 143.4177, 1171903426.0]
159 ['Nov 2013', 3885019.0, 8150142.0, 281.481, 134.1767, 1093559089.0]
160 ['Dec 2013', 3892923.0, 8150651.0, 280.9564, 134.1907, 1093741645.0]
161 ['Jan 2014', 3904044.0, 8196464.0, 280.0882, 133.4083, 1093476718.0]
162 ['Feb 2014', 3896104.0, 8160612.0, 280.6364, 133.9836, 1093388407.0]
163 ['Mar 2014', 3923826.0, 8193216.0, 280.2257, 134.2033, 1099556746.0]
164 ['Apr 2014', 3937420.0, 8203460.0, 278.9695, 133.8972, 1098420054.0]
165 ['May 2014', 3955034.0, 8224864.0, 278.5838, 133.9607, 1101808559.0]
166 ['Jun 2014', 3968133.0, 8281901.0, 277.1896, 132.8107, 1099925143.0]
167 ['Jul 2014', 3973636.0, 8292940.0, 276.5718, 132.5218, 1098995642.0]
168 ['Aug 2014', 3984290.0, 8296405.0, 276.3487, 132.7145, 1101053265.0]
169 ['Sep 2014', 3980831.0, 8271618.0, 274.3853, 132.0518, 1092281704.0]
170 ['Total', 3933078.75, 8216127.6667, 280.4866, 134.2696, 13238110398.0]
171 ['', '', '', '', '', '']
172 ['', '', '', '', '', '']
173 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
174 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [459]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,25,41,57,73,89,105,121,137,153,157]:
        #for the rows that have the state names
        state = row[0]
        if state == 'WRO':
            break
        else:
            continue         
    if i in [18,23,38,54,70,86,102,118,134,150,155,170]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [460]:
pprint.pprint(snap_data)

{'Alabama': {'cost_by_household': 261.8137,
             'cost_by_individual': 121.7689,
             'household_participation': 419552.0,
             'individual_participation': 902073.1667,
             'total_cost': 1318133562.0},
 'Alaska': {'cost_by_household': 392.4666,
            'cost_by_individual': 165.9705,
            'household_participation': 36997.1667,
            'individual_participation': 87486.3333,
            'total_cost': 174241813.0},
 'American Samoa': {'cost_by_household': '',
                    'cost_by_individual': '',
                    'household_participation': '',
                    'individual_participation': '',
                    'total_cost': ''},
 'Arizona': {'cost_by_household': 273.6935,
             'cost_by_individual': 117.8419,
             'household_participation': 449639.8333,
             'individual_participation': 1044310.0833,
             'total_cost': 1476761898.0},
 'Arkansas': {'cost_by_household': 249.767,
              'cost_by_individual': 112.4266,
              'household_participation': 221446.1667,
              'individual_participation': 491964.6667,
              'total_cost': 663719268.0},
 'California': {'cost_by_household': 305.8645,
                'cost_by_individual': 141.9944,
                'household_participation': 2019272.25,
                'individual_participation': 4349634.25,
                'total_cost': 7411483685.0},
 'Colorado': {'cost_by_household': 272.5846,
              'cost_by_individual': 126.3169,
              'household_participation': 234097.6667,
              'individual_participation': 505169.25,
              'total_cost': 765737085.0},
 'Connecticut': {'cost_by_household': 239.1931,
                 'cost_by_individual': 132.5242,
                 'household_participation': 242982.0833,
                 'individual_participation': 438558.8333,
                 'total_cost': 697435672.0},
 'Delaware': {'cost_by_household': 257.1523,
              'cost_by_individual': 122.2289,
              'household_participation': 71408.0,
              'individual_participation': 150232.3333,
              'total_cost': 220352805.0},
 'District of Columbia': {'cost_by_household': 230.8397,
                          'cost_by_individual': 129.9891,
                          'household_participation': 80360.25,
                          'individual_participation': 142706.9167,
                          'total_cost': 222604041.0},
 'Florida': {'cost_by_household': 237.45,
             'cost_by_individual': 129.3333,
             'household_participation': 1920697.3333,
             'individual_participation': 3526311.25,
             'total_cost': 5472834001.0},
 'Georgia': {'cost_by_household': 267.1472,
             'cost_by_individual': 121.3033,
             'household_participation': 882114.8333,
             'individual_participation': 1942688.9167,
             'total_cost': 2827853876.0},
 'Guam': {'cost_by_household': 583.7498,
          'cost_by_individual': 191.0827,
          'household_participation': 15479.5,
          'individual_participation': 47289.25,
          'total_cost': 108433869.0},
 'Hawaii': {'cost_by_household': 443.0153,
            'cost_by_individual': 225.3798,
            'household_participation': 98829.9167,
            'individual_participation': 194263.9167,
            'total_cost': 525397960.0},
 'Idaho': {'cost_by_household': 273.2727,
           'cost_by_individual': 116.34,
           'household_participation': 90161.1667,
           'individual_participation': 211780.8333,
           'total_cost': 295662973.0},
 'Illinois': {'cost_by_household': 261.3483,
              'cost_by_individual': 132.4247,
              'household_participation': 1021149.8333,
              'individual_participation': 2015303.1667,
              'total_cost': 3202509863.0},
 'Indiana': {'cost_by_household': 270.1329,
             'cost_by_individual': 122.4255,
             'household_participation': 404575.0833,
             'individual_participation': 892698.5833,
             'total_cost': 1311468403.0},
 'Iowa': {'cost_by_household': 229.3008,
          'cost_by_individual': 108.659,
          'household_participation': 193372.3333,
          'individual_participation': 408069.75,
          'total_cost': 532085213.0},
 'Kansas': {'cost_by_household': 247.9508,
            'cost_by_individual': 112.2286,
            'household_participation': 132825.4167,
            'individual_participation': 293456.0833,
            'total_cost': 395209994.0},
 'Kentucky': {'cost_by_household': 244.441,
              'cost_by_individual': 117.8425,
              'household_participation': 399206.75,
              'individual_participation': 828075.8333,
              'total_cost': 1170989948.0},
 'Louisiana': {'cost_by_household': 270.8178,
               'cost_by_individual': 122.3695,
               'household_participation': 396427.75,
               'individual_participation': 877340.1667,
               'total_cost': 1288316273.0},
 'Maine': {'cost_by_household': 218.4024,
           'cost_by_individual': 116.2331,
           'household_participation': 122690.4167,
           'individual_participation': 230535.5833,
           'total_cost': 321550513.0},
 'Maryland': {'cost_by_household': 233.8592,
              'cost_by_individual': 119.8938,
              'household_participation': 403781.3333,
              'individual_participation': 787597.25,
              'total_cost': 1133135874.0},
 'Massachusetts': {'cost_by_household': 216.918,
                   'cost_by_individual': 122.8631,
                   'household_participation': 489039.4167,
                   'individual_participation': 863411.9167,
                   'total_cost': 1272977488.0},
 'Michigan': {'cost_by_household': 246.0413,
              'cost_by_individual': 127.8301,
              'household_participation': 872538.3333,
              'individual_participation': 1679420.6667,
              'total_cost': 2576165148.0},
 'Minnesota': {'cost_by_household': 214.4481,
               'cost_by_individual': 104.6387,
               'household_participation': 260437.0,
               'individual_participation': 533743.3333,
               'total_cost': 670202668.0},
 'Mississippi': {'cost_by_household': 251.7594,
                 'cost_by_individual': 115.825,
                 'household_participation': 302201.75,
                 'individual_participation': 656871.3333,
                 'total_cost': 912985504.0},
 'Missouri': {'cost_by_household': 255.0973,
              'cost_by_individual': 120.0317,
              'household_participation': 403912.75,
              'individual_participation': 858415.5833,
              'total_cost': 1236444630.0},
 'Montana': {'cost_by_household': 248.4186,
             'cost_by_individual': 117.5347,
             'household_participation': 59097.0,
             'individual_participation': 124906.0833,
             'total_cost': 176169543.0},
 'Nebraska': {'cost_by_household': 258.8282,
              'cost_by_individual': 114.7275,
              'household_participation': 76918.5833,
              'individual_participation': 173530.3333,
              'total_cost': 238904358.0},
 'Nevada': {'cost_by_household': 236.9724,
            'cost_by_individual': 116.5886,
            'household_participation': 188739.0,
            'individual_participation': 383621.8333,
            'total_cost': 536711313.0},
 'New Hampshire': {'cost_by_household': 218.9464,
                   'cost_by_individual': 104.9813,
                   'household_participation': 53559.0,
                   'individual_participation': 111701.3333,
                   'total_cost': 140718624.0},
 'New Jersey': {'cost_by_household': 244.6184,
                'cost_by_individual': 121.7491,
                'household_participation': 439694.5,
                'individual_participation': 883434.4167,
                'total_cost': 1290688313.0},
 'New Mexico': {'cost_by_household': 268.5163,
                'cost_by_individual': 121.5083,
                'household_participation': 195258.3333,
                'individual_participation': 431493.5,
                'total_cost': 629160453.0},
 'New York': {'cost_by_household': 255.1554,
              'cost_by_individual': 138.7811,
              'household_participation': 1698559.25,
              'individual_participation': 3122878.8333,
              'total_cost': 5200758093.0},
 'North Carolina': {'cost_by_household': 260.9772,
                    'cost_by_individual': 126.0608,
                    'household_participation': 761104.5833,
                    'individual_participation': 1575675.75,
                    'total_cost': 2383571501.0},
 'North Dakota': {'cost_by_household': 252.4373,
                  'cost_by_individual': 117.4582,
                  'household_participation': 25011.1667,
                  'individual_participation': 53753.1667,
                  'total_cost': 75765024.0},
 'Ohio': {'cost_by_household': 252.6254,
          'cost_by_individual': 122.8386,
          'household_participation': 851972.25,
          'individual_participation': 1752135.1667,
          'total_cost': 2582757967.0},
 'Oklahoma': {'cost_by_household': 257.8185,
              'cost_by_individual': 118.469,
              'household_participation': 279605.5,
              'individual_participation': 608492.3333,
              'total_cost': 865049765.0},
 'Oregon': {'cost_by_household': 215.71,
            'cost_by_individual': 120.6978,
            'household_participation': 448855.4167,
            'individual_participation': 802190.0833,
            'total_cost': 1161871005.0},
 'Outlying Areas': {'cost_by_household': '',
                    'cost_by_individual': '',
                    'household_participation': '',
                    'individual_participation': '',
                    'total_cost': ''},
 'Pennsylvania': {'cost_by_household': 241.0536,
                  'cost_by_individual': 119.4059,
                  'household_participation': 889725.1667,
                  'individual_participation': 1796154.3333,
                  'total_cost': 2573657445.0},
 'Puerto Rico': {'cost_by_household': '',
                 'cost_by_individual': '',
                 'household_participation': '',
                 'individual_participation': '',
                 'total_cost': ''},
 'Rhode Island': {'cost_by_household': 230.8887,
                  'cost_by_individual': 130.6327,
                  'household_participation': 101002.25,
                  'individual_participation': 178517.8333,
                  'total_cost': 279843287.0},
 'South Carolina': {'cost_by_household': 260.5579,
                    'cost_by_individual': 123.3952,
                    'household_participation': 395208.5,
                    'individual_participation': 834511.0,
                    'total_cost': 1235696260.0},
 'South Dakota': {'cost_by_household': 281.8308,
                  'cost_by_individual': 122.9619,
                  'household_participation': 44038.9167,
                  'individual_participation': 100937.9167,
                  'total_cost': 148938276.0},
 'Tennessee': {'cost_by_household': 250.1495,
               'cost_by_individual': 123.9309,
               'household_participation': 650250.8333,
               'individual_participation': 1312505.3333,
               'total_cost': 1951918832.0},
 'Texas': {'cost_by_household': 276.3136,
           'cost_by_individual': 115.3019,
           'household_participation': 1607669.3333,
           'individual_participation': 3852674.9167,
           'total_cost': 5330650619.0},
 'Utah': {'cost_by_household': 291.369,
          'cost_by_individual': 114.7804,
          'household_participation': 90570.0833,
          'individual_participation': 229911.3333,
          'total_cost': 316671764.0},
 'Vermont': {'cost_by_household': 223.581,
             'cost_by_individual': 116.7786,
             'household_participation': 48574.6667,
             'individual_participation': 92999.6667,
             'total_cost': 130324476.0},
 'Virgin Islands': {'cost_by_household': 367.9798,
                    'cost_by_individual': 165.0243,
                    'household_participation': 12477.9167,
                    'individual_participation': 27823.9167,
                    'total_cost': 55099458.0},
 'Virginia': {'cost_by_household': 244.8269,
              'cost_by_individual': 118.1919,
              'household_participation': 443606.5833,
              'individual_participation': 918902.0833,
              'total_cost': 1303281631.0},
 'Washington': {'cost_by_household': 220.4088,
                'cost_by_individual': 117.7144,
                'household_participation': 585104.5,
                'individual_participation': 1095551.0833,
                'total_cost': 1547545882.0},
 'West Virginia': {'cost_by_household': 225.4056,
                   'cost_by_individual': 109.4559,
                   'household_participation': 176028.6667,
                   'individual_participation': 362500.8333,
                   'total_cost': 476134200.0},
 'Wisconsin': {'cost_by_household': 220.3924,
               'cost_by_individual': 110.2137,
               'household_participation': 420833.0833,
               'individual_participation': 841532.8333,
               'total_cost': 1112980884.0},
 'Wyoming': {'cost_by_household': 269.2593,
             'cost_by_individual': 114.467,
             'household_participation': 15249.4167,
             'individual_participation': 35871.0,
             'total_cost': 49272569.0}}

In [461]:
snap_data_2014 = pd.DataFrame.from_dict(snap_data, orient = "index")

In [462]:
pd.DataFrame.to_csv(snap_data_2014,'SNAP/SNAP DFs/snap_2014_df.csv')

# 2013

In [463]:
pd.DataFrame.to_csv(snap_data_2017,'SNAP/SNAP DFs/snap_2017_df.csv')

In [464]:
book = xlrd.open_workbook('SNAP/FY13.xls')

In [465]:
sheet = book.sheet_by_name('NERO')

In [466]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2013', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Connecticut', '', '', '', '', '']
6 ['Oct 2012', 226133.0, 414875.0, 255.2593, 139.1324, 57722545.0]
7 ['Nov 2012', 229648.0, 420819.0, 275.5637, 150.3798, 63282664.0]
8 ['Dec 2012', 231541.0, 424197.0, 254.6552, 138.9994, 58963125.0]
9 ['Jan 2013', 232871.0, 426519.0, 248.6896, 135.7796, 57912595.0]
10 ['Feb 2013', 231412.0, 422884.0, 248.9585, 136.2359, 57611979.0]
11 ['Mar 2013', 231407.0, 422064.0, 248.7022, 136.3571, 57551430.0]
12 ['Apr 2013', 232481.0, 423328.0, 248.4562, 136.4459, 57761351.0]
13 ['May 2013', 234209.0, 426863.0, 250.1218, 137.2356, 58580783.0]
14 ['Jun 2013', 237105.0, 430599.0, 248.6833, 136.935, 58964057.0]
15 ['Jul 2013', 237063.0, 430157.0, 248.5035, 136.9523, 58910984.0]
16 ['Aug 2013', 236117.0, 429190.0, 255.2653, 140.4331, 60272469.0]
17 ['Sep 2013', 238070.0, 432339.0, 252.5334, 139.059, 60120630.0]
18 ['Total', 233171.4167, 425319.5, 252.9093, 138.6516, 707654612.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Maine', '', '', '', '', '']
22 ['Oct 2012', 130700.0, 250912.0, 236.7928, 123.3453, 30948823.0]
23 ['Nov 2012', 130150.0, 249099.0, 236.8787, 123.7651, 30829762.0]
24 ['Dec 2012', 130415.0, 249792.0, 236.8411, 123.6534, 30887635.0]
25 ['Jan 2013', 131489.0, 252482.0, 234.5606, 122.1558, 30842135.0]
26 ['Feb 2013', 130544.0, 250189.0, 234.4256, 122.3189, 30602855.0]
27 ['Mar 2013', 131246.0, 251418.0, 234.6441, 122.4897, 30796106.0]
28 ['Apr 2013', 131126.0, 250434.0, 234.2222, 122.6376, 30712619.0]
29 ['May 2013', 131042.0, 249920.0, 233.5368, 122.4517, 30603130.0]
30 ['Jun 2013', 130678.0, 248730.0, 233.2939, 122.5682, 30486377.0]
31 ['Jul 2013', 129947.0, 247565.0, 233.3497, 122.4854, 30323088.0]
32 ['Aug 2013', 128799.0, 244855.0, 234.1805, 123.184, 30162208.0]
33 ['Sep 2013', 128355.0, 244026.0, 232.7541, 122.4261, 29875150.0]
34 ['Total', 130374.25, 249118.5, 234.6258, 122.7896, 367069888.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Massachusetts', '', '', '', '', '']
38 ['Oct 2012', 495475.0, 884453.0, 233.4335, 130.7706, 115660475.0]
39 ['Nov 2012', 496634.0, 886055.0, 236.2159, 132.3991, 117312859.0]
40 ['Dec 2012', 496759.0, 885564.0, 234.652, 131.6285, 116565496.0]
41 ['Jan 2013', 499221.0, 888527.0, 233.8706, 131.4007, 116753094.0]
42 ['Feb 2013', 497816.0, 885956.0, 235.9565, 132.5832, 117462901.0]
43 ['Mar 2013', 499305.0, 887990.0, 232.5555, 130.7629, 116116135.0]
44 ['Apr 2013', 500041.0, 888531.0, 230.9946, 129.9975, 115506777.0]
45 ['May 2013', 497352.0, 885701.0, 233.9639, 131.3789, 116362415.0]
46 ['Jun 2013', 499181.0, 888377.0, 233.6003, 131.2605, 116608844.0]
47 ['Jul 2013', 498164.0, 887184.0, 230.18, 129.2487, 114667405.0]
48 ['Aug 2013', 501108.0, 891502.0, 232.7968, 130.8537, 116656352.0]
49 ['Sep 2013', 501905.0, 891584.0, 228.8537, 128.8301, 114862826.0]
50 ['Total', 498580.0833, 887618.6667, 233.0845, 130.9248, 1394535579.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['New Hampshire', '', '', '', '', '']
54 ['Oct 2012', 57615.0, 119115.0, 244.6553, 118.3378, 14095813.0]
55 ['Nov 2012', 57564.0, 119014.0, 241.5014, 116.808, 13901784.0]
56 ['Dec 2012', 57507.0, 118871.0, 242.2525, 117.1961, 13931217.0]
57 ['Jan 2013', 58214.0, 120160.0, 240.606, 116.5666, 14006637.0]
58 ['Feb 2013', 56278.0, 117641.0, 241.854, 115.7, 13611060.0]
59 ['Mar 2013', 56058.0, 117420.0, 241.9364, 115.5039, 13562470.0]
60 ['Apr 2013', 55919.0, 117148.0, 242.2234, 115.622, 13544889.0]
61 ['May 2013', 55332.0, 116319.0, 241.6121, 114.9329, 13368881.0]
62 ['Jun 2013', 55181.0, 116098.0, 241.4562, 114.7633, 13323795.0]
63 ['Jul 2013', 55063.0, 115721.0, 240.3103, 114.3458, 13232207.0]
64 ['Aug 2013', 55034.0, 115529.0, 240.8273, 114.7218, 13253690.0]
65 ['Sep 2013', 54648.0, 114742.0, 240.4179, 114.5035, 13138357.0]
66 ['Total', 56201.0833, 117314.8333, 241.6484, 115.7646, 162970800.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['New York', '', '', '', '', '']
70 ['Oct 2012', 1673078.0, 3110070.0, 272.0418, 146.3463, 455147188.0]
71 ['Nov 2012', 1696317.0, 3152122.0, 320.0349, 172.2271, 542880694.0]
72 ['Dec 2012', 1716394.0, 3186236.0, 280.4771, 151.0902, 481409152.0]
73 ['Jan 2013', 1703073.0, 3158541.0, 268.9415, 145.0122, 458026953.0]
74 ['Feb 2013', 1700761.0, 3153979.0, 268.4876, 144.78, 456633217.0]
75 ['Mar 2013', 1718504.0, 3182976.0, 268.8535, 145.1553, 462025886.0]
76 ['Apr 2013', 1719342.0, 3181218.0, 267.8162, 144.7457, 460467643.0]
77 ['May 2013', 1720229.0, 3183287.0, 268.3828, 145.0325, 461679940.0]
78 ['Jun 2013', 1721266.0, 3186788.0, 268.053, 144.7823, 461390591.0]
79 ['Jul 2013', 1725772.0, 3194470.0, 267.9957, 144.7813, 462499461.0]
80 ['Aug 2013', 1721010.0, 3186530.0, 268.0601, 144.7763, 461334040.0]
81 ['Sep 2013', 1710269.0, 3169363.0, 267.7418, 144.4803, 457910480.0]
82 ['Total', 1710501.25, 3170465.0, 273.8673, 147.7545, 5621405245.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Rhode Island', '', '', '', '', '']
86 ['Oct 2012', 98396.0, 176998.0, 250.1977, 139.0889, 24618457.0]
87 ['Nov 2012', 99486.0, 178630.0, 255.7856, 142.4569, 25447082.0]
88 ['Dec 2012', 99796.0, 179127.0, 251.1927, 139.9456, 25068028.0]
89 ['Jan 2013', 100424.0, 180392.0, 248.0383, 138.0826, 24908995.0]
90 ['Feb 2013', 100686.0, 180626.0, 251.852, 140.3894, 25357968.0]
91 ['Mar 2013', 101090.0, 180940.0, 269.5942, 150.6205, 27253280.0]
92 ['Apr 2013', 101117.0, 180731.0, 248.2597, 138.8985, 25103272.0]
93 ['May 2013', 101096.0, 180546.0, 248.0104, 138.8724, 25072863.0]
94 ['Jun 2013', 100965.0, 180260.0, 247.9341, 138.8698, 25032666.0]
95 ['Jul 2013', 101047.0, 180405.0, 247.9804, 138.8968, 25057671.0]
96 ['Aug 2013', 101159.0, 180294.0, 247.1902, 138.693, 25005518.0]
97 ['Sep 2013', 101250.0, 180151.0, 246.5652, 138.5767, 24964723.0]
98 ['Total', 100542.6667, 179925.0, 251.0464, 140.2855, 302890523.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['Vermont', '', '', '', '', '']
102 ['Oct 2012', 51289.0, 99416.0, 242.9609, 125.3443, 12461224.0]
103 ['Nov 2012', 51676.0, 100111.0, 240.9014, 124.3502, 12448820.0]
104 ['Dec 2012', 52017.0, 100624.0, 240.4096, 124.2784, 12505386.0]
105 ['Jan 2013', 52708.0, 101768.0, 240.5695, 124.5965, 12679939.0]
106 ['Feb 2013', 52809.0, 101793.0, 240.3655, 124.6988, 12693463.0]
107 ['Mar 2013', 52871.0, 101712.0, 238.6479, 124.0518, 12617554.0]
108 ['Apr 2013', 52659.0, 100985.0, 237.0494, 123.6103, 12482782.0]
109 ['May 2013', 52606.0, 100607.0, 238.8489, 124.8908, 12564887.0]
110 ['Jun 2013', 52370.0, 100020.0, 236.0411, 123.59, 12361474.0]
111 ['Jul 2013', 52179.0, 99608.0, 237.6519, 124.4924, 12400440.0]
112 ['Aug 2013', 52354.0, 99764.0, 236.804, 124.2697, 12397639.0]
113 ['Sep 2013', 52510.0, 100087.0, 236.9178, 124.2974, 12440556.0]
114 ['Total', 52337.3333, 100541.25, 238.9215, 124.372, 150054164.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['NERO', '', '', '', '', '']
118 ['Oct 2012', 2732686.0, 5055839.0, 260.0571, 140.5611, 710654525.0]
119 ['Nov 2012', 2761475.0, 5105850.0, 291.9105, 157.8784, 806103665.0]
120 ['Dec 2012', 2784429.0, 5144411.0, 265.523, 143.7152, 739330039.0]
121 ['Jan 2013', 2778000.0, 5128389.0, 257.4263, 139.4454, 715130348.0]
122 ['Feb 2013', 2770306.0, 5113068.0, 257.7237, 139.637, 713973443.0]
123 ['Mar 2013', 2790481.0, 5144520.0, 257.9924, 139.9398, 719922861.0]
124 ['Apr 2013', 2792685.0, 5142375.0, 256.2335, 139.1535, 715579333.0]
125 ['May 2013', 2791866.0, 5143243.0, 257.2591, 139.6459, 718232899.0]
126 ['Jun 2013', 2796746.0, 5150872.0, 256.7869, 139.4265, 718167804.0]
127 ['Jul 2013', 2799235.0, 5155110.0, 256.174, 139.103, 717091256.0]
128 ['Aug 2013', 2795581.0, 5147664.0, 257.2209, 139.6909, 719081916.0]
129 ['Sep 2013', 2787007.0, 5132292.0, 255.9422, 138.9852, 713312722.0]
130 ['Total', 2781708.0833, 5130302.75, 260.8284, 141.4241, 8706580811.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
134 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [467]:
snap_data = {}

########################
#                      #
# NERO                 #
#                      #
########################

for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117]:
        #for the rows that have the state names
        state = row[0]
        if state == 'NERO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [468]:
########################
#                      #
# MARO                 #
#                      #
########################

sheet = book.sheet_by_name('MARO')

In [469]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2013', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Delaware', '', '', '', '', '']
6 ['Oct 2012', 71326.0, 151387.0, 270.1328, 127.2731, 19267493.0]
7 ['Nov 2012', 72357.0, 153651.0, 273.4439, 128.7696, 19785582.0]
8 ['Dec 2012', 71854.0, 152507.0, 268.9997, 126.7398, 19328706.0]
9 ['Jan 2013', 73231.0, 155334.0, 271.487, 127.9904, 19881262.0]
10 ['Feb 2013', 72041.0, 152756.0, 274.5585, 129.4841, 19779468.0]
11 ['Mar 2013', 71812.0, 152002.0, 270.3205, 127.7105, 19412256.0]
12 ['Apr 2013', 72693.0, 153857.0, 270.6689, 127.8833, 19675737.0]
13 ['May 2013', 72523.0, 153339.0, 270.6814, 128.0211, 19630624.0]
14 ['Jun 2013', 72084.0, 152809.0, 271.6531, 128.1458, 19581839.0]
15 ['Jul 2013', 71700.0, 151921.0, 271.0393, 127.9186, 19433516.0]
16 ['Aug 2013', 72483.0, 153885.0, 271.9982, 128.1167, 19715243.0]
17 ['Sep 2013', 72819.0, 154199.0, 268.292, 126.6983, 19536755.0]
18 ['Total', 72243.5833, 153137.25, 271.1065, 127.8964, 235028481.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['District of Columbia', '', '', '', '', '']
22 ['Oct 2012', 81615.0, 144495.0, 240.8513, 136.0398, 19657078.0]
23 ['Nov 2012', 82107.0, 145398.0, 240.214, 135.6501, 19723254.0]
24 ['Dec 2012', 81885.0, 145054.0, 239.5542, 135.2317, 19615893.0]
25 ['Jan 2013', 82243.0, 145327.0, 238.3661, 134.8954, 19603943.0]
26 ['Feb 2013', 81783.0, 144545.0, 237.4089, 134.325, 19416008.0]
27 ['Mar 2013', 81832.0, 144193.0, 237.4435, 134.7532, 19430475.0]
28 ['Apr 2013', 81253.0, 143361.0, 238.3176, 135.0717, 19364018.0]
29 ['May 2013', 81617.0, 144200.0, 238.7444, 135.129, 19485598.0]
30 ['Jun 2013', 81769.0, 144619.0, 238.3241, 134.7508, 19487524.0]
31 ['Jul 2013', 82059.0, 145249.0, 239.0904, 135.0751, 19619522.0]
32 ['Aug 2013', 82453.0, 146161.0, 240.2166, 135.5121, 19806579.0]
33 ['Sep 2013', 82231.0, 146065.0, 240.915, 135.6292, 19810678.0]
34 ['Total', 81903.9167, 144888.9167, 239.1222, 135.1728, 235020570.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Maryland', '', '', '', '', '']
38 ['Oct 2012', 378116.0, 747316.0, 252.7062, 127.8606, 95552243.0]
39 ['Nov 2012', 380139.0, 750784.0, 256.7186, 129.9824, 97588733.0]
40 ['Dec 2012', 381713.0, 754171.0, 253.1275, 128.1169, 96622060.0]
41 ['Jan 2013', 386397.0, 760830.0, 249.662, 126.794, 96468653.0]
42 ['Feb 2013', 387924.0, 762890.0, 249.8602, 127.0521, 96926774.0]
43 ['Mar 2013', 390689.0, 766599.0, 249.5478, 127.1794, 97495584.0]
44 ['Apr 2013', 394312.0, 773137.0, 249.1814, 127.0864, 98255200.0]
45 ['May 2013', 396443.0, 776725.0, 249.3191, 127.2533, 98840827.0]
46 ['Jun 2013', 399175.0, 782926.0, 249.1303, 127.0192, 99446607.0]
47 ['Jul 2013', 401323.0, 787382.0, 248.477, 126.647, 99719533.0]
48 ['Aug 2013', 404314.0, 793693.0, 249.2804, 126.9856, 100787545.0]
49 ['Sep 2013', 405658.0, 795796.0, 248.8751, 126.8644, 100958172.0]
50 ['Total', 392183.5833, 771020.75, 250.4486, 127.3919, 1178661931.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['New Jersey', '', '', '', '', '']
54 ['Oct 2012', 424092.0, 857605.0, 267.6627, 132.3612, 113513618.0]
55 ['Nov 2012', 437020.0, 882345.0, 315.1, 156.0671, 137704994.0]
56 ['Dec 2012', 441233.0, 906148.0, 338.9988, 165.0696, 149577445.0]
57 ['Jan 2013', 427849.0, 867660.0, 263.2173, 129.7942, 112617260.0]
58 ['Feb 2013', 427271.0, 866157.0, 263.746, 130.1046, 112691034.0]
59 ['Mar 2013', 431095.0, 873657.0, 263.7911, 130.1644, 113719009.0]
60 ['Apr 2013', 430554.0, 871760.0, 262.4431, 129.6181, 112995916.0]
61 ['May 2013', 433734.0, 877752.0, 262.7066, 129.8143, 113944780.0]
62 ['Jun 2013', 432363.0, 875437.0, 261.7038, 129.2509, 113151027.0]
63 ['Jul 2013', 432521.0, 877043.0, 260.391, 128.414, 112624596.0]
64 ['Aug 2013', 436033.0, 883015.0, 261.0937, 128.9281, 113845486.0]
65 ['Sep 2013', 433469.0, 876613.0, 260.3219, 128.7244, 112841457.0]
66 ['Total', 432269.5, 876266.0, 273.5999, 134.9692, 1419226622.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Pennsylvania', '', '', '', '', '']
70 ['Oct 2012', 860280.0, 1772081.0, 263.7107, 128.0218, 226865027.0]
71 ['Nov 2012', 873121.0, 1797976.0, 285.9368, 138.8547, 249657440.0]
72 ['Dec 2012', 854631.0, 1761270.0, 264.0405, 128.1218, 225657159.0]
73 ['Jan 2013', 857817.0, 1767367.0, 264.5249, 128.391, 226913929.0]
74 ['Feb 2013', 858782.0, 1767598.0, 261.4366, 127.0181, 224517012.0]
75 ['Mar 2013', 864963.0, 1777618.0, 264.0238, 128.4701, 228370810.0]
76 ['Apr 2013', 865358.0, 1776949.0, 261.6701, 127.4309, 226438298.0]
77 ['May 2013', 871026.0, 1784566.0, 261.3446, 127.5593, 227637965.0]
78 ['Jun 2013', 874379.0, 1788531.0, 260.2117, 127.2126, 227523681.0]
79 ['Jul 2013', 881090.0, 1800392.0, 258.2748, 126.3966, 227563364.0]
80 ['Aug 2013', 888231.0, 1812492.0, 257.6442, 126.2613, 228847569.0]
81 ['Sep 2013', 888352.0, 1810643.0, 257.0538, 126.1178, 228354275.0]
82 ['Total', 869835.8333, 1784790.25, 263.3013, 128.3226, 2748346529.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Puerto Rico', '', '', '', '', '']
86 [' No data found.', '', '', '', '', '']
87 ['', '', '', '', '', '']
88 ['', '', '', '', '', '']
89 ['Virginia', '', '', '', '', '']
90 ['Oct 2012', 451865.0, 933462.0, 265.3775, 128.4624, 119914788.0]
91 ['Nov 2012', 453761.0, 937224.0, 264.8178, 128.2127, 120163981.0]
92 ['Dec 2012', 453213.0, 936337.0, 264.5189, 128.0345, 119883410.0]
93 ['Jan 2013', 455073.0, 938389.0, 262.0949, 127.1033, 119272322.0]
94 ['Feb 2013', 456394.0, 940712.0, 262.5836, 127.3945, 119841577.0]
95 ['Mar 2013', 456182.0, 939561.0, 263.7612, 128.0631, 120323097.0]
96 ['Apr 2013', 456540.0, 939775.0, 263.2089, 127.8661, 120165395.0]
97 ['May 2013', 457805.0, 942648.0, 262.9241, 127.6913, 120367985.0]
98 ['Jun 2013', 458390.0, 944377.0, 263.7324, 128.0127, 120892273.0]
99 ['Jul 2013', 458606.0, 944657.0, 262.7846, 127.575, 120514612.0]
100 ['Aug 2013', 460031.0, 947445.0, 262.1934, 127.3077, 120617083.0]
101 ['Sep 2013', 460003.0, 946599.0, 261.9239, 127.2828, 120485796.0]
102 ['Total', 456488.5833, 940932.1667, 263.3221, 127.7494, 1442442319.0]
103 ['', '', '', '', '', '']
104 ['', '', '', '', '', '']
105 ['Virgin Islands', '', '', '', '', '']
106 ['Oct 2012', 11576.0, 26804.0, 410.1003, 177.1124, 4747321.0]
107 ['Nov 2012', 11560.0, 26724.0, 405.9458, 175.6, 4692734.0]
108 ['Dec 2012', 11690.0, 26973.0, 401.5121, 174.0139, 4693677.0]
109 ['Jan 2013', 11712.0, 27002.0, 399.7312, 173.3817, 4681652.0]
110 ['Feb 2013', 11721.0, 27011.0, 396.9394, 172.2456, 4652527.0]
111 ['Mar 2013', 11805.0, 27182.0, 396.7218, 172.2942, 4683301.0]
112 ['Apr 2013', 11847.0, 27406.0, 394.3138, 170.453, 4671435.0]
113 ['May 2013', 12082.0, 27673.0, 395.9436, 172.8685, 4783791.0]
114 ['Jun 2013', 12115.0, 27635.0, 392.1541, 171.9177, 4750947.0]
115 ['Jul 2013', 12338.0, 28103.0, 393.239, 172.6429, 4851783.0]
116 ['Aug 2013', 12526.0, 28355.0, 390.0636, 172.3131, 4885937.0]
117 ['Sep 2013', 12516.0, 28365.0, 391.1579, 172.5976, 4895732.0]
118 ['Total', 11957.3333, 27436.0833, 397.1819, 173.1018, 56990837.0]
119 ['', '', '', '', '', '']
120 ['', '', '', '', '', '']
121 ['West Virginia', '', '', '', '', '']
122 ['Oct 2012', 165779.0, 349450.0, 260.2189, 123.4478, 43138821.0]
123 ['Nov 2012', 166829.0, 350217.0, 289.8477, 138.0716, 48355009.0]
124 ['Dec 2012', 165840.0, 349754.0, 254.5723, 120.7085, 42218268.0]
125 ['Jan 2013', 167986.0, 352352.0, 245.6683, 117.1239, 41268831.0]
126 ['Feb 2013', 166410.0, 349853.0, 249.1391, 118.5047, 41459237.0]
127 ['Mar 2013', 166724.0, 349481.0, 246.7068, 117.6944, 41131941.0]
128 ['Apr 2013', 166461.0, 349325.0, 246.6542, 117.5361, 41058306.0]
129 ['May 2013', 166442.0, 349169.0, 246.0765, 117.2998, 40957458.0]
130 ['Jun 2013', 166417.0, 348273.0, 245.9017, 117.5004, 40922227.0]
131 ['Jul 2013', 167018.0, 350303.0, 245.0103, 116.8164, 40921122.0]
132 ['Aug 2013', 168774.0, 355048.0, 245.635, 116.7639, 41456802.0]
133 ['Sep 2013', 169487.0, 355120.0, 245.4334, 117.1372, 41597763.0]
134 ['Total', 167013.9167, 350695.4167, 251.7184, 119.8775, 504485785.0]
135 ['', '', '', '', '', '']
136 ['', '', '', '', '', '']
137 ['MARO', '', '', '', '', '']
138 ['Oct 2012', 2444649.0, 4982600.0, 262.8829, 128.9801, 642656389.0]
139 ['Nov 2012', 2476894.0, 5044319.0, 281.672, 138.3084, 697671727.0]
140 ['Dec 2012', 2462059.0, 5032214.0, 275.2154, 134.6518, 677596618.0]
141 ['Jan 2013', 2462308.0, 5014261.0, 260.2062, 127.7771, 640707852.0]
142 ['Feb 2013', 2462326.0, 5011522.0, 259.6259, 127.5628, 639283637.0]
143 ['Mar 2013', 2475102.0, 5030293.0, 260.4202, 128.137, 644566473.0]
144 ['Apr 2013', 2479018.0, 5035570.0, 259.2253, 127.617, 642624305.0]
145 ['May 2013', 2491672.0, 5056072.0, 259.1228, 127.6978, 645649028.0]
146 ['Jun 2013', 2496692.0, 5064607.0, 258.6447, 127.5037, 645756125.0]
147 ['Jul 2013', 2506655.0, 5085050.0, 257.414, 126.8912, 645248048.0]
148 ['Aug 2013', 2524845.0, 5120094.0, 257.4266, 126.9434, 649962244.0]
149 ['Sep 2013', 2524535.0, 5113400.0, 256.8713, 126.8199, 648480628.0]
150 ['Total', 2483896.25, 5049166.8333, 262.3634, 129.0675, 7820203074.0]
151 ['', '', '', '', '', '']
152 ['', '', '', '', '', '']
153 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
154 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [470]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,89,105,121,137]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MARO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,87,102,118,134,150]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [471]:
########################
#                      #
# SERO                 #
#                      #
########################

sheet = book.sheet_by_name('SERO')

In [472]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2013', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Alabama', '', '', '', '', '']
6 ['Oct 2012', 419610.0, 919211.0, 284.0318, 129.6575, 119182564.0]
7 ['Nov 2012', 421139.0, 920764.0, 282.5053, 129.2123, 118974012.0]
8 ['Dec 2012', 421325.0, 919706.0, 282.4782, 129.4056, 119015145.0]
9 ['Jan 2013', 421040.0, 917452.0, 278.4077, 127.7678, 117220799.0]
10 ['Feb 2013', 420032.0, 913949.0, 278.4185, 127.9554, 116944693.0]
11 ['Mar 2013', 419669.0, 911626.0, 279.6112, 128.7196, 117344139.0]
12 ['Apr 2013', 419286.0, 909254.0, 278.0043, 128.1966, 116563301.0]
13 ['May 2013', 421921.0, 914462.0, 278.1799, 128.3486, 117369959.0]
14 ['Jun 2013', 422338.0, 914339.0, 278.5854, 128.6801, 117657213.0]
15 ['Jul 2013', 423752.0, 916543.0, 278.2793, 128.6589, 117921417.0]
16 ['Aug 2013', 422704.0, 913774.0, 280.3431, 129.6843, 118502151.0]
17 ['Sep 2013', 422810.0, 912789.0, 279.6918, 129.5551, 118256471.0]
18 ['Total', 421302.1667, 915322.4167, 279.8767, 128.8209, 1414951864.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Florida', '', '', '', '', '']
22 ['Oct 2012', 1919666.0, 3521938.0, 255.9432, 139.5043, 491325456.0]
23 ['Nov 2012', 1930259.0, 3541637.0, 254.0274, 138.4497, 490338685.0]
24 ['Dec 2012', 1942245.0, 3562318.0, 253.0694, 137.9784, 491522813.0]
25 ['Jan 2013', 1954717.0, 3573410.0, 251.8223, 137.7511, 492241319.0]
26 ['Feb 2013', 1943112.0, 3548832.0, 251.5004, 137.7054, 488693482.0]
27 ['Mar 2013', 1956662.0, 3566784.0, 250.5162, 137.4279, 490175488.0]
28 ['Apr 2013', 1949078.0, 3548465.0, 250.3937, 137.5346, 488036785.0]
29 ['May 2013', 1948578.0, 3556098.0, 252.1517, 138.1675, 491337245.0]
30 ['Jun 2013', 1952890.0, 3568672.0, 252.7931, 138.3364, 493677171.0]
31 ['Jul 2013', 1943579.0, 3558254.0, 254.8164, 139.1851, 495255899.0]
32 ['Aug 2013', 1945408.0, 3570722.0, 256.6759, 139.8427, 499339419.0]
33 ['Sep 2013', 1940625.0, 3560545.0, 254.6681, 138.8032, 494215195.0]
34 ['Total', 1943901.5833, 3556472.9167, 253.1918, 138.3899, 5906158957.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Georgia', '', '', '', '', '']
38 ['Oct 2012', 913017.0, 1963601.0, 294.1337, 136.7636, 268549046.0]
39 ['Nov 2012', 917567.0, 1972221.0, 293.3327, 136.4717, 269152441.0]
40 ['Dec 2012', 917124.0, 1969534.0, 292.7002, 136.2974, 268442412.0]
41 ['Jan 2013', 918712.0, 1969696.0, 290.3235, 135.4136, 266723704.0]
42 ['Feb 2013', 914884.0, 1960035.0, 291.0132, 135.836, 266243347.0]
43 ['Mar 2013', 915542.0, 1956754.0, 291.7518, 136.5072, 267110996.0]
44 ['Apr 2013', 909433.0, 1945001.0, 290.9097, 136.022, 264562889.0]
45 ['May 2013', 910852.0, 1950577.0, 291.1183, 135.9422, 265165648.0]
46 ['Jun 2013', 910610.0, 1950819.0, 292.6162, 136.5884, 266459225.0]
47 ['Jul 2013', 902066.0, 1933572.0, 292.2129, 136.3256, 263595306.0]
48 ['Aug 2013', 892309.0, 1918247.0, 294.0011, 136.7602, 262339832.0]
49 ['Sep 2013', 872640.0, 1888206.0, 298.4034, 137.908, 260398740.0]
50 ['Total', 907896.3333, 1948188.5833, 292.6861, 136.3978, 3188743586.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Kentucky', '', '', '', '', '']
54 ['Oct 2012', 415498.0, 867676.0, 266.5366, 127.6345, 110745421.0]
55 ['Nov 2012', 414599.0, 865540.0, 265.8141, 127.3266, 110206267.0]
56 ['Dec 2012', 416316.0, 867345.0, 265.4509, 127.4135, 110511468.0]
57 ['Jan 2013', 421513.0, 876465.0, 263.1376, 126.5492, 110915928.0]
58 ['Feb 2013', 417952.0, 869765.0, 264.2647, 126.9883, 110449955.0]
59 ['Mar 2013', 421036.0, 874094.0, 264.9315, 127.6129, 111545687.0]
60 ['Apr 2013', 421665.0, 873899.0, 263.3641, 127.0758, 111051435.0]
61 ['May 2013', 422704.0, 875644.0, 263.8039, 127.3474, 111510978.0]
62 ['Jun 2013', 424192.0, 878344.0, 264.5284, 127.7527, 112210840.0]
63 ['Jul 2013', 425222.0, 879771.0, 263.617, 127.4147, 112095756.0]
64 ['Aug 2013', 422092.0, 873683.0, 264.3174, 127.6965, 111566255.0]
65 ['Sep 2013', 419741.0, 867037.0, 262.5159, 127.0865, 110188674.0]
66 ['Total', 420210.8333, 872438.5833, 264.3512, 127.325, 1332998664.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Mississippi', '', '', '', '', '']
70 ['Oct 2012', 305001.0, 669930.0, 273.3092, 124.4303, 83359584.0]
71 ['Nov 2012', 305983.0, 672441.0, 273.0391, 124.2419, 83545327.0]
72 ['Dec 2012', 306062.0, 672339.0, 272.4333, 124.017, 83381480.0]
73 ['Jan 2013', 304724.0, 668862.0, 269.2973, 122.688, 82061342.0]
74 ['Feb 2013', 304347.0, 668255.0, 271.5234, 123.6614, 82637318.0]
75 ['Mar 2013', 303931.0, 666700.0, 270.6349, 123.3753, 82254342.0]
76 ['Apr 2013', 302355.0, 663151.0, 271.1039, 123.6063, 81969620.0]
77 ['May 2013', 303008.0, 664219.0, 271.1497, 123.695, 82160538.0]
78 ['Jun 2013', 304632.0, 667267.0, 271.2088, 123.8168, 82618880.0]
79 ['Jul 2013', 304952.0, 667575.0, 271.0252, 123.8058, 82649683.0]
80 ['Aug 2013', 307367.0, 671774.0, 270.8663, 123.9336, 83255357.0]
81 ['Sep 2013', 307697.0, 670979.0, 270.3455, 123.9748, 83184485.0]
82 ['Total', 305004.9167, 668624.3333, 271.3284, 123.7713, 993077956.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['North Carolina', '', '', '', '', '']
86 ['Oct 2012', 826367.0, 1756474.0, 257.19, 121.0, 212533367.0]
87 ['Nov 2012', 818480.0, 1738799.0, 257.1899, 121.0633, 210504787.0]
88 ['Dec 2012', 805902.0, 1726440.0, 259.19, 120.9899, 208881759.0]
89 ['Jan 2013', 787773.0, 1725504.0, 263.4995, 120.2998, 207577785.0]
90 ['Feb 2013', 799209.0, 1698745.0, 257.19, 121.0002, 205548543.0]
91 ['Mar 2013', 802078.0, 1704848.0, 257.1902, 121.0, 206286587.0]
92 ['Apr 2013', 775785.0, 1706588.0, 263.9688, 119.9956, 204783021.0]
93 ['May 2013', 773042.0, 1721681.0, 266.4777, 119.6496, 205998463.0]
94 ['Jun 2013', 777783.0, 1734913.0, 267.5103, 119.9282, 208064945.0]
95 ['Jul 2013', 763885.0, 1705966.0, 265.327, 118.8062, 202679346.0]
96 ['Aug 2013', 755859.0, 1682965.0, 273.5318, 122.8495, 206751469.0]
97 ['Sep 2013', 746604.0, 1541482.0, 283.4002, 137.2625, 211587722.0]
98 ['Total', 786063.9167, 1703700.4167, 264.1004, 121.8523, 2491197794.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['South Carolina', '', '', '', '', '']
102 ['Oct 2012', 414616.0, 875328.0, 280.5722, 132.8984, 116329712.0]
103 ['Nov 2012', 416399.0, 878636.0, 279.7509, 132.5782, 116488008.0]
104 ['Dec 2012', 417184.0, 879358.0, 278.3288, 132.0444, 116114315.0]
105 ['Jan 2013', 417702.0, 878022.0, 274.6348, 130.6522, 114715487.0]
106 ['Feb 2013', 417246.0, 876505.0, 274.8808, 130.8526, 114692929.0]
107 ['Mar 2013', 418182.0, 876632.0, 274.613, 130.9994, 114838230.0]
108 ['Apr 2013', 416540.0, 873591.0, 274.2582, 130.77, 114239531.0]
109 ['May 2013', 415819.0, 872313.0, 274.596, 130.896, 114182248.0]
110 ['Jun 2013', 415314.0, 871501.0, 275.9979, 131.5269, 114625803.0]
111 ['Jul 2013', 416274.0, 873803.0, 275.9634, 131.4672, 114876392.0]
112 ['Aug 2013', 417713.0, 877202.0, 276.588, 131.7079, 115534419.0]
113 ['Sep 2013', 417696.0, 877498.0, 275.6671, 131.2197, 115145044.0]
114 ['Total', 416723.75, 875865.75, 276.3186, 131.4682, 1381782118.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['Tennessee', '', '', '', '', '']
118 ['Oct 2012', 659339.0, 1342144.0, 270.5538, 132.9117, 178386645.0]
119 ['Nov 2012', 655176.0, 1332860.0, 270.1771, 132.8073, 177013583.0]
120 ['Dec 2012', 653209.0, 1326541.0, 268.0073, 131.9709, 175064760.0]
121 ['Jan 2013', 662209.0, 1342605.0, 266.3449, 131.3685, 176375964.0]
122 ['Feb 2013', 658461.0, 1335790.0, 267.3485, 131.7861, 176038567.0]
123 ['Mar 2013', 661291.0, 1339440.0, 266.9504, 131.7953, 176531900.0]
124 ['Apr 2013', 662972.0, 1343265.0, 269.3594, 132.9431, 178577747.0]
125 ['May 2013', 667327.0, 1351113.0, 266.5581, 131.6555, 177881450.0]
126 ['Jun 2013', 667103.0, 1350184.0, 265.9859, 131.4191, 177440002.0]
127 ['Jul 2013', 670666.0, 1356160.0, 266.4215, 131.7543, 178679863.0]
128 ['Aug 2013', 667987.0, 1351040.0, 268.5846, 132.7948, 179411044.0]
129 ['Sep 2013', 660712.0, 1333931.0, 266.8037, 132.1511, 176280428.0]
130 ['Total', 662204.3333, 1342089.4167, 267.7524, 132.1125, 2127681953.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['SERO', '', '', '', '', '']
134 ['Oct 2012', 5873114.0, 11916302.0, 269.0926, 132.626, 1580411795.0]
135 ['Nov 2012', 5879602.0, 11922898.0, 268.0833, 132.2013, 1576223110.0]
136 ['Dec 2012', 5879367.0, 11923581.0, 267.5346, 131.9179, 1572934152.0]
137 ['Jan 2013', 5888390.0, 11952016.0, 266.2582, 131.1772, 1567832328.0]
138 ['Feb 2013', 5875243.0, 11871876.0, 265.7335, 131.5082, 1561248834.0]
139 ['Mar 2013', 5898391.0, 11896878.0, 265.5109, 131.6385, 1566087369.0]
140 ['Apr 2013', 5857114.0, 11863214.0, 266.306, 131.4808, 1559784329.0]
141 ['May 2013', 5863251.0, 11906107.0, 267.0202, 131.4961, 1565606529.0]
142 ['Jun 2013', 5874862.0, 11936039.0, 267.7091, 131.7652, 1572754079.0]
143 ['Jul 2013', 5850396.0, 11891644.0, 267.9739, 131.8366, 1567753662.0]
144 ['Aug 2013', 5831439.0, 11859407.0, 270.3792, 132.9493, 1576699946.0]
145 ['Sep 2013', 5788525.0, 11652467.0, 271.0979, 134.6716, 1569256759.0]
146 ['Total', 5863307.8333, 11882702.4167, 267.7185, 132.1009, 18836592892.0]
147 ['', '', '', '', '', '']
148 ['', '', '', '', '', '']
149 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
150 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [473]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117, 133]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SERO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114, 130,146]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [474]:
########################
#                      #
# MWRO                 #
#                      #
########################

sheet = book.sheet_by_name('MWRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2013', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Illinois', '', '', '', '', '']
6 ['Oct 2012', 993695.0, 2004436.0, 282.2851, 139.9422, 280505272.0]
7 ['Nov 2012', 1000965.0, 2012520.0, 278.3672, 138.4512, 278635828.0]
8 ['Dec 2012', 1019975.0, 2051286.0, 280.3318, 139.3913, 285931412.0]
9 ['Jan 2013', 1012243.0, 2027281.0, 278.7157, 139.1657, 282127996.0]
10 ['Feb 2013', 1011302.0, 2023635.0, 278.2228, 139.0405, 281367273.0]
11 ['Mar 2013', 1023322.0, 2048658.0, 279.823, 139.7739, 286349012.0]
12 ['Apr 2013', 1016540.0, 2029103.0, 275.8348, 138.1877, 280397136.0]
13 ['May 2013', 1025575.0, 2048898.0, 276.5137, 138.4088, 283585577.0]
14 ['Jun 2013', 1053161.0, 2149813.0, 287.0714, 140.632, 302332434.0]
15 ['Jul 2013', 1019234.0, 2036411.0, 248.4078, 124.3294, 253185660.0]
16 ['Aug 2013', 1020785.0, 2037738.0, 279.4599, 139.9927, 285268502.0]
17 ['Sep 2013', 1009478.0, 2010860.0, 275.7956, 138.453, 278409555.0]
18 ['Total', 1017189.5833, 2040053.25, 276.7507, 137.9905, 3378095657.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Indiana', '', '', '', '', '']
22 ['Oct 2012', 412820.0, 925574.0, 296.8342, 132.3925, 122539077.0]
23 ['Nov 2012', 411830.0, 922564.0, 294.68, 131.5443, 121358051.0]
24 ['Dec 2012', 412719.0, 923750.0, 294.5067, 131.5816, 121548498.0]
25 ['Jan 2013', 415066.0, 927030.0, 292.5014, 130.9638, 121407379.0]
26 ['Feb 2013', 414279.0, 925554.0, 292.7668, 131.0427, 121287127.0]
27 ['Mar 2013', 415731.0, 926959.0, 293.0216, 131.417, 121818149.0]
28 ['Apr 2013', 415325.0, 924463.0, 292.9708, 131.6203, 121678106.0]
29 ['May 2013', 416540.0, 926574.0, 292.2309, 131.372, 121725878.0]
30 ['Jun 2013', 416138.0, 924122.0, 291.1709, 131.1161, 121167262.0]
31 ['Jul 2013', 416777.0, 925265.0, 294.792, 132.7863, 122862540.0]
32 ['Aug 2013', 419988.0, 931675.0, 290.7825, 131.0813, 122125173.0]
33 ['Sep 2013', 419005.0, 928601.0, 290.2565, 130.9701, 121618936.0]
34 ['Total', 415518.1667, 926010.9167, 293.035, 131.4902, 1461136176.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Michigan', '', '', '', '', '']
38 ['Oct 2012', 920122.0, 1807567.0, 268.3864, 136.6191, 246948258.0]
39 ['Nov 2012', 915237.0, 1796122.0, 267.4286, 136.2717, 244760568.0]
40 ['Dec 2012', 912446.0, 1790024.0, 268.6512, 136.9421, 245129707.0]
41 ['Jan 2013', 911303.0, 1784755.0, 266.4172, 136.0337, 242786829.0]
42 ['Feb 2013', 909552.0, 1779085.0, 266.9432, 136.4739, 242798699.0]
43 ['Mar 2013', 907868.0, 1773290.0, 267.3207, 136.8597, 242691869.0]
44 ['Apr 2013', 909848.0, 1773173.0, 265.4468, 136.2057, 241516222.0]
45 ['May 2013', 909168.0, 1768141.0, 266.6457, 137.1077, 242425762.0]
46 ['Jun 2013', 907432.0, 1764866.0, 267.3386, 137.4561, 242591616.0]
47 ['Jul 2013', 905617.0, 1760433.0, 266.1478, 136.914, 241027995.0]
48 ['Aug 2013', 905308.0, 1757800.0, 265.4889, 136.733, 240349184.0]
49 ['Sep 2013', 903267.0, 1752492.0, 264.1494, 136.1475, 238597401.0]
50 ['Total', 909764.0, 1775645.6667, 266.7014, 136.6463, 2911624110.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Minnesota', '', '', '', '', '']
54 ['Oct 2012', 271500.0, 547774.0, 236.4914, 117.2151, 64207411.0]
55 ['Nov 2012', 270314.0, 545690.0, 235.316, 116.5666, 63609213.0]
56 ['Dec 2012', 270457.0, 545613.0, 234.079, 116.0315, 63308309.0]
57 ['Jan 2013', 273480.0, 551209.0, 232.9225, 115.5635, 63699651.0]
58 ['Feb 2013', 272813.0, 550644.0, 233.6725, 115.7715, 63748897.0]
59 ['Mar 2013', 275192.0, 554321.0, 234.243, 116.2897, 64461808.0]
60 ['Apr 2013', 275671.0, 555092.0, 234.4784, 116.4472, 64638908.0]
61 ['May 2013', 276333.0, 556621.0, 233.903, 116.1205, 64635104.0]
62 ['Jun 2013', 275819.0, 555029.0, 236.1038, 117.3307, 65121915.0]
63 ['Jul 2013', 277275.0, 560132.0, 237.587, 117.6097, 65876948.0]
64 ['Aug 2013', 276308.0, 557037.0, 233.021, 115.5858, 64385568.0]
65 ['Sep 2013', 275673.0, 555978.0, 230.9576, 114.5167, 63668780.0]
66 ['Total', 274236.25, 552928.3333, 234.3972, 116.2541, 771362512.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Ohio', '', '', '', '', '']
70 ['Oct 2012', 878574.0, 1804887.0, 280.7949, 136.684, 246699135.0]
71 ['Nov 2012', 883094.0, 1816409.0, 283.4303, 137.7969, 250295575.0]
72 ['Dec 2012', 890184.0, 1832777.0, 277.8543, 134.9545, 247341466.0]
73 ['Jan 2013', 896188.0, 1845325.0, 271.3109, 131.763, 243145548.0]
74 ['Feb 2013', 892714.0, 1837229.0, 271.0635, 131.7104, 241982211.0]
75 ['Mar 2013', 901062.0, 1853963.0, 272.0659, 132.2293, 245148207.0]
76 ['Apr 2013', 898796.0, 1844692.0, 271.5946, 132.33, 244108149.0]
77 ['May 2013', 893965.0, 1830161.0, 271.6551, 132.6933, 242850135.0]
78 ['Jun 2013', 887854.0, 1815695.0, 271.6856, 132.8511, 241217157.0]
79 ['Jul 2013', 887470.0, 1813874.0, 272.9801, 133.5603, 242261622.0]
80 ['Aug 2013', 882497.0, 1802036.0, 271.9027, 133.1568, 239953358.0]
81 ['Sep 2013', 880728.0, 1799050.0, 270.4106, 132.3799, 238158144.0]
82 ['Total', 889427.1667, 1824674.8333, 273.8805, 133.5014, 2923160707.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Wisconsin', '', '', '', '', '']
86 ['Oct 2012', 410077.0, 849574.0, 241.5264, 116.5813, 99044424.0]
87 ['Nov 2012', 410770.0, 848832.0, 239.7865, 116.0384, 98497104.0]
88 ['Dec 2012', 410160.0, 846950.0, 237.5069, 115.0196, 97415814.0]
89 ['Jan 2013', 414343.0, 854697.0, 247.1188, 119.7991, 102391938.0]
90 ['Feb 2013', 416116.0, 857811.0, 238.8652, 115.8713, 99395637.0]
91 ['Mar 2013', 417163.0, 858342.0, 239.7132, 116.5031, 99999462.0]
92 ['Apr 2013', 418472.0, 860186.0, 240.2671, 116.8876, 100545037.0]
93 ['May 2013', 419948.0, 861950.0, 240.4021, 117.1255, 100956366.0]
94 ['Jun 2013', 420649.0, 861644.0, 237.7915, 116.0882, 100026738.0]
95 ['Jul 2013', 420407.0, 859769.0, 238.4077, 116.5758, 100228262.0]
96 ['Aug 2013', 421786.0, 861179.0, 238.0926, 116.6124, 100424109.0]
97 ['Sep 2013', 422026.0, 859820.0, 235.4773, 115.5795, 99377531.0]
98 ['Total', 416826.4167, 856729.5, 239.5686, 116.5578, 1198302422.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['MWRO', '', '', '', '', '']
102 ['Oct 2012', 3886788.0, 7939812.0, 272.7042, 133.4973, 1059943577.0]
103 ['Nov 2012', 3892210.0, 7942137.0, 271.6082, 133.1073, 1057156339.0]
104 ['Dec 2012', 3915941.0, 7990400.0, 270.8609, 132.7437, 1060675206.0]
105 ['Jan 2013', 3922623.0, 7990297.0, 269.0953, 132.1051, 1055559341.0]
106 ['Feb 2013', 3916776.0, 7973958.0, 268.2257, 131.7514, 1050579844.0]
107 ['Mar 2013', 3940338.0, 8015533.0, 269.1314, 132.3017, 1060468507.0]
108 ['Apr 2013', 3934652.0, 7986709.0, 267.5925, 131.8295, 1052883558.0]
109 ['May 2013', 3941529.0, 7992345.0, 267.9617, 132.1488, 1056178822.0]
110 ['Jun 2013', 3961053.0, 8071169.0, 270.7505, 132.8751, 1072457122.0]
111 ['Jul 2013', 3926780.0, 7955884.0, 261.1409, 128.8911, 1025443027.0]
112 ['Aug 2013', 3926672.0, 7947465.0, 268.0402, 132.4329, 1052505894.0]
113 ['Sep 2013', 3910177.0, 7906801.0, 265.9292, 131.5109, 1039830347.0]
114 ['Total', 3922961.5833, 7976042.5, 268.5828, 132.1006, 12643681584.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
118 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [475]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MWRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [476]:
########################
#                      #
# SWRO                 #
#                      #
########################

sheet = book.sheet_by_name('SWRO ')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2013', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Arkansas', '', '', '', '', '']
6 ['Oct 2012', 224371.0, 508583.0, 276.4207, 121.9482, 62020788.0]
7 ['Nov 2012', 225280.0, 509224.0, 274.1095, 121.2657, 61751399.0]
8 ['Dec 2012', 225779.0, 509349.0, 272.791, 120.92, 61590471.0]
9 ['Jan 2013', 225728.0, 508572.0, 271.0659, 120.3117, 61187172.0]
10 ['Feb 2013', 223617.0, 503375.0, 271.3434, 120.5404, 60677004.0]
11 ['Mar 2013', 224119.0, 502491.0, 270.7365, 120.7528, 60677184.0]
12 ['Apr 2013', 223392.0, 500689.0, 269.9418, 120.4397, 60302842.0]
13 ['May 2013', 222652.0, 499603.0, 270.5551, 120.575, 60239625.0]
14 ['Jun 2013', 223986.0, 502070.0, 270.6046, 120.7235, 60611646.0]
15 ['Jul 2013', 224172.0, 502723.0, 271.2479, 120.9536, 60806178.0]
16 ['Aug 2013', 225080.0, 504844.0, 271.2711, 120.9437, 61057692.0]
17 ['Sep 2013', 225270.0, 503928.0, 270.4483, 120.898, 60923895.0]
18 ['Total', 224453.8333, 504620.9167, 271.7136, 120.8574, 731845896.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Louisiana', '', '', '', '', '']
22 ['Oct 2012', 426961.0, 948475.0, 295.2055, 132.8883, 126041252.0]
23 ['Nov 2012', 437341.0, 969609.0, 293.0775, 132.1922, 128174792.0]
24 ['Dec 2012', 446404.0, 986234.0, 293.3461, 132.7787, 130950890.0]
25 ['Jan 2013', 438921.0, 967731.0, 287.6504, 130.4658, 126255787.0]
26 ['Feb 2013', 435630.0, 961253.0, 289.0496, 130.9943, 125918684.0]
27 ['Mar 2013', 431556.0, 951535.0, 289.8394, 131.4528, 125081929.0]
28 ['Apr 2013', 416539.0, 919032.0, 286.5329, 129.8672, 119352123.0]
29 ['May 2013', 413505.0, 914196.0, 286.8519, 129.7475, 118614682.0]
30 ['Jun 2013', 415174.0, 917053.0, 289.383, 131.0113, 120144312.0]
31 ['Jul 2013', 411767.0, 908502.0, 287.7885, 130.4365, 118501811.0]
32 ['Aug 2013', 418405.0, 922845.0, 290.1017, 131.5281, 121380015.0]
33 ['Sep 2013', 415572.0, 914731.0, 287.3434, 130.5431, 119411856.0]
34 ['Total', 425647.9167, 940099.6667, 289.7207, 131.1765, 1479828133.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['New Mexico', '', '', '', '', '']
38 ['Oct 2012', 197005.0, 442237.0, 287.9778, 128.2866, 56733068.0]
39 ['Nov 2012', 196917.0, 442217.0, 287.6982, 128.1106, 56652671.0]
40 ['Dec 2012', 197629.0, 442631.0, 287.3912, 128.3164, 56796828.0]
41 ['Jan 2013', 198314.0, 442753.0, 284.6826, 127.5125, 56456541.0]
42 ['Feb 2013', 197323.0, 440872.0, 285.6855, 127.8655, 56372327.0]
43 ['Mar 2013', 198533.0, 442302.0, 285.9774, 128.3647, 56775944.0]
44 ['Apr 2013', 198283.0, 441550.0, 283.8569, 127.4691, 56283996.0]
45 ['May 2013', 198814.0, 442570.0, 284.6269, 127.8619, 56587820.0]
46 ['Jun 2013', 199316.0, 443784.0, 285.5728, 128.2589, 56919228.0]
47 ['Jul 2013', 199619.0, 443453.0, 283.6327, 127.6764, 56618469.0]
48 ['Aug 2013', 193213.0, 431094.0, 294.2217, 131.8679, 56847460.0]
49 ['Sep 2013', 193342.0, 428877.0, 291.9048, 131.5936, 56437459.0]
50 ['Total', 197359.0, 440361.6667, 286.906, 128.584, 679481811.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Oklahoma', '', '', '', '', '']
54 ['Oct 2012', 285851.0, 621760.0, 279.7942, 128.6339, 79979444.0]
55 ['Nov 2012', 286157.0, 621286.0, 279.6258, 128.7924, 80016892.0]
56 ['Dec 2012', 285517.0, 619440.0, 280.0268, 129.0721, 79952406.0]
57 ['Jan 2013', 285960.0, 618863.0, 275.39, 127.2503, 78750533.0]
58 ['Feb 2013', 284803.0, 615154.0, 277.0206, 128.2546, 78896311.0]
59 ['Mar 2013', 284728.0, 615158.0, 275.3102, 127.4283, 78388529.0]
60 ['Apr 2013', 284894.0, 614471.0, 275.498, 127.7322, 78487737.0]
61 ['May 2013', 286552.0, 618624.0, 277.1931, 128.3982, 79430226.0]
62 ['Jun 2013', 288830.0, 622684.0, 284.6929, 132.0539, 82227857.0]
63 ['Jul 2013', 288953.0, 622578.0, 277.185, 128.6481, 80093451.0]
64 ['Aug 2013', 293098.0, 631815.0, 277.8277, 128.8838, 81430731.0]
65 ['Sep 2013', 293435.0, 640138.0, 276.1436, 126.5824, 81030208.0]
66 ['Total', 287398.1667, 621830.9167, 277.978, 128.476, 958684325.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Texas', '', '', '', '', '']
70 ['Oct 2012', 1707329.0, 4123827.0, 299.3244, 123.925, 511045263.0]
71 ['Nov 2012', 1699968.0, 4111672.0, 296.4628, 122.5724, 503977303.0]
72 ['Dec 2012', 1696300.0, 4102800.0, 294.8565, 121.9082, 500165116.0]
73 ['Jan 2013', 1686477.0, 4072529.0, 293.6588, 121.6072, 495248810.0]
74 ['Feb 2013', 1664797.0, 4024348.0, 294.8392, 121.9694, 490847431.0]
75 ['Mar 2013', 1668186.0, 4026519.0, 294.9606, 122.2021, 492049116.0]
76 ['Apr 2013', 1653110.0, 3992627.0, 294.5132, 121.9404, 486862675.0]
77 ['May 2013', 1658553.0, 4007194.0, 295.1753, 122.1713, 489563908.0]
78 ['Jun 2013', 1659579.0, 4007128.0, 294.7464, 122.0712, 489154853.0]
79 ['Jul 2013', 1664112.0, 4016999.0, 294.9465, 122.1867, 490824042.0]
80 ['Aug 2013', 1673965.0, 4035868.0, 294.1776, 122.0166, 492442959.0]
81 ['Sep 2013', 1659825.0, 3981182.0, 296.5736, 123.6468, 492260355.0]
82 ['Total', 1674350.0833, 4041891.0833, 295.3605, 122.3528, 5934441831.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['SWRO', '', '', '', '', '']
86 ['Oct 2012', 2841517.0, 6644882.0, 294.1456, 125.784, 835819815.0]
87 ['Nov 2012', 2845663.0, 6654008.0, 291.8733, 124.823, 830573057.0]
88 ['Dec 2012', 2851629.0, 6660454.0, 290.8708, 124.5344, 829455711.0]
89 ['Jan 2013', 2835400.0, 6610448.0, 288.4598, 123.7282, 817898843.0]
90 ['Feb 2013', 2806170.0, 6545002.0, 289.616, 124.1729, 812711757.0]
91 ['Mar 2013', 2807122.0, 6538005.0, 289.6107, 124.3457, 812972702.0]
92 ['Apr 2013', 2776218.0, 6468369.0, 288.6262, 123.8781, 801289373.0]
93 ['May 2013', 2780076.0, 6482187.0, 289.3577, 124.0995, 804436261.0]
94 ['Jun 2013', 2786885.0, 6492719.0, 290.309, 124.61, 809057896.0]
95 ['Jul 2013', 2788623.0, 6494255.0, 289.3342, 124.2396, 806843951.0]
96 ['Aug 2013', 2803761.0, 6526466.0, 290.0243, 124.5941, 813158857.0]
97 ['Sep 2013', 2787444.0, 6468856.0, 290.6117, 125.2252, 810063773.0]
98 ['Total', 2809209.0, 6548804.25, 290.2443, 124.5047, 9784281996.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
102 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [477]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SWRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [478]:
########################
#                      #
# MPRO                 #
#                      #
########################
sheet = book.sheet_by_name('MPRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2013', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Colorado', '', '', '', '', '']
6 ['Oct 2012', 228794.0, 505366.0, 300.1422, 135.8832, 68670740.0]
7 ['Nov 2012', 228734.0, 504741.0, 298.0981, 135.0894, 68185180.0]
8 ['Dec 2012', 231000.0, 508679.0, 297.7533, 135.2149, 68781002.0]
9 ['Jan 2013', 232886.0, 511802.0, 295.6748, 134.5413, 68858527.0]
10 ['Feb 2013', 230834.0, 507192.0, 294.37, 133.9741, 67950596.0]
11 ['Mar 2013', 234397.0, 513483.0, 297.6935, 135.8925, 69778465.0]
12 ['Apr 2013', 233101.0, 510696.0, 296.6144, 135.386, 69141106.0]
13 ['May 2013', 232963.0, 510441.0, 296.6135, 135.3731, 69099970.0]
14 ['Jun 2013', 231671.0, 507135.0, 296.894, 135.628, 68781726.0]
15 ['Jul 2013', 231646.0, 506228.0, 295.7344, 135.3258, 68505697.0]
16 ['Aug 2013', 231464.0, 506169.0, 294.6778, 134.752, 68207292.0]
17 ['Sep 2013', 230362.0, 503275.0, 293.3179, 134.2592, 67569306.0]
18 ['Total', 231487.6667, 507933.9167, 296.4627, 135.111, 823529607.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Iowa', '', '', '', '', '']
22 ['Oct 2012', 197323.0, 419315.0, 255.7066, 120.3315, 50456787.0]
23 ['Nov 2012', 197154.0, 418440.0, 246.2521, 116.0252, 48549590.0]
24 ['Dec 2012', 197540.0, 417418.0, 245.6341, 116.2446, 48522568.0]
25 ['Jan 2013', 198028.0, 418533.0, 243.3328, 115.1324, 48186714.0]
26 ['Feb 2013', 197947.0, 419296.0, 245.5697, 115.9319, 48609789.0]
27 ['Mar 2013', 198796.0, 420704.0, 245.0406, 115.7894, 48713084.0]
28 ['Apr 2013', 198555.0, 420360.0, 245.2765, 115.8552, 48700876.0]
29 ['May 2013', 198843.0, 420914.0, 245.621, 116.0333, 48840024.0]
30 ['Jun 2013', 199538.0, 422004.0, 245.8835, 116.2622, 49063107.0]
31 ['Jul 2013', 198846.0, 421082.0, 245.8659, 116.1043, 48889450.0]
32 ['Aug 2013', 199849.0, 423428.0, 245.6523, 115.9426, 49093360.0]
33 ['Sep 2013', 199584.0, 422639.0, 245.0937, 115.7413, 48916774.0]
34 ['Total', 198500.25, 420344.4167, 246.239, 116.282, 586542123.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Kansas', '', '', '', '', '']
38 ['Oct 2012', 148943.0, 316506.0, 267.1689, 125.7257, 39792932.0]
39 ['Nov 2012', 148286.0, 314932.0, 267.2953, 125.8562, 39636149.0]
40 ['Dec 2012', 148472.0, 315394.0, 267.0676, 125.7223, 39652058.0]
41 ['Jan 2013', 148947.0, 315953.0, 262.7113, 123.8477, 39130060.0]
42 ['Feb 2013', 147869.0, 313906.0, 265.6521, 125.1384, 39281708.0]
43 ['Mar 2013', 148681.0, 315220.0, 263.3664, 124.223, 39157574.0]
44 ['Apr 2013', 149226.0, 316523.0, 263.814, 124.3761, 39367908.0]
45 ['May 2013', 149766.0, 317892.0, 263.5274, 124.1536, 39467452.0]
46 ['Jun 2013', 150477.0, 319827.0, 263.588, 124.0168, 39663924.0]
47 ['Jul 2013', 150182.0, 319275.0, 264.4159, 124.3771, 39710512.0]
48 ['Aug 2013', 150633.0, 320638.0, 265.0542, 124.5202, 39925902.0]
49 ['Sep 2013', 149314.0, 317725.0, 264.3399, 124.2258, 39469650.0]
50 ['Total', 149233.0, 316982.5833, 264.8296, 124.6798, 474255829.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Missouri', '', '', '', '', '']
54 ['Oct 2012', 442404.0, 942918.0, 274.1436, 128.6244, 121282236.0]
55 ['Nov 2012', 440484.0, 938507.0, 270.1178, 126.7786, 118982558.0]
56 ['Dec 2012', 441535.0, 940064.0, 273.1589, 128.2989, 120609195.0]
57 ['Jan 2013', 442594.0, 941247.0, 272.8144, 128.2831, 120746038.0]
58 ['Feb 2013', 438495.0, 932446.0, 271.28, 127.573, 118954914.0]
59 ['Mar 2013', 441497.0, 936963.0, 270.9205, 127.6577, 119610571.0]
60 ['Apr 2013', 438782.0, 931761.0, 269.8602, 127.0817, 118409794.0]
61 ['May 2013', 437079.0, 927925.0, 275.3401, 129.693, 120345394.0]
62 ['Jun 2013', 436873.0, 927927.0, 277.6212, 130.7055, 121285207.0]
63 ['Jul 2013', 432365.0, 918776.0, 272.8557, 128.4026, 117973243.0]
64 ['Aug 2013', 430870.0, 915469.0, 269.5631, 126.8712, 116146673.0]
65 ['Sep 2013', 426340.0, 905311.0, 268.6507, 126.5162, 114536529.0]
66 ['Total', 437443.1667, 929942.8333, 272.2034, 128.0439, 1428882352.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Montana', '', '', '', '', '']
70 ['Oct 2012', 58597.0, 123967.0, 267.5172, 126.4506, 15675705.0]
71 ['Nov 2012', 59312.0, 128124.0, 257.5682, 119.2352, 15276885.0]
72 ['Dec 2012', 59587.0, 131681.0, 264.3039, 119.6002, 15749075.0]
73 ['Jan 2013', 59119.0, 129150.0, 272.073, 124.5427, 16084685.0]
74 ['Feb 2013', 59207.0, 129555.0, 272.578, 124.5689, 16138525.0]
75 ['Mar 2013', 59178.0, 128481.0, 275.1196, 126.7193, 16281028.0]
76 ['Apr 2013', 59839.0, 130952.0, 272.6569, 124.5916, 16315515.0]
77 ['May 2013', 59691.0, 129797.0, 272.2578, 125.2058, 16251343.0]
78 ['Jun 2013', 59506.0, 129067.0, 272.4932, 125.6323, 16214980.0]
79 ['Jul 2013', 59578.0, 129492.0, 271.27, 124.8087, 16161724.0]
80 ['Aug 2013', 59725.0, 126095.0, 270.1993, 127.9801, 16137653.0]
81 ['Sep 2013', 59435.0, 126010.0, 268.7401, 126.7563, 15972567.0]
82 ['Total', 59397.8333, 128530.9167, 269.7344, 124.652, 192259685.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Nebraska', '', '', '', '', '']
86 ['Oct 2012', 76903.0, 174264.0, 277.1942, 122.3263, 21317067.0]
87 ['Nov 2012', 77156.0, 175402.0, 281.0032, 123.608, 21681082.0]
88 ['Dec 2012', 78269.0, 177523.0, 279.3487, 123.1634, 21864344.0]
89 ['Jan 2013', 79587.0, 180193.0, 277.704, 122.6553, 22101632.0]
90 ['Feb 2013', 79694.0, 180460.0, 278.1905, 122.8533, 22170114.0]
91 ['Mar 2013', 80147.0, 180774.0, 278.7999, 123.6072, 22344973.0]
92 ['Apr 2013', 79621.0, 179816.0, 275.8056, 122.1244, 21959914.0]
93 ['May 2013', 80434.0, 181796.0, 278.2121, 123.0924, 22377710.0]
94 ['Jun 2013', 80560.0, 182149.0, 279.4221, 123.5815, 22510245.0]
95 ['Jul 2013', 80672.0, 182487.0, 276.1779, 122.0899, 22279825.0]
96 ['Aug 2013', 80119.0, 181484.0, 277.7108, 122.5999, 22249915.0]
97 ['Sep 2013', 79382.0, 180180.0, 274.3631, 120.8763, 21779493.0]
98 ['Total', 79378.6667, 179710.6667, 277.8206, 122.7141, 264636314.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['North Dakota', '', '', '', '', '']
102 ['Oct 2012', 27085.0, 57911.0, 272.5619, 127.4773, 7382339.0]
103 ['Nov 2012', 26948.0, 57565.0, 270.9654, 126.8475, 7301975.0]
104 ['Dec 2012', 26884.0, 57610.0, 272.48, 127.1542, 7325352.0]
105 ['Jan 2013', 26953.0, 57658.0, 267.819, 125.1955, 7218525.0]
106 ['Feb 2013', 26734.0, 57449.0, 270.1499, 125.7148, 7222187.0]
107 ['Mar 2013', 26423.0, 56918.0, 271.0685, 125.8379, 7162444.0]
108 ['Apr 2013', 26283.0, 56676.0, 271.4253, 125.8711, 7133872.0]
109 ['May 2013', 25993.0, 56136.0, 272.7734, 126.304, 7090200.0]
110 ['Jun 2013', 25783.0, 55721.0, 272.2666, 125.9821, 7019851.0]
111 ['Jul 2013', 25474.0, 55125.0, 272.5689, 125.9578, 6943421.0]
112 ['Aug 2013', 25404.0, 55005.0, 271.6278, 125.451, 6900432.0]
113 ['Sep 2013', 25275.0, 54500.0, 270.2144, 125.315, 6829668.0]
114 ['Total', 26269.9167, 56522.8333, 271.3188, 126.0999, 85530266.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['South Dakota', '', '', '', '', '']
118 ['Oct 2012', 45084.0, 103511.0, 304.6537, 132.6913, 13735008.0]
119 ['Nov 2012', 45296.0, 103821.0, 302.5419, 131.9958, 13703938.0]
120 ['Dec 2012', 45322.0, 103832.0, 303.4945, 132.4734, 13754978.0]
121 ['Jan 2013', 45741.0, 104806.0, 303.8253, 132.6, 13897273.0]
122 ['Feb 2013', 45721.0, 104629.0, 301.4875, 131.7446, 13784309.0]
123 ['Mar 2013', 45571.0, 104407.0, 304.3767, 132.8527, 13870752.0]
124 ['Apr 2013', 45465.0, 104175.0, 302.5104, 132.0243, 13753635.0]
125 ['May 2013', 45310.0, 104135.0, 304.7128, 132.5831, 13806538.0]
126 ['Jun 2013', 45301.0, 104445.0, 304.4049, 132.0297, 13789845.0]
127 ['Jul 2013', 45040.0, 104004.0, 305.1837, 132.1629, 13745473.0]
128 ['Aug 2013', 45123.0, 104099.0, 304.2649, 131.8874, 13729346.0]
129 ['Sep 2013', 44770.0, 102755.0, 300.8508, 131.0796, 13469089.0]
130 ['Total', 45312.0, 104051.5833, 303.5255, 132.1782, 165040184.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['Utah', '', '', '', '', '']
134 ['Oct 2012', 105722.0, 257744.0, 310.2497, 127.2589, 32800216.0]
135 ['Nov 2012', 106009.0, 258722.0, 309.9944, 127.0174, 32862197.0]
136 ['Dec 2012', 105586.0, 258188.0, 308.4928, 126.1582, 32572522.0]
137 ['Jan 2013', 106490.0, 261426.0, 307.2886, 125.1718, 32723167.0]
138 ['Feb 2013', 104300.0, 258560.0, 310.8063, 125.3755, 32417098.0]
139 ['Mar 2013', 103263.0, 257781.0, 314.6031, 126.025, 32486861.0]
140 ['Apr 2013', 100880.0, 252378.0, 312.755, 125.0137, 31550720.0]
141 ['May 2013', 99006.0, 248821.0, 313.9838, 124.9343, 31086283.0]
142 ['Jun 2013', 96976.0, 244726.0, 314.0266, 124.4373, 30453047.0]
143 ['Jul 2013', 95404.0, 241380.0, 313.0927, 123.748, 29870300.0]
144 ['Aug 2013', 95194.0, 241892.0, 313.3954, 123.3334, 29833361.0]
145 ['Sep 2013', 93497.0, 237894.0, 312.8169, 122.9432, 29247442.0]
146 ['Total', 101027.25, 251626.0, 311.7172, 125.1537, 377903214.0]
147 ['', '', '', '', '', '']
148 ['', '', '', '', '', '']
149 ['Wyoming', '', '', '', '', '']
150 ['Oct 2012', 16367.0, 37715.0, 290.87, 126.2275, 4760669.0]
151 ['Nov 2012', 16803.0, 38914.0, 291.2094, 125.7437, 4893191.0]
152 ['Dec 2012', 16664.0, 38417.0, 289.3741, 125.5207, 4822130.0]
153 ['Jan 2013', 16404.0, 38254.0, 289.859, 124.2967, 4754847.0]
154 ['Feb 2013', 15973.0, 37488.0, 290.8865, 123.9418, 4646330.0]
155 ['Mar 2013', 16288.0, 38180.0, 294.7244, 125.7326, 4800471.0]
156 ['Apr 2013', 16277.0, 38502.0, 295.5576, 124.9491, 4810791.0]
157 ['May 2013', 16249.0, 38492.0, 296.0652, 124.9809, 4810763.0]
158 ['Jun 2013', 16062.0, 37965.0, 295.3138, 124.9395, 4743330.0]
159 ['Jul 2013', 15824.0, 37553.0, 293.3586, 123.6148, 4642107.0]
160 ['Aug 2013', 15716.0, 37200.0, 294.7581, 124.5274, 4632419.0]
161 ['Sep 2013', 15905.0, 37874.0, 293.1787, 123.119, 4663008.0]
162 ['Total', 16211.0, 38046.1667, 292.9084, 124.8046, 56980056.0]
163 ['', '', '', '', '', '']
164 ['', '', '', '', '', '']
165 ['MPRO', '', '', '', '', '']
166 ['Oct 2012', 1347222.0, 2939217.0, 278.9991, 127.8823, 375873699.0]
167 ['Nov 2012', 1346182.0, 2939168.0, 275.6483, 126.2509, 371072745.0]
168 ['Dec 2012', 1350859.0, 2948806.0, 276.6042, 126.7134, 373653224.0]
169 ['Jan 2013', 1356749.0, 2959022.0, 275.4389, 126.2922, 373701468.0]
170 ['Feb 2013', 1346774.0, 2940981.0, 275.6035, 126.2081, 371175570.0]
171 ['Mar 2013', 1354241.0, 2952911.0, 276.3217, 126.7245, 374206223.0]
172 ['Apr 2013', 1348029.0, 2941839.0, 275.3236, 126.1606, 371144131.0]
173 ['May 2013', 1345334.0, 2936349.0, 277.3852, 127.0883, 373175677.0]
174 ['Jun 2013', 1342747.0, 2930966.0, 278.1799, 127.441, 373525262.0]
175 ['Jul 2013', 1335031.0, 2915402.0, 276.1897, 126.4737, 368721752.0]
176 ['Aug 2013', 1334097.0, 2911479.0, 274.9848, 126.0034, 366856353.0]
177 ['Sep 2013', 1323864.0, 2888163.0, 273.7846, 125.4962, 362453526.0]
178 ['Total', 1344260.75, 2933691.9167, 276.2088, 126.5629, 4455559630.0]
179 ['', '', '', '', '', '']
180 ['', '', '', '', '', '']
181 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
182 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [479]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117, 133, 149,165]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MPRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114, 130,146, 162, 178]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [480]:

########################
#                      #
# WRO                  #
#                      #
########################
sheet = book.sheet_by_name('WRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2013', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Alaska', '', '', '', '', '']
6 ['Oct 2012', 33974.0, 78080.0, 389.4837, 169.4713, 13232318.0]
7 ['Nov 2012', 37924.0, 89782.0, 405.2369, 171.1725, 15368206.0]
8 ['Dec 2012', 37949.0, 90289.0, 412.2764, 173.2822, 15645477.0]
9 ['Jan 2013', 38700.0, 92451.0, 415.8635, 174.0805, 16093918.0]
10 ['Feb 2013', 38866.0, 93417.0, 419.3374, 174.4647, 16297968.0]
11 ['Mar 2013', 39500.0, 94905.0, 418.4618, 174.1662, 16529242.0]
12 ['Apr 2013', 39739.0, 95371.0, 413.8681, 172.4497, 16446705.0]
13 ['May 2013', 39398.0, 94514.0, 412.6626, 172.0177, 16258081.0]
14 ['Jun 2013', 39260.0, 94336.0, 414.221, 172.3872, 16262316.0]
15 ['Jul 2013', 38387.0, 92289.0, 416.7153, 173.33, 15996450.0]
16 ['Aug 2013', 38074.0, 91258.0, 416.7535, 173.8748, 15867471.0]
17 ['Sep 2013', 37578.0, 89674.0, 414.2715, 173.601, 15567494.0]
18 ['Total', 38279.0833, 91363.8333, 412.6833, 172.9036, 189565646.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['American Samoa', '', '', '', '', '']
22 [' No data found.', '', '', '', '', '']
23 ['', '', '', '', '', '']
24 ['', '', '', '', '', '']
25 ['Arizona', '', '', '', '', '']
26 ['Oct 2012', 490522.0, 1137786.0, 289.4678, 124.7953, 141990333.0]
27 ['Nov 2012', 485236.0, 1128883.0, 286.7058, 123.2368, 139119959.0]
28 ['Dec 2012', 483599.0, 1124669.0, 286.0757, 123.0103, 138345914.0]
29 ['Jan 2013', 477411.0, 1108674.0, 286.4539, 123.3512, 136756224.0]
30 ['Feb 2013', 473132.0, 1101324.0, 283.9085, 121.9679, 134326183.0]
31 ['Mar 2013', 478406.0, 1114638.0, 284.066, 121.922, 135898879.0]
32 ['Apr 2013', 472251.0, 1099471.0, 285.9104, 122.8059, 135021491.0]
33 ['May 2013', 473117.0, 1102305.0, 286.761, 123.0798, 135671507.0]
34 ['Jun 2013', 474577.0, 1106860.0, 288.0584, 123.5079, 136705907.0]
35 ['Jul 2013', 469142.0, 1109093.0, 293.6853, 124.2278, 137780128.0]
36 ['Aug 2013', 471871.0, 1100429.0, 293.4674, 125.8407, 138478760.0]
37 ['Sep 2013', 470998.0, 1099131.0, 293.2942, 125.682, 138140973.0]
38 ['Total', 476688.5, 1111105.25, 288.14, 123.6184, 1648236258.0]
39 ['', '', '', '', '', '']
40 ['', '', '', '', '', '']
41 ['California', '', '', '', '', '']
42 ['Oct 2012', 1871771.0, 4107543.0, 326.7149, 148.8811, 611535495.0]
43 ['Nov 2012', 1870687.0, 4108565.0, 326.2628, 148.552, 610335663.0]
44 ['Dec 2012', 1879514.0, 4127070.0, 326.1706, 148.5418, 613042245.0]
45 ['Jan 2013', 1903182.0, 4155083.0, 332.5803, 152.3341, 632960816.0]
46 ['Feb 2013', 1891174.0, 4147880.0, 334.3229, 152.4304, 632262863.0]
47 ['Mar 2013', 1914602.0, 4180235.0, 334.2115, 153.0732, 639882067.0]
48 ['Apr 2013', 1911075.0, 4163620.0, 331.9708, 152.3725, 634421108.0]
49 ['May 2013', 1915130.0, 4169854.0, 332.1503, 152.55, 636111028.0]
50 ['Jun 2013', 1914830.0, 4167502.0, 331.1396, 152.1477, 634076011.0]
51 ['Jul 2013', 1926688.0, 4181660.0, 330.3486, 152.2072, 636478761.0]
52 ['Aug 2013', 1933680.0, 4198369.0, 330.7958, 152.3576, 639653300.0]
53 ['Sep 2013', 1938095.0, 4200988.0, 328.9772, 151.7712, 637589036.0]
54 ['Total', 1905869.0, 4159030.75, 330.4857, 151.4445, 7558348393.0]
55 ['', '', '', '', '', '']
56 ['', '', '', '', '', '']
57 ['Guam', '', '', '', '', '']
58 ['Oct 2012', 14485.0, 44799.0, 668.3182, 216.0894, 9680589.0]
59 ['Nov 2012', 14721.0, 45130.0, 658.1761, 214.6911, 9689011.0]
60 ['Dec 2012', 14837.0, 45380.0, 657.9414, 215.1141, 9761876.0]
61 ['Jan 2013', 14955.0, 45620.0, 660.1338, 216.4029, 9872301.0]
62 ['Feb 2013', 15139.0, 45846.0, 650.953, 214.9539, 9854778.0]
63 ['Mar 2013', 15064.0, 45348.0, 656.783, 218.1745, 9893779.0]
64 ['Apr 2013', 15188.0, 45246.0, 649.4371, 218.0005, 9863651.0]
65 ['May 2013', 15188.0, 45324.0, 653.6586, 219.04, 9927767.0]
66 ['Jun 2013', 15310.0, 45694.0, 643.8157, 215.7136, 9856818.0]
67 ['Jul 2013', 15379.0, 45973.0, 641.0489, 214.4452, 9858691.0]
68 ['Aug 2013', 15317.0, 45804.0, 648.5356, 216.8723, 9933620.0]
69 ['Sep 2013', 15578.0, 46489.0, 639.7588, 214.3768, 9966163.0]
70 ['Total', 15096.75, 45554.4167, 652.2322, 216.15, 118159044.0]
71 ['', '', '', '', '', '']
72 ['', '', '', '', '', '']
73 ['Hawaii', '', '', '', '', '']
74 ['Oct 2012', 93919.0, 186330.0, 433.2826, 218.3946, 40693469.0]
75 ['Nov 2012', 94250.0, 187034.0, 432.6169, 218.0039, 40774144.0]
76 ['Dec 2012', 94852.0, 187917.0, 431.1708, 217.6355, 40897410.0]
77 ['Jan 2013', 95305.0, 188763.0, 428.6918, 216.4432, 40856473.0]
78 ['Feb 2013', 95646.0, 188564.0, 427.219, 216.6998, 40861788.0]
79 ['Mar 2013', 96073.0, 188933.0, 427.5158, 217.3931, 41072728.0]
80 ['Apr 2013', 96407.0, 189366.0, 426.4902, 217.1279, 41116641.0]
81 ['May 2013', 96558.0, 189647.0, 427.0831, 217.4476, 41238290.0]
82 ['Jun 2013', 96677.0, 189855.0, 428.4723, 218.1845, 41423413.0]
83 ['Jul 2013', 97420.0, 191509.0, 427.6977, 217.5684, 41666308.0]
84 ['Aug 2013', 97629.0, 192117.0, 428.8201, 217.9155, 41865273.0]
85 ['Sep 2013', 97522.0, 192162.0, 427.7608, 217.0881, 41716090.0]
86 ['Total', 96021.5, 189349.75, 428.8814, 217.4908, 494182027.0]
87 ['', '', '', '', '', '']
88 ['', '', '', '', '', '']
89 ['Idaho', '', '', '', '', '']
90 ['Oct 2012', 98152.0, 226538.0, 296.5217, 128.4738, 29104199.0]
91 ['Nov 2012', 98054.0, 226759.0, 296.127, 128.0498, 29036437.0]
92 ['Dec 2012', 98222.0, 227854.0, 297.5725, 128.2759, 29228167.0]
93 ['Jan 2013', 99226.0, 230569.0, 294.3727, 126.6841, 29209426.0]
94 ['Feb 2013', 99292.0, 231015.0, 297.3398, 127.7989, 29523468.0]
95 ['Mar 2013', 99678.0, 231301.0, 296.7575, 127.8862, 29580197.0]
96 ['Apr 2013', 99069.0, 229927.0, 295.9687, 127.5245, 29321328.0]
97 ['May 2013', 98314.0, 228311.0, 295.8348, 127.3907, 29084702.0]
98 ['Jun 2013', 97735.0, 226041.0, 294.469, 127.3217, 28779926.0]
99 ['Jul 2013', 96537.0, 223398.0, 292.4824, 126.3904, 28235370.0]
100 ['Aug 2013', 95741.0, 221841.0, 292.2057, 126.1086, 27976069.0]
101 ['Sep 2013', 95105.0, 220521.0, 291.2955, 125.6282, 27703658.0]
102 ['Total', 97927.0833, 227006.25, 295.103, 127.303, 346782947.0]
103 ['', '', '', '', '', '']
104 ['', '', '', '', '', '']
105 ['Nevada', '', '', '', '', '']
106 ['Oct 2012', 173332.0, 360559.0, 259.4826, 124.7414, 44976639.0]
107 ['Nov 2012', 173401.0, 360777.0, 255.5924, 122.8459, 44319978.0]
108 ['Dec 2012', 172676.0, 358892.0, 255.9128, 123.129, 44190000.0]
109 ['Jan 2013', 173005.0, 358457.0, 254.7865, 122.9696, 44079330.0]
110 ['Feb 2013', 172384.0, 356414.0, 259.9525, 125.7292, 44811652.0]
111 ['Mar 2013', 172193.0, 355312.0, 257.061, 124.5781, 44264109.0]
112 ['Apr 2013', 173665.0, 358319.0, 255.0727, 123.6251, 44297207.0]
113 ['May 2013', 175120.0, 360207.0, 255.6539, 124.29, 44770113.0]
114 ['Jun 2013', 175935.0, 362203.0, 254.4501, 123.5955, 44766677.0]
115 ['Jul 2013', 176364.0, 363155.0, 252.28, 122.5182, 44493103.0]
116 ['Aug 2013', 178132.0, 367101.0, 253.1802, 122.8531, 45099503.0]
117 ['Sep 2013', 179454.0, 370042.0, 251.6655, 122.0466, 45162382.0]
118 ['Total', 174638.4167, 360953.1667, 255.3995, 123.5688, 535230693.0]
119 ['', '', '', '', '', '']
120 ['', '', '', '', '', '']
121 ['Oregon', '', '', '', '', '']
122 ['Oct 2012', 452619.0, 818772.0, 231.3353, 127.8827, 104706760.0]
123 ['Nov 2012', 452127.0, 817748.0, 231.1847, 127.8203, 104524827.0]
124 ['Dec 2012', 450419.0, 815377.0, 232.4543, 128.4091, 104701832.0]
125 ['Jan 2013', 452973.0, 820014.0, 231.1649, 127.6947, 104711438.0]
126 ['Feb 2013', 452898.0, 819465.0, 232.7345, 128.6266, 105404995.0]
127 ['Mar 2013', 442074.0, 819534.0, 237.6753, 128.2071, 105070090.0]
128 ['Apr 2013', 452644.0, 817676.0, 231.2452, 128.0113, 104671743.0]
129 ['May 2013', 451771.0, 816010.0, 230.7451, 127.7484, 104243941.0]
130 ['Jun 2013', 451581.0, 814318.0, 229.4818, 127.2594, 103629626.0]
131 ['Jul 2013', 453744.0, 820927.0, 227.3883, 125.6824, 103176082.0]
132 ['Aug 2013', 453204.0, 819503.0, 227.2415, 125.6698, 102986776.0]
133 ['Sep 2013', 450981.0, 811554.0, 226.946, 126.114, 102348318.0]
134 ['Total', 451419.5833, 817574.8333, 230.7861, 127.4273, 1250176428.0]
135 ['', '', '', '', '', '']
136 ['', '', '', '', '', '']
137 ['Washington', '', '', '', '', '']
138 ['Oct 2012', 589066.0, 1112770.0, 238.6048, 126.31, 140553946.0]
139 ['Nov 2012', 587135.0, 1109014.0, 238.027, 126.0164, 139753984.0]
140 ['Dec 2012', 588212.0, 1114742.0, 238.5004, 125.8487, 140288777.0]
141 ['Jan 2013', 590614.0, 1117999.0, 238.2017, 125.8366, 140685232.0]
142 ['Feb 2013', 590584.0, 1117832.0, 237.7413, 125.6058, 140406187.0]
143 ['Mar 2013', 591941.0, 1116250.0, 238.6573, 126.5586, 141271035.0]
144 ['Apr 2013', 591253.0, 1111505.0, 236.2789, 125.686, 139700637.0]
145 ['May 2013', 592696.0, 1112751.0, 236.5928, 126.0189, 140227604.0]
146 ['Jun 2013', 592002.0, 1107066.0, 234.8804, 125.602, 139049660.0]
147 ['Jul 2013', 593451.0, 1112119.0, 233.9354, 124.833, 138829183.0]
148 ['Aug 2013', 593653.0, 1116059.0, 235.0504, 125.0278, 139538374.0]
149 ['Sep 2013', 592743.0, 1113184.0, 233.5455, 124.3572, 138432458.0]
150 ['Total', 591112.5, 1113440.9167, 236.6635, 125.6418, 1678737077.0]
151 ['', '', '', '', '', '']
152 ['', '', '', '', '', '']
153 ['Outlying Areas', '', '', '', '', '']
154 [' No data found.', '', '', '', '', '']
155 ['', '', '', '', '', '']
156 ['', '', '', '', '', '']
157 ['WRO', '', '', '', '', '']
158 ['Oct 2012', 3817840.0, 8073177.0, 297.6745, 140.7716, 1136473748.0]
159 ['Nov 2012', 3813535.0, 8073692.0, 297.0793, 140.3227, 1132922209.0]
160 ['Dec 2012', 3820280.0, 8092190.0, 297.387, 140.3948, 1136101698.0]
161 ['Jan 2013', 3845371.0, 8117630.0, 300.4197, 142.3106, 1155225158.0]
162 ['Feb 2013', 3829115.0, 8101757.0, 301.3098, 142.4074, 1153749882.0]
163 ['Mar 2013', 3849531.0, 8146456.0, 302.2348, 142.8182, 1163462126.0]
164 ['Apr 2013', 3851291.0, 8110501.0, 299.8632, 142.3908, 1154860511.0]
165 ['May 2013', 3857292.0, 8118923.0, 300.0896, 142.5722, 1157533033.0]
166 ['Jun 2013', 3857907.0, 8113875.0, 299.2686, 142.2933, 1154550354.0]
167 ['Jul 2013', 3867112.0, 8140123.0, 299.064, 142.0757, 1156514076.0]
168 ['Aug 2013', 3877301.0, 8152481.0, 299.538, 142.4596, 1161399146.0]
169 ['Sep 2013', 3878054.0, 8143745.0, 298.2492, 142.0264, 1156626572.0]
170 ['Total', 3847052.4167, 8115379.1667, 299.3508, 141.9057, 13819418513.0]
171 ['', '', '', '', '', '']
172 ['', '', '', '', '', '']
173 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
174 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [481]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,25,41,57,73,89,105,121,137,153,157]:
        #for the rows that have the state names
        state = row[0]
        if state == 'WRO':
            break
        else:
            continue         
    if i in [18,23,38,54,70,86,102,118,134,150,155,170]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [482]:
pprint.pprint(snap_data)

{'Alabama': {'cost_by_household': 279.8767,
             'cost_by_individual': 128.8209,
             'household_participation': 421302.1667,
             'individual_participation': 915322.4167,
             'total_cost': 1414951864.0},
 'Alaska': {'cost_by_household': 412.6833,
            'cost_by_individual': 172.9036,
            'household_participation': 38279.0833,
            'individual_participation': 91363.8333,
            'total_cost': 189565646.0},
 'American Samoa': {'cost_by_household': '',
                    'cost_by_individual': '',
                    'household_participation': '',
                    'individual_participation': '',
                    'total_cost': ''},
 'Arizona': {'cost_by_household': 288.14,
             'cost_by_individual': 123.6184,
             'household_participation': 476688.5,
             'individual_participation': 1111105.25,
             'total_cost': 1648236258.0},
 'Arkansas': {'cost_by_household': 271.7136,
              'cost_by_individual': 120.8574,
              'household_participation': 224453.8333,
              'individual_participation': 504620.9167,
              'total_cost': 731845896.0},
 'California': {'cost_by_household': 330.4857,
                'cost_by_individual': 151.4445,
                'household_participation': 1905869.0,
                'individual_participation': 4159030.75,
                'total_cost': 7558348393.0},
 'Colorado': {'cost_by_household': 296.4627,
              'cost_by_individual': 135.111,
              'household_participation': 231487.6667,
              'individual_participation': 507933.9167,
              'total_cost': 823529607.0},
 'Connecticut': {'cost_by_household': 252.9093,
                 'cost_by_individual': 138.6516,
                 'household_participation': 233171.4167,
                 'individual_participation': 425319.5,
                 'total_cost': 707654612.0},
 'Delaware': {'cost_by_household': 271.1065,
              'cost_by_individual': 127.8964,
              'household_participation': 72243.5833,
              'individual_participation': 153137.25,
              'total_cost': 235028481.0},
 'District of Columbia': {'cost_by_household': 239.1222,
                          'cost_by_individual': 135.1728,
                          'household_participation': 81903.9167,
                          'individual_participation': 144888.9167,
                          'total_cost': 235020570.0},
 'Florida': {'cost_by_household': 253.1918,
             'cost_by_individual': 138.3899,
             'household_participation': 1943901.5833,
             'individual_participation': 3556472.9167,
             'total_cost': 5906158957.0},
 'Georgia': {'cost_by_household': 292.6861,
             'cost_by_individual': 136.3978,
             'household_participation': 907896.3333,
             'individual_participation': 1948188.5833,
             'total_cost': 3188743586.0},
 'Guam': {'cost_by_household': 652.2322,
          'cost_by_individual': 216.15,
          'household_participation': 15096.75,
          'individual_participation': 45554.4167,
          'total_cost': 118159044.0},
 'Hawaii': {'cost_by_household': 428.8814,
            'cost_by_individual': 217.4908,
            'household_participation': 96021.5,
            'individual_participation': 189349.75,
            'total_cost': 494182027.0},
 'Idaho': {'cost_by_household': 295.103,
           'cost_by_individual': 127.303,
           'household_participation': 97927.0833,
           'individual_participation': 227006.25,
           'total_cost': 346782947.0},
 'Illinois': {'cost_by_household': 276.7507,
              'cost_by_individual': 137.9905,
              'household_participation': 1017189.5833,
              'individual_participation': 2040053.25,
              'total_cost': 3378095657.0},
 'Indiana': {'cost_by_household': 293.035,
             'cost_by_individual': 131.4902,
             'household_participation': 415518.1667,
             'individual_participation': 926010.9167,
             'total_cost': 1461136176.0},
 'Iowa': {'cost_by_household': 246.239,
          'cost_by_individual': 116.282,
          'household_participation': 198500.25,
          'individual_participation': 420344.4167,
          'total_cost': 586542123.0},
 'Kansas': {'cost_by_household': 264.8296,
            'cost_by_individual': 124.6798,
            'household_participation': 149233.0,
            'individual_participation': 316982.5833,
            'total_cost': 474255829.0},
 'Kentucky': {'cost_by_household': 264.3512,
              'cost_by_individual': 127.325,
              'household_participation': 420210.8333,
              'individual_participation': 872438.5833,
              'total_cost': 1332998664.0},
 'Louisiana': {'cost_by_household': 289.7207,
               'cost_by_individual': 131.1765,
               'household_participation': 425647.9167,
               'individual_participation': 940099.6667,
               'total_cost': 1479828133.0},
 'Maine': {'cost_by_household': 234.6258,
           'cost_by_individual': 122.7896,
           'household_participation': 130374.25,
           'individual_participation': 249118.5,
           'total_cost': 367069888.0},
 'Maryland': {'cost_by_household': 250.4486,
              'cost_by_individual': 127.3919,
              'household_participation': 392183.5833,
              'individual_participation': 771020.75,
              'total_cost': 1178661931.0},
 'Massachusetts': {'cost_by_household': 233.0845,
                   'cost_by_individual': 130.9248,
                   'household_participation': 498580.0833,
                   'individual_participation': 887618.6667,
                   'total_cost': 1394535579.0},
 'Michigan': {'cost_by_household': 266.7014,
              'cost_by_individual': 136.6463,
              'household_participation': 909764.0,
              'individual_participation': 1775645.6667,
              'total_cost': 2911624110.0},
 'Minnesota': {'cost_by_household': 234.3972,
               'cost_by_individual': 116.2541,
               'household_participation': 274236.25,
               'individual_participation': 552928.3333,
               'total_cost': 771362512.0},
 'Mississippi': {'cost_by_household': 271.3284,
                 'cost_by_individual': 123.7713,
                 'household_participation': 305004.9167,
                 'individual_participation': 668624.3333,
                 'total_cost': 993077956.0},
 'Missouri': {'cost_by_household': 272.2034,
              'cost_by_individual': 128.0439,
              'household_participation': 437443.1667,
              'individual_participation': 929942.8333,
              'total_cost': 1428882352.0},
 'Montana': {'cost_by_household': 269.7344,
             'cost_by_individual': 124.652,
             'household_participation': 59397.8333,
             'individual_participation': 128530.9167,
             'total_cost': 192259685.0},
 'Nebraska': {'cost_by_household': 277.8206,
              'cost_by_individual': 122.7141,
              'household_participation': 79378.6667,
              'individual_participation': 179710.6667,
              'total_cost': 264636314.0},
 'Nevada': {'cost_by_household': 255.3995,
            'cost_by_individual': 123.5688,
            'household_participation': 174638.4167,
            'individual_participation': 360953.1667,
            'total_cost': 535230693.0},
 'New Hampshire': {'cost_by_household': 241.6484,
                   'cost_by_individual': 115.7646,
                   'household_participation': 56201.0833,
                   'individual_participation': 117314.8333,
                   'total_cost': 162970800.0},
 'New Jersey': {'cost_by_household': 273.5999,
                'cost_by_individual': 134.9692,
                'household_participation': 432269.5,
                'individual_participation': 876266.0,
                'total_cost': 1419226622.0},
 'New Mexico': {'cost_by_household': 286.906,
                'cost_by_individual': 128.584,
                'household_participation': 197359.0,
                'individual_participation': 440361.6667,
                'total_cost': 679481811.0},
 'New York': {'cost_by_household': 273.8673,
              'cost_by_individual': 147.7545,
              'household_participation': 1710501.25,
              'individual_participation': 3170465.0,
              'total_cost': 5621405245.0},
 'North Carolina': {'cost_by_household': 264.1004,
                    'cost_by_individual': 121.8523,
                    'household_participation': 786063.9167,
                    'individual_participation': 1703700.4167,
                    'total_cost': 2491197794.0},
 'North Dakota': {'cost_by_household': 271.3188,
                  'cost_by_individual': 126.0999,
                  'household_participation': 26269.9167,
                  'individual_participation': 56522.8333,
                  'total_cost': 85530266.0},
 'Ohio': {'cost_by_household': 273.8805,
          'cost_by_individual': 133.5014,
          'household_participation': 889427.1667,
          'individual_participation': 1824674.8333,
          'total_cost': 2923160707.0},
 'Oklahoma': {'cost_by_household': 277.978,
              'cost_by_individual': 128.476,
              'household_participation': 287398.1667,
              'individual_participation': 621830.9167,
              'total_cost': 958684325.0},
 'Oregon': {'cost_by_household': 230.7861,
            'cost_by_individual': 127.4273,
            'household_participation': 451419.5833,
            'individual_participation': 817574.8333,
            'total_cost': 1250176428.0},
 'Outlying Areas': {'cost_by_household': '',
                    'cost_by_individual': '',
                    'household_participation': '',
                    'individual_participation': '',
                    'total_cost': ''},
 'Pennsylvania': {'cost_by_household': 263.3013,
                  'cost_by_individual': 128.3226,
                  'household_participation': 869835.8333,
                  'individual_participation': 1784790.25,
                  'total_cost': 2748346529.0},
 'Puerto Rico': {'cost_by_household': '',
                 'cost_by_individual': '',
                 'household_participation': '',
                 'individual_participation': '',
                 'total_cost': ''},
 'Rhode Island': {'cost_by_household': 251.0464,
                  'cost_by_individual': 140.2855,
                  'household_participation': 100542.6667,
                  'individual_participation': 179925.0,
                  'total_cost': 302890523.0},
 'South Carolina': {'cost_by_household': 276.3186,
                    'cost_by_individual': 131.4682,
                    'household_participation': 416723.75,
                    'individual_participation': 875865.75,
                    'total_cost': 1381782118.0},
 'South Dakota': {'cost_by_household': 303.5255,
                  'cost_by_individual': 132.1782,
                  'household_participation': 45312.0,
                  'individual_participation': 104051.5833,
                  'total_cost': 165040184.0},
 'Tennessee': {'cost_by_household': 267.7524,
               'cost_by_individual': 132.1125,
               'household_participation': 662204.3333,
               'individual_participation': 1342089.4167,
               'total_cost': 2127681953.0},
 'Texas': {'cost_by_household': 295.3605,
           'cost_by_individual': 122.3528,
           'household_participation': 1674350.0833,
           'individual_participation': 4041891.0833,
           'total_cost': 5934441831.0},
 'Utah': {'cost_by_household': 311.7172,
          'cost_by_individual': 125.1537,
          'household_participation': 101027.25,
          'individual_participation': 251626.0,
          'total_cost': 377903214.0},
 'Vermont': {'cost_by_household': 238.9215,
             'cost_by_individual': 124.372,
             'household_participation': 52337.3333,
             'individual_participation': 100541.25,
             'total_cost': 150054164.0},
 'Virgin Islands': {'cost_by_household': 397.1819,
                    'cost_by_individual': 173.1018,
                    'household_participation': 11957.3333,
                    'individual_participation': 27436.0833,
                    'total_cost': 56990837.0},
 'Virginia': {'cost_by_household': 263.3221,
              'cost_by_individual': 127.7494,
              'household_participation': 456488.5833,
              'individual_participation': 940932.1667,
              'total_cost': 1442442319.0},
 'Washington': {'cost_by_household': 236.6635,
                'cost_by_individual': 125.6418,
                'household_participation': 591112.5,
                'individual_participation': 1113440.9167,
                'total_cost': 1678737077.0},
 'West Virginia': {'cost_by_household': 251.7184,
                   'cost_by_individual': 119.8775,
                   'household_participation': 167013.9167,
                   'individual_participation': 350695.4167,
                   'total_cost': 504485785.0},
 'Wisconsin': {'cost_by_household': 239.5686,
               'cost_by_individual': 116.5578,
               'household_participation': 416826.4167,
               'individual_participation': 856729.5,
               'total_cost': 1198302422.0},
 'Wyoming': {'cost_by_household': 292.9084,
             'cost_by_individual': 124.8046,
             'household_participation': 16211.0,
             'individual_participation': 38046.1667,
             'total_cost': 56980056.0}}

In [483]:
snap_data_2013 = pd.DataFrame.from_dict(snap_data, orient = "index")

In [484]:
pd.DataFrame.to_csv(snap_data_2013,'SNAP/SNAP DFs/snap_2013_df.csv')

# 2012

In [485]:
book = xlrd.open_workbook('SNAP/FY12.xls')

In [486]:
sheet = book.sheet_by_name('NERO')

In [487]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2012', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Connecticut', '', '', '', '', '']
6 ['Oct 2011', 215463.0, 396517.0, 333.0694, 180.9863, 71764136.0]
7 ['Nov 2011', 217202.0, 400072.0, 303.7848, 164.927, 65982670.0]
8 ['Dec 2011', 219660.0, 405215.0, 258.4518, 140.1022, 56771532.0]
9 ['Jan 2012', 220259.0, 405779.0, 250.057, 135.7323, 55077315.0]
10 ['Feb 2012', 219069.0, 402571.0, 251.2115, 136.703, 55032660.0]
11 ['Mar 2012', 218854.0, 401009.0, 252.0887, 137.5795, 55170623.0]
12 ['Apr 2012', 218897.0, 400541.0, 252.2218, 137.84, 55210587.0]
13 ['May 2012', 218816.0, 400203.0, 251.732, 137.6376, 55082999.0]
14 ['Jun 2012', 220659.0, 404164.0, 258.2976, 141.0212, 56995693.0]
15 ['Jul 2012', 221414.0, 405613.0, 250.7871, 136.8984, 55527785.0]
16 ['Aug 2012', 223075.0, 408569.0, 255.2876, 139.3847, 56948279.0]
17 ['Sep 2012', 224434.0, 411344.0, 254.4458, 138.8285, 57106285.0]
18 ['Total', 219816.8333, 403466.4167, 264.1103, 143.8927, 696670564.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Maine', '', '', '', '', '']
22 ['Oct 2011', 129541.0, 251189.0, 243.6458, 125.6509, 31562118.0]
23 ['Nov 2011', 129610.0, 250864.0, 242.844, 125.4665, 31475016.0]
24 ['Dec 2011', 130838.0, 253278.0, 242.5018, 125.2712, 31728450.0]
25 ['Jan 2012', 131285.0, 253961.0, 237.4303, 122.7394, 31171033.0]
26 ['Feb 2012', 131043.0, 253135.0, 238.0226, 123.2196, 31191197.0]
27 ['Mar 2012', 131950.0, 254498.0, 238.7238, 123.7715, 31499603.0]
28 ['Apr 2012', 131752.0, 253496.0, 238.1314, 123.7664, 31374288.0]
29 ['May 2012', 132116.0, 254363.0, 237.8964, 123.5633, 31429924.0]
30 ['Jun 2012', 132061.0, 253903.0, 238.5038, 124.0515, 31497044.0]
31 ['Jul 2012', 131784.0, 253305.0, 239.19, 124.4405, 31521412.0]
32 ['Aug 2012', 131201.0, 252244.0, 238.262, 123.9285, 31260215.0]
33 ['Sep 2012', 130659.0, 250084.0, 237.5703, 124.1211, 31040699.0]
34 ['Total', 131153.3333, 252860.0, 239.3833, 124.1632, 376750999.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Massachusetts', '', '', '', '', '']
38 ['Oct 2011', 463858.0, 838603.0, 238.2014, 131.7568, 110491632.0]
39 ['Nov 2011', 466579.0, 843231.0, 255.9652, 141.6314, 119427979.0]
40 ['Dec 2011', 468363.0, 845334.0, 241.8554, 134.0016, 113276105.0]
41 ['Jan 2012', 472313.0, 850393.0, 236.8072, 131.524, 111847097.0]
42 ['Feb 2012', 474807.0, 853862.0, 234.772, 130.5496, 111471384.0]
43 ['Mar 2012', 478312.0, 858616.0, 235.3536, 131.1092, 112572441.0]
44 ['Apr 2012', 481499.0, 862959.0, 233.3739, 130.214, 112369309.0]
45 ['May 2012', 485279.0, 868872.0, 239.2593, 133.6302, 116107526.0]
46 ['Jun 2012', 488334.0, 873891.0, 236.9358, 132.4007, 115703797.0]
47 ['Jul 2012', 490836.0, 877542.0, 234.6354, 131.2387, 115167491.0]
48 ['Aug 2012', 493241.0, 881951.0, 235.7491, 131.8453, 116281108.0]
49 ['Sep 2012', 494536.0, 883565.0, 233.1108, 130.4733, 115281682.0]
50 ['Total', 479829.75, 861568.25, 237.9312, 132.5101, 1369997551.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['New Hampshire', '', '', '', '', '']
54 ['Oct 2011', 54922.0, 114744.0, 248.6797, 119.0301, 13657985.0]
55 ['Nov 2011', 54893.0, 114478.0, 249.6999, 119.7328, 13706774.0]
56 ['Dec 2011', 55662.0, 115730.0, 247.0328, 118.814, 13750340.0]
57 ['Jan 2012', 56269.0, 117063.0, 245.6672, 118.0855, 13823446.0]
58 ['Feb 2012', 56455.0, 117323.0, 242.6129, 116.7436, 13696712.0]
59 ['Mar 2012', 56529.0, 117269.0, 246.4328, 118.7918, 13930600.0]
60 ['Apr 2012', 56675.0, 117455.0, 246.8898, 119.1306, 13992479.0]
61 ['May 2012', 56910.0, 117749.0, 246.4343, 119.1057, 14024577.0]
62 ['Jun 2012', 56954.0, 117734.0, 246.2156, 119.1072, 14022964.0]
63 ['Jul 2012', 56875.0, 117650.0, 245.7958, 118.8239, 13979636.0]
64 ['Aug 2012', 57147.0, 117935.0, 244.5955, 118.522, 13977897.0]
65 ['Sep 2012', 56961.0, 117605.0, 244.188, 118.2704, 13909195.0]
66 ['Total', 56354.3333, 116894.5833, 246.1695, 118.6772, 166472605.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['New York', '', '', '', '', '']
70 ['Oct 2011', 1633974.0, 3060107.0, 282.6025, 150.8983, 461765083.0]
71 ['Nov 2011', 1627251.0, 3046972.0, 279.5229, 149.2806, 454853898.0]
72 ['Dec 2011', 1640278.0, 3068575.0, 278.1563, 148.6858, 456253622.0]
73 ['Jan 2012', 1638345.0, 3059120.0, 272.6313, 146.0106, 446664074.0]
74 ['Feb 2012', 1639443.0, 3059262.0, 274.3877, 147.043, 449842979.0]
75 ['Mar 2012', 1656028.0, 3081831.0, 276.0126, 148.3159, 457084622.0]
76 ['Apr 2012', 1645353.0, 3063238.0, 271.8107, 145.9973, 447224602.0]
77 ['May 2012', 1656662.0, 3082995.0, 273.1209, 146.7628, 452468956.0]
78 ['Jun 2012', 1662926.0, 3095534.0, 272.6797, 146.484, 453446186.0]
79 ['Jul 2012', 1662829.0, 3094677.0, 272.4412, 146.3879, 453023151.0]
80 ['Aug 2012', 1671083.0, 3109436.0, 273.4517, 146.9593, 456960514.0]
81 ['Sep 2012', 1667012.0, 3101190.0, 272.6519, 146.5612, 454513975.0]
82 ['Total', 1650098.6667, 3076911.4167, 274.9382, 147.445, 5444101662.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Rhode Island', '', '', '', '', '']
86 ['Oct 2011', 92039.0, 168694.0, 258.5132, 141.0441, 23793295.0]
87 ['Nov 2011', 92460.0, 169376.0, 256.5086, 140.0245, 23716782.0]
88 ['Dec 2011', 93356.0, 170547.0, 255.2617, 139.7281, 23830211.0]
89 ['Jan 2012', 94579.0, 172629.0, 253.2357, 138.7414, 23950782.0]
90 ['Feb 2012', 94672.0, 172284.0, 255.6962, 140.5079, 24207268.0]
91 ['Mar 2012', 95342.0, 172907.0, 254.6541, 140.4178, 24279229.0]
92 ['Apr 2012', 95558.0, 172781.0, 251.3749, 139.025, 24020887.0]
93 ['May 2012', 96127.0, 173639.0, 250.5746, 138.7188, 24086989.0]
94 ['Jun 2012', 96431.0, 174069.0, 248.5389, 137.6859, 23966854.0]
95 ['Jul 2012', 97251.0, 175014.0, 250.8214, 139.3753, 24392629.0]
96 ['Aug 2012', 97461.0, 175590.0, 250.1576, 138.8496, 24380610.0]
97 ['Sep 2012', 98106.0, 176619.0, 250.9563, 139.3979, 24620316.0]
98 ['Total', 95281.8333, 172845.75, 252.9739, 139.4528, 289245852.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['Vermont', '', '', '', '', '']
102 ['Oct 2011', 47833.0, 94604.0, 243.1492, 122.9394, 11630557.0]
103 ['Nov 2011', 48252.0, 95316.0, 242.078, 122.5476, 11680749.0]
104 ['Dec 2011', 48508.0, 95652.0, 241.7284, 122.5877, 11725761.0]
105 ['Jan 2012', 48907.0, 96198.0, 237.4633, 120.7262, 11613616.0]
106 ['Feb 2012', 49148.0, 96365.0, 239.9112, 122.3593, 11791155.0]
107 ['Mar 2012', 49141.0, 96080.0, 236.9018, 121.1656, 11641593.0]
108 ['Apr 2012', 49422.0, 96458.0, 235.5323, 120.6792, 11640476.0]
109 ['May 2012', 49660.0, 96805.0, 237.6709, 121.9228, 11802739.0]
110 ['Jun 2012', 49741.0, 96854.0, 236.7136, 121.5683, 11774372.0]
111 ['Jul 2012', 50031.0, 97243.0, 236.4952, 121.6755, 11832091.0]
112 ['Aug 2012', 50670.0, 98561.0, 237.212, 121.9502, 12019531.0]
113 ['Sep 2012', 50884.0, 98817.0, 237.8565, 122.4799, 12103092.0]
114 ['Total', 49349.75, 96579.4167, 238.5283, 121.8822, 141255732.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['NERO', '', '', '', '', '']
118 ['Oct 2011', 2637630.0, 4924458.0, 274.7409, 147.1563, 724664806.0]
119 ['Nov 2011', 2636247.0, 4920309.0, 273.4356, 146.5038, 720843868.0]
120 ['Dec 2011', 2656665.0, 4954331.0, 266.2496, 142.7712, 707336021.0]
121 ['Jan 2012', 2661957.0, 4955143.0, 260.7658, 140.0862, 694147363.0]
122 ['Feb 2012', 2664637.0, 4954802.0, 261.6617, 140.7187, 697233355.0]
123 ['Mar 2012', 2686156.0, 4982210.0, 262.8956, 141.7401, 706178711.0]
124 ['Apr 2012', 2679156.0, 4966928.0, 259.7208, 140.0932, 695832628.0]
125 ['May 2012', 2695570.0, 4994626.0, 261.5416, 141.1525, 705003710.0]
126 ['Jun 2012', 2707106.0, 5016149.0, 261.3148, 141.0259, 707406910.0]
127 ['Jul 2012', 2711020.0, 5021044.0, 260.2136, 140.4975, 705444195.0]
128 ['Aug 2012', 2723878.0, 5044286.0, 261.3289, 141.1157, 711828154.0]
129 ['Sep 2012', 2722592.0, 5039224.0, 260.2576, 140.612, 708575244.0]
130 ['Total', 2681884.5, 4981125.8333, 263.636, 141.9441, 8484494965.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
134 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [488]:
snap_data = {}

########################
#                      #
# NERO                 #
#                      #
########################

for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117]:
        #for the rows that have the state names
        state = row[0]
        if state == 'NERO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [489]:
########################
#                      #
# MARO                 #
#                      #
########################

sheet = book.sheet_by_name('MARO')

In [490]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2012', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Delaware', '', '', '', '', '']
6 ['Oct 2011', 67229.0, 144612.0, 271.2127, 126.0847, 18233356.0]
7 ['Nov 2011', 68727.0, 147475.0, 271.3341, 126.4484, 18647976.0]
8 ['Dec 2011', 69432.0, 148525.0, 271.3232, 126.8373, 18838510.0]
9 ['Jan 2012', 69730.0, 148854.0, 269.3161, 126.16, 18779415.0]
10 ['Feb 2012', 69983.0, 148764.0, 270.008, 127.0198, 18895972.0]
11 ['Mar 2012', 70121.0, 148654.0, 271.5268, 128.0808, 19039729.0]
12 ['Apr 2012', 68831.0, 146263.0, 271.4844, 127.7599, 18686544.0]
13 ['May 2012', 69770.0, 148467.0, 272.8609, 128.2272, 19037505.0]
14 ['Jun 2012', 69714.0, 148295.0, 274.5177, 129.0517, 19137726.0]
15 ['Jul 2012', 69466.0, 147509.0, 270.0795, 127.1878, 18761344.0]
16 ['Aug 2012', 71066.0, 151337.0, 272.6981, 128.0557, 19379564.0]
17 ['Sep 2012', 70701.0, 150330.0, 270.7089, 127.3158, 19139390.0]
18 ['Total', 69564.1667, 148257.0833, 271.4245, 127.3559, 226577031.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['District of Columbia', '', '', '', '', '']
22 ['Oct 2011', 78962.0, 140003.0, 248.0953, 139.9263, 19590105.0]
23 ['Nov 2011', 79172.0, 140384.0, 247.6937, 139.6912, 19610404.0]
24 ['Dec 2011', 79634.0, 141112.0, 246.823, 139.2901, 19655500.0]
25 ['Jan 2012', 79382.0, 140515.0, 241.99, 136.7089, 19209652.0]
26 ['Feb 2012', 79298.0, 140311.0, 242.1059, 136.8283, 19198517.0]
27 ['Mar 2012', 79616.0, 140549.0, 240.8, 136.4046, 19171533.0]
28 ['Apr 2012', 78983.0, 139626.0, 240.4533, 136.0185, 18991726.0]
29 ['May 2012', 79328.0, 140187.0, 240.9528, 136.3486, 19114301.0]
30 ['Jun 2012', 79926.0, 141266.0, 240.4711, 136.0546, 19219894.0]
31 ['Jul 2012', 80199.0, 142025.0, 251.1462, 141.8178, 20141675.0]
32 ['Aug 2012', 81109.0, 143951.0, 242.987, 136.9107, 19708433.0]
33 ['Sep 2012', 81134.0, 143839.0, 242.7001, 136.8977, 19691233.0]
34 ['Total', 79728.5833, 141147.3333, 243.8512, 137.742, 233302973.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Maryland', '', '', '', '', '']
38 ['Oct 2011', 353242.0, 709681.0, 256.893, 127.8679, 90745408.0]
39 ['Nov 2011', 354110.0, 709254.0, 255.6934, 127.6603, 90543582.0]
40 ['Dec 2011', 355275.0, 710675.0, 255.6324, 127.7937, 90819788.0]
41 ['Jan 2012', 356557.0, 709754.0, 249.5024, 125.3418, 88961841.0]
42 ['Feb 2012', 356682.0, 708889.0, 251.11, 126.3476, 89566433.0]
43 ['Mar 2012', 357590.0, 709305.0, 250.747, 126.4119, 89664619.0]
44 ['Apr 2012', 358965.0, 711720.0, 250.3287, 126.2564, 89859238.0]
45 ['May 2012', 360299.0, 712757.0, 250.7336, 126.7459, 90339051.0]
46 ['Jun 2012', 363433.0, 719507.0, 250.83, 126.6977, 91159891.0]
47 ['Jul 2012', 365565.0, 722629.0, 288.0068, 145.6975, 105285219.0]
48 ['Aug 2012', 371186.0, 733869.0, 251.7404, 127.3286, 93442522.0]
49 ['Sep 2012', 373372.0, 738510.0, 251.6258, 127.2156, 93950022.0]
50 ['Total', 360523.0, 716379.1667, 255.2629, 128.4629, 1104337614.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['New Jersey', '', '', '', '', '']
54 ['Oct 2011', 423026.0, 890859.0, 290.2082, 137.8059, 122765625.0]
55 ['Nov 2011', 392802.0, 808040.0, 279.5269, 135.8828, 109798725.0]
56 ['Dec 2011', 394530.0, 809026.0, 279.8642, 136.4787, 110414819.0]
57 ['Jan 2012', 393792.0, 800525.0, 268.6656, 132.1612, 105798351.0]
58 ['Feb 2012', 397667.0, 805529.0, 268.4508, 132.5266, 106754022.0]
59 ['Mar 2012', 405260.0, 818954.0, 269.5766, 133.4002, 109248621.0]
60 ['Apr 2012', 402351.0, 812224.0, 265.9954, 131.766, 107023501.0]
61 ['May 2012', 408526.0, 824550.0, 266.8319, 132.2027, 109007753.0]
62 ['Jun 2012', 411286.0, 829584.0, 266.093, 131.922, 109440339.0]
63 ['Jul 2012', 410460.0, 829379.0, 265.2791, 131.2867, 108886463.0]
64 ['Aug 2012', 417220.0, 842973.0, 266.7185, 132.0093, 111280298.0]
65 ['Sep 2012', 416790.0, 841960.0, 265.561, 131.4589, 110683177.0]
66 ['Total', 406142.5, 826133.5833, 271.0669, 133.2615, 1321101694.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Pennsylvania', '', '', '', '', '']
70 ['Oct 2011', 855467.0, 1785240.0, 290.9059, 139.3989, 248860431.0]
71 ['Nov 2011', 860770.0, 1793433.0, 269.5286, 129.362, 232002095.0]
72 ['Dec 2011', 865654.0, 1801249.0, 269.4217, 129.4801, 233225965.0]
73 ['Jan 2012', 872319.0, 1811363.0, 265.3631, 127.794, 231481292.0]
74 ['Feb 2012', 873717.0, 1811047.0, 264.9062, 127.8007, 231453021.0]
75 ['Mar 2012', 878156.0, 1816406.0, 261.9314, 126.6328, 230016640.0]
76 ['Apr 2012', 875857.0, 1809656.0, 260.0568, 125.8651, 227772583.0]
77 ['May 2012', 875251.0, 1806592.0, 261.6167, 126.7471, 228980259.0]
78 ['Jun 2012', 871271.0, 1795920.0, 261.6625, 126.9427, 227978942.0]
79 ['Jul 2012', 870350.0, 1793687.0, 261.097, 126.692, 227245754.0]
80 ['Aug 2012', 866429.0, 1784210.0, 263.0053, 127.7178, 227875443.0]
81 ['Sep 2012', 864645.0, 1781699.0, 261.3857, 126.8485, 226005799.0]
82 ['Total', 869157.1667, 1799208.5, 265.8608, 128.4314, 2772898224.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Puerto Rico', '', '', '', '', '']
86 [' No data found.', '', '', '', '', '']
87 ['', '', '', '', '', '']
88 ['', '', '', '', '', '']
89 ['Virginia', '', '', '', '', '']
90 ['Oct 2011', 428663.0, 896420.0, 268.684, 128.4832, 115174871.0]
91 ['Nov 2011', 432504.0, 902803.0, 268.4701, 128.6154, 116114383.0]
92 ['Dec 2011', 435978.0, 908527.0, 268.1527, 128.6793, 116908660.0]
93 ['Jan 2012', 438208.0, 911412.0, 264.3058, 127.0786, 115820925.0]
94 ['Feb 2012', 439966.0, 914445.0, 264.4258, 127.2229, 116338344.0]
95 ['Mar 2012', 440443.0, 914709.0, 265.4136, 127.7998, 116899582.0]
96 ['Apr 2012', 439751.0, 912926.0, 264.9521, 127.6259, 116512962.0]
97 ['May 2012', 440948.0, 914236.0, 264.7742, 127.7041, 116751669.0]
98 ['Jun 2012', 442920.0, 917816.0, 264.6197, 127.7003, 117205360.0]
99 ['Jul 2012', 443968.0, 919909.0, 268.0238, 129.3541, 118993981.0]
100 ['Aug 2012', 447913.0, 926872.0, 264.6253, 127.8808, 118529134.0]
101 ['Sep 2012', 447826.0, 926457.0, 264.5467, 127.8752, 118470902.0]
102 ['Total', 439924.0, 913877.6667, 265.9021, 128.0004, 1403720773.0]
103 ['', '', '', '', '', '']
104 ['', '', '', '', '', '']
105 ['Virgin Islands', '', '', '', '', '']
106 ['Oct 2011', 10016.0, 23836.0, 421.8653, 177.2698, 4225403.0]
107 ['Nov 2011', 10118.0, 24024.0, 421.9824, 177.723, 4269618.0]
108 ['Dec 2011', 10271.0, 24336.0, 420.0147, 177.2671, 4313971.0]
109 ['Jan 2012', 10247.0, 24270.0, 418.3257, 176.6206, 4286583.0]
110 ['Feb 2012', 10287.0, 24281.0, 417.4989, 176.8795, 4294811.0]
111 ['Mar 2012', 10440.0, 24492.0, 413.5281, 176.2711, 4317233.0]
112 ['Apr 2012', 10462.0, 24599.0, 414.7546, 176.3959, 4339163.0]
113 ['May 2012', 10687.0, 25040.0, 413.7289, 176.5783, 4421521.0]
114 ['Jun 2012', 10822.0, 25317.0, 415.0156, 177.4025, 4491299.0]
115 ['Jul 2012', 10983.0, 25663.0, 414.733, 177.4934, 4555013.0]
116 ['Aug 2012', 11134.0, 25930.0, 414.569, 178.0105, 4615811.0]
117 ['Sep 2012', 11244.0, 26137.0, 414.0198, 178.1092, 4655239.0]
118 ['Total', 10559.25, 24827.0833, 416.5831, 177.1777, 52785665.0]
119 ['', '', '', '', '', '']
120 ['', '', '', '', '', '']
121 ['West Virginia', '', '', '', '', '']
122 ['Oct 2011', 163339.0, 347064.0, 253.5558, 119.3312, 41415550.0]
123 ['Nov 2011', 163029.0, 346387.0, 254.7089, 119.8802, 41524943.0]
124 ['Dec 2011', 163192.0, 345833.0, 255.1252, 120.3887, 41634397.0]
125 ['Jan 2012', 164612.0, 347986.0, 252.4278, 119.4089, 41552641.0]
126 ['Feb 2012', 162805.0, 344066.0, 249.8651, 118.2311, 40679291.0]
127 ['Mar 2012', 162691.0, 342678.0, 250.222, 118.7963, 40708872.0]
128 ['Apr 2012', 161618.0, 340365.0, 246.202, 116.9059, 39790670.0]
129 ['May 2012', 161830.0, 341384.0, 245.8992, 116.5663, 39793862.0]
130 ['Jun 2012', 162148.0, 341853.0, 245.7793, 116.5782, 39852614.0]
131 ['Jul 2012', 170933.0, 362023.0, 301.8132, 142.5043, 51589842.0]
132 ['Aug 2012', 167257.0, 354395.0, 245.8515, 116.0298, 41120389.0]
133 ['Sep 2012', 164953.0, 347956.0, 246.9762, 117.0822, 40739464.0]
134 ['Total', 164033.9167, 346832.5, 254.217, 120.2316, 500402535.0]
135 ['', '', '', '', '', '']
136 ['', '', '', '', '', '']
137 ['MARO', '', '', '', '', '']
138 ['Oct 2011', 2379944.0, 4937715.0, 277.7421, 133.8698, 661010749.0]
139 ['Nov 2011', 2361232.0, 4871800.0, 267.8736, 129.8312, 632511726.0]
140 ['Dec 2011', 2373966.0, 4889283.0, 267.8268, 130.0419, 635811610.0]
141 ['Jan 2012', 2384847.0, 4894679.0, 262.4448, 127.8717, 625890700.0]
142 ['Feb 2012', 2390405.0, 4897332.0, 262.3741, 128.0657, 627180411.0]
143 ['Mar 2012', 2404317.0, 4915747.0, 261.6406, 127.9697, 629066829.0]
144 ['Apr 2012', 2396818.0, 4897379.0, 259.9181, 127.2061, 622976387.0]
145 ['May 2012', 2406639.0, 4913213.0, 260.7146, 127.7058, 627445921.0]
146 ['Jun 2012', 2411520.0, 4919558.0, 260.6182, 127.7525, 628486065.0]
147 ['Jul 2012', 2421924.0, 4942824.0, 270.6358, 132.6083, 655459291.0]
148 ['Aug 2012', 2433314.0, 4963537.0, 261.352, 128.1247, 635951594.0]
149 ['Sep 2012', 2430665.0, 4956888.0, 260.5605, 127.7687, 633335226.0]
150 ['Total', 2399632.5833, 4916662.9167, 264.4546, 129.07, 7615126509.0]
151 ['', '', '', '', '', '']
152 ['', '', '', '', '', '']
153 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
154 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [491]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,89,105,121,137]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MARO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,87,102,118,134,150]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [492]:
########################
#                      #
# SERO                 #
#                      #
########################

sheet = book.sheet_by_name('SERO')

In [493]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2012', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Alabama', '', '', '', '', '']
6 ['Oct 2011', 407776.0, 910034.0, 286.4335, 128.3476, 116800689.0]
7 ['Nov 2011', 411396.0, 916257.0, 285.0649, 127.9931, 117274558.0]
8 ['Dec 2011', 412474.0, 916345.0, 284.9663, 128.2718, 117541184.0]
9 ['Jan 2012', 411949.0, 913281.0, 279.4594, 126.0543, 115123001.0]
10 ['Feb 2012', 410562.0, 908268.0, 279.7578, 126.4582, 114857918.0]
11 ['Mar 2012', 409763.0, 905117.0, 279.7092, 126.6294, 114614465.0]
12 ['Apr 2012', 408935.0, 902277.0, 279.4322, 126.6458, 114269595.0]
13 ['May 2012', 411372.0, 906884.0, 278.9901, 126.5528, 114768703.0]
14 ['Jun 2012', 412350.0, 908345.0, 279.9946, 127.1056, 115455780.0]
15 ['Jul 2012', 413101.0, 909525.0, 280.7573, 127.5183, 115981124.0]
16 ['Aug 2012', 415804.0, 914441.0, 280.536, 127.5621, 116648002.0]
17 ['Sep 2012', 415459.0, 912152.0, 280.8381, 127.9137, 116676713.0]
18 ['Total', 411745.0833, 910243.8333, 281.3253, 127.2564, 1390011732.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Florida', '', '', '', '', '']
22 ['Oct 2011', 1750037.0, 3225957.0, 258.866, 140.4312, 453025155.0]
23 ['Nov 2011', 1769675.0, 3260561.0, 257.9135, 139.983, 456422989.0]
24 ['Dec 2011', 1791776.0, 3297834.0, 257.3964, 139.8484, 461196693.0]
25 ['Jan 2012', 1793619.0, 3293516.0, 255.5302, 139.1594, 458323755.0]
26 ['Feb 2012', 1799179.0, 3302790.0, 254.5985, 138.6913, 458068281.0]
27 ['Mar 2012', 1824243.0, 3346145.0, 254.4283, 138.7086, 464138995.0]
28 ['Apr 2012', 1823623.0, 3343861.0, 252.9738, 137.9629, 461328881.0]
29 ['May 2012', 1844224.0, 3384489.0, 253.6374, 138.2082, 467764148.0]
30 ['Jun 2012', 1864183.0, 3419492.0, 252.7886, 137.8112, 471244240.0]
31 ['Jul 2012', 1866562.0, 3426193.0, 254.7132, 138.7657, 475437914.0]
32 ['Aug 2012', 1886839.0, 3461158.0, 255.3148, 139.184, 481737976.0]
33 ['Sep 2012', 1895801.0, 3474773.0, 255.0542, 139.155, 483532067.0]
34 ['Total', 1825813.4167, 3353064.0833, 255.2388, 138.9829, 5592221094.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Georgia', '', '', '', '', '']
38 ['Oct 2011', 848975.0, 1870781.0, 300.2595, 136.2601, 254912823.0]
39 ['Nov 2011', 855332.0, 1880277.0, 300.0844, 136.5074, 256671752.0]
40 ['Dec 2011', 860213.0, 1885046.0, 299.4259, 136.6386, 257570032.0]
41 ['Jan 2012', 866679.0, 1891322.0, 294.7053, 135.0457, 255414902.0]
42 ['Feb 2012', 867139.0, 1891077.0, 295.8769, 135.6721, 256566395.0]
43 ['Mar 2012', 873090.0, 1898349.0, 295.0394, 135.6947, 257595907.0]
44 ['Apr 2012', 876786.0, 1905267.0, 294.8575, 135.6907, 258526967.0]
45 ['May 2012', 886339.0, 1923169.0, 294.5319, 135.7422, 261055129.0]
46 ['Jun 2012', 894789.0, 1936525.0, 293.3299, 135.5358, 262468377.0]
47 ['Jul 2012', 908470.0, 1959113.0, 291.5868, 135.2131, 264897823.0]
48 ['Aug 2012', 908747.0, 1959837.0, 294.2082, 136.4199, 267360845.0]
49 ['Sep 2012', 907360.0, 1953302.0, 293.5935, 136.3819, 266394955.0]
50 ['Total', 879493.25, 1912838.75, 295.5713, 135.8991, 3119435907.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Kentucky', '', '', '', '', '']
54 ['Oct 2011', 395614.0, 842885.0, 272.0797, 127.7025, 107638526.0]
55 ['Nov 2011', 396398.0, 841996.0, 270.8501, 127.5118, 107364439.0]
56 ['Dec 2011', 398157.0, 844144.0, 270.2052, 127.4476, 107584093.0]
57 ['Jan 2012', 401866.0, 849312.0, 266.2811, 125.9953, 107009323.0]
58 ['Feb 2012', 397633.0, 840590.0, 268.2302, 126.8837, 106657178.0]
59 ['Mar 2012', 401389.0, 846211.0, 271.732, 128.8925, 109070255.0]
60 ['Apr 2012', 401340.0, 844461.0, 266.6334, 126.7206, 107010636.0]
61 ['May 2012', 403614.0, 847901.0, 266.8387, 127.0194, 107699851.0]
62 ['Jun 2012', 406689.0, 853820.0, 267.425, 127.3791, 108758807.0]
63 ['Jul 2012', 408752.0, 857677.0, 268.9621, 128.182, 109938789.0]
64 ['Aug 2012', 410475.0, 861376.0, 267.8065, 127.6189, 109927882.0]
65 ['Sep 2012', 410877.0, 860599.0, 267.6025, 127.7618, 109951696.0]
66 ['Total', 402733.6667, 849247.6667, 268.7077, 127.4276, 1298611475.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Mississippi', '', '', '', '', '']
70 ['Oct 2011', 286026.0, 645220.0, 278.8081, 123.5956, 79746378.0]
71 ['Nov 2011', 288095.0, 647215.0, 277.3259, 123.4462, 79896213.0]
72 ['Dec 2011', 291330.0, 651696.0, 275.75, 123.2695, 80334244.0]
73 ['Jan 2012', 291881.0, 650774.0, 270.3609, 121.2605, 78913202.0]
74 ['Feb 2012', 292747.0, 651171.0, 271.7489, 122.1702, 79553681.0]
75 ['Mar 2012', 293780.0, 651812.0, 270.8832, 122.0905, 79580065.0]
76 ['Apr 2012', 293957.0, 651721.0, 271.1866, 122.318, 79717195.0]
77 ['May 2012', 295218.0, 654029.0, 271.868, 122.7168, 80260332.0]
78 ['Jun 2012', 297992.0, 659191.0, 272.3109, 123.1001, 81146459.0]
79 ['Jul 2012', 299116.0, 660743.0, 272.8534, 123.5198, 81614813.0]
80 ['Aug 2012', 302145.0, 666220.0, 273.1558, 123.882, 82532669.0]
81 ['Sep 2012', 325804.0, 728675.0, 296.9039, 132.7512, 96732465.0]
82 ['Total', 296507.5833, 659872.25, 275.4364, 123.7648, 980027716.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['North Carolina', '', '', '', '', '']
86 ['Oct 2011', 773629.0, 1655694.0, 262.0739, 122.455, 202747981.0]
87 ['Nov 2011', 776801.0, 1660154.0, 262.1569, 122.6656, 203643744.0]
88 ['Dec 2011', 778553.0, 1660591.0, 260.4955, 122.1309, 202809538.0]
89 ['Jan 2012', 780722.0, 1660464.0, 258.2792, 121.4385, 201644219.0]
90 ['Feb 2012', 780713.0, 1655362.0, 256.3486, 120.9009, 200134696.0]
91 ['Mar 2012', 780967.0, 1653501.0, 255.7618, 120.7992, 199741519.0]
92 ['Apr 2012', 779956.0, 1650483.0, 256.3222, 121.1282, 199920032.0]
93 ['May 2012', 781834.0, 1653436.0, 256.2833, 121.1846, 200371004.0]
94 ['Jun 2012', 791703.0, 1674350.0, 256.2801, 121.18, 202897715.0]
95 ['Jul 2012', 792793.0, 1687148.0, 257.1889, 120.8534, 203897528.0]
96 ['Aug 2012', 801851.0, 1706480.0, 257.19, 120.85, 206228062.0]
97 ['Sep 2012', 801341.0, 1705395.0, 257.1901, 120.85, 206096995.0]
98 ['Total', 785071.9167, 1668588.1667, 257.9523, 121.3667, 2430133033.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['South Carolina', '', '', '', '', '']
102 ['Oct 2011', 406281.0, 867258.0, 283.602, 132.8579, 115222119.0]
103 ['Nov 2011', 408780.0, 870438.0, 283.4687, 133.1242, 115876321.0]
104 ['Dec 2011', 408814.0, 869018.0, 280.3114, 131.8675, 114595241.0]
105 ['Jan 2012', 408109.0, 866362.0, 276.5369, 130.2656, 112857206.0]
106 ['Feb 2012', 407992.0, 865231.0, 277.1054, 130.6666, 113056767.0]
107 ['Mar 2012', 411540.0, 869859.0, 276.0233, 130.5897, 113594626.0]
108 ['Apr 2012', 410540.0, 868216.0, 275.8159, 130.4209, 113233469.0]
109 ['May 2012', 410947.0, 869916.0, 276.34, 130.5426, 113561082.0]
110 ['Jun 2012', 413965.0, 872149.0, 277.835, 131.8742, 115013965.0]
111 ['Jul 2012', 414481.0, 875828.0, 275.3753, 130.3199, 114137845.0]
112 ['Aug 2012', 413125.0, 873432.0, 278.7458, 131.8441, 115156852.0]
113 ['Sep 2012', 411316.0, 869900.0, 279.6621, 132.233, 115029507.0]
114 ['Total', 410490.8333, 869800.5833, 278.3933, 131.384, 1371335000.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['Tennessee', '', '', '', '', '']
118 ['Oct 2011', 619716.0, 1280908.0, 275.1077, 133.0998, 170488626.0]
119 ['Nov 2011', 624061.0, 1288645.0, 274.2732, 132.8242, 171163227.0]
120 ['Dec 2011', 625091.0, 1288879.0, 275.0304, 133.3865, 171918998.0]
121 ['Jan 2012', 634420.0, 1303369.0, 271.7441, 132.2725, 172399893.0]
122 ['Feb 2012', 635445.0, 1306650.0, 270.4369, 131.5178, 171847756.0]
123 ['Mar 2012', 642435.0, 1319476.0, 272.0546, 132.4597, 174777384.0]
124 ['Apr 2012', 642997.0, 1320324.0, 267.5885, 130.3154, 172058611.0]
125 ['May 2012', 650663.0, 1334012.0, 269.5757, 131.4853, 175402961.0]
126 ['Jun 2012', 655372.0, 1342885.0, 271.0014, 132.2576, 177606737.0]
127 ['Jul 2012', 655218.0, 1341252.0, 269.5351, 131.6712, 176604232.0]
128 ['Aug 2012', 657587.0, 1345085.0, 271.5104, 132.7364, 178541695.0]
129 ['Sep 2012', 651521.0, 1330238.0, 270.5099, 132.4898, 176242912.0]
130 ['Total', 641210.5, 1316810.25, 271.4986, 132.2041, 2089053032.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['SERO', '', '', '', '', '']
134 ['Oct 2011', 5488054.0, 11298737.0, 273.427, 132.8097, 1500582297.0]
135 ['Nov 2011', 5530538.0, 11365543.0, 272.7245, 132.7093, 1508313243.0]
136 ['Dec 2011', 5566408.0, 11413553.0, 271.9078, 132.6099, 1513550023.0]
137 ['Jan 2012', 5589245.0, 11428400.0, 268.6741, 131.3995, 1501685501.0]
138 ['Feb 2012', 5591410.0, 11421139.0, 268.4015, 131.4004, 1500742672.0]
139 ['Mar 2012', 5637207.0, 11490470.0, 268.4154, 131.6842, 1513113216.0]
140 ['Apr 2012', 5638134.0, 11486610.0, 267.1212, 131.1149, 1506065386.0]
141 ['May 2012', 5684211.0, 11573836.0, 267.5628, 131.407, 1520883210.0]
142 ['Jun 2012', 5737043.0, 11666757.0, 267.4883, 131.5354, 1534592080.0]
143 ['Jul 2012', 5758493.0, 11717479.0, 267.867, 131.6418, 1542510068.0]
144 ['Aug 2012', 5796573.0, 11788029.0, 268.8026, 132.1793, 1558133983.0]
145 ['Sep 2012', 5819479.0, 11835034.0, 269.8966, 132.7125, 1570657310.0]
146 ['Total', 5653066.25, 11540465.5833, 269.3351, 131.9331, 18270828989.0]
147 ['', '', '', '', '', '']
148 ['', '', '', '', '', '']
149 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
150 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [494]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117, 133]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SERO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114, 130,146]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [495]:
########################
#                      #
# MWRO                 #
#                      #
########################

sheet = book.sheet_by_name('MWRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2012', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Illinois', '', '', '', '', '']
6 ['Oct 2011', 887218.0, 1831037.0, 288.0598, 139.5776, 255571805.0]
7 ['Nov 2011', 897371.0, 1850593.0, 286.4907, 138.9222, 257088425.0]
8 ['Dec 2011', 910295.0, 1879585.0, 291.2919, 141.0745, 265161548.0]
9 ['Jan 2012', 887715.0, 1818122.0, 284.4113, 138.8665, 252476210.0]
10 ['Feb 2012', 892188.0, 1831898.0, 286.7357, 139.6487, 255822128.0]
11 ['Mar 2012', 904902.0, 1856202.0, 290.6359, 141.6855, 262996976.0]
12 ['Apr 2012', 892838.0, 1820124.0, 283.3162, 138.9771, 252955501.0]
13 ['May 2012', 907408.0, 1852926.0, 284.0408, 139.0994, 257740894.0]
14 ['Jun 2012', 918947.0, 1874051.0, 284.6151, 139.5619, 261546188.0]
15 ['Jul 2012', 932742.0, 1891581.0, 280.1075, 138.1215, 261268048.0]
16 ['Aug 2012', 964544.0, 1957192.0, 282.4211, 139.1829, 272407596.0]
17 ['Sep 2012', 975271.0, 1973243.0, 280.5927, 138.6823, 273653956.0]
18 ['Total', 914286.5833, 1869712.8333, 285.1667, 139.4461, 3128689275.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Indiana', '', '', '', '', '']
22 ['Oct 2011', 395327.0, 901967.0, 303.0897, 132.8425, 119819554.0]
23 ['Nov 2011', 395321.0, 900760.0, 302.1296, 132.5971, 119438184.0]
24 ['Dec 2011', 398604.0, 906446.0, 299.7329, 131.8057, 119474740.0]
25 ['Jan 2012', 400104.0, 909866.0, 298.5192, 131.2707, 119438744.0]
26 ['Feb 2012', 399169.0, 906552.0, 297.0872, 130.8121, 118588009.0]
27 ['Mar 2012', 400223.0, 906894.0, 296.8151, 130.988, 118792233.0]
28 ['Apr 2012', 398315.0, 901265.0, 297.1575, 131.3291, 118362308.0]
29 ['May 2012', 400506.0, 904686.0, 299.7332, 132.6924, 120044930.0]
30 ['Jun 2012', 402931.0, 908458.0, 297.4161, 131.9138, 119838160.0]
31 ['Jul 2012', 405247.0, 911977.0, 305.6536, 135.8205, 123865194.0]
32 ['Aug 2012', 410267.0, 922382.0, 303.4955, 134.992, 124514195.0]
33 ['Sep 2012', 410961.0, 923201.0, 297.4335, 132.4019, 122233556.0]
34 ['Total', 401414.5833, 908704.5, 299.8583, 132.4605, 1444409807.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Michigan', '', '', '', '', '']
38 ['Oct 2011', 948058.0, 1884542.0, 271.2246, 136.4451, 257136605.0]
39 ['Nov 2011', 933974.0, 1851697.0, 269.864, 136.1162, 252045969.0]
40 ['Dec 2011', 929610.0, 1843646.0, 271.2571, 136.7743, 252163319.0]
41 ['Jan 2012', 927375.0, 1838439.0, 267.7263, 135.0508, 248282687.0]
42 ['Feb 2012', 926802.0, 1834577.0, 269.3156, 136.0544, 249602254.0]
43 ['Mar 2012', 924674.0, 1828826.0, 268.5348, 135.7741, 248307170.0]
44 ['Apr 2012', 921081.0, 1820669.0, 268.7671, 135.9699, 247556270.0]
45 ['May 2012', 918360.0, 1813788.0, 268.9139, 136.1569, 246959784.0]
46 ['Jun 2012', 915811.0, 1806925.0, 268.0221, 135.8427, 245457607.0]
47 ['Jul 2012', 915142.0, 1805450.0, 267.0765, 135.3751, 244412950.0]
48 ['Aug 2012', 916797.0, 1806365.0, 267.1398, 135.5833, 244913003.0]
49 ['Sep 2012', 918035.0, 1805687.0, 265.2015, 134.8319, 243464289.0]
50 ['Total', 924643.25, 1828384.25, 268.5993, 135.835, 2980301907.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Minnesota', '', '', '', '', '']
54 ['Oct 2011', 259233.0, 531781.0, 238.0511, 116.0453, 61710693.0]
55 ['Nov 2011', 260572.0, 533562.0, 235.8291, 115.1702, 61450458.0]
56 ['Dec 2011', 262365.0, 536546.0, 237.0627, 115.921, 62196955.0]
57 ['Jan 2012', 262077.0, 535308.0, 236.4131, 115.7435, 61958424.0]
58 ['Feb 2012', 262431.0, 535455.0, 237.3399, 116.3223, 62285345.0]
59 ['Mar 2012', 265125.0, 539710.0, 237.9595, 116.8943, 63089020.0]
60 ['Apr 2012', 265114.0, 539415.0, 236.5591, 116.2651, 62715116.0]
61 ['May 2012', 267222.0, 542735.0, 234.9637, 115.6872, 62787472.0]
62 ['Jun 2012', 266971.0, 541786.0, 234.1156, 115.363, 62502069.0]
63 ['Jul 2012', 268103.0, 542945.0, 234.5926, 115.8404, 62894989.0]
64 ['Aug 2012', 269099.0, 544835.0, 234.5553, 115.849, 63118585.0]
65 ['Sep 2012', 268555.0, 542348.0, 233.9445, 115.8425, 62826955.0]
66 ['Total', 264738.9167, 538868.8333, 235.9356, 115.912, 749536081.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Ohio', '', '', '', '', '']
70 ['Oct 2011', 850986.0, 1766584.0, 291.969, 140.6452, 248461492.0]
71 ['Nov 2011', 861833.0, 1793380.0, 290.6265, 139.6645, 250471517.0]
72 ['Dec 2011', 873900.0, 1816920.0, 290.4571, 139.7037, 253830493.0]
73 ['Jan 2012', 879758.0, 1827815.0, 285.768, 137.5449, 251406663.0]
74 ['Feb 2012', 881517.0, 1830187.0, 284.8634, 137.2056, 251111934.0]
75 ['Mar 2012', 888212.0, 1842315.0, 285.9965, 137.8839, 254025535.0]
76 ['Apr 2012', 881745.0, 1824217.0, 281.7625, 136.1914, 248442667.0]
77 ['May 2012', 874097.0, 1803697.0, 282.7157, 137.008, 247120919.0]
78 ['Jun 2012', 869297.0, 1790955.0, 283.6304, 137.6691, 246559090.0]
79 ['Jul 2012', 888924.0, 1831862.0, 296.5638, 143.9097, 263622699.0]
80 ['Aug 2012', 869189.0, 1787919.0, 284.1836, 138.1546, 247009278.0]
81 ['Sep 2012', 866475.0, 1779101.0, 282.6037, 137.6364, 244869028.0]
82 ['Total', 873827.75, 1807912.6667, 286.7586, 138.6005, 3006931315.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Wisconsin', '', '', '', '', '']
86 ['Oct 2011', 391547.0, 828362.0, 242.0878, 114.4292, 94788770.0]
87 ['Nov 2011', 393511.0, 829732.0, 244.8285, 116.1131, 96342716.0]
88 ['Dec 2011', 393611.0, 828661.0, 247.4234, 117.5252, 97388591.0]
89 ['Jan 2012', 395520.0, 831423.0, 244.8591, 116.483, 96846663.0]
90 ['Feb 2012', 396960.0, 832935.0, 243.1395, 115.8754, 96516640.0]
91 ['Mar 2012', 397492.0, 832304.0, 244.0179, 116.5381, 96995154.0]
92 ['Apr 2012', 398356.0, 833234.0, 240.7923, 115.119, 95921039.0]
93 ['May 2012', 400305.0, 835789.0, 244.852, 117.273, 98015471.0]
94 ['Jun 2012', 401740.0, 837565.0, 244.9452, 117.4886, 98404300.0]
95 ['Jul 2012', 403677.0, 841062.0, 242.4275, 116.3558, 97862415.0]
96 ['Aug 2012', 407209.0, 846451.0, 245.8041, 118.251, 100093646.0]
97 ['Sep 2012', 407658.0, 846230.0, 241.849, 116.507, 98591691.0]
98 ['Total', 398965.5, 835312.3333, 243.9156, 116.5, 1167767096.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['MWRO', '', '', '', '', '']
102 ['Oct 2011', 3732369.0, 7744273.0, 277.9706, 133.9685, 1037488919.0]
103 ['Nov 2011', 3742582.0, 7759724.0, 277.038, 133.6178, 1036837269.0]
104 ['Dec 2011', 3768385.0, 7811804.0, 278.6912, 134.4396, 1050215646.0]
105 ['Jan 2012', 3752549.0, 7760973.0, 274.5892, 132.7681, 1030409391.0]
106 ['Feb 2012', 3759067.0, 7771604.0, 275.0487, 133.039, 1033926310.0]
107 ['Mar 2012', 3780628.0, 7806251.0, 276.1991, 133.7654, 1044206088.0]
108 ['Apr 2012', 3757449.0, 7738924.0, 273.0451, 132.5705, 1025952901.0]
109 ['May 2012', 3767898.0, 7753621.0, 274.0704, 133.1854, 1032669470.0]
110 ['Jun 2012', 3775697.0, 7759740.0, 273.9381, 133.2915, 1034307414.0]
111 ['Jul 2012', 3813835.0, 7824877.0, 276.3429, 134.6892, 1053926295.0]
112 ['Aug 2012', 3837105.0, 7865144.0, 274.1797, 133.7619, 1052056303.0]
113 ['Sep 2012', 3846955.0, 7869810.0, 271.8096, 132.8672, 1045639475.0]
114 ['Total', 3777876.5833, 7788895.4167, 275.2348, 133.4981, 12477635481.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
118 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [496]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MWRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [497]:
########################
#                      #
# SWRO                 #
#                      #
########################

sheet = book.sheet_by_name('SWRO ')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2012', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Arkansas', '', '', '', '', '']
6 ['Oct 2011', 218344.0, 501876.0, 282.8008, 123.0341, 61747866.0]
7 ['Nov 2011', 219652.0, 504060.0, 281.4481, 122.6454, 61820638.0]
8 ['Dec 2011', 221194.0, 507466.0, 280.9808, 122.4738, 62151272.0]
9 ['Jan 2012', 220964.0, 505812.0, 275.7322, 120.4536, 60926893.0]
10 ['Feb 2012', 219608.0, 501713.0, 276.8051, 121.1621, 60788625.0]
11 ['Mar 2012', 219366.0, 500233.0, 275.9818, 121.0256, 60541023.0]
12 ['Apr 2012', 218272.0, 496399.0, 276.1935, 121.4453, 60285313.0]
13 ['May 2012', 218332.0, 497114.0, 276.4151, 121.4012, 60350258.0]
14 ['Jun 2012', 220076.0, 500190.0, 275.6309, 121.2734, 60659737.0]
15 ['Jul 2012', 220675.0, 502287.0, 276.7859, 121.6032, 61079723.0]
16 ['Aug 2012', 222491.0, 504553.0, 276.9389, 122.1208, 61616409.0]
17 ['Sep 2012', 222166.0, 503794.0, 276.501, 121.933, 61429117.0]
18 ['Total', 220095.0, 502124.75, 277.6819, 121.7156, 733396874.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Louisiana', '', '', '', '', '']
22 ['Oct 2011', 406436.0, 916060.0, 295.0695, 130.916, 119926885.0]
23 ['Nov 2011', 405943.0, 914423.0, 294.6813, 130.8189, 119623823.0]
24 ['Dec 2011', 404879.0, 911130.0, 296.1347, 131.5934, 119898728.0]
25 ['Jan 2012', 397685.0, 894400.0, 290.5395, 129.1852, 115543210.0]
26 ['Feb 2012', 395505.0, 890395.0, 292.7991, 130.0586, 115803518.0]
27 ['Mar 2012', 397384.0, 892347.0, 292.0669, 130.0646, 116062725.0]
28 ['Apr 2012', 392175.0, 880069.0, 290.8793, 129.6212, 114075580.0]
29 ['May 2012', 396640.0, 890253.0, 292.2238, 130.1963, 115907665.0]
30 ['Jun 2012', 401943.0, 901586.0, 294.8581, 131.453, 118516169.0]
31 ['Jul 2012', 402526.0, 901593.0, 293.1697, 130.8888, 118008410.0]
32 ['Aug 2012', 408174.0, 913420.0, 292.411, 130.6678, 119354586.0]
33 ['Sep 2012', 662865.0, 1479423.0, 387.4656, 173.6065, 256837394.0]
34 ['Total', 422679.5833, 948758.25, 305.503, 136.1041, 1549558693.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['New Mexico', '', '', '', '', '']
38 ['Oct 2011', 189333.0, 432289.0, 294.1395, 128.8266, 55690323.0]
39 ['Nov 2011', 191080.0, 435482.0, 293.8403, 128.9307, 56147002.0]
40 ['Dec 2011', 192418.0, 437540.0, 293.2488, 128.9627, 56426342.0]
41 ['Jan 2012', 193122.0, 438455.0, 289.2651, 127.4098, 55863456.0]
42 ['Feb 2012', 192741.0, 437424.0, 290.6881, 128.0851, 56027506.0]
43 ['Mar 2012', 193647.0, 438145.0, 290.7883, 128.5197, 56310281.0]
44 ['Apr 2012', 193464.0, 437267.0, 289.3565, 128.0226, 55980072.0]
45 ['May 2012', 194333.0, 438911.0, 288.3623, 127.6758, 56038310.0]
46 ['Jun 2012', 195043.0, 440267.0, 288.9066, 127.9887, 56349201.0]
47 ['Jul 2012', 195163.0, 440019.0, 288.0933, 127.7789, 56225159.0]
48 ['Aug 2012', 196232.0, 442594.0, 287.9953, 127.6879, 56513887.0]
49 ['Sep 2012', 195683.0, 440628.0, 288.7089, 128.2157, 56495426.0]
50 ['Total', 193521.5833, 438251.75, 290.2635, 128.1735, 674066965.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Oklahoma', '', '', '', '', '']
54 ['Oct 2011', 280606.0, 624112.0, 287.33, 129.186, 80626523.0]
55 ['Nov 2011', 280772.0, 622996.0, 287.3055, 129.4829, 80667337.0]
56 ['Dec 2011', 281151.0, 622774.0, 286.1729, 129.1926, 80457795.0]
57 ['Jan 2012', 279767.0, 617178.0, 280.2494, 127.0372, 78404545.0]
58 ['Feb 2012', 278869.0, 613639.0, 281.9197, 128.1188, 78618670.0]
59 ['Mar 2012', 277693.0, 610392.0, 280.2328, 127.4897, 77818682.0]
60 ['Apr 2012', 276049.0, 604999.0, 279.8106, 127.672, 77241425.0]
61 ['May 2012', 276915.0, 606710.0, 280.6336, 128.087, 77711658.0]
62 ['Jun 2012', 278733.0, 610448.0, 280.2742, 127.9743, 78121673.0]
63 ['Jul 2012', 278312.0, 608952.0, 280.3041, 128.1086, 78011985.0]
64 ['Aug 2012', 282743.0, 618019.0, 281.7732, 128.9109, 79669410.0]
65 ['Sep 2012', 284176.0, 619146.0, 280.9873, 128.9677, 79849852.0]
66 ['Total', 279648.8333, 614947.0833, 282.2586, 128.3579, 947199555.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Texas', '', '', '', '', '']
70 ['Oct 2011', 1709297.0, 4174348.0, 303.1823, 124.146, 518228545.0]
71 ['Nov 2011', 1709575.0, 4172512.0, 301.3235, 123.4592, 515135058.0]
72 ['Dec 2011', 1714209.0, 4179010.0, 299.5137, 122.859, 513429165.0]
73 ['Jan 2012', 1703288.0, 4141317.0, 298.6063, 122.8142, 508612529.0]
74 ['Feb 2012', 1664358.0, 4043923.0, 305.1426, 125.5876, 507866533.0]
75 ['Mar 2012', 1623276.0, 3913693.0, 298.8603, 123.9578, 485132798.0]
76 ['Apr 2012', 1627640.0, 3936704.0, 298.5643, 123.4421, 485955174.0]
77 ['May 2012', 1639624.0, 3967242.0, 301.8608, 124.7562, 494938142.0]
78 ['Jun 2012', 1637730.0, 3951184.0, 299.8281, 124.276, 491037503.0]
79 ['Jul 2012', 1647439.0, 3976675.0, 301.2981, 124.8204, 496370312.0]
80 ['Aug 2012', 1657338.0, 3998108.0, 301.3467, 124.9174, 499433378.0]
81 ['Sep 2012', 1662567.0, 4006566.0, 295.0832, 122.4479, 490595512.0]
82 ['Total', 1666361.75, 4038440.1667, 300.3917, 123.9491, 6006734649.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['SWRO', '', '', '', '', '']
86 ['Oct 2011', 2804016.0, 6648685.0, 298.2223, 125.7723, 836220142.0]
87 ['Nov 2011', 2807022.0, 6649473.0, 296.8961, 125.3323, 833393858.0]
88 ['Dec 2011', 2813851.0, 6657920.0, 295.8093, 125.0185, 832363302.0]
89 ['Jan 2012', 2794826.0, 6597162.0, 293.167, 124.1974, 819350633.0]
90 ['Feb 2012', 2751081.0, 6487094.0, 297.7393, 126.2668, 819104852.0]
91 ['Mar 2012', 2711366.0, 6354810.0, 293.5294, 125.2383, 795865509.0]
92 ['Apr 2012', 2707600.0, 6355438.0, 293.0778, 124.8596, 793537564.0]
93 ['May 2012', 2725844.0, 6400230.0, 295.3016, 125.7683, 804946033.0]
94 ['Jun 2012', 2733525.0, 6403675.0, 294.376, 125.6598, 804684283.0]
95 ['Jul 2012', 2744115.0, 6429526.0, 295.0662, 125.9339, 809695589.0]
96 ['Aug 2012', 2766978.0, 6476694.0, 295.119, 126.0809, 816587670.0]
97 ['Sep 2012', 3027457.0, 7049557.0, 312.2116, 134.0804, 945207301.0]
98 ['Total', 2782306.75, 6542522.0, 296.8447, 126.2377, 9910956736.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
102 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [498]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SWRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [499]:
########################
#                      #
# MPRO                 #
#                      #
########################
sheet = book.sheet_by_name('MPRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2012', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Colorado', '', '', '', '', '']
6 ['Oct 2011', 213701.0, 480566.0, 313.4946, 139.4067, 66994114.0]
7 ['Nov 2011', 214517.0, 481440.0, 310.1191, 138.1809, 66525829.0]
8 ['Dec 2011', 218232.0, 488527.0, 310.2382, 138.5878, 67703899.0]
9 ['Jan 2012', 220219.0, 491483.0, 308.139, 138.068, 67858070.0]
10 ['Feb 2012', 219187.0, 488691.0, 306.1746, 137.325, 67109497.0]
11 ['Mar 2012', 223002.0, 496109.0, 308.4323, 138.641, 68781028.0]
12 ['Apr 2012', 220983.0, 491333.0, 301.4356, 135.5743, 66612141.0]
13 ['May 2012', 222073.0, 493638.0, 302.5259, 136.0974, 67182842.0]
14 ['Jun 2012', 222620.0, 494316.0, 301.6822, 135.8655, 67160488.0]
15 ['Jul 2012', 223860.0, 496559.0, 301.5085, 135.9268, 67495694.0]
16 ['Aug 2012', 225249.0, 499273.0, 301.387, 135.972, 67887126.0]
17 ['Sep 2012', 224845.0, 497621.0, 298.8488, 135.0318, 67194663.0]
18 ['Total', 220707.3333, 491629.6667, 305.2706, 137.0451, 808505391.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Iowa', '', '', '', '', '']
22 ['Oct 2011', 184833.0, 398574.0, 265.6445, 123.1889, 49099879.0]
23 ['Nov 2011', 185479.0, 399430.0, 263.984, 122.5834, 48963484.0]
24 ['Dec 2011', 187775.0, 403116.0, 262.5101, 122.2795, 49292837.0]
25 ['Jan 2012', 187849.0, 402829.0, 258.0084, 120.3156, 48466611.0]
26 ['Feb 2012', 189240.0, 405317.0, 259.8121, 121.3047, 49166837.0]
27 ['Mar 2012', 191043.0, 408614.0, 258.6646, 120.9358, 49416070.0]
28 ['Apr 2012', 191574.0, 409261.0, 258.0357, 120.7858, 49432927.0]
29 ['May 2012', 192483.0, 410761.0, 257.7153, 120.7656, 49605810.0]
30 ['Jun 2012', 193588.0, 412889.0, 257.178, 120.581, 49786583.0]
31 ['Jul 2012', 193407.0, 412187.0, 257.2518, 120.7081, 49754294.0]
32 ['Aug 2012', 195154.0, 415718.0, 256.8465, 120.5736, 50124630.0]
33 ['Sep 2012', 196222.0, 417898.0, 256.5143, 120.4451, 50333753.0]
34 ['Total', 190720.5833, 408049.5, 259.2989, 121.1952, 593443715.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Kansas', '', '', '', '', '']
38 ['Oct 2011', 141760.0, 302633.0, 270.0099, 126.4786, 38276609.0]
39 ['Nov 2011', 140216.0, 298842.0, 269.441, 126.4211, 37779942.0]
40 ['Dec 2011', 140624.0, 299591.0, 268.4782, 126.0201, 37754473.0]
41 ['Jan 2012', 141649.0, 302020.0, 261.8828, 122.8245, 37095443.0]
42 ['Feb 2012', 141043.0, 299661.0, 265.3634, 124.9, 37427657.0]
43 ['Mar 2012', 142064.0, 301567.0, 263.2012, 123.9904, 37391419.0]
44 ['Apr 2012', 142801.0, 303106.0, 264.0003, 124.3773, 37699505.0]
45 ['May 2012', 143374.0, 304240.0, 264.8667, 124.8192, 37974998.0]
46 ['Jun 2012', 144918.0, 307886.0, 265.0569, 124.7589, 38411522.0]
47 ['Jul 2012', 145699.0, 309715.0, 266.2982, 125.2745, 38799387.0]
48 ['Aug 2012', 146895.0, 312630.0, 268.4055, 126.1153, 39427420.0]
49 ['Sep 2012', 147855.0, 314742.0, 266.7519, 125.3109, 39440597.0]
50 ['Total', 143241.5, 304719.4167, 266.1467, 125.1093, 457478972.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Missouri', '', '', '', '', '']
54 ['Oct 2011', 440881.0, 950725.0, 274.5707, 127.3271, 121053018.0]
55 ['Nov 2011', 444191.0, 955724.0, 277.6351, 129.0362, 123323032.0]
56 ['Dec 2011', 447561.0, 961801.0, 276.882, 128.8433, 123921589.0]
57 ['Jan 2012', 444230.0, 955681.0, 272.8883, 126.8469, 121225170.0]
58 ['Feb 2012', 441023.0, 948760.0, 279.4916, 129.9193, 123262228.0]
59 ['Mar 2012', 442477.0, 950350.0, 274.6255, 127.8639, 121515489.0]
60 ['Apr 2012', 440349.0, 945233.0, 275.2254, 128.2173, 121195215.0]
61 ['May 2012', 440185.0, 944058.0, 278.6678, 129.9342, 122665396.0]
62 ['Jun 2012', 440673.0, 943835.0, 274.674, 128.2443, 121041437.0]
63 ['Jul 2012', 438697.0, 938829.0, 273.3125, 127.7138, 119901381.0]
64 ['Aug 2012', 439685.0, 940597.0, 278.21, 130.0501, 122324765.0]
65 ['Sep 2012', 439559.0, 939070.0, 274.4738, 128.4754, 120647416.0]
66 ['Total', 441625.9167, 947888.5833, 275.8889, 128.538, 1462076136.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Montana', '', '', '', '', '']
70 ['Oct 2011', 58271.0, 121992.0, 278.5124, 133.0349, 16229197.0]
71 ['Nov 2011', 58724.0, 126259.0, 277.6697, 129.1462, 16305876.0]
72 ['Dec 2011', 59117.0, 127185.0, 277.7311, 129.0925, 16418631.0]
73 ['Jan 2012', 59165.0, 127111.0, 274.9585, 127.982, 16267917.0]
74 ['Feb 2012', 59430.0, 127385.0, 273.6273, 127.6577, 16261671.0]
75 ['Mar 2012', 59669.0, 127558.0, 275.3529, 128.8044, 16430033.0]
76 ['Apr 2012', 59275.0, 126536.0, 268.973, 125.9987, 15943377.0]
77 ['May 2012', 59209.0, 126351.0, 269.1612, 126.1309, 15936768.0]
78 ['Jun 2012', 59138.0, 126048.0, 268.2598, 125.8596, 15864346.0]
79 ['Jul 2012', 58629.0, 124902.0, 271.9383, 127.6479, 15943473.0]
80 ['Aug 2012', 58811.0, 125226.0, 268.7347, 126.2083, 15804557.0]
81 ['Sep 2012', 58414.0, 123931.0, 267.1518, 125.9201, 15605408.0]
82 ['Total', 58987.6667, 125873.6667, 272.6718, 127.7811, 193011254.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Nebraska', '', '', '', '', '']
86 ['Oct 2011', 76294.0, 174941.0, 282.6125, 123.2509, 21561640.0]
87 ['Nov 2011', 75380.0, 173170.0, 282.3505, 122.9057, 21283577.0]
88 ['Dec 2011', 76225.0, 175414.0, 284.5251, 123.6385, 21687926.0]
89 ['Jan 2012', 76641.0, 175711.0, 278.0438, 121.2762, 21309557.0]
90 ['Feb 2012', 77572.0, 177832.0, 281.2589, 122.6878, 21817812.0]
91 ['Mar 2012', 78331.0, 178643.0, 279.4208, 122.5198, 21887312.0]
92 ['Apr 2012', 77148.0, 175613.0, 273.156, 119.9993, 21073436.0]
93 ['May 2012', 77401.0, 176177.0, 277.1116, 121.7453, 21448714.0]
94 ['Jun 2012', 77260.0, 175930.0, 279.3335, 122.6699, 21581309.0]
95 ['Jul 2012', 77485.0, 176193.0, 279.4422, 122.8912, 21652575.0]
96 ['Aug 2012', 78049.0, 177958.0, 278.4256, 122.1122, 21730841.0]
97 ['Sep 2012', 77009.0, 175296.0, 281.0053, 123.448, 21639935.0]
98 ['Total', 77066.25, 176073.1667, 279.7102, 122.4276, 258674634.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['North Dakota', '', '', '', '', '']
102 ['Oct 2011', 27292.0, 59383.0, 283.7123, 130.3921, 7743075.0]
103 ['Nov 2011', 27380.0, 59334.0, 282.5326, 130.3762, 7735743.0]
104 ['Dec 2011', 27549.0, 59600.0, 281.0502, 129.9103, 7742652.0]
105 ['Jan 2012', 27446.0, 59501.0, 278.5879, 128.5041, 7646123.0]
106 ['Feb 2012', 27375.0, 59195.0, 280.1977, 129.5787, 7670412.0]
107 ['Mar 2012', 27355.0, 59134.0, 279.1076, 129.1134, 7634989.0]
108 ['Apr 2012', 27143.0, 58575.0, 274.285, 127.1006, 7444918.0]
109 ['May 2012', 27181.0, 58379.0, 273.6212, 127.3968, 7437297.0]
110 ['Jun 2012', 27122.0, 58243.0, 273.157, 127.2009, 7408563.0]
111 ['Jul 2012', 27058.0, 57901.0, 273.018, 127.5854, 7387321.0]
112 ['Aug 2012', 27260.0, 58400.0, 272.7078, 127.2948, 7434015.0]
113 ['Sep 2012', 27061.0, 57911.0, 273.1831, 127.6547, 7392609.0]
114 ['Total', 27268.5, 58796.3333, 277.1138, 128.5195, 90677717.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['South Dakota', '', '', '', '', '']
118 ['Oct 2011', 44718.0, 103282.0, 307.1854, 133.002, 13736715.0]
119 ['Nov 2011', 44847.0, 103336.0, 304.6138, 132.2, 13661017.0]
120 ['Dec 2011', 45156.0, 104007.0, 307.3313, 133.4319, 13877853.0]
121 ['Jan 2012', 45594.0, 104704.0, 305.3322, 132.9588, 13921316.0]
122 ['Feb 2012', 45420.0, 104084.0, 302.517, 132.0118, 13740321.0]
123 ['Mar 2012', 45259.0, 103909.0, 306.0219, 133.2921, 13850247.0]
124 ['Apr 2012', 45034.0, 103632.0, 306.0928, 133.0147, 13784582.0]
125 ['May 2012', 44912.0, 103349.0, 306.3926, 133.1479, 13760704.0]
126 ['Jun 2012', 45057.0, 103914.0, 307.0722, 133.1462, 13835754.0]
127 ['Jul 2012', 45032.0, 103934.0, 306.3984, 132.7548, 13797735.0]
128 ['Aug 2012', 45266.0, 104501.0, 306.2482, 132.6555, 13862631.0]
129 ['Sep 2012', 45034.0, 103498.0, 303.3209, 131.9809, 13659755.0]
130 ['Total', 45110.75, 103845.8333, 305.708, 132.7999, 165488630.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['Utah', '', '', '', '', '']
134 ['Oct 2011', 116318.0, 285695.0, 295.7307, 120.4039, 34398805.0]
135 ['Nov 2011', 115386.0, 283184.0, 296.3135, 120.7357, 34190431.0]
136 ['Dec 2011', 116504.0, 285824.0, 293.7154, 119.7206, 34219019.0]
137 ['Jan 2012', 116914.0, 285527.0, 291.5129, 119.3651, 34081945.0]
138 ['Feb 2012', 117110.0, 287651.0, 293.6818, 119.5653, 34393077.0]
139 ['Mar 2012', 117272.0, 285742.0, 292.7427, 120.1452, 34330526.0]
140 ['Apr 2012', 115217.0, 280865.0, 293.2448, 120.2955, 33786790.0]
141 ['May 2012', 114431.0, 279523.0, 294.0874, 120.3934, 33652720.0]
142 ['Jun 2012', 112716.0, 275698.0, 295.1498, 120.6687, 33268107.0]
143 ['Jul 2012', 105884.0, 257736.0, 308.5386, 126.7549, 32669300.0]
144 ['Aug 2012', 105918.0, 258520.0, 310.8602, 127.3623, 32925690.0]
145 ['Sep 2012', 105375.0, 256715.0, 309.6151, 127.0891, 32625690.0]
146 ['Total', 113253.75, 276890.0, 297.6664, 121.7517, 404542100.0]
147 ['', '', '', '', '', '']
148 ['', '', '', '', '', '']
149 ['Wyoming', '', '', '', '', '']
150 ['Oct 2011', 14431.0, 33252.0, 285.0644, 123.7148, 4113764.0]
151 ['Nov 2011', 14728.0, 33936.0, 287.0268, 124.5677, 4227330.0]
152 ['Dec 2011', 14945.0, 34476.0, 289.0954, 125.32, 4320531.0]
153 ['Jan 2012', 15213.0, 35104.0, 288.2457, 124.9169, 4385082.0]
154 ['Feb 2012', 15019.0, 34467.0, 288.0832, 125.5323, 4326721.0]
155 ['Mar 2012', 15284.0, 35058.0, 291.8678, 127.2437, 4460908.0]
156 ['Apr 2012', 14921.0, 34131.0, 289.5521, 126.5831, 4320407.0]
157 ['May 2012', 14773.0, 33827.0, 288.2731, 125.8952, 4258658.0]
158 ['Jun 2012', 14892.0, 34184.0, 289.7229, 126.2156, 4314554.0]
159 ['Jul 2012', 14876.0, 34223.0, 287.8558, 125.1247, 4282143.0]
160 ['Aug 2012', 14799.0, 33863.0, 287.538, 125.6615, 4255275.0]
161 ['Sep 2012', 15477.0, 35642.0, 291.0244, 126.373, 4504185.0]
162 ['Total', 14946.5, 34346.9167, 288.6381, 125.6046, 51769558.0]
163 ['', '', '', '', '', '']
164 ['', '', '', '', '', '']
165 ['MPRO', '', '', '', '', '']
166 ['Oct 2011', 1318499.0, 2911043.0, 283.0543, 128.2038, 373206816.0]
167 ['Nov 2011', 1320848.0, 2914655.0, 283.1486, 128.3158, 373996261.0]
168 ['Dec 2011', 1333688.0, 2939541.0, 282.6294, 128.2307, 376939410.0]
169 ['Jan 2012', 1334920.0, 2939671.0, 278.8611, 126.6323, 372257234.0]
170 ['Feb 2012', 1332419.0, 2933043.0, 281.5753, 127.9136, 375176233.0]
171 ['Mar 2012', 1341756.0, 2946684.0, 280.0047, 127.4986, 375698021.0]
172 ['Apr 2012', 1334445.0, 2928285.0, 278.238, 126.7955, 371293298.0]
173 ['May 2012', 1336022.0, 2930303.0, 279.8786, 127.6059, 373923907.0]
174 ['Jun 2012', 1337984.0, 2932943.0, 278.533, 127.0644, 372672663.0]
175 ['Jul 2012', 1330627.0, 2912179.0, 279.3294, 127.6307, 371683303.0]
176 ['Aug 2012', 1337086.0, 2926686.0, 281.0417, 128.3967, 375776950.0]
177 ['Sep 2012', 1336851.0, 2922324.0, 279.0468, 127.6532, 373044011.0]
178 ['Total', 1332928.75, 2928113.0833, 280.4394, 127.6609, 4485668107.0]
179 ['', '', '', '', '', '']
180 ['', '', '', '', '', '']
181 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
182 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [500]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117, 133, 149,165]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MPRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114, 130,146, 162, 178]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [501]:

########################
#                      #
# WRO                  #
#                      #
########################
sheet = book.sheet_by_name('WRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2012', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Alaska', '', '', '', '', '']
6 ['Oct 2011', 31529.0, 74792.0, 399.3719, 168.3575, 12591797.0]
7 ['Nov 2011', 36904.0, 88790.0, 406.6397, 169.0126, 15006630.0]
8 ['Dec 2011', 37546.0, 90639.0, 408.9364, 169.3965, 15353925.0]
9 ['Jan 2012', 38170.0, 92220.0, 407.0085, 168.4614, 15535514.0]
10 ['Feb 2012', 38565.0, 93199.0, 411.0755, 170.0997, 15853126.0]
11 ['Mar 2012', 38977.0, 94092.0, 410.8855, 170.2067, 16015085.0]
12 ['Apr 2012', 39600.0, 95420.0, 408.5578, 169.5545, 16178887.0]
13 ['May 2012', 39229.0, 94749.0, 409.9779, 169.7435, 16083023.0]
14 ['Jun 2012', 39223.0, 94298.0, 411.3165, 171.086, 16133067.0]
15 ['Jul 2012', 38729.0, 93031.0, 413.7682, 172.2526, 16024828.0]
16 ['Aug 2012', 38757.0, 93002.0, 412.4068, 171.8635, 15983651.0]
17 ['Sep 2012', 38191.0, 91340.0, 407.5721, 170.4137, 15565586.0]
18 ['Total', 37951.6667, 91297.6667, 409.1281, 170.0711, 186325119.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['American Samoa', '', '', '', '', '']
22 [' No data found.', '', '', '', '', '']
23 ['', '', '', '', '', '']
24 ['', '', '', '', '', '']
25 ['Arizona', '', '', '', '', '']
26 ['Oct 2011', 490485.0, 1138220.0, 295.266, 127.2369, 144823557.0]
27 ['Nov 2011', 489396.0, 1136565.0, 295.003, 127.026, 144373287.0]
28 ['Dec 2011', 490227.0, 1137378.0, 294.6832, 127.0129, 144461672.0]
29 ['Jan 2012', 488528.0, 1131693.0, 293.7805, 126.8189, 143520018.0]
30 ['Feb 2012', 482617.0, 1118039.0, 291.2802, 125.7351, 140576783.0]
31 ['Mar 2012', 483395.0, 1118247.0, 291.7986, 126.1385, 141053981.0]
32 ['Apr 2012', 480166.0, 1112064.0, 292.2096, 126.17, 140309134.0]
33 ['May 2012', 480043.0, 1110833.0, 292.0704, 126.2173, 140206353.0]
34 ['Jun 2012', 481901.0, 1116483.0, 292.2686, 126.1502, 140844538.0]
35 ['Jul 2012', 482485.0, 1119607.0, 294.1911, 126.7791, 141942811.0]
36 ['Aug 2012', 486306.0, 1127702.0, 293.8163, 126.7043, 142884652.0]
37 ['Sep 2012', 483317.0, 1120861.0, 292.985, 126.3356, 141604651.0]
38 ['Total', 484905.5, 1123974.3333, 293.2876, 126.5303, 1706601437.0]
39 ['', '', '', '', '', '']
40 ['', '', '', '', '', '']
41 ['California', '', '', '', '', '']
42 ['Oct 2011', 1720236.0, 3867094.0, 338.7136, 150.6732, 582667257.0]
43 ['Nov 2011', 1722785.0, 3875258.0, 336.8845, 149.7654, 580379534.0]
44 ['Dec 2011', 1738884.0, 3904099.0, 331.4923, 147.6465, 576426618.0]
45 ['Jan 2012', 1751440.0, 3917804.0, 333.1594, 148.9377, 583508744.0]
46 ['Feb 2012', 1750085.0, 3925017.0, 334.2405, 149.031, 584949255.0]
47 ['Mar 2012', 1774677.0, 3961829.0, 333.8055, 149.5261, 592396971.0]
48 ['Apr 2012', 1776742.0, 3956504.0, 331.243, 148.7509, 588533434.0]
49 ['May 2012', 1791393.0, 3980231.0, 330.4908, 148.7448, 592038845.0]
50 ['Jun 2012', 1804088.0, 4011628.0, 331.051, 148.8785, 597245060.0]
51 ['Jul 2012', 1827008.0, 4034260.0, 328.7292, 148.8726, 600590809.0]
52 ['Aug 2012', 1844039.0, 4062422.0, 328.4557, 149.0946, 605685175.0]
53 ['Sep 2012', 1849513.0, 4074501.0, 327.5455, 148.6807, 605799655.0]
54 ['Total', 1779240.8333, 3964220.5833, 332.0808, 149.0461, 7090221357.0]
55 ['', '', '', '', '', '']
56 ['', '', '', '', '', '']
57 ['Guam', '', '', '', '', '']
58 ['Oct 2011', 13707.0, 42951.0, 677.0347, 216.0628, 9280114.0]
59 ['Nov 2011', 14038.0, 43521.0, 667.0942, 215.1759, 9364669.0]
60 ['Dec 2011', 14229.0, 43954.0, 661.8561, 214.2592, 9417550.0]
61 ['Jan 2012', 14201.0, 43769.0, 655.605, 212.7133, 9310247.0]
62 ['Feb 2012', 14208.0, 43719.0, 658.1565, 213.8907, 9351088.0]
63 ['Mar 2012', 14129.0, 43258.0, 664.4184, 217.0135, 9387568.0]
64 ['Apr 2012', 14199.0, 43190.0, 667.9123, 219.5806, 9483687.0]
65 ['May 2012', 14301.0, 43277.0, 662.8585, 219.0434, 9479540.0]
66 ['Jun 2012', 14442.0, 43824.0, 657.4501, 216.6597, 9494895.0]
67 ['Jul 2012', 14493.0, 43973.0, 655.5703, 216.0685, 9501180.0]
68 ['Aug 2012', 14541.0, 44244.0, 660.6489, 217.1254, 9606496.0]
69 ['Sep 2012', 14809.0, 45043.0, 649.9096, 213.6739, 9624512.0]
70 ['Total', 14274.75, 43726.9167, 661.4333, 215.9264, 113301546.0]
71 ['', '', '', '', '', '']
72 ['', '', '', '', '', '']
73 ['Hawaii', '', '', '', '', '']
74 ['Oct 2011', 84635.0, 169405.0, 434.3719, 217.0129, 36763066.0]
75 ['Nov 2011', 85563.0, 171436.0, 432.8011, 216.0092, 37031757.0]
76 ['Dec 2011', 83949.0, 173143.0, 444.5183, 215.5263, 37316870.0]
77 ['Jan 2012', 85905.0, 173786.0, 429.5695, 212.3426, 36902168.0]
78 ['Feb 2012', 87863.0, 175291.0, 424.0743, 212.5634, 37260443.0]
79 ['Mar 2012', 88699.0, 176729.0, 423.8805, 212.7425, 37597778.0]
80 ['Apr 2012', 88587.0, 176160.0, 423.0295, 212.7322, 37474912.0]
81 ['May 2012', 89619.0, 177887.0, 423.3645, 213.2899, 37941501.0]
82 ['Jun 2012', 90534.0, 179700.0, 422.7974, 213.008, 38277543.0]
83 ['Jul 2012', 91056.0, 180733.0, 423.4023, 213.3164, 38553321.0]
84 ['Aug 2012', 92114.0, 182867.0, 422.9445, 213.0462, 38959113.0]
85 ['Sep 2012', 92932.0, 184734.0, 422.3809, 212.4823, 39252702.0]
86 ['Total', 88454.6667, 176822.5833, 427.0843, 213.6469, 453331174.0]
87 ['', '', '', '', '', '']
88 ['', '', '', '', '', '']
89 ['Idaho', '', '', '', '', '']
90 ['Oct 2011', 100461.0, 233194.0, 305.1071, 131.4415, 30651362.0]
91 ['Nov 2011', 101230.0, 234331.0, 302.4658, 130.6639, 30618610.0]
92 ['Dec 2011', 102090.0, 236395.0, 302.1679, 130.4948, 30848326.0]
93 ['Jan 2012', 102769.0, 237816.0, 298.1761, 128.8528, 30643256.0]
94 ['Feb 2012', 102081.0, 236731.0, 300.0572, 129.3879, 30630138.0]
95 ['Mar 2012', 102065.0, 236641.0, 299.4582, 129.1585, 30564200.0]
96 ['Apr 2012', 100978.0, 234750.0, 300.0364, 129.061, 30297073.0]
97 ['May 2012', 100288.0, 233077.0, 299.2479, 128.7599, 30010974.0]
98 ['Jun 2012', 99502.0, 231059.0, 298.431, 128.5147, 29694480.0]
99 ['Jul 2012', 98506.0, 228432.0, 296.9304, 128.0444, 29249429.0]
100 ['Aug 2012', 98261.0, 227869.0, 296.4237, 127.823, 29126893.0]
101 ['Sep 2012', 97711.0, 226111.0, 295.7238, 127.7933, 28895468.0]
102 ['Total', 100495.1667, 233033.8333, 299.5419, 129.1766, 361230209.0]
103 ['', '', '', '', '', '']
104 ['', '', '', '', '', '']
105 ['Nevada', '', '', '', '', '']
106 ['Oct 2011', 166354.0, 351686.0, 260.6311, 123.2833, 43357028.0]
107 ['Nov 2011', 167445.0, 353737.0, 260.2742, 123.2034, 43581606.0]
108 ['Dec 2011', 167601.0, 353889.0, 261.7002, 123.9406, 43861221.0]
109 ['Jan 2012', 168023.0, 354081.0, 258.0797, 122.4673, 43363330.0]
110 ['Feb 2012', 168368.0, 354540.0, 258.0326, 122.5374, 43444425.0]
111 ['Mar 2012', 168603.0, 353855.0, 260.8552, 124.2909, 43980963.0]
112 ['Apr 2012', 169044.0, 353983.0, 257.7524, 123.0892, 43571497.0]
113 ['May 2012', 170031.0, 355713.0, 260.0637, 124.3106, 44218888.0]
114 ['Jun 2012', 170134.0, 355349.0, 258.1256, 123.5854, 43915936.0]
115 ['Jul 2012', 170556.0, 355940.0, 258.1978, 123.7208, 44037190.0]
116 ['Aug 2012', 171776.0, 358009.0, 257.2702, 123.4406, 44192850.0]
117 ['Sep 2012', 171830.0, 358015.0, 254.8663, 122.3236, 43793678.0]
118 ['Total', 169147.0833, 354899.75, 258.8076, 123.3491, 525318612.0]
119 ['', '', '', '', '', '']
120 ['', '', '', '', '', '']
121 ['Oregon', '', '', '', '', '']
122 ['Oct 2011', 436390.0, 798772.0, 234.4896, 128.1078, 102328937.0]
123 ['Nov 2011', 439764.0, 803891.0, 233.958, 127.9854, 102886286.0]
124 ['Dec 2011', 440894.0, 805396.0, 235.2304, 128.7711, 103711691.0]
125 ['Jan 2012', 446732.0, 822995.0, 233.9344, 126.9825, 104505982.0]
126 ['Feb 2012', 445852.0, 812701.0, 235.0783, 128.9652, 104810112.0]
127 ['Mar 2012', 446011.0, 812900.0, 235.0474, 128.9626, 104833717.0]
128 ['Apr 2012', 449538.0, 817164.0, 233.5951, 128.5053, 105009886.0]
129 ['May 2012', 450508.0, 819469.0, 234.1843, 128.7442, 105501903.0]
130 ['Jun 2012', 453139.0, 823852.0, 232.7165, 127.9998, 105452903.0]
131 ['Jul 2012', 452513.0, 821247.0, 232.194, 127.9405, 105070791.0]
132 ['Aug 2012', 453769.0, 823810.0, 231.3606, 127.4375, 104984287.0]
133 ['Sep 2012', 452944.0, 820459.0, 230.8445, 127.4404, 104559644.0]
134 ['Total', 447337.8333, 815221.3333, 233.5402, 128.1509, 1253656139.0]
135 ['', '', '', '', '', '']
136 ['', '', '', '', '', '']
137 ['Washington', '', '', '', '', '']
138 ['Oct 2011', 569499.0, 1095139.0, 244.7799, 127.2915, 139401907.0]
139 ['Nov 2011', 571727.0, 1097281.0, 243.6102, 126.9306, 139278502.0]
140 ['Dec 2011', 574391.0, 1102830.0, 244.771, 127.485, 140594266.0]
141 ['Jan 2012', 574620.0, 1099545.0, 244.5221, 127.7868, 140507314.0]
142 ['Feb 2012', 576774.0, 1102036.0, 243.0563, 127.2087, 140188543.0]
143 ['Mar 2012', 579682.0, 1111501.0, 243.5204, 127.0034, 141164387.0]
144 ['Apr 2012', 580314.0, 1111832.0, 241.1093, 125.8455, 139919103.0]
145 ['May 2012', 584330.0, 1115696.0, 240.3963, 125.9042, 140470782.0]
146 ['Jun 2012', 586341.0, 1115286.0, 240.4397, 126.4067, 140979671.0]
147 ['Jul 2012', 586471.0, 1111084.0, 239.6792, 126.5115, 140564910.0]
148 ['Aug 2012', 589966.0, 1118464.0, 239.817, 126.4984, 141483871.0]
149 ['Sep 2012', 588411.0, 1116382.0, 238.0904, 125.4902, 140094990.0]
150 ['Total', 580210.5, 1108089.6667, 241.9593, 126.6931, 1684648246.0]
151 ['', '', '', '', '', '']
152 ['', '', '', '', '', '']
153 ['Outlying Areas', '', '', '', '', '']
154 [' No data found.', '', '', '', '', '']
155 ['', '', '', '', '', '']
156 ['', '', '', '', '', '']
157 ['WRO', '', '', '', '', '']
158 ['Oct 2011', 3613296.0, 7771253.0, 304.9473, 141.7873, 1101865025.0]
159 ['Nov 2011', 3628852.0, 7804810.0, 303.8208, 141.2617, 1102520881.0]
160 ['Dec 2011', 3649811.0, 7847723.0, 301.9313, 140.4219, 1101992139.0]
161 ['Jan 2012', 3670388.0, 7873709.0, 301.82, 140.6956, 1107796573.0]
162 ['Feb 2012', 3666413.0, 7861273.0, 301.9474, 140.825, 1107063913.0]
163 ['Mar 2012', 3696238.0, 7909052.0, 302.1977, 141.2299, 1116994650.0]
164 ['Apr 2012', 3699168.0, 7901067.0, 300.2777, 140.5858, 1110777613.0]
165 ['May 2012', 3719742.0, 7930932.0, 300.0079, 140.7088, 1115951809.0]
166 ['Jun 2012', 3739304.0, 7971479.0, 300.066, 140.7566, 1122038093.0]
167 ['Jul 2012', 3761817.0, 7988307.0, 299.1999, 140.8978, 1125535269.0]
168 ['Aug 2012', 3789529.0, 8038389.0, 298.9572, 140.9371, 1132906988.0]
169 ['Sep 2012', 3789658.0, 8037446.0, 297.9664, 140.4913, 1129190886.0]
170 ['Total', 3702018.0, 7911286.6667, 301.0663, 140.8814, 13374633839.0]
171 ['', '', '', '', '', '']
172 ['', '', '', '', '', '']
173 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
174 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [502]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,25,41,57,73,89,105,121,137,153,157]:
        #for the rows that have the state names
        state = row[0]
        if state == 'WRO':
            break
        else:
            continue         
    if i in [18,23,38,54,70,86,102,118,134,150,155,170]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [503]:
pprint.pprint(snap_data)

{'Alabama': {'cost_by_household': 281.3253,
             'cost_by_individual': 127.2564,
             'household_participation': 411745.0833,
             'individual_participation': 910243.8333,
             'total_cost': 1390011732.0},
 'Alaska': {'cost_by_household': 409.1281,
            'cost_by_individual': 170.0711,
            'household_participation': 37951.6667,
            'individual_participation': 91297.6667,
            'total_cost': 186325119.0},
 'American Samoa': {'cost_by_household': '',
                    'cost_by_individual': '',
                    'household_participation': '',
                    'individual_participation': '',
                    'total_cost': ''},
 'Arizona': {'cost_by_household': 293.2876,
             'cost_by_individual': 126.5303,
             'household_participation': 484905.5,
             'individual_participation': 1123974.3333,
             'total_cost': 1706601437.0},
 'Arkansas': {'cost_by_household': 277.6819,
              'cost_by_individual': 121.7156,
              'household_participation': 220095.0,
              'individual_participation': 502124.75,
              'total_cost': 733396874.0},
 'California': {'cost_by_household': 332.0808,
                'cost_by_individual': 149.0461,
                'household_participation': 1779240.8333,
                'individual_participation': 3964220.5833,
                'total_cost': 7090221357.0},
 'Colorado': {'cost_by_household': 305.2706,
              'cost_by_individual': 137.0451,
              'household_participation': 220707.3333,
              'individual_participation': 491629.6667,
              'total_cost': 808505391.0},
 'Connecticut': {'cost_by_household': 264.1103,
                 'cost_by_individual': 143.8927,
                 'household_participation': 219816.8333,
                 'individual_participation': 403466.4167,
                 'total_cost': 696670564.0},
 'Delaware': {'cost_by_household': 271.4245,
              'cost_by_individual': 127.3559,
              'household_participation': 69564.1667,
              'individual_participation': 148257.0833,
              'total_cost': 226577031.0},
 'District of Columbia': {'cost_by_household': 243.8512,
                          'cost_by_individual': 137.742,
                          'household_participation': 79728.5833,
                          'individual_participation': 141147.3333,
                          'total_cost': 233302973.0},
 'Florida': {'cost_by_household': 255.2388,
             'cost_by_individual': 138.9829,
             'household_participation': 1825813.4167,
             'individual_participation': 3353064.0833,
             'total_cost': 5592221094.0},
 'Georgia': {'cost_by_household': 295.5713,
             'cost_by_individual': 135.8991,
             'household_participation': 879493.25,
             'individual_participation': 1912838.75,
             'total_cost': 3119435907.0},
 'Guam': {'cost_by_household': 661.4333,
          'cost_by_individual': 215.9264,
          'household_participation': 14274.75,
          'individual_participation': 43726.9167,
          'total_cost': 113301546.0},
 'Hawaii': {'cost_by_household': 427.0843,
            'cost_by_individual': 213.6469,
            'household_participation': 88454.6667,
            'individual_participation': 176822.5833,
            'total_cost': 453331174.0},
 'Idaho': {'cost_by_household': 299.5419,
           'cost_by_individual': 129.1766,
           'household_participation': 100495.1667,
           'individual_participation': 233033.8333,
           'total_cost': 361230209.0},
 'Illinois': {'cost_by_household': 285.1667,
              'cost_by_individual': 139.4461,
              'household_participation': 914286.5833,
              'individual_participation': 1869712.8333,
              'total_cost': 3128689275.0},
 'Indiana': {'cost_by_household': 299.8583,
             'cost_by_individual': 132.4605,
             'household_participation': 401414.5833,
             'individual_participation': 908704.5,
             'total_cost': 1444409807.0},
 'Iowa': {'cost_by_household': 259.2989,
          'cost_by_individual': 121.1952,
          'household_participation': 190720.5833,
          'individual_participation': 408049.5,
          'total_cost': 593443715.0},
 'Kansas': {'cost_by_household': 266.1467,
            'cost_by_individual': 125.1093,
            'household_participation': 143241.5,
            'individual_participation': 304719.4167,
            'total_cost': 457478972.0},
 'Kentucky': {'cost_by_household': 268.7077,
              'cost_by_individual': 127.4276,
              'household_participation': 402733.6667,
              'individual_participation': 849247.6667,
              'total_cost': 1298611475.0},
 'Louisiana': {'cost_by_household': 305.503,
               'cost_by_individual': 136.1041,
               'household_participation': 422679.5833,
               'individual_participation': 948758.25,
               'total_cost': 1549558693.0},
 'Maine': {'cost_by_household': 239.3833,
           'cost_by_individual': 124.1632,
           'household_participation': 131153.3333,
           'individual_participation': 252860.0,
           'total_cost': 376750999.0},
 'Maryland': {'cost_by_household': 255.2629,
              'cost_by_individual': 128.4629,
              'household_participation': 360523.0,
              'individual_participation': 716379.1667,
              'total_cost': 1104337614.0},
 'Massachusetts': {'cost_by_household': 237.9312,
                   'cost_by_individual': 132.5101,
                   'household_participation': 479829.75,
                   'individual_participation': 861568.25,
                   'total_cost': 1369997551.0},
 'Michigan': {'cost_by_household': 268.5993,
              'cost_by_individual': 135.835,
              'household_participation': 924643.25,
              'individual_participation': 1828384.25,
              'total_cost': 2980301907.0},
 'Minnesota': {'cost_by_household': 235.9356,
               'cost_by_individual': 115.912,
               'household_participation': 264738.9167,
               'individual_participation': 538868.8333,
               'total_cost': 749536081.0},
 'Mississippi': {'cost_by_household': 275.4364,
                 'cost_by_individual': 123.7648,
                 'household_participation': 296507.5833,
                 'individual_participation': 659872.25,
                 'total_cost': 980027716.0},
 'Missouri': {'cost_by_household': 275.8889,
              'cost_by_individual': 128.538,
              'household_participation': 441625.9167,
              'individual_participation': 947888.5833,
              'total_cost': 1462076136.0},
 'Montana': {'cost_by_household': 272.6718,
             'cost_by_individual': 127.7811,
             'household_participation': 58987.6667,
             'individual_participation': 125873.6667,
             'total_cost': 193011254.0},
 'Nebraska': {'cost_by_household': 279.7102,
              'cost_by_individual': 122.4276,
              'household_participation': 77066.25,
              'individual_participation': 176073.1667,
              'total_cost': 258674634.0},
 'Nevada': {'cost_by_household': 258.8076,
            'cost_by_individual': 123.3491,
            'household_participation': 169147.0833,
            'individual_participation': 354899.75,
            'total_cost': 525318612.0},
 'New Hampshire': {'cost_by_household': 246.1695,
                   'cost_by_individual': 118.6772,
                   'household_participation': 56354.3333,
                   'individual_participation': 116894.5833,
                   'total_cost': 166472605.0},
 'New Jersey': {'cost_by_household': 271.0669,
                'cost_by_individual': 133.2615,
                'household_participation': 406142.5,
                'individual_participation': 826133.5833,
                'total_cost': 1321101694.0},
 'New Mexico': {'cost_by_household': 290.2635,
                'cost_by_individual': 128.1735,
                'household_participation': 193521.5833,
                'individual_participation': 438251.75,
                'total_cost': 674066965.0},
 'New York': {'cost_by_household': 274.9382,
              'cost_by_individual': 147.445,
              'household_participation': 1650098.6667,
              'individual_participation': 3076911.4167,
              'total_cost': 5444101662.0},
 'North Carolina': {'cost_by_household': 257.9523,
                    'cost_by_individual': 121.3667,
                    'household_participation': 785071.9167,
                    'individual_participation': 1668588.1667,
                    'total_cost': 2430133033.0},
 'North Dakota': {'cost_by_household': 277.1138,
                  'cost_by_individual': 128.5195,
                  'household_participation': 27268.5,
                  'individual_participation': 58796.3333,
                  'total_cost': 90677717.0},
 'Ohio': {'cost_by_household': 286.7586,
          'cost_by_individual': 138.6005,
          'household_participation': 873827.75,
          'individual_participation': 1807912.6667,
          'total_cost': 3006931315.0},
 'Oklahoma': {'cost_by_household': 282.2586,
              'cost_by_individual': 128.3579,
              'household_participation': 279648.8333,
              'individual_participation': 614947.0833,
              'total_cost': 947199555.0},
 'Oregon': {'cost_by_household': 233.5402,
            'cost_by_individual': 128.1509,
            'household_participation': 447337.8333,
            'individual_participation': 815221.3333,
            'total_cost': 1253656139.0},
 'Outlying Areas': {'cost_by_household': '',
                    'cost_by_individual': '',
                    'household_participation': '',
                    'individual_participation': '',
                    'total_cost': ''},
 'Pennsylvania': {'cost_by_household': 265.8608,
                  'cost_by_individual': 128.4314,
                  'household_participation': 869157.1667,
                  'individual_participation': 1799208.5,
                  'total_cost': 2772898224.0},
 'Puerto Rico': {'cost_by_household': '',
                 'cost_by_individual': '',
                 'household_participation': '',
                 'individual_participation': '',
                 'total_cost': ''},
 'Rhode Island': {'cost_by_household': 252.9739,
                  'cost_by_individual': 139.4528,
                  'household_participation': 95281.8333,
                  'individual_participation': 172845.75,
                  'total_cost': 289245852.0},
 'South Carolina': {'cost_by_household': 278.3933,
                    'cost_by_individual': 131.384,
                    'household_participation': 410490.8333,
                    'individual_participation': 869800.5833,
                    'total_cost': 1371335000.0},
 'South Dakota': {'cost_by_household': 305.708,
                  'cost_by_individual': 132.7999,
                  'household_participation': 45110.75,
                  'individual_participation': 103845.8333,
                  'total_cost': 165488630.0},
 'Tennessee': {'cost_by_household': 271.4986,
               'cost_by_individual': 132.2041,
               'household_participation': 641210.5,
               'individual_participation': 1316810.25,
               'total_cost': 2089053032.0},
 'Texas': {'cost_by_household': 300.3917,
           'cost_by_individual': 123.9491,
           'household_participation': 1666361.75,
           'individual_participation': 4038440.1667,
           'total_cost': 6006734649.0},
 'Utah': {'cost_by_household': 297.6664,
          'cost_by_individual': 121.7517,
          'household_participation': 113253.75,
          'individual_participation': 276890.0,
          'total_cost': 404542100.0},
 'Vermont': {'cost_by_household': 238.5283,
             'cost_by_individual': 121.8822,
             'household_participation': 49349.75,
             'individual_participation': 96579.4167,
             'total_cost': 141255732.0},
 'Virgin Islands': {'cost_by_household': 416.5831,
                    'cost_by_individual': 177.1777,
                    'household_participation': 10559.25,
                    'individual_participation': 24827.0833,
                    'total_cost': 52785665.0},
 'Virginia': {'cost_by_household': 265.9021,
              'cost_by_individual': 128.0004,
              'household_participation': 439924.0,
              'individual_participation': 913877.6667,
              'total_cost': 1403720773.0},
 'Washington': {'cost_by_household': 241.9593,
                'cost_by_individual': 126.6931,
                'household_participation': 580210.5,
                'individual_participation': 1108089.6667,
                'total_cost': 1684648246.0},
 'West Virginia': {'cost_by_household': 254.217,
                   'cost_by_individual': 120.2316,
                   'household_participation': 164033.9167,
                   'individual_participation': 346832.5,
                   'total_cost': 500402535.0},
 'Wisconsin': {'cost_by_household': 243.9156,
               'cost_by_individual': 116.5,
               'household_participation': 398965.5,
               'individual_participation': 835312.3333,
               'total_cost': 1167767096.0},
 'Wyoming': {'cost_by_household': 288.6381,
             'cost_by_individual': 125.6046,
             'household_participation': 14946.5,
             'individual_participation': 34346.9167,
             'total_cost': 51769558.0}}

In [504]:
snap_data_2012 = pd.DataFrame.from_dict(snap_data, orient = "index")

In [505]:
pd.DataFrame.to_csv(snap_data_2012,'SNAP/SNAP DFs/snap_2012_df.csv')

# 2011

In [506]:
book = xlrd.open_workbook('SNAP/FY11.xls')

In [507]:
sheet = book.sheet_by_name('NERO')

In [508]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2011', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Connecticut', '', '', '', '', '']
6 ['Oct 2010', 198428.0, 367664.0, 257.7497, 139.1073, 51144760.0]
7 ['Nov 2010', 200388.0, 370665.0, 256.4864, 138.661, 51396794.0]
8 ['Dec 2010', 200991.0, 371675.0, 255.9055, 138.3862, 51434707.0]
9 ['Jan 2011', 201794.0, 372531.0, 255.4169, 138.3552, 51541591.0]
10 ['Feb 2011', 202791.0, 373808.0, 254.3947, 138.0092, 51588948.0]
11 ['Mar 2011', 205793.0, 378406.0, 253.8306, 138.0437, 52236556.0]
12 ['Apr 2011', 206768.0, 379698.0, 253.4253, 138.005, 52400237.0]
13 ['May 2011', 208228.0, 381501.0, 247.1059, 134.8735, 51454363.0]
14 ['Jun 2011', 209399.0, 383390.0, 249.4685, 136.2541, 52238453.0]
15 ['Jul 2011', 211166.0, 386724.0, 248.96, 135.9416, 52571886.0]
16 ['Aug 2011', 210915.0, 386985.0, 252.6192, 137.6828, 53281185.0]
17 ['Sep 2011', 212598.0, 391078.0, 357.9554, 194.5919, 76100607.0]
18 ['Total', 205771.5833, 378677.0833, 262.1799, 142.4675, 647390087.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Maine', '', '', '', '', '']
22 ['Oct 2010', 121848.0, 242806.0, 253.604, 127.2668, 30901137.0]
23 ['Nov 2010', 121421.0, 241117.0, 255.6122, 128.7205, 31036695.0]
24 ['Dec 2010', 122619.0, 242824.0, 255.3064, 128.9222, 31305410.0]
25 ['Jan 2011', 124767.0, 246812.0, 253.387, 128.0908, 31614338.0]
26 ['Feb 2011', 124550.0, 245172.0, 253.2197, 128.6383, 31538517.0]
27 ['Mar 2011', 126964.0, 250082.0, 252.7246, 128.3056, 32086924.0]
28 ['Apr 2011', 126836.0, 248254.0, 245.9827, 125.6756, 31199460.0]
29 ['May 2011', 128396.0, 251007.0, 245.6772, 125.6697, 31543973.0]
30 ['Jun 2011', 128791.0, 251630.0, 244.4869, 125.135, 31487718.0]
31 ['Jul 2011', 128919.0, 251630.0, 244.9417, 125.4923, 31577633.0]
32 ['Aug 2011', 129536.0, 252223.0, 263.2841, 135.2167, 34104764.0]
33 ['Sep 2011', 129559.0, 251762.0, 260.3822, 133.995, 33734857.0]
34 ['Total', 126183.8333, 247943.25, 252.3642, 128.4338, 382131426.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Massachusetts', '', '', '', '', '']
38 ['Oct 2010', 433613.0, 793872.0, 238.456, 130.2447, 103397601.0]
39 ['Nov 2010', 436957.0, 799770.0, 240.1797, 131.223, 104948212.0]
40 ['Dec 2010', 439138.0, 802456.0, 241.2663, 132.0312, 105949202.0]
41 ['Jan 2011', 439836.0, 801902.0, 240.4081, 131.8617, 105740145.0]
42 ['Feb 2011', 442656.0, 805949.0, 240.649, 132.173, 106524706.0]
43 ['Mar 2011', 445998.0, 810776.0, 241.4901, 132.8407, 107704083.0]
44 ['Apr 2011', 446579.0, 810900.0, 239.0639, 131.6573, 106760923.0]
45 ['May 2011', 449180.0, 815538.0, 238.4574, 131.337, 107110275.0]
46 ['Jun 2011', 457014.0, 832768.0, 256.8244, 140.9424, 117372332.0]
47 ['Jul 2011', 454985.0, 825084.0, 237.546, 130.9926, 108079863.0]
48 ['Aug 2011', 458283.0, 830593.0, 237.4897, 131.0359, 108837493.0]
49 ['Sep 2011', 460552.0, 833963.0, 237.0735, 130.9227, 109184656.0]
50 ['Total', 447065.9167, 813630.9167, 240.7567, 132.2886, 1291609491.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['New Hampshire', '', '', '', '', '']
54 ['Oct 2010', 52553.0, 110727.0, 252.7434, 119.9565, 13282426.0]
55 ['Nov 2010', 52956.0, 111518.0, 252.4944, 119.9007, 13371091.0]
56 ['Dec 2010', 53431.0, 112319.0, 252.9874, 120.348, 13517371.0]
57 ['Jan 2011', 53923.0, 113128.0, 252.4128, 120.3138, 13610856.0]
58 ['Feb 2011', 53863.0, 112822.0, 253.4742, 121.0126, 13652879.0]
59 ['Mar 2011', 54616.0, 114020.0, 252.3901, 120.8958, 13784538.0]
60 ['Apr 2011', 54748.0, 114459.0, 248.2992, 118.7664, 13593883.0]
61 ['May 2011', 54820.0, 114657.0, 248.874, 118.9921, 13643275.0]
62 ['Jun 2011', 54732.0, 114468.0, 247.7455, 118.4576, 13559605.0]
63 ['Jul 2011', 54536.0, 114046.0, 248.8851, 119.0151, 13573198.0]
64 ['Aug 2011', 54746.0, 114332.0, 247.8634, 118.6853, 13569532.0]
65 ['Sep 2011', 54682.0, 114388.0, 247.2628, 118.2014, 13520824.0]
66 ['Total', 54133.8333, 113407.0, 250.4279, 119.5396, 162679478.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['New York', '', '', '', '', '']
70 ['Oct 2010', 1552821.0, 2918849.0, 281.3708, 149.6886, 436918450.0]
71 ['Nov 2010', 1560721.0, 2934493.0, 281.5295, 149.7325, 439389055.0]
72 ['Dec 2010', 1580565.0, 2969868.0, 281.3606, 149.7402, 444708650.0]
73 ['Jan 2011', 1583310.0, 2971876.0, 279.7873, 149.0607, 442990037.0]
74 ['Feb 2011', 1587097.0, 2975444.0, 279.8635, 149.2787, 444170561.0]
75 ['Mar 2011', 1610728.0, 3013945.0, 282.6802, 151.0714, 455320910.0]
76 ['Apr 2011', 1612039.0, 3017404.0, 275.5479, 147.2106, 444193992.0]
77 ['May 2011', 1614089.0, 3019981.0, 275.8158, 147.4152, 445191237.0]
78 ['Jun 2011', 1622860.0, 3035825.0, 274.7219, 146.858, 445835208.0]
79 ['Jul 2011', 1626836.0, 3043751.0, 274.4907, 146.7109, 446551388.0]
80 ['Aug 2011', 1624477.0, 3040684.0, 276.6673, 147.8087, 449439617.0]
81 ['Sep 2011', 1632734.0, 3057767.0, 279.2564, 149.1126, 455951436.0]
82 ['Total', 1600689.75, 2999990.5833, 278.5602, 148.6299, 5350660541.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Rhode Island', '', '', '', '', '']
86 ['Oct 2010', 81157.0, 152373.0, 265.3013, 141.3049, 21531055.0]
87 ['Nov 2010', 82248.0, 154031.0, 267.0119, 142.5765, 21961196.0]
88 ['Dec 2010', 83032.0, 155184.0, 265.5874, 142.1039, 22052257.0]
89 ['Jan 2011', 83405.0, 155742.0, 260.4494, 139.4793, 21722782.0]
90 ['Feb 2011', 85507.0, 159299.0, 261.9302, 140.5964, 22396869.0]
91 ['Mar 2011', 86579.0, 160756.0, 261.3555, 140.7593, 22627900.0]
92 ['Apr 2011', 87141.0, 161381.0, 259.2325, 139.9779, 22589776.0]
93 ['May 2011', 88150.0, 162759.0, 258.9295, 140.2358, 22824636.0]
94 ['Jun 2011', 88800.0, 163608.0, 259.2627, 140.7176, 23022527.0]
95 ['Jul 2011', 89149.0, 164055.0, 257.8988, 140.1446, 22991421.0]
96 ['Aug 2011', 90156.0, 165753.0, 260.2695, 141.5652, 23464854.0]
97 ['Sep 2011', 91095.0, 167472.0, 302.4408, 164.5102, 27550844.0]
98 ['Total', 86368.25, 160201.0833, 265.0821, 142.9121, 274736117.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['Vermont', '', '', '', '', '']
102 ['Oct 2010', 44182.0, 88567.0, 246.0052, 122.7207, 10869002.0]
103 ['Nov 2010', 44539.0, 89316.0, 246.5211, 122.9321, 10979804.0]
104 ['Dec 2010', 45163.0, 90556.0, 245.8696, 122.6226, 11104211.0]
105 ['Jan 2011', 45904.0, 91846.0, 241.7554, 120.8277, 11097539.0]
106 ['Feb 2011', 46356.0, 92558.0, 244.2715, 122.339, 11323449.0]
107 ['Mar 2011', 46678.0, 92964.0, 242.4159, 121.719, 11315488.0]
108 ['Apr 2011', 46853.0, 93159.0, 241.8677, 121.6439, 11332226.0]
109 ['May 2011', 47010.0, 93252.0, 239.8612, 120.9183, 11275875.0]
110 ['Jun 2011', 47022.0, 93058.0, 242.0429, 122.3038, 11381343.0]
111 ['Jul 2011', 46876.0, 92643.0, 239.0227, 120.942, 11204427.0]
112 ['Aug 2011', 46996.0, 92940.0, 238.1764, 120.4362, 11193338.0]
113 ['Sep 2011', 47284.0, 93594.0, 249.1292, 125.8609, 11779824.0]
114 ['Total', 46238.5833, 92037.75, 243.0447, 122.1025, 134856526.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['NERO', '', '', '', '', '']
118 ['Oct 2010', 2484602.0, 4674858.0, 268.8738, 142.9015, 668044431.0]
119 ['Nov 2010', 2499230.0, 4700910.0, 269.3161, 143.1814, 673082847.0]
120 ['Dec 2010', 2524939.0, 4744882.0, 269.3419, 143.3274, 680071808.0]
121 ['Jan 2011', 2532939.0, 4753837.0, 267.7985, 142.6884, 678317288.0]
122 ['Feb 2011', 2542820.0, 4765052.0, 267.89, 142.9567, 681195929.0]
123 ['Mar 2011', 2577356.0, 4820949.0, 269.6858, 144.1783, 695076399.0]
124 ['Apr 2011', 2580964.0, 4825255.0, 264.2697, 141.3543, 682070497.0]
125 ['May 2011', 2589873.0, 4838695.0, 263.7363, 141.1628, 683043634.0]
126 ['Jun 2011', 2608618.0, 4874747.0, 266.3852, 142.5504, 694897186.0]
127 ['Jul 2011', 2612467.0, 4877933.0, 262.7975, 140.7461, 686549816.0]
128 ['Aug 2011', 2615109.0, 4883510.0, 265.3391, 142.0885, 693890783.0]
129 ['Sep 2011', 2628504.0, 4910024.0, 276.8963, 148.2321, 727823048.0]
130 ['Total', 2566451.75, 4805887.6667, 267.6868, 142.9508, 8244063666.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
134 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [509]:
snap_data = {}

########################
#                      #
# NERO                 #
#                      #
########################

for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117]:
        #for the rows that have the state names
        state = row[0]
        if state == 'NERO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [510]:
########################
#                      #
# MARO                 #
#                      #
########################

sheet = book.sheet_by_name('MARO')

In [511]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2011', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Delaware', '', '', '', '', '']
6 ['Oct 2010', 57640.0, 127255.0, 277.0294, 125.4801, 15967974.0]
7 ['Nov 2010', 58418.0, 129049.0, 276.5727, 125.1991, 16156823.0]
8 ['Dec 2010', 60206.0, 132371.0, 278.5006, 126.6698, 16767407.0]
9 ['Jan 2011', 60353.0, 132433.0, 277.4579, 126.4444, 16745416.0]
10 ['Feb 2011', 60851.0, 133136.0, 278.2406, 127.1724, 16931221.0]
11 ['Mar 2011', 61816.0, 134427.0, 280.7367, 129.0962, 17354017.0]
12 ['Apr 2011', 61401.0, 133382.0, 276.8938, 127.4652, 17001557.0]
13 ['May 2011', 62310.0, 135131.0, 272.6544, 125.7231, 16989093.0]
14 ['Jun 2011', 63618.0, 137963.0, 277.3109, 127.8746, 17641966.0]
15 ['Jul 2011', 63645.0, 137840.0, 274.4219, 126.7091, 17465579.0]
16 ['Aug 2011', 65583.0, 141915.0, 273.0952, 126.2052, 17910405.0]
17 ['Sep 2011', 66681.0, 144220.0, 275.543, 127.399, 18373486.0]
18 ['Total', 61876.8333, 134926.8333, 276.4968, 126.8002, 205304944.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['District of Columbia', '', '', '', '', '']
22 ['Oct 2010', 73233.0, 130170.0, 244.0563, 137.3049, 17872974.0]
23 ['Nov 2010', 74122.0, 131611.0, 242.8272, 136.7578, 17998837.0]
24 ['Dec 2010', 74837.0, 132704.0, 241.0465, 135.9356, 18039197.0]
25 ['Jan 2011', 74672.0, 132107.0, 244.1062, 137.9783, 18227899.0]
26 ['Feb 2011', 74711.0, 132083.0, 245.3751, 138.7932, 18332221.0]
27 ['Mar 2011', 75525.0, 133308.0, 248.7749, 140.9422, 18788724.0]
28 ['Apr 2011', 75516.0, 133865.0, 257.5906, 145.3121, 19452208.0]
29 ['May 2011', 75900.0, 134500.0, 254.0239, 143.3488, 19280412.0]
30 ['Jun 2011', 76962.0, 136347.0, 257.8715, 145.5573, 19846306.0]
31 ['Jul 2011', 79000.0, 140295.0, 267.4532, 150.6027, 21128800.0]
32 ['Aug 2011', 79374.0, 140836.0, 258.7695, 145.8403, 20539571.0]
33 ['Sep 2011', 79052.0, 140315.0, 249.7536, 140.7086, 19743525.0]
34 ['Total', 76075.3333, 134845.0833, 251.1224, 141.6753, 229250674.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Maryland', '', '', '', '', '']
38 ['Oct 2010', 303759.0, 630341.0, 268.0512, 129.1729, 81422966.0]
39 ['Nov 2010', 311476.0, 643651.0, 265.9043, 128.6766, 82822813.0]
40 ['Dec 2010', 317394.0, 653293.0, 264.8802, 128.6887, 84071402.0]
41 ['Jan 2011', 319704.0, 654721.0, 260.4813, 127.1945, 83276906.0]
42 ['Feb 2011', 322160.0, 657518.0, 261.189, 127.9732, 84144656.0]
43 ['Mar 2011', 326713.0, 653618.0, 259.0875, 129.5057, 84647248.0]
44 ['Apr 2011', 333530.0, 676770.0, 259.8639, 128.0677, 86672409.0]
45 ['May 2011', 330786.0, 670605.0, 258.4179, 127.4685, 85481017.0]
46 ['Jun 2011', 337265.0, 681949.0, 257.3051, 127.2529, 86780009.0]
47 ['Jul 2011', 340941.0, 688816.0, 257.6015, 127.5042, 87826903.0]
48 ['Aug 2011', 346926.0, 698969.0, 258.0827, 128.0967, 89535600.0]
49 ['Sep 2011', 349277.0, 702604.0, 281.9934, 140.184, 98493821.0]
50 ['Total', 328327.5833, 667737.9167, 262.7396, 129.1894, 1035175750.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['New Jersey', '', '', '', '', '']
54 ['Oct 2010', 342962.0, 702119.0, 270.9914, 132.3704, 92939746.0]
55 ['Nov 2010', 345231.0, 706702.0, 271.0735, 132.4221, 93582975.0]
56 ['Dec 2010', 353680.0, 724224.0, 276.6765, 135.117, 97854939.0]
57 ['Jan 2011', 354357.0, 725238.0, 274.5866, 134.1652, 97301696.0]
58 ['Feb 2011', 359507.0, 736360.0, 273.9932, 133.7694, 98502469.0]
59 ['Mar 2011', 365878.0, 742945.0, 285.3944, 140.5482, 104419548.0]
60 ['Apr 2011', 370723.0, 756462.0, 267.7112, 131.1985, 99246709.0]
61 ['May 2011', 374332.0, 761594.0, 266.2721, 130.8757, 99674185.0]
62 ['Jun 2011', 379574.0, 770909.0, 265.1162, 130.5358, 100631217.0]
63 ['Jul 2011', 383450.0, 778822.0, 264.4925, 130.2219, 101419642.0]
64 ['Aug 2011', 387288.0, 787460.0, 265.0676, 130.3654, 102657502.0]
65 ['Sep 2011', 433663.0, 916798.0, 290.0009, 137.176, 125762660.0]
66 ['Total', 370887.0833, 759136.0833, 272.7679, 133.2648, 1213993288.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Pennsylvania', '', '', '', '', '']
70 ['Oct 2010', 783911.0, 1663135.0, 271.7671, 128.0962, 213041194.0]
71 ['Nov 2010', 789307.0, 1673714.0, 271.1373, 127.8657, 214010560.0]
72 ['Dec 2010', 795118.0, 1684790.0, 273.7975, 129.2157, 217701313.0]
73 ['Jan 2011', 801875.0, 1697563.0, 268.4739, 126.8186, 215282500.0]
74 ['Feb 2011', 805534.0, 1703120.0, 268.5285, 127.0074, 216308806.0]
75 ['Mar 2011', 812613.0, 1712108.0, 272.0812, 129.1372, 221096760.0]
76 ['Apr 2011', 821242.0, 1727954.0, 268.8243, 127.7637, 220769785.0]
77 ['May 2011', 824583.0, 1732273.0, 268.2755, 127.7024, 221215385.0]
78 ['Jun 2011', 827158.0, 1735414.0, 269.2549, 128.3361, 222716328.0]
79 ['Jul 2011', 837099.0, 1754322.0, 268.0927, 127.9242, 224420161.0]
80 ['Aug 2011', 843759.0, 1764550.0, 268.2347, 128.2624, 226325418.0]
81 ['Sep 2011', 846976.0, 1769585.0, 276.9681, 132.5652, 234585309.0]
82 ['Total', 815764.5833, 1718210.6667, 270.4491, 128.4026, 2647473519.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Puerto Rico', '', '', '', '', '']
86 [' No data found.', '', '', '', '', '']
87 ['', '', '', '', '', '']
88 ['', '', '', '', '', '']
89 ['Virginia', '', '', '', '', '']
90 ['Oct 2010', 389623.0, 829940.0, 274.4518, 128.8439, 106932716.0]
91 ['Nov 2010', 393917.0, 837005.0, 273.7642, 128.8408, 107840369.0]
92 ['Dec 2010', 395247.0, 839472.0, 273.1234, 128.5942, 107951190.0]
93 ['Jan 2011', 397508.0, 842225.0, 272.6606, 128.6886, 108384763.0]
94 ['Feb 2011', 399824.0, 845393.0, 272.6798, 128.9624, 109023947.0]
95 ['Mar 2011', 404241.0, 852743.0, 273.0283, 129.4285, 110369233.0]
96 ['Apr 2011', 406200.0, 856745.0, 272.0045, 128.9628, 110488230.0]
97 ['May 2011', 409278.0, 862236.0, 272.8865, 129.5312, 111686451.0]
98 ['Jun 2011', 414598.0, 871823.0, 271.5382, 129.1308, 112579215.0]
99 ['Jul 2011', 416749.0, 876522.0, 271.4164, 129.047, 113112506.0]
100 ['Aug 2011', 422614.0, 886725.0, 271.2915, 129.2978, 114651605.0]
101 ['Sep 2011', 431935.0, 904557.0, 282.4932, 134.8933, 122018681.0]
102 ['Total', 406811.1667, 858782.1667, 273.4764, 129.5477, 1335038906.0]
103 ['', '', '', '', '', '']
104 ['', '', '', '', '', '']
105 ['Virgin Islands', '', '', '', '', '']
106 ['Oct 2010', 8828.0, 21624.0, 431.6065, 176.2034, 3810222.0]
107 ['Nov 2010', 9030.0, 22028.0, 430.2991, 176.3937, 3885601.0]
108 ['Dec 2010', 9149.0, 22303.0, 430.3445, 176.5333, 3937222.0]
109 ['Jan 2011', 9156.0, 22338.0, 429.2171, 175.9294, 3929912.0]
110 ['Feb 2011', 9170.0, 22324.0, 427.6495, 175.665, 3921546.0]
111 ['Mar 2011', 9271.0, 22474.0, 426.1788, 175.8078, 3951104.0]
112 ['Apr 2011', 9307.0, 22534.0, 424.5721, 175.3569, 3951493.0]
113 ['May 2011', 9438.0, 22779.0, 424.0602, 175.7004, 4002280.0]
114 ['Jun 2011', 9540.0, 22981.0, 422.2123, 175.2711, 4027905.0]
115 ['Jul 2011', 9715.0, 23310.0, 425.3683, 177.2824, 4132453.0]
116 ['Aug 2011', 9782.0, 23480.0, 423.645, 176.4947, 4144095.0]
117 ['Sep 2011', 9922.0, 23684.0, 421.6148, 176.6282, 4183262.0]
118 ['Total', 9359.0, 22654.9167, 426.3017, 176.11, 47877095.0]
119 ['', '', '', '', '', '']
120 ['', '', '', '', '', '']
121 ['West Virginia', '', '', '', '', '']
122 ['Oct 2010', 158501.0, 344644.0, 259.9297, 119.5411, 41199119.0]
123 ['Nov 2010', 159389.0, 345683.0, 260.2131, 119.9802, 41475112.0]
124 ['Dec 2010', 161088.0, 348880.0, 257.7041, 118.9894, 41513037.0]
125 ['Jan 2011', 159609.0, 343763.0, 260.1509, 120.7879, 41522420.0]
126 ['Feb 2011', 160473.0, 345786.0, 258.4848, 119.9581, 41479829.0]
127 ['Mar 2011', 160449.0, 344581.0, 258.7613, 120.4883, 41517993.0]
128 ['Apr 2011', 160210.0, 344400.0, 259.1655, 120.5601, 41520899.0]
129 ['May 2011', 161258.0, 345501.0, 257.5265, 120.1971, 41528205.0]
130 ['Jun 2011', 161114.0, 345169.0, 255.5335, 119.275, 41170021.0]
131 ['Jul 2011', 161328.0, 346088.0, 256.135, 119.3966, 41321740.0]
132 ['Aug 2011', 162731.0, 349232.0, 255.6686, 119.1335, 41605214.0]
133 ['Sep 2011', 162502.0, 347738.0, 255.6067, 119.448, 41536602.0]
134 ['Total', 160721.0, 345955.4167, 257.8953, 119.8108, 497390191.0]
135 ['', '', '', '', '', '']
136 ['', '', '', '', '', '']
137 ['MARO', '', '', '', '', '']
138 ['Oct 2010', 2118457.0, 4449228.0, 270.5681, 128.8284, 573186911.0]
139 ['Nov 2010', 2140890.0, 4489443.0, 269.8752, 128.6959, 577773090.0]
140 ['Dec 2010', 2166719.0, 4538037.0, 271.3022, 129.5352, 587835707.0]
141 ['Jan 2011', 2177234.0, 4550388.0, 268.5387, 128.4883, 584671512.0]
142 ['Feb 2011', 2192230.0, 4575720.0, 268.5141, 128.6453, 588644695.0]
143 ['Mar 2011', 2216506.0, 4596204.0, 271.6639, 131.0091, 602144627.0]
144 ['Apr 2011', 2238129.0, 4652112.0, 267.6804, 128.7809, 599103290.0]
145 ['May 2011', 2247885.0, 4664619.0, 266.854, 128.5972, 599857028.0]
146 ['Jun 2011', 2269829.0, 4702555.0, 266.713, 128.737, 605392967.0]
147 ['Jul 2011', 2291927.0, 4746015.0, 266.5128, 128.7033, 610827784.0]
148 ['Aug 2011', 2318057.0, 4793167.0, 266.3306, 128.802, 617369410.0]
149 ['Sep 2011', 2380008.0, 4949501.0, 279.2837, 134.2958, 664697346.0]
150 ['Total', 2229822.5833, 4642249.0833, 269.5096, 129.4542, 7211504367.0]
151 ['', '', '', '', '', '']
152 ['', '', '', '', '', '']
153 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
154 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [512]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,89,105,121,137]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MARO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,87,102,118,134,150]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [513]:
########################
#                      #
# SERO                 #
#                      #
########################

sheet = book.sheet_by_name('SERO')

In [514]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2011', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Alabama', '', '', '', '', '']
6 ['Oct 2010', 373039.0, 855732.0, 293.3015, 127.8588, 109412900.0]
7 ['Nov 2010', 377791.0, 863606.0, 291.4409, 127.4931, 110103764.0]
8 ['Dec 2010', 380946.0, 868312.0, 291.7883, 128.0134, 111155578.0]
9 ['Jan 2011', 380234.0, 864727.0, 290.1568, 127.5865, 110327494.0]
10 ['Feb 2011', 380876.0, 864745.0, 289.3393, 127.4392, 110202388.0]
11 ['Mar 2011', 384071.0, 869429.0, 290.0764, 128.1415, 111409943.0]
12 ['Apr 2011', 384379.0, 868813.0, 288.3241, 127.5599, 110825734.0]
13 ['May 2011', 618494.0, 1420146.0, 378.7011, 164.9298, 234224348.0]
14 ['Jun 2011', 394167.0, 887777.0, 290.3023, 128.8922, 114427572.0]
15 ['Jul 2011', 376553.0, 873174.0, 373.6832, 161.1495, 140711520.0]
16 ['Aug 2011', 401479.0, 900496.0, 286.1631, 127.5835, 114888458.0]
17 ['Sep 2011', 405481.0, 907420.0, 284.2836, 127.0322, 115271599.0]
18 ['Total', 404792.5, 920364.75, 307.3512, 135.1784, 1492961298.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Florida', '', '', '', '', '']
22 ['Oct 2010', 1576162.0, 2951682.0, 265.673, 141.8661, 418743637.0]
23 ['Nov 2010', 1601560.0, 2994413.0, 262.5959, 140.4492, 420563059.0]
24 ['Dec 2010', 1631430.0, 3043115.0, 261.3007, 140.0847, 426293804.0]
25 ['Jan 2011', 1639050.0, 3045847.0, 258.5154, 139.1139, 423719667.0]
26 ['Feb 2011', 1640232.0, 3043704.0, 258.187, 139.1353, 423486579.0]
27 ['Mar 2011', 1660612.0, 3072800.0, 258.0225, 139.4413, 428475255.0]
28 ['Apr 2011', 1658023.0, 3064160.0, 256.1268, 138.5907, 424664173.0]
29 ['May 2011', 1671018.0, 3086696.0, 256.3806, 138.7945, 428416538.0]
30 ['Jun 2011', 1690512.0, 3117913.0, 256.1147, 138.8637, 432964984.0]
31 ['Jul 2011', 1694948.0, 3125331.0, 256.4929, 139.1027, 434742097.0]
32 ['Aug 2011', 1715740.0, 3163228.0, 257.6509, 139.7503, 442062012.0]
33 ['Sep 2011', 1729471.0, 3187157.0, 257.0635, 139.4923, 444583933.0]
34 ['Total', 1659063.1667, 3074670.5, 258.6156, 139.5465, 5148715738.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Georgia', '', '', '', '', '']
38 ['Oct 2010', 747821.0, 1710882.0, 309.6859, 135.3627, 231589629.0]
39 ['Nov 2010', 759279.0, 1732865.0, 308.0581, 134.98, 233902080.0]
40 ['Dec 2010', 766567.0, 1743287.0, 306.2918, 134.6842, 234793153.0]
41 ['Jan 2011', 758550.0, 1739838.0, 308.187, 134.3661, 233775239.0]
42 ['Feb 2011', 771191.0, 1744488.0, 305.8613, 135.213, 235877468.0]
43 ['Mar 2011', 781489.0, 1761577.0, 304.7503, 135.1965, 238159030.0]
44 ['Apr 2011', 787080.0, 1771385.0, 303.8871, 135.0262, 239183458.0]
45 ['May 2011', 799688.0, 1794537.0, 313.7297, 139.8053, 250885857.0]
46 ['Jun 2011', 812078.0, 1818580.0, 301.8619, 134.795, 245135435.0]
47 ['Jul 2011', 818832.0, 1828053.0, 301.8763, 135.2182, 247185984.0]
48 ['Aug 2011', 832958.0, 1851586.0, 300.2088, 135.0525, 250061357.0]
49 ['Sep 2011', 841888.0, 1863393.0, 298.2184, 134.7362, 251066473.0]
50 ['Total', 789785.0833, 1780039.25, 305.1057, 135.3723, 2891615163.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Kentucky', '', '', '', '', '']
54 ['Oct 2010', 370672.0, 808308.0, 277.3636, 127.1927, 102810913.0]
55 ['Nov 2010', 373822.0, 813041.0, 275.455, 126.6494, 102971129.0]
56 ['Dec 2010', 374531.0, 812779.0, 275.7313, 127.0578, 103269913.0]
57 ['Jan 2011', 379518.0, 820738.0, 273.6343, 126.5314, 103849124.0]
58 ['Feb 2011', 376651.0, 814144.0, 274.893, 127.1749, 103538720.0]
59 ['Mar 2011', 381265.0, 821931.0, 274.8511, 127.4938, 104791097.0]
60 ['Apr 2011', 379771.0, 818109.0, 275.2455, 127.7706, 104530240.0]
61 ['May 2011', 383559.0, 825184.0, 274.8506, 127.7551, 105421432.0]
62 ['Jun 2011', 387018.0, 831476.0, 274.9352, 127.971, 106404852.0]
63 ['Jul 2011', 387387.0, 832178.0, 275.3474, 128.1769, 106665998.0]
64 ['Aug 2011', 393080.0, 842499.0, 278.2728, 129.8322, 109383462.0]
65 ['Sep 2011', 393601.0, 841275.0, 272.4889, 127.4873, 107251889.0]
66 ['Total', 381739.5833, 823471.8333, 275.2506, 127.5989, 1260888769.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Mississippi', '', '', '', '', '']
70 ['Oct 2010', 264439.0, 607556.0, 280.884, 122.2549, 74276671.0]
71 ['Nov 2010', 267423.0, 612889.0, 280.3959, 122.3457, 74984323.0]
72 ['Dec 2010', 269496.0, 616748.0, 279.6792, 122.2094, 75372430.0]
73 ['Jan 2011', 269289.0, 615375.0, 278.4265, 121.8398, 74977182.0]
74 ['Feb 2011', 268822.0, 614090.0, 280.3458, 122.7232, 75363120.0]
75 ['Mar 2011', 269716.0, 615510.0, 279.5471, 122.4973, 75398319.0]
76 ['Apr 2011', 271567.0, 619598.0, 280.0136, 122.7287, 76042456.0]
77 ['May 2011', 273716.0, 623371.0, 292.3097, 128.3503, 80009838.0]
78 ['Jun 2011', 277037.0, 630250.0, 281.8594, 123.896, 78085485.0]
79 ['Jul 2011', 278832.0, 633764.0, 280.6139, 123.4594, 78244137.0]
80 ['Aug 2011', 282028.0, 639609.0, 280.1911, 123.5469, 79021737.0]
81 ['Sep 2011', 283988.0, 642397.0, 279.3549, 123.496, 79333441.0]
82 ['Total', 273029.4167, 622596.4167, 281.1386, 123.2887, 921109139.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['North Carolina', '', '', '', '', '']
86 ['Oct 2010', 686890.0, 1503558.0, 271.6697, 124.1104, 186607197.0]
87 ['Nov 2010', 700510.0, 1531255.0, 270.0472, 123.5397, 189170741.0]
88 ['Dec 2010', 710016.0, 1547621.0, 267.3414, 122.6506, 189816663.0]
89 ['Jan 2011', 711387.0, 1544547.0, 264.3088, 121.7353, 188025867.0]
90 ['Feb 2011', 716471.0, 1551054.0, 264.8121, 122.3234, 189730180.0]
91 ['Mar 2011', 722702.0, 1561887.0, 264.5459, 122.4082, 191187852.0]
92 ['Apr 2011', 727955.0, 1571115.0, 265.5647, 123.0458, 193319160.0]
93 ['May 2011', 747700.0, 1615715.0, 272.549, 126.1267, 203784850.0]
94 ['Jun 2011', 747188.0, 1608560.0, 264.5624, 122.8912, 197677824.0]
95 ['Jul 2011', 750490.0, 1614848.0, 264.8691, 123.0962, 198781628.0]
96 ['Aug 2011', 760066.0, 1633664.0, 265.4584, 123.5051, 201765906.0]
97 ['Sep 2011', 832413.0, 1797003.0, 296.9982, 137.5764, 247225152.0]
98 ['Total', 734482.3333, 1590068.9167, 269.7016, 124.5802, 2377093020.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['South Carolina', '', '', '', '', '']
102 ['Oct 2010', 381879.0, 834846.0, 289.5366, 132.4411, 110567938.0]
103 ['Nov 2010', 384653.0, 839109.0, 288.435, 132.2205, 110947377.0]
104 ['Dec 2010', 386873.0, 841158.0, 287.4811, 132.2209, 111218677.0]
105 ['Jan 2011', 385404.0, 835154.0, 285.763, 131.8729, 110134187.0]
106 ['Feb 2011', 386873.0, 841158.0, 284.2837, 130.7503, 109981692.0]
107 ['Mar 2011', 390161.0, 840159.0, 285.484, 132.5758, 111384731.0]
108 ['Apr 2011', 389536.0, 838503.0, 284.9272, 132.3661, 110989396.0]
109 ['May 2011', 391901.0, 843281.0, 284.3944, 132.1676, 111454468.0]
110 ['Jun 2011', 394366.0, 847467.0, 284.305, 132.3004, 112120241.0]
111 ['Jul 2011', 395755.0, 850183.0, 284.8146, 132.5795, 112716796.0]
112 ['Aug 2011', 401009.0, 859660.0, 284.436, 132.682, 114061403.0]
113 ['Sep 2011', 402827.0, 862178.0, 283.1686, 132.3021, 114067953.0]
114 ['Total', 390936.4167, 844404.6667, 285.5632, 132.208, 1339644859.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['Tennessee', '', '', '', '', '']
118 ['Oct 2010', 600271.0, 1263470.0, 283.2661, 134.5789, 170036418.0]
119 ['Nov 2010', 602751.0, 1264407.0, 278.4001, 132.7151, 167805956.0]
120 ['Dec 2010', 608734.0, 1276410.0, 280.4431, 133.7464, 170715251.0]
121 ['Jan 2011', 608144.0, 1272315.0, 276.6162, 132.2176, 168222463.0]
122 ['Feb 2011', 605557.0, 1265707.0, 277.6383, 132.8315, 168125813.0]
123 ['Mar 2011', 614900.0, 1282530.0, 279.2161, 133.8682, 171689959.0]
124 ['Apr 2011', 609602.0, 1270529.0, 279.9192, 134.3057, 170639303.0]
125 ['May 2011', 613717.0, 1276500.0, 280.8946, 135.0488, 172389789.0]
126 ['Jun 2011', 620160.0, 1289963.0, 279.3608, 134.3049, 173248415.0]
127 ['Jul 2011', 614579.0, 1277706.0, 280.228, 134.7902, 172222232.0]
128 ['Aug 2011', 619539.0, 1285316.0, 276.8708, 133.4553, 171532237.0]
129 ['Sep 2011', 620070.0, 1284624.0, 277.4038, 133.8989, 172009754.0]
130 ['Total', 611502.0, 1275789.75, 279.1811, 133.815, 2048637590.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['SERO', '', '', '', '', '']
134 ['Oct 2010', 5001173.0, 10536034.0, 280.7432, 133.2613, 1404045303.0]
135 ['Nov 2010', 5067789.0, 10651585.0, 278.3163, 132.4168, 1410448429.0]
136 ['Dec 2010', 5128593.0, 10749430.0, 277.3929, 132.3452, 1422635469.0]
137 ['Jan 2011', 5131576.0, 10738541.0, 275.3601, 131.585, 1413031223.0]
138 ['Feb 2011', 5146673.0, 10739090.0, 275.1886, 131.8832, 1416305960.0]
139 ['Mar 2011', 5204916.0, 10825823.0, 275.2198, 132.3222, 1432496186.0]
140 ['Apr 2011', 5207913.0, 10822212.0, 274.6194, 132.1536, 1430193920.0]
141 ['May 2011', 5499793.0, 11485430.0, 288.4812, 138.1391, 1586587120.0]
142 ['Jun 2011', 5322526.0, 11031986.0, 274.318, 132.3483, 1460064808.0]
143 ['Jul 2011', 5317376.0, 11035237.0, 280.4523, 135.1371, 1491270392.0]
144 ['Aug 2011', 5405899.0, 11176058.0, 274.2886, 132.6744, 1482776572.0]
145 ['Sep 2011', 5509739.0, 11385447.0, 277.8372, 134.4532, 1530810194.0]
146 ['Total', 5245330.5, 10931406.0833, 277.7179, 133.2603, 17480665576.0]
147 ['', '', '', '', '', '']
148 ['', '', '', '', '', '']
149 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
150 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [515]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117, 133]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SERO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114, 130,146]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [516]:
########################
#                      #
# MWRO                 #
#                      #
########################

sheet = book.sheet_by_name('MWRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2011', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Illinois', '', '', '', '', '']
6 ['Oct 2010', 817687.0, 1720960.0, 295.1096, 140.2167, 241307320.0]
7 ['Nov 2010', 825059.0, 1732169.0, 289.4139, 137.8523, 238783521.0]
8 ['Dec 2010', 857282.0, 1802214.0, 291.896, 138.8499, 250237172.0]
9 ['Jan 2011', 861850.0, 1803223.0, 288.3381, 137.8111, 248504171.0]
10 ['Feb 2011', 860797.0, 1802252.0, 288.4389, 137.7651, 248287378.0]
11 ['Mar 2011', 870640.0, 1821010.0, 291.924, 139.5713, 254160697.0]
12 ['Apr 2011', 867737.0, 1805034.0, 291.167, 139.9732, 252656378.0]
13 ['May 2011', 862243.0, 1791653.0, 286.8136, 138.0307, 247303046.0]
14 ['Jun 2011', 872630.0, 1818182.0, 291.2437, 139.7814, 254147965.0]
15 ['Jul 2011', 864369.0, 1791592.0, 290.5641, 140.1852, 251154597.0]
16 ['Aug 2011', 874109.0, 1811357.0, 290.3524, 140.1157, 253799604.0]
17 ['Sep 2011', 883015.0, 1826991.0, 288.9273, 139.6434, 255127163.0]
18 ['Total', 859784.8333, 1793886.4167, 290.3313, 139.1517, 2995469012.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Indiana', '', '', '', '', '']
22 ['Oct 2010', 370919.0, 860911.0, 306.2138, 131.9306, 113580525.0]
23 ['Nov 2010', 372486.0, 863489.0, 305.1822, 131.6474, 113676082.0]
24 ['Dec 2010', 376700.0, 871666.0, 304.3315, 131.5202, 114641679.0]
25 ['Jan 2011', 377040.0, 872037.0, 302.5748, 130.8234, 114082819.0]
26 ['Feb 2011', 377104.0, 871500.0, 303.4716, 131.3142, 114440348.0]
27 ['Mar 2011', 381386.0, 878389.0, 303.4366, 131.7485, 115726464.0]
28 ['Apr 2011', 381191.0, 876142.0, 302.3826, 131.5603, 115265517.0]
29 ['May 2011', 382708.0, 878259.0, 302.1623, 131.6695, 115639924.0]
30 ['Jun 2011', 384867.0, 882664.0, 301.8505, 131.6155, 116172287.0]
31 ['Jul 2011', 386316.0, 884325.0, 301.6657, 131.7822, 116538303.0]
32 ['Aug 2011', 391571.0, 895008.0, 302.6385, 132.406, 118504445.0]
33 ['Sep 2011', 392310.0, 896328.0, 301.3177, 131.8825, 118209940.0]
34 ['Total', 381216.5, 877559.8333, 303.082, 131.6604, 1386478333.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Michigan', '', '', '', '', '']
38 ['Oct 2010', 947985.0, 1901600.0, 272.2198, 135.7069, 258060273.0]
39 ['Nov 2010', 960620.0, 1920330.0, 270.6876, 135.4079, 260027880.0]
40 ['Dec 2010', 967944.0, 1926594.0, 272.005, 136.6586, 263285606.0]
41 ['Jan 2011', 980321.0, 1946040.0, 269.3834, 135.7023, 264082196.0]
42 ['Feb 2011', 981931.0, 1945982.0, 271.2193, 136.8557, 266318669.0]
43 ['Mar 2011', 984205.0, 1948044.0, 271.0621, 136.9479, 266780625.0]
44 ['Apr 2011', 960268.0, 1920552.0, 271.0728, 135.5353, 260302506.0]
45 ['May 2011', 963021.0, 1926072.0, 271.7963, 135.8961, 261745586.0]
46 ['Jun 2011', 963569.0, 1924272.0, 272.4991, 136.4525, 262571692.0]
47 ['Jul 2011', 965647.0, 1928071.0, 272.1173, 136.2861, 262769220.0]
48 ['Aug 2011', 969117.0, 1931821.0, 272.0928, 136.498, 263689782.0]
49 ['Sep 2011', 966160.0, 1922354.0, 271.0163, 136.2107, 261845139.0]
50 ['Total', 967565.6667, 1928477.6667, 271.4268, 136.1816, 3151479174.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Minnesota', '', '', '', '', '']
54 ['Oct 2010', 224344.0, 459160.0, 245.4949, 119.948, 55075311.0]
55 ['Nov 2010', 230368.0, 473803.0, 240.0493, 116.7145, 55299678.0]
56 ['Dec 2010', 235341.0, 485516.0, 240.2326, 116.4464, 56536590.0]
57 ['Jan 2011', 240635.0, 496729.0, 237.1712, 114.895, 57071689.0]
58 ['Feb 2011', 242499.0, 501132.0, 236.87, 114.622, 57440750.0]
59 ['Mar 2011', 248210.0, 512100.0, 237.8889, 115.3025, 59046398.0]
60 ['Apr 2011', 249656.0, 515766.0, 237.5881, 115.0043, 59315303.0]
61 ['May 2011', 253244.0, 521715.0, 239.669, 116.337, 60694744.0]
62 ['Jun 2011', 255522.0, 526376.0, 233.2095, 113.2083, 59590153.0]
63 ['Jul 2011', 253681.0, 522258.0, 233.8245, 113.5777, 59316843.0]
64 ['Aug 2011', 256671.0, 528289.0, 232.3684, 112.897, 59642220.0]
65 ['Sep 2011', 256853.0, 528180.0, 231.1798, 112.4223, 59379214.0]
66 ['Total', 245585.3333, 505918.6667, 236.9879, 115.0397, 698408893.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Ohio', '', '', '', '', '']
70 ['Oct 2010', 809908.0, 1710948.0, 293.3999, 138.8861, 237626903.0]
71 ['Nov 2010', 837162.0, 1772608.0, 291.0893, 137.4748, 243688878.0]
72 ['Dec 2010', 849568.0, 1795578.0, 292.0967, 138.204, 248156037.0]
73 ['Jan 2011', 855273.0, 1805861.0, 290.1115, 137.3996, 248124499.0]
74 ['Feb 2011', 856883.0, 1807165.0, 292.2002, 138.5493, 250381364.0]
75 ['Mar 2011', 868903.0, 1830051.0, 292.9324, 139.0835, 254529873.0]
76 ['Apr 2011', 858135.0, 1801679.0, 294.3633, 140.2045, 252603430.0]
77 ['May 2011', 851810.0, 1781487.0, 294.286, 140.7115, 250675721.0]
78 ['Jun 2011', 846044.0, 1767340.0, 295.9101, 141.6552, 250352973.0]
79 ['Jul 2011', 842228.0, 1756228.0, 296.5344, 142.2079, 249749563.0]
80 ['Aug 2011', 847585.0, 1765519.0, 295.5001, 141.8628, 250461458.0]
81 ['Sep 2011', 845019.0, 1756380.0, 295.8124, 142.3195, 249967078.0]
82 ['Total', 847376.5, 1779237.0, 293.6827, 139.8688, 2986317777.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Wisconsin', '', '', '', '', '']
86 ['Oct 2010', 348260.0, 766353.0, 253.2947, 115.1067, 88212397.0]
87 ['Nov 2010', 351480.0, 771413.0, 257.2968, 117.2325, 90434683.0]
88 ['Dec 2010', 354850.0, 777514.0, 255.7256, 116.7107, 90744217.0]
89 ['Jan 2011', 360401.0, 787412.0, 249.0048, 113.9703, 89741593.0]
90 ['Feb 2011', 364544.0, 793098.0, 251.288, 115.5034, 91605538.0]
91 ['Mar 2011', 369842.0, 801577.0, 255.4705, 117.8723, 94483736.0]
92 ['Apr 2011', 374020.0, 807908.0, 251.4515, 116.4091, 94047879.0]
93 ['May 2011', 377664.0, 813430.0, 245.3087, 113.8934, 92644271.0]
94 ['Jun 2011', 381429.0, 818564.0, 254.4433, 118.5638, 97052045.0]
95 ['Jul 2011', 383707.0, 821212.0, 249.5161, 116.5851, 95741078.0]
96 ['Aug 2011', 388667.0, 827293.0, 247.1036, 116.0907, 96041026.0]
97 ['Sep 2011', 389598.0, 827101.0, 249.1145, 117.343, 97054506.0]
98 ['Total', 370371.8333, 801072.9167, 251.5047, 116.2819, 1117802969.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['MWRO', '', '', '', '', '']
102 ['Oct 2010', 3519103.0, 7419932.0, 282.4193, 133.945, 993862729.0]
103 ['Nov 2010', 3577175.0, 7533812.0, 280.0843, 132.9885, 1001910722.0]
104 ['Dec 2010', 3641685.0, 7659082.0, 281.079, 133.6454, 1023601301.0]
105 ['Jan 2011', 3675520.0, 7711302.0, 277.949, 132.4818, 1021606967.0]
106 ['Feb 2011', 3683758.0, 7721129.0, 279.1915, 133.2025, 1028474047.0]
107 ['Mar 2011', 3723186.0, 7791171.0, 280.6005, 134.0912, 1044727793.0]
108 ['Apr 2011', 3691007.0, 7727081.0, 280.1921, 133.8398, 1034191013.0]
109 ['May 2011', 3690690.0, 7712616.0, 278.7293, 133.3793, 1028703292.0]
110 ['Jun 2011', 3704061.0, 7737398.0, 280.7424, 134.3975, 1039887115.0]
111 ['Jul 2011', 3695948.0, 7703686.0, 280.1094, 134.3863, 1035269604.0]
112 ['Aug 2011', 3727720.0, 7759287.0, 279.5646, 134.3085, 1042138535.0]
113 ['Sep 2011', 3732955.0, 7757334.0, 279.0237, 134.2707, 1041583040.0]
114 ['Total', 3671900.6667, 7686152.5, 279.963, 133.7465, 12335956158.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
118 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [517]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MWRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [518]:
########################
#                      #
# SWRO                 #
#                      #
########################

sheet = book.sheet_by_name('SWRO ')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2011', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Arkansas', '', '', '', '', '']
6 ['Oct 2010', 206680.0, 483223.0, 287.6133, 123.0155, 59443922.0]
7 ['Nov 2010', 209176.0, 487786.0, 286.3654, 122.8013, 59900776.0]
8 ['Dec 2010', 210257.0, 489295.0, 284.7746, 122.3717, 59875856.0]
9 ['Jan 2011', 210445.0, 488294.0, 283.8737, 122.3439, 59739794.0]
10 ['Feb 2011', 208019.0, 482697.0, 282.9703, 121.9465, 58863190.0]
11 ['Mar 2011', 209937.0, 486246.0, 284.0892, 122.6557, 59640836.0]
12 ['Apr 2011', 208162.0, 481702.0, 284.9352, 123.1315, 59312683.0]
13 ['May 2011', 208084.0, 480605.0, 292.342, 126.5732, 60831696.0]
14 ['Jun 2011', 209353.0, 484651.0, 291.0027, 125.7034, 60922282.0]
15 ['Jul 2011', 213019.0, 492080.0, 284.0855, 122.9792, 60515612.0]
16 ['Aug 2011', 221953.0, 490744.0, 278.4083, 125.9181, 61793548.0]
17 ['Sep 2011', 212955.0, 490090.0, 288.1135, 125.1917, 61355204.0]
18 ['Total', 210670.0, 486451.0833, 285.674, 123.7184, 722195399.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Louisiana', '', '', '', '', '']
22 ['Oct 2010', 378560.0, 871159.0, 302.217, 131.3276, 114407263.0]
23 ['Nov 2010', 377716.0, 866905.0, 299.3195, 130.4154, 113057776.0]
24 ['Dec 2010', 382997.0, 877189.0, 299.5272, 130.7791, 114718021.0]
25 ['Jan 2011', 378976.0, 865377.0, 295.8343, 129.5552, 112114086.0]
26 ['Feb 2011', 381927.0, 871591.0, 297.2291, 130.2444, 113519826.0]
27 ['Mar 2011', 385068.0, 876510.0, 295.7786, 129.9413, 113894887.0]
28 ['Apr 2011', 386106.0, 878616.0, 296.7257, 130.3955, 114567572.0]
29 ['May 2011', 388090.0, 881585.0, 296.108, 130.3522, 114916549.0]
30 ['Jun 2011', 395457.0, 897846.0, 296.3608, 130.5324, 117197950.0]
31 ['Jul 2011', 399336.0, 905323.0, 298.1647, 131.5198, 119067884.0]
32 ['Aug 2011', 401461.0, 906938.0, 295.6296, 130.862, 118683737.0]
33 ['Sep 2011', 406496.0, 915185.0, 295.1313, 131.0879, 119969676.0]
34 ['Total', 388515.8333, 884518.6667, 297.3099, 130.5903, 1386115227.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['New Mexico', '', '', '', '', '']
38 ['Oct 2010', 167968.0, 393656.0, 296.6972, 126.5969, 49835632.0]
39 ['Nov 2010', 170927.0, 399454.0, 295.135, 126.2887, 50446539.0]
40 ['Dec 2010', 173357.0, 403551.0, 295.8987, 127.1118, 51296104.0]
41 ['Jan 2011', 175744.0, 407943.0, 295.3271, 127.2285, 51901972.0]
42 ['Feb 2011', 175821.0, 408207.0, 296.7441, 127.8122, 52173849.0]
43 ['Mar 2011', 178226.0, 411947.0, 295.6717, 127.9203, 52696392.0]
44 ['Apr 2011', 184686.0, 428732.0, 287.5208, 123.8561, 53101063.0]
45 ['May 2011', 181030.0, 417260.0, 293.788, 127.4611, 53184433.0]
46 ['Jun 2011', 182356.0, 419750.0, 290.7976, 126.334, 53028694.0]
47 ['Jul 2011', 183441.0, 422123.0, 295.375, 128.3604, 54183893.0]
48 ['Aug 2011', 186786.0, 428642.0, 293.312, 127.8143, 54786568.0]
49 ['Sep 2011', 187741.0, 430032.0, 293.2029, 128.0049, 55046214.0]
50 ['Total', 179006.9167, 414274.75, 294.0675, 127.0657, 631681353.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Oklahoma', '', '', '', '', '']
54 ['Oct 2010', 267865.0, 613505.0, 294.4541, 128.5629, 78873957.0]
55 ['Nov 2010', 269201.0, 615191.0, 293.9736, 128.6397, 79137981.0]
56 ['Dec 2010', 271138.0, 617920.0, 293.1189, 128.6181, 79475669.0]
57 ['Jan 2011', 270974.0, 614960.0, 289.3531, 127.4996, 78407161.0]
58 ['Feb 2011', 267313.0, 605422.0, 290.3799, 128.2119, 77622319.0]
59 ['Mar 2011', 269280.0, 608562.0, 289.3561, 128.036, 77917821.0]
60 ['Apr 2011', 270877.0, 610534.0, 289.1074, 128.2689, 78312539.0]
61 ['May 2011', 271669.0, 611136.0, 288.9823, 128.4616, 78507528.0]
62 ['Jun 2011', 272750.0, 612078.0, 288.9322, 128.752, 78806244.0]
63 ['Jul 2011', 275034.0, 616494.0, 287.8997, 128.4395, 79182201.0]
64 ['Aug 2011', 279286.0, 624489.0, 288.2788, 128.925, 80512222.0]
65 ['Sep 2011', 280882.0, 626153.0, 286.8922, 128.6951, 80582842.0]
66 ['Total', 272189.0833, 614703.6667, 290.0369, 128.4275, 947338484.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Texas', '', '', '', '', '']
70 ['Oct 2010', 1557979.0, 3893077.0, 314.8782, 126.0118, 490573679.0]
71 ['Nov 2010', 1575009.0, 3925119.0, 313.8789, 125.9483, 494362024.0]
72 ['Dec 2010', 1592631.0, 3955321.0, 311.8707, 125.5764, 496694923.0]
73 ['Jan 2011', 1583071.0, 3928058.0, 310.2894, 125.0517, 491210198.0]
74 ['Feb 2011', 1568987.0, 3895618.0, 310.2137, 124.9407, 486721329.0]
75 ['Mar 2011', 1585351.0, 3921802.0, 312.362, 126.2693, 495203356.0]
76 ['Apr 2011', 1587675.0, 3926922.0, 308.8991, 124.8895, 490431447.0]
77 ['May 2011', 1602367.0, 3954852.0, 310.2512, 125.7029, 497136224.0]
78 ['Jun 2011', 1625225.0, 4003570.0, 309.3239, 125.5682, 502720983.0]
79 ['Jul 2011', 1648098.0, 4051042.0, 308.7792, 125.6216, 508898453.0]
80 ['Aug 2011', 1682723.0, 4124402.0, 309.0185, 126.0771, 519992601.0]
81 ['Sep 2011', 1692595.0, 4147489.0, 306.7363, 125.1794, 519180276.0]
82 ['Total', 1608475.9167, 3977272.6667, 310.4971, 125.5703, 5993125493.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['SWRO', '', '', '', '', '']
86 ['Oct 2010', 2579052.0, 6254620.0, 307.5295, 126.8078, 793134453.0]
87 ['Nov 2010', 2602029.0, 6294455.0, 306.263, 126.6043, 796905096.0]
88 ['Dec 2010', 2630380.0, 6343276.0, 304.9219, 126.4426, 802060573.0]
89 ['Jan 2011', 2619210.0, 6304632.0, 302.9055, 125.8397, 793373211.0]
90 ['Feb 2011', 2602067.0, 6263535.0, 303.1822, 125.9513, 788900513.0]
91 ['Mar 2011', 2627862.0, 6305067.0, 304.1839, 126.7795, 799353292.0]
92 ['Apr 2011', 2637506.0, 6326506.0, 301.6961, 125.7764, 795725304.0]
93 ['May 2011', 2651240.0, 6345438.0, 303.4717, 126.796, 804576430.0]
94 ['Jun 2011', 2685141.0, 6417895.0, 302.6568, 126.6266, 812676153.0]
95 ['Jul 2011', 2718928.0, 6487062.0, 302.2691, 126.6903, 821848043.0]
96 ['Aug 2011', 2772209.0, 6575215.0, 301.4811, 127.109, 835768676.0]
97 ['Sep 2011', 2780669.0, 6608949.0, 300.6953, 126.5155, 836134212.0]
98 ['Total', 2658857.75, 6377220.8333, 303.4027, 126.4978, 9680455956.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
102 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [519]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SWRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [520]:
########################
#                      #
# MPRO                 #
#                      #
########################
sheet = book.sheet_by_name('MPRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2011', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Colorado', '', '', '', '', '']
6 ['Oct 2010', 187636.0, 428941.0, 322.6309, 141.1317, 60537168.0]
7 ['Nov 2010', 190947.0, 435306.0, 321.3713, 140.9695, 61364880.0]
8 ['Dec 2010', 193500.0, 441221.0, 320.646, 140.6212, 62045010.0]
9 ['Jan 2011', 194957.0, 443242.0, 317.6883, 139.7331, 61935557.0]
10 ['Feb 2011', 195866.0, 443661.0, 317.7919, 140.2977, 62244628.0]
11 ['Mar 2011', 201125.0, 455250.0, 322.2753, 142.3781, 64817612.0]
12 ['Apr 2011', 200814.0, 454810.0, 316.9379, 139.9388, 63645570.0]
13 ['May 2011', 203636.0, 460292.0, 315.9223, 139.766, 64333163.0]
14 ['Jun 2011', 205548.0, 464498.0, 316.4954, 140.0544, 65055003.0]
15 ['Jul 2011', 205920.0, 464088.0, 314.1277, 139.3813, 64685183.0]
16 ['Aug 2011', 209649.0, 471363.0, 314.839, 140.0315, 66005688.0]
17 ['Sep 2011', 211165.0, 474564.0, 313.1729, 139.3514, 66131146.0]
18 ['Total', 200063.5833, 453103.0, 317.7326, 140.292, 762800608.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Iowa', '', '', '', '', '']
22 ['Oct 2010', 163090.0, 352981.0, 280.6099, 129.6519, 45764661.0]
23 ['Nov 2010', 163055.0, 351898.0, 279.5037, 129.5104, 45574468.0]
24 ['Dec 2010', 164841.0, 354552.0, 279.2471, 129.8297, 46031368.0]
25 ['Jan 2011', 167412.0, 360546.0, 276.1652, 128.2315, 46233362.0]
26 ['Feb 2011', 169427.0, 365749.0, 275.4939, 127.6179, 46676109.0]
27 ['Mar 2011', 173097.0, 373505.0, 272.8743, 126.4607, 47233720.0]
28 ['Apr 2011', 175483.0, 379147.0, 271.0346, 125.4446, 47561960.0]
29 ['May 2011', 177067.0, 382412.0, 269.8226, 124.9351, 47776680.0]
30 ['Jun 2011', 178827.0, 386153.0, 268.3002, 124.2495, 47979316.0]
31 ['Jul 2011', 180015.0, 388973.0, 268.7004, 124.3534, 48370104.0]
32 ['Aug 2011', 182184.0, 393624.0, 266.9003, 123.5315, 48624962.0]
33 ['Sep 2011', 183734.0, 396727.0, 266.1772, 123.2732, 48905797.0]
34 ['Total', 173186.0, 373855.5833, 272.6993, 126.3261, 566732507.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Kansas', '', '', '', '', '']
38 ['Oct 2010', 135807.0, 294947.0, 272.7647, 125.5933, 37043355.0]
39 ['Nov 2010', 136708.0, 295787.0, 271.55, 125.506, 37123056.0]
40 ['Dec 2010', 136701.0, 295080.0, 272.9809, 126.4632, 37316764.0]
41 ['Jan 2011', 138374.0, 298200.0, 268.8723, 124.765, 37204934.0]
42 ['Feb 2011', 137944.0, 296961.0, 271.3695, 126.0563, 37433794.0]
43 ['Mar 2011', 138406.0, 296988.0, 271.6692, 126.6066, 37600654.0]
44 ['Apr 2011', 139873.0, 300333.0, 271.0099, 126.2165, 37906974.0]
45 ['May 2011', 139774.0, 299552.0, 271.6127, 126.7372, 37964388.0]
46 ['Jun 2011', 140051.0, 299944.0, 271.5403, 126.7886, 38029485.0]
47 ['Jul 2011', 140840.0, 301926.0, 271.0407, 126.4329, 38173376.0]
48 ['Aug 2011', 141850.0, 303667.0, 272.3806, 127.2354, 38637187.0]
49 ['Sep 2011', 140586.0, 300320.0, 272.6723, 127.6436, 38333911.0]
50 ['Total', 138909.5, 298642.0833, 271.6204, 126.3407, 452767878.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Missouri', '', '', '', '', '']
54 ['Oct 2010', 424684.0, 927581.0, 271.5943, 124.3468, 115341771.0]
55 ['Nov 2010', 427495.0, 931933.0, 271.0896, 124.3538, 115889445.0]
56 ['Dec 2010', 430481.0, 938015.0, 278.3936, 127.7625, 119843157.0]
57 ['Jan 2011', 433219.0, 943733.0, 274.6934, 126.0975, 119002403.0]
58 ['Feb 2011', 431728.0, 940259.0, 277.2847, 127.3176, 119711554.0]
59 ['Mar 2011', 434645.0, 946034.0, 279.0806, 128.2206, 121301003.0]
60 ['Apr 2011', 436662.0, 949025.0, 279.5815, 128.64, 122082612.0]
61 ['May 2011', 435004.0, 944363.0, 279.0904, 128.558, 121405424.0]
62 ['Jun 2011', 437211.0, 949136.0, 279.4454, 128.724, 122176597.0]
63 ['Jul 2011', 436360.0, 945985.0, 274.4047, 126.5763, 119739234.0]
64 ['Aug 2011', 439195.0, 951103.0, 275.6347, 127.281, 121057377.0]
65 ['Sep 2011', 440102.0, 949889.0, 273.428, 126.6845, 120336191.0]
66 ['Total', 433898.8333, 943088.0, 276.1563, 127.0548, 1437886768.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Montana', '', '', '', '', '']
70 ['Oct 2010', 54290.0, 118915.0, 283.2905, 129.3348, 15379843.0]
71 ['Nov 2010', 54919.0, 120013.0, 282.8932, 129.4544, 15536212.0]
72 ['Dec 2010', 55920.0, 122155.0, 282.9472, 129.5273, 15822407.0]
73 ['Jan 2011', 56605.0, 123476.0, 282.0227, 129.2874, 15963895.0]
74 ['Feb 2011', 57052.0, 124364.0, 283.0059, 129.829, 16146053.0]
75 ['Mar 2011', 57677.0, 125404.0, 283.8087, 130.532, 16369236.0]
76 ['Apr 2011', 57974.0, 125945.0, 280.9025, 129.3028, 16285041.0]
77 ['May 2011', 57677.0, 125404.0, 284.6173, 130.9039, 16415873.0]
78 ['Jun 2011', 58455.0, 126521.0, 280.933, 129.7961, 16421936.0]
79 ['Jul 2011', 58223.0, 126203.0, 281.1682, 129.7153, 16370458.0]
80 ['Aug 2011', 58532.0, 126723.0, 280.1343, 129.3911, 16396823.0]
81 ['Sep 2011', 58266.0, 125792.0, 278.0897, 128.8092, 16203173.0]
82 ['Total', 57132.5, 124242.9167, 281.9629, 129.6593, 193310950.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Nebraska', '', '', '', '', '']
86 ['Oct 2010', 74333.0, 170063.0, 280.9973, 122.8214, 20887373.0]
87 ['Nov 2010', 74662.0, 170731.0, 277.9432, 121.5467, 20751795.0]
88 ['Dec 2010', 75733.0, 173040.0, 281.5364, 123.2177, 21321597.0]
89 ['Jan 2011', 76487.0, 174467.0, 277.8911, 121.8285, 21255053.0]
90 ['Feb 2011', 76600.0, 174635.0, 281.3331, 123.4009, 21550116.0]
91 ['Mar 2011', 77261.0, 175919.0, 280.8736, 123.3555, 21700576.0]
92 ['Apr 2011', 77134.0, 176299.0, 283.5577, 124.0616, 21871938.0]
93 ['May 2011', 76550.0, 174936.0, 277.6601, 121.5009, 21254881.0]
94 ['Jun 2011', 76375.0, 174936.0, 280.8419, 122.6123, 21449299.0]
95 ['Jul 2011', 75738.0, 173674.0, 282.7029, 123.2847, 21411353.0]
96 ['Aug 2011', 76595.0, 175754.0, 280.0744, 122.0587, 21452299.0]
97 ['Sep 2011', 76723.0, 175993.0, 281.1572, 122.5686, 21571224.0]
98 ['Total', 76182.5833, 174203.9167, 280.5513, 122.6903, 256477504.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['North Dakota', '', '', '', '', '']
102 ['Oct 2010', 27754.0, 60638.0, 287.197, 131.45, 7970866.0]
103 ['Nov 2010', 27884.0, 60681.0, 285.8733, 131.3639, 7971292.0]
104 ['Dec 2010', 28053.0, 60947.0, 285.1601, 131.255, 7999597.0]
105 ['Jan 2011', 28202.0, 61362.0, 284.016, 130.5339, 8009819.0]
106 ['Feb 2011', 28060.0, 61177.0, 285.3195, 130.8673, 8006066.0]
107 ['Mar 2011', 27994.0, 61049.0, 284.8977, 130.6398, 7975427.0]
108 ['Apr 2011', 27811.0, 60851.0, 285.7927, 130.6171, 7948182.0]
109 ['May 2011', 27638.0, 60333.0, 287.7598, 131.8201, 7953105.0]
110 ['Jun 2011', 27674.0, 60451.0, 286.0486, 130.9508, 7916109.0]
111 ['Jul 2011', 28593.0, 62956.0, 296.9665, 134.8745, 8491162.0]
112 ['Aug 2011', 27564.0, 60369.0, 285.6314, 130.417, 7873144.0]
113 ['Sep 2011', 27483.0, 60011.0, 283.9419, 130.0357, 7803575.0]
114 ['Total', 27892.5, 60902.0833, 286.5715, 131.2467, 95918344.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['South Dakota', '', '', '', '', '']
118 ['Oct 2010', 42223.0, 99327.0, 311.6949, 132.4987, 13160694.0]
119 ['Nov 2010', 42527.0, 99826.0, 309.7089, 131.9395, 13170990.0]
120 ['Dec 2010', 43049.0, 100789.0, 310.1956, 132.4908, 13353612.0]
121 ['Jan 2011', 43512.0, 101635.0, 308.5618, 132.1015, 13426141.0]
122 ['Feb 2011', 43535.0, 101526.0, 308.9336, 132.4727, 13449424.0]
123 ['Mar 2011', 43608.0, 101636.0, 311.5862, 133.6893, 13587649.0]
124 ['Apr 2011', 43682.0, 101924.0, 310.5743, 133.1042, 13566508.0]
125 ['May 2011', 43706.0, 102005.0, 310.2985, 132.9534, 13561907.0]
126 ['Jun 2011', 43945.0, 102748.0, 310.4351, 132.7721, 13642069.0]
127 ['Jul 2011', 44151.0, 103343.0, 310.7286, 132.7519, 13718978.0]
128 ['Aug 2011', 44480.0, 103771.0, 310.668, 133.1635, 13818512.0]
129 ['Sep 2011', 44605.0, 103277.0, 306.67, 132.4498, 13679016.0]
130 ['Total', 43585.25, 101817.25, 309.9969, 132.7014, 162135500.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['Utah', '', '', '', '', '']
134 ['Oct 2010', 104214.0, 271868.0, 305.323, 117.0382, 31818930.0]
135 ['Nov 2010', 104448.0, 268216.0, 302.9818, 117.9864, 31645846.0]
136 ['Dec 2010', 108631.0, 288540.0, 302.4328, 113.8614, 32853578.0]
137 ['Jan 2011', 109877.0, 300729.0, 307.868, 112.4854, 33827613.0]
138 ['Feb 2011', 109287.0, 283313.0, 303.8287, 117.2009, 33204529.0]
139 ['Mar 2011', 116604.0, 291056.0, 290.5432, 116.3986, 33878501.0]
140 ['Apr 2011', 114021.0, 283704.0, 294.026, 118.1694, 33525142.0]
141 ['May 2011', 113969.0, 282745.0, 297.2555, 119.8179, 33877914.0]
142 ['Jun 2011', 114696.0, 284001.0, 297.1242, 119.9959, 34078961.0]
143 ['Jul 2011', 113215.0, 279293.0, 298.4986, 121.0002, 33794520.0]
144 ['Aug 2011', 116647.0, 287635.0, 295.367, 119.7826, 34453670.0]
145 ['Sep 2011', 115979.0, 286549.0, 295.7625, 119.7081, 34302235.0]
146 ['Total', 111799.0, 283970.75, 299.0944, 117.7532, 401261439.0]
147 ['', '', '', '', '', '']
148 ['', '', '', '', '', '']
149 ['Wyoming', '', '', '', '', '']
150 ['Oct 2010', 15037.0, 35703.0, 289.3571, 121.8682, 4351062.0]
151 ['Nov 2010', 15233.0, 35924.0, 288.8344, 122.4756, 4399814.0]
152 ['Dec 2010', 15418.0, 36472.0, 293.4978, 124.0719, 4525149.0]
153 ['Jan 2011', 15763.0, 37237.0, 288.2007, 121.9998, 4542907.0]
154 ['Feb 2011', 15809.0, 37405.0, 288.936, 122.1171, 4567790.0]
155 ['Mar 2011', 16034.0, 37732.0, 291.17, 123.7311, 4668620.0]
156 ['Apr 2011', 15808.0, 37180.0, 289.3553, 123.0266, 4574128.0]
157 ['May 2011', 15687.0, 36885.0, 289.0104, 122.9146, 4533706.0]
158 ['Jun 2011', 15382.0, 35921.0, 287.9043, 123.2857, 4428544.0]
159 ['Jul 2011', 14872.0, 34793.0, 288.085, 123.1397, 4284400.0]
160 ['Aug 2011', 14660.0, 33949.0, 285.7751, 123.4046, 4189463.0]
161 ['Sep 2011', 14394.0, 33170.0, 284.6068, 123.5041, 4096630.0]
162 ['Total', 15341.4167, 36030.9167, 288.7728, 122.9551, 53162213.0]
163 ['', '', '', '', '', '']
164 ['', '', '', '', '', '']
165 ['MPRO', '', '', '', '', '']
166 ['Oct 2010', 1229068.0, 2760964.0, 286.6039, 127.5843, 352255723.0]
167 ['Nov 2010', 1237878.0, 2770315.0, 285.511, 127.5768, 353427798.0]
168 ['Dec 2010', 1252327.0, 2810811.0, 288.353, 128.4726, 361112239.0]
169 ['Jan 2011', 1264408.0, 2844627.0, 285.8268, 127.0471, 361401684.0]
170 ['Feb 2011', 1265308.0, 2829050.0, 286.8788, 128.3081, 362990063.0]
171 ['Mar 2011', 1286451.0, 2864573.0, 286.939, 128.8614, 369132998.0]
172 ['Apr 2011', 1289262.0, 2869218.0, 286.1855, 128.5953, 368968055.0]
173 ['May 2011', 1290708.0, 2868927.0, 285.9493, 128.6464, 369077041.0]
174 ['Jun 2011', 1298164.0, 2884309.0, 285.9248, 128.6885, 371177319.0]
175 ['Jul 2011', 1297927.0, 2881234.0, 284.3294, 128.0836, 369038768.0]
176 ['Aug 2011', 1311356.0, 2907958.0, 284.0641, 128.0999, 372509125.0]
177 ['Sep 2011', 1313037.0, 2906292.0, 282.8274, 127.7789, 371362898.0]
178 ['Total', 1277991.1667, 2849856.5, 285.7645, 128.1484, 4382453711.0]
179 ['', '', '', '', '', '']
180 ['', '', '', '', '', '']
181 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
182 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [521]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117, 133, 149,165]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MPRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114, 130,146, 162, 178]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [522]:

########################
#                      #
# WRO                  #
#                      #
########################
sheet = book.sheet_by_name('WRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2011', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Alaska', '', '', '', '', '']
6 ['Oct 2010', 27579.0, 66363.0, 405.3379, 168.4495, 11178814.0]
7 ['Nov 2010', 32481.0, 79242.0, 412.9478, 169.2658, 13412958.0]
8 ['Dec 2010', 33099.0, 81190.0, 419.8537, 171.1631, 13896736.0]
9 ['Jan 2011', 34395.0, 84709.0, 421.9274, 171.3182, 14512193.0]
10 ['Feb 2011', 35175.0, 86714.0, 425.4525, 172.5822, 14965290.0]
11 ['Mar 2011', 36138.0, 88718.0, 419.8823, 171.033, 15173707.0]
12 ['Apr 2011', 36855.0, 90545.0, 419.3172, 170.6769, 15453936.0]
13 ['May 2011', 36975.0, 90837.0, 419.4848, 170.7504, 15510451.0]
14 ['Jun 2011', 37167.0, 91501.0, 421.1674, 171.0749, 15653528.0]
15 ['Jul 2011', 36999.0, 91100.0, 423.9704, 172.1897, 15686482.0]
16 ['Aug 2011', 37023.0, 91079.0, 421.4211, 171.3049, 15602275.0]
17 ['Sep 2011', 36980.0, 90531.0, 414.7902, 169.433, 15338941.0]
18 ['Total', 35072.1667, 86044.0833, 419.1009, 170.8284, 176385311.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['American Samoa', '', '', '', '', '']
22 [' No data found.', '', '', '', '', '']
23 ['', '', '', '', '', '']
24 ['', '', '', '', '', '']
25 ['Arizona', '', '', '', '', '']
26 ['Oct 2010', 461881.0, 1055205.0, 298.6856, 130.7397, 137957199.0]
27 ['Nov 2010', 459600.0, 1050181.0, 295.9066, 129.5002, 135998657.0]
28 ['Dec 2010', 460322.0, 1050686.0, 295.5342, 129.4782, 136040894.0]
29 ['Jan 2011', 455595.0, 1039326.0, 294.5434, 129.1149, 134192485.0]
30 ['Feb 2011', 451547.0, 1030139.0, 295.6355, 129.5877, 133493312.0]
31 ['Mar 2011', 454468.0, 1034624.0, 296.957, 130.4411, 134957459.0]
32 ['Apr 2011', 457671.0, 1047088.0, 294.1358, 128.5636, 134617444.0]
33 ['May 2011', 462693.0, 1063434.0, 293.8139, 127.8365, 135945654.0]
34 ['Jun 2011', 470060.0, 1083451.0, 293.3625, 127.2766, 137897979.0]
35 ['Jul 2011', 477227.0, 1102573.0, 294.7337, 127.5697, 140654897.0]
36 ['Aug 2011', 485568.0, 1123333.0, 295.5204, 127.7406, 143495261.0]
37 ['Sep 2011', 487866.0, 1131358.0, 294.2829, 126.9011, 143570623.0]
38 ['Total', 465374.8333, 1067616.5, 295.2498, 128.6996, 1648821864.0]
39 ['', '', '', '', '', '']
40 ['', '', '', '', '', '']
41 ['California', '', '', '', '', '']
42 ['Oct 2010', 1519439.0, 3499878.0, 338.9238, 147.1406, 514974082.0]
43 ['Nov 2010', 1531452.0, 3521881.0, 336.0922, 146.1461, 514709137.0]
44 ['Dec 2010', 1552881.0, 3570066.0, 337.1516, 146.6517, 523556312.0]
45 ['Jan 2011', 1572832.0, 3602170.0, 334.2823, 145.9592, 525769886.0]
46 ['Feb 2011', 1578837.0, 3619055.0, 335.0115, 146.151, 528928486.0]
47 ['Mar 2011', 1613482.0, 3669962.0, 334.5142, 147.0676, 539732576.0]
48 ['Apr 2011', 1616336.0, 3679671.0, 333.1348, 146.3331, 538457778.0]
49 ['May 2011', 1642508.0, 3727005.0, 332.5156, 146.5411, 546159528.0]
50 ['Jun 2011', 1655292.0, 3739233.0, 330.4913, 146.3026, 547059525.0]
51 ['Jul 2011', 1668941.0, 3776195.0, 336.095, 148.5418, 560922707.0]
52 ['Aug 2011', 1695650.0, 3818822.0, 335.3998, 148.9257, 568720754.0]
53 ['Sep 2011', 1706251.0, 3851823.0, 335.7985, 148.7494, 572956506.0]
54 ['Total', 1612825.0833, 3672980.0833, 334.9168, 147.0638, 6481947277.0]
55 ['', '', '', '', '', '']
56 ['', '', '', '', '', '']
57 ['Guam', '', '', '', '', '']
58 ['Oct 2010', 12217.0, 39037.0, 688.1175, 215.3529, 8406731.0]
59 ['Nov 2010', 12460.0, 39469.0, 678.6879, 214.2555, 8456451.0]
60 ['Dec 2010', 12592.0, 39885.0, 681.7282, 215.2268, 8584321.0]
61 ['Jan 2011', 12631.0, 39947.0, 682.3723, 215.762, 8619045.0]
62 ['Feb 2011', 12709.0, 40055.0, 681.8205, 216.334, 8665257.0]
63 ['Mar 2011', 12772.0, 40205.0, 679.2554, 215.7804, 8675450.0]
64 ['Apr 2011', 12902.0, 40499.0, 679.3234, 216.416, 8764630.0]
65 ['May 2011', 13117.0, 41016.0, 673.9082, 215.5172, 8839654.0]
66 ['Jun 2011', 13168.0, 41029.0, 678.7117, 217.8283, 8937276.0]
67 ['Jul 2011', 13392.0, 41655.0, 674.9063, 216.981, 9038345.0]
68 ['Aug 2011', 13496.0, 41818.0, 683.7038, 220.653, 9227266.0]
69 ['Sep 2011', 13884.0, 42960.0, 664.4891, 214.7525, 9225766.0]
70 ['Total', 12945.0, 40631.25, 678.7704, 216.2543, 105440192.0]
71 ['', '', '', '', '', '']
72 ['', '', '', '', '', '']
73 ['Hawaii', '', '', '', '', '']
74 ['Oct 2010', 75134.0, 150480.0, 433.6909, 216.54, 32584933.0]
75 ['Nov 2010', 76182.0, 153018.0, 433.7686, 215.9574, 33045362.0]
76 ['Dec 2010', 77721.0, 156355.0, 434.974, 216.217, 33806611.0]
77 ['Jan 2011', 78091.0, 157163.0, 430.668, 213.9899, 33631292.0]
78 ['Feb 2011', 78748.0, 158152.0, 429.9045, 214.0606, 33854118.0]
79 ['Mar 2011', 79528.0, 159404.0, 431.0181, 215.0386, 34278007.0]
80 ['Apr 2011', 79768.0, 159704.0, 429.5691, 214.5586, 34265867.0]
81 ['May 2011', 80185.0, 160462.0, 430.075, 214.9142, 34485560.0]
82 ['Jun 2011', 81174.0, 162426.0, 430.8924, 215.3427, 34977258.0]
83 ['Jul 2011', 82041.0, 164325.0, 430.7991, 215.081, 35343190.0]
84 ['Aug 2011', 82998.0, 166093.0, 432.5941, 216.1707, 35904448.0]
85 ['Sep 2011', 83922.0, 168151.0, 434.0638, 216.6356, 36427501.0]
86 ['Total', 79624.3333, 159644.4167, 431.8238, 215.3766, 412604147.0]
87 ['', '', '', '', '', '']
88 ['', '', '', '', '', '']
89 ['Idaho', '', '', '', '', '']
90 ['Oct 2010', 89478.0, 216658.0, 315.3709, 130.2456, 28218756.0]
91 ['Nov 2010', 91105.0, 219271.0, 314.8571, 130.8201, 28685053.0]
92 ['Dec 2010', 93023.0, 223347.0, 315.3945, 131.3603, 29338940.0]
93 ['Jan 2011', 94371.0, 226604.0, 315.7036, 131.4772, 29793267.0]
94 ['Feb 2011', 95310.0, 227897.0, 316.923, 132.542, 30205932.0]
95 ['Mar 2011', 97347.0, 231047.0, 314.6747, 132.5818, 30632634.0]
96 ['Apr 2011', 98164.0, 232445.0, 314.3092, 132.7361, 30853844.0]
97 ['May 2011', 98938.0, 233526.0, 313.0675, 132.6374, 30974273.0]
98 ['Jun 2011', 99421.0, 233699.0, 311.2171, 132.399, 30941516.0]
99 ['Jul 2011', 99134.0, 232349.0, 309.7923, 132.1759, 30710948.0]
100 ['Aug 2011', 99977.0, 233450.0, 308.6535, 132.1836, 30858251.0]
101 ['Sep 2011', 100200.0, 233254.0, 307.2429, 131.9837, 30785735.0]
102 ['Total', 96372.3333, 228628.9167, 313.0213, 131.9457, 361999149.0]
103 ['', '', '', '', '', '']
104 ['', '', '', '', '', '']
105 ['Nevada', '', '', '', '', '']
106 ['Oct 2010', 148048.0, 317641.0, 265.9238, 123.9434, 39369490.0]
107 ['Nov 2010', 150561.0, 322950.0, 266.6222, 124.3007, 40142909.0]
108 ['Dec 2010', 151527.0, 324658.0, 265.9092, 124.1073, 40292429.0]
109 ['Jan 2011', 152810.0, 326936.0, 265.0021, 123.8621, 40494964.0]
110 ['Feb 2011', 152993.0, 326836.0, 262.4384, 122.8483, 40151244.0]
111 ['Mar 2011', 154532.0, 329105.0, 268.522, 126.0851, 41495248.0]
112 ['Apr 2011', 155981.0, 331623.0, 266.1334, 125.1776, 41511755.0]
113 ['May 2011', 158378.0, 336524.0, 265.1048, 124.766, 41986766.0]
114 ['Jun 2011', 160348.0, 340195.0, 264.2759, 124.5642, 42376109.0]
115 ['Jul 2011', 161488.0, 342462.0, 264.1991, 124.5831, 42664980.0]
116 ['Aug 2011', 164255.0, 347848.0, 264.8676, 125.0714, 43505824.0]
117 ['Sep 2011', 164908.0, 348727.0, 259.9966, 122.9487, 42875516.0]
118 ['Total', 156319.0833, 332958.75, 264.8787, 124.3566, 496867234.0]
119 ['', '', '', '', '', '']
120 ['', '', '', '', '', '']
121 ['Oregon', '', '', '', '', '']
122 ['Oct 2010', 399765.0, 744532.0, 236.7441, 127.1161, 94642022.0]
123 ['Nov 2010', 403294.0, 749761.0, 236.7325, 127.3377, 95472815.0]
124 ['Dec 2010', 412047.0, 756352.0, 234.5537, 127.7806, 96647132.0]
125 ['Jan 2011', 411949.0, 764667.0, 236.6101, 127.469, 97471303.0]
126 ['Feb 2011', 415269.0, 769223.0, 238.3255, 128.6612, 98969176.0]
127 ['Mar 2011', 418286.0, 774317.0, 237.7853, 128.4516, 99462267.0]
128 ['Apr 2011', 421552.0, 779025.0, 237.8299, 128.6963, 100257659.0]
129 ['May 2011', 423581.0, 781235.0, 237.4195, 128.7274, 100566378.0]
130 ['Jun 2011', 436098.0, 776972.0, 231.325, 129.8378, 100880368.0]
131 ['Jul 2011', 428504.0, 788165.0, 236.4695, 128.5621, 101328137.0]
132 ['Aug 2011', 432001.0, 793120.0, 235.6834, 128.3733, 101815449.0]
133 ['Sep 2011', 433972.0, 795706.0, 234.3224, 127.7976, 101689350.0]
134 ['Total', 419693.1667, 772756.25, 236.1253, 128.2425, 1189202056.0]
135 ['', '', '', '', '', '']
136 ['', '', '', '', '', '']
137 ['Washington', '', '', '', '', '']
138 ['Oct 2010', 518181.0, 1015622.0, 244.0616, 124.5228, 126468064.0]
139 ['Nov 2010', 522769.0, 1019791.0, 243.0716, 124.6043, 127070311.0]
140 ['Dec 2010', 530329.0, 1034304.0, 245.0839, 125.6643, 129975094.0]
141 ['Jan 2011', 535238.0, 1043025.0, 245.4091, 125.934, 131352267.0]
142 ['Feb 2011', 537964.0, 1047832.0, 247.8379, 127.2417, 133327879.0]
143 ['Mar 2011', 543079.0, 1056106.0, 251.1781, 129.1628, 136409556.0]
144 ['Apr 2011', 547166.0, 1064797.0, 247.0543, 126.9535, 135179736.0]
145 ['May 2011', 549351.0, 1060919.0, 245.6417, 127.1949, 134943524.0]
146 ['Jun 2011', 553334.0, 1066531.0, 246.3446, 127.8077, 136310865.0]
147 ['Jul 2011', 556523.0, 1075482.0, 245.2259, 126.8955, 136473850.0]
148 ['Aug 2011', 562532.0, 1083716.0, 243.9691, 126.6388, 137240448.0]
149 ['Sep 2011', 565925.0, 1088193.0, 243.5053, 126.6372, 137805764.0]
150 ['Total', 543532.5833, 1054693.1667, 245.7009, 126.6211, 1602557358.0]
151 ['', '', '', '', '', '']
152 ['', '', '', '', '', '']
153 ['Outlying Areas', '', '', '', '', '']
154 [' No data found.', '', '', '', '', '']
155 ['', '', '', '', '', '']
156 ['', '', '', '', '', '']
157 ['WRO', '', '', '', '', '']
158 ['Oct 2010', 3251722.0, 7105416.0, 305.6227, 139.8652, 993800091.0]
159 ['Nov 2010', 3279904.0, 7155564.0, 303.9704, 139.3312, 996993653.0]
160 ['Dec 2010', 3323541.0, 7236843.0, 304.5362, 139.8591, 1012138469.0]
161 ['Jan 2011', 3347912.0, 7284547.0, 303.424, 139.4509, 1015836702.0]
162 ['Feb 2011', 3358552.0, 7305903.0, 304.4647, 139.9636, 1022560694.0]
163 ['Mar 2011', 3409632.0, 7383488.0, 305.2578, 140.9655, 1040816904.0]
164 ['Apr 2011', 3426395.0, 7425397.0, 303.34, 139.974, 1039362649.0]
165 ['May 2011', 3465726.0, 7494958.0, 302.7971, 140.0157, 1049411788.0]
166 ['Jun 2011', 3506062.0, 7535037.0, 300.9172, 140.0172, 1055034424.0]
167 ['Jul 2011', 3524249.0, 7614306.0, 304.412, 140.8958, 1072823536.0]
168 ['Aug 2011', 3573500.0, 7699279.0, 304.0073, 141.1002, 1086369976.0]
169 ['Sep 2011', 3593908.0, 7750703.0, 303.479, 140.7196, 1090675702.0]
170 ['Total', 3421758.5833, 7415953.4167, 303.8356, 140.1913, 12475824588.0]
171 ['', '', '', '', '', '']
172 ['', '', '', '', '', '']
173 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
174 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [523]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,25,41,57,73,89,105,121,137,153,157]:
        #for the rows that have the state names
        state = row[0]
        if state == 'WRO':
            break
        else:
            continue         
    if i in [18,23,38,54,70,86,102,118,134,150,155,170]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [524]:
pprint.pprint(snap_data)

{'Alabama': {'cost_by_household': 307.3512,
             'cost_by_individual': 135.1784,
             'household_participation': 404792.5,
             'individual_participation': 920364.75,
             'total_cost': 1492961298.0},
 'Alaska': {'cost_by_household': 419.1009,
            'cost_by_individual': 170.8284,
            'household_participation': 35072.1667,
            'individual_participation': 86044.0833,
            'total_cost': 176385311.0},
 'American Samoa': {'cost_by_household': '',
                    'cost_by_individual': '',
                    'household_participation': '',
                    'individual_participation': '',
                    'total_cost': ''},
 'Arizona': {'cost_by_household': 295.2498,
             'cost_by_individual': 128.6996,
             'household_participation': 465374.8333,
             'individual_participation': 1067616.5,
             'total_cost': 1648821864.0},
 'Arkansas': {'cost_by_household': 285.674,
              'cost_by_individual': 123.7184,
              'household_participation': 210670.0,
              'individual_participation': 486451.0833,
              'total_cost': 722195399.0},
 'California': {'cost_by_household': 334.9168,
                'cost_by_individual': 147.0638,
                'household_participation': 1612825.0833,
                'individual_participation': 3672980.0833,
                'total_cost': 6481947277.0},
 'Colorado': {'cost_by_household': 317.7326,
              'cost_by_individual': 140.292,
              'household_participation': 200063.5833,
              'individual_participation': 453103.0,
              'total_cost': 762800608.0},
 'Connecticut': {'cost_by_household': 262.1799,
                 'cost_by_individual': 142.4675,
                 'household_participation': 205771.5833,
                 'individual_participation': 378677.0833,
                 'total_cost': 647390087.0},
 'Delaware': {'cost_by_household': 276.4968,
              'cost_by_individual': 126.8002,
              'household_participation': 61876.8333,
              'individual_participation': 134926.8333,
              'total_cost': 205304944.0},
 'District of Columbia': {'cost_by_household': 251.1224,
                          'cost_by_individual': 141.6753,
                          'household_participation': 76075.3333,
                          'individual_participation': 134845.0833,
                          'total_cost': 229250674.0},
 'Florida': {'cost_by_household': 258.6156,
             'cost_by_individual': 139.5465,
             'household_participation': 1659063.1667,
             'individual_participation': 3074670.5,
             'total_cost': 5148715738.0},
 'Georgia': {'cost_by_household': 305.1057,
             'cost_by_individual': 135.3723,
             'household_participation': 789785.0833,
             'individual_participation': 1780039.25,
             'total_cost': 2891615163.0},
 'Guam': {'cost_by_household': 678.7704,
          'cost_by_individual': 216.2543,
          'household_participation': 12945.0,
          'individual_participation': 40631.25,
          'total_cost': 105440192.0},
 'Hawaii': {'cost_by_household': 431.8238,
            'cost_by_individual': 215.3766,
            'household_participation': 79624.3333,
            'individual_participation': 159644.4167,
            'total_cost': 412604147.0},
 'Idaho': {'cost_by_household': 313.0213,
           'cost_by_individual': 131.9457,
           'household_participation': 96372.3333,
           'individual_participation': 228628.9167,
           'total_cost': 361999149.0},
 'Illinois': {'cost_by_household': 290.3313,
              'cost_by_individual': 139.1517,
              'household_participation': 859784.8333,
              'individual_participation': 1793886.4167,
              'total_cost': 2995469012.0},
 'Indiana': {'cost_by_household': 303.082,
             'cost_by_individual': 131.6604,
             'household_participation': 381216.5,
             'individual_participation': 877559.8333,
             'total_cost': 1386478333.0},
 'Iowa': {'cost_by_household': 272.6993,
          'cost_by_individual': 126.3261,
          'household_participation': 173186.0,
          'individual_participation': 373855.5833,
          'total_cost': 566732507.0},
 'Kansas': {'cost_by_household': 271.6204,
            'cost_by_individual': 126.3407,
            'household_participation': 138909.5,
            'individual_participation': 298642.0833,
            'total_cost': 452767878.0},
 'Kentucky': {'cost_by_household': 275.2506,
              'cost_by_individual': 127.5989,
              'household_participation': 381739.5833,
              'individual_participation': 823471.8333,
              'total_cost': 1260888769.0},
 'Louisiana': {'cost_by_household': 297.3099,
               'cost_by_individual': 130.5903,
               'household_participation': 388515.8333,
               'individual_participation': 884518.6667,
               'total_cost': 1386115227.0},
 'Maine': {'cost_by_household': 252.3642,
           'cost_by_individual': 128.4338,
           'household_participation': 126183.8333,
           'individual_participation': 247943.25,
           'total_cost': 382131426.0},
 'Maryland': {'cost_by_household': 262.7396,
              'cost_by_individual': 129.1894,
              'household_participation': 328327.5833,
              'individual_participation': 667737.9167,
              'total_cost': 1035175750.0},
 'Massachusetts': {'cost_by_household': 240.7567,
                   'cost_by_individual': 132.2886,
                   'household_participation': 447065.9167,
                   'individual_participation': 813630.9167,
                   'total_cost': 1291609491.0},
 'Michigan': {'cost_by_household': 271.4268,
              'cost_by_individual': 136.1816,
              'household_participation': 967565.6667,
              'individual_participation': 1928477.6667,
              'total_cost': 3151479174.0},
 'Minnesota': {'cost_by_household': 236.9879,
               'cost_by_individual': 115.0397,
               'household_participation': 245585.3333,
               'individual_participation': 505918.6667,
               'total_cost': 698408893.0},
 'Mississippi': {'cost_by_household': 281.1386,
                 'cost_by_individual': 123.2887,
                 'household_participation': 273029.4167,
                 'individual_participation': 622596.4167,
                 'total_cost': 921109139.0},
 'Missouri': {'cost_by_household': 276.1563,
              'cost_by_individual': 127.0548,
              'household_participation': 433898.8333,
              'individual_participation': 943088.0,
              'total_cost': 1437886768.0},
 'Montana': {'cost_by_household': 281.9629,
             'cost_by_individual': 129.6593,
             'household_participation': 57132.5,
             'individual_participation': 124242.9167,
             'total_cost': 193310950.0},
 'Nebraska': {'cost_by_household': 280.5513,
              'cost_by_individual': 122.6903,
              'household_participation': 76182.5833,
              'individual_participation': 174203.9167,
              'total_cost': 256477504.0},
 'Nevada': {'cost_by_household': 264.8787,
            'cost_by_individual': 124.3566,
            'household_participation': 156319.0833,
            'individual_participation': 332958.75,
            'total_cost': 496867234.0},
 'New Hampshire': {'cost_by_household': 250.4279,
                   'cost_by_individual': 119.5396,
                   'household_participation': 54133.8333,
                   'individual_participation': 113407.0,
                   'total_cost': 162679478.0},
 'New Jersey': {'cost_by_household': 272.7679,
                'cost_by_individual': 133.2648,
                'household_participation': 370887.0833,
                'individual_participation': 759136.0833,
                'total_cost': 1213993288.0},
 'New Mexico': {'cost_by_household': 294.0675,
                'cost_by_individual': 127.0657,
                'household_participation': 179006.9167,
                'individual_participation': 414274.75,
                'total_cost': 631681353.0},
 'New York': {'cost_by_household': 278.5602,
              'cost_by_individual': 148.6299,
              'household_participation': 1600689.75,
              'individual_participation': 2999990.5833,
              'total_cost': 5350660541.0},
 'North Carolina': {'cost_by_household': 269.7016,
                    'cost_by_individual': 124.5802,
                    'household_participation': 734482.3333,
                    'individual_participation': 1590068.9167,
                    'total_cost': 2377093020.0},
 'North Dakota': {'cost_by_household': 286.5715,
                  'cost_by_individual': 131.2467,
                  'household_participation': 27892.5,
                  'individual_participation': 60902.0833,
                  'total_cost': 95918344.0},
 'Ohio': {'cost_by_household': 293.6827,
          'cost_by_individual': 139.8688,
          'household_participation': 847376.5,
          'individual_participation': 1779237.0,
          'total_cost': 2986317777.0},
 'Oklahoma': {'cost_by_household': 290.0369,
              'cost_by_individual': 128.4275,
              'household_participation': 272189.0833,
              'individual_participation': 614703.6667,
              'total_cost': 947338484.0},
 'Oregon': {'cost_by_household': 236.1253,
            'cost_by_individual': 128.2425,
            'household_participation': 419693.1667,
            'individual_participation': 772756.25,
            'total_cost': 1189202056.0},
 'Outlying Areas': {'cost_by_household': '',
                    'cost_by_individual': '',
                    'household_participation': '',
                    'individual_participation': '',
                    'total_cost': ''},
 'Pennsylvania': {'cost_by_household': 270.4491,
                  'cost_by_individual': 128.4026,
                  'household_participation': 815764.5833,
                  'individual_participation': 1718210.6667,
                  'total_cost': 2647473519.0},
 'Puerto Rico': {'cost_by_household': '',
                 'cost_by_individual': '',
                 'household_participation': '',
                 'individual_participation': '',
                 'total_cost': ''},
 'Rhode Island': {'cost_by_household': 265.0821,
                  'cost_by_individual': 142.9121,
                  'household_participation': 86368.25,
                  'individual_participation': 160201.0833,
                  'total_cost': 274736117.0},
 'South Carolina': {'cost_by_household': 285.5632,
                    'cost_by_individual': 132.208,
                    'household_participation': 390936.4167,
                    'individual_participation': 844404.6667,
                    'total_cost': 1339644859.0},
 'South Dakota': {'cost_by_household': 309.9969,
                  'cost_by_individual': 132.7014,
                  'household_participation': 43585.25,
                  'individual_participation': 101817.25,
                  'total_cost': 162135500.0},
 'Tennessee': {'cost_by_household': 279.1811,
               'cost_by_individual': 133.815,
               'household_participation': 611502.0,
               'individual_participation': 1275789.75,
               'total_cost': 2048637590.0},
 'Texas': {'cost_by_household': 310.4971,
           'cost_by_individual': 125.5703,
           'household_participation': 1608475.9167,
           'individual_participation': 3977272.6667,
           'total_cost': 5993125493.0},
 'Utah': {'cost_by_household': 299.0944,
          'cost_by_individual': 117.7532,
          'household_participation': 111799.0,
          'individual_participation': 283970.75,
          'total_cost': 401261439.0},
 'Vermont': {'cost_by_household': 243.0447,
             'cost_by_individual': 122.1025,
             'household_participation': 46238.5833,
             'individual_participation': 92037.75,
             'total_cost': 134856526.0},
 'Virgin Islands': {'cost_by_household': 426.3017,
                    'cost_by_individual': 176.11,
                    'household_participation': 9359.0,
                    'individual_participation': 22654.9167,
                    'total_cost': 47877095.0},
 'Virginia': {'cost_by_household': 273.4764,
              'cost_by_individual': 129.5477,
              'household_participation': 406811.1667,
              'individual_participation': 858782.1667,
              'total_cost': 1335038906.0},
 'Washington': {'cost_by_household': 245.7009,
                'cost_by_individual': 126.6211,
                'household_participation': 543532.5833,
                'individual_participation': 1054693.1667,
                'total_cost': 1602557358.0},
 'West Virginia': {'cost_by_household': 257.8953,
                   'cost_by_individual': 119.8108,
                   'household_participation': 160721.0,
                   'individual_participation': 345955.4167,
                   'total_cost': 497390191.0},
 'Wisconsin': {'cost_by_household': 251.5047,
               'cost_by_individual': 116.2819,
               'household_participation': 370371.8333,
               'individual_participation': 801072.9167,
               'total_cost': 1117802969.0},
 'Wyoming': {'cost_by_household': 288.7728,
             'cost_by_individual': 122.9551,
             'household_participation': 15341.4167,
             'individual_participation': 36030.9167,
             'total_cost': 53162213.0}}

In [525]:
snap_data_2011 = pd.DataFrame.from_dict(snap_data, orient = "index")

In [526]:
pd.DataFrame.to_csv(snap_data_2011,'SNAP/SNAP DFs/snap_2011_df.csv')

# 2010

In [527]:
book = xlrd.open_workbook('SNAP/FY10.xls')

In [528]:
sheet = book.sheet_by_name('NERO')

In [529]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2010', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Connecticut', '', '', '', '', '']
6 ['Oct 2009', 163500.0, 305078.0, 273.4201, 146.5336, 44704180.0]
7 ['Nov 2009', 167878.0, 313839.0, 264.2118, 141.3315, 44355346.0]
8 ['Dec 2009', 170340.0, 318918.0, 272.1459, 145.3582, 46357336.0]
9 ['Jan 2010', 173273.0, 324295.0, 262.7431, 140.3854, 45526279.0]
10 ['Feb 2010', 175309.0, 327242.0, 265.5443, 142.2565, 46552313.0]
11 ['Mar 2010', 179585.0, 334372.0, 264.3814, 141.9944, 47478939.0]
12 ['Apr 2010', 182331.0, 339218.0, 261.6196, 140.6216, 47701372.0]
13 ['May 2010', 185210.0, 344243.0, 259.6582, 139.7016, 48091302.0]
14 ['Jun 2010', 187728.0, 348636.0, 258.3694, 139.1227, 48503170.0]
15 ['Jul 2010', 190206.0, 353104.0, 262.1393, 141.2062, 49860466.0]
16 ['Aug 2010', 193807.0, 359487.0, 256.8766, 138.4876, 49784490.0]
17 ['Sep 2010', 196388.0, 364341.0, 258.5147, 139.3453, 50769189.0]
18 ['Total', 180462.9167, 336064.4167, 263.0662, 141.2637, 569684382.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Maine', '', '', '', '', '']
22 ['Oct 2009', 108003.0, 218264.0, 260.4655, 128.8854, 28131050.0]
23 ['Nov 2009', 108945.0, 219862.0, 259.8473, 128.7583, 28309066.0]
24 ['Dec 2009', 110917.0, 224068.0, 260.0819, 128.7444, 28847501.0]
25 ['Jan 2010', 111799.0, 225496.0, 260.3692, 129.0889, 29109021.0]
26 ['Feb 2010', 112662.0, 227110.0, 261.1028, 129.5248, 29416366.0]
27 ['Mar 2010', 114805.0, 231666.0, 259.3481, 128.5232, 29774455.0]
28 ['Apr 2010', 114985.0, 230914.0, 259.1585, 129.0495, 29799342.0]
29 ['May 2010', 116181.0, 232768.0, 259.2043, 129.3761, 30114610.0]
30 ['Jun 2010', 117148.0, 235455.0, 258.1955, 128.4623, 30247088.0]
31 ['Jul 2010', 117772.0, 236262.0, 260.5926, 129.9004, 30690517.0]
32 ['Aug 2010', 118372.0, 237377.0, 260.5609, 129.933, 30843110.0]
33 ['Sep 2010', 118937.0, 237530.0, 259.0885, 129.7319, 30815209.0]
34 ['Total', 114210.5, 229731.0, 259.8253, 129.1718, 356097335.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Massachusetts', '', '', '', '', '']
38 ['Oct 2009', 384781.0, 712389.0, 238.4809, 128.8101, 91762924.0]
39 ['Nov 2009', 389675.0, 720511.0, 238.7343, 129.115, 93028798.0]
40 ['Dec 2009', 392999.0, 726541.0, 241.0969, 130.4136, 94750845.0]
41 ['Jan 2010', 399757.0, 737061.0, 236.2833, 128.1521, 94455899.0]
42 ['Feb 2010', 402247.0, 740985.0, 241.8234, 131.2749, 97272728.0]
43 ['Mar 2010', 406277.0, 747150.0, 238.3433, 129.6037, 96833384.0]
44 ['Apr 2010', 409181.0, 751393.0, 236.0835, 128.5624, 96600881.0]
45 ['May 2010', 411991.0, 755739.0, 239.2363, 130.4196, 98563213.0]
46 ['Jun 2010', 415582.0, 762323.0, 238.0009, 129.7467, 98908873.0]
47 ['Jul 2010', 421620.0, 771886.0, 238.7663, 130.419, 100668636.0]
48 ['Aug 2010', 424783.0, 778033.0, 238.2085, 130.0548, 101186930.0]
49 ['Sep 2010', 428753.0, 785435.0, 237.6068, 129.7047, 101874633.0]
50 ['Total', 407303.8333, 749120.5, 238.5418, 129.6974, 1165907744.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['New Hampshire', '', '', '', '', '']
54 ['Oct 2009', 45179.0, 94763.0, 256.1592, 122.1259, 11573015.0]
55 ['Nov 2009', 46051.0, 96729.0, 255.0787, 121.4385, 11746627.0]
56 ['Dec 2009', 47201.0, 99262.0, 253.4628, 120.5265, 11963697.0]
57 ['Jan 2010', 48055.0, 101031.0, 253.0346, 120.3549, 12159580.0]
58 ['Feb 2010', 48895.0, 102783.0, 257.5767, 122.5321, 12594213.0]
59 ['Mar 2010', 50005.0, 105115.0, 256.5869, 122.0628, 12830626.0]
60 ['Apr 2010', 50588.0, 106319.0, 254.1248, 120.916, 12855665.0]
61 ['May 2010', 51048.0, 108118.0, 256.7942, 121.2456, 13108830.0]
62 ['Jun 2010', 51391.0, 108682.0, 255.0894, 120.6207, 13109298.0]
63 ['Jul 2010', 51609.0, 109159.0, 255.3017, 120.7034, 13175863.0]
64 ['Aug 2010', 52040.0, 109967.0, 255.6465, 120.9803, 13303843.0]
65 ['Sep 2010', 52385.0, 110576.0, 255.6558, 121.116, 13392527.0]
66 ['Total', 49537.25, 104375.3333, 255.3866, 121.2082, 151813784.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['New York', '', '', '', '', '']
70 ['Oct 2009', 1375776.0, 2599938.0, 286.7834, 151.7535, 394549664.0]
71 ['Nov 2009', 1386412.0, 2623264.0, 285.6523, 150.9691, 396031841.0]
72 ['Dec 2009', 1414173.0, 2673143.0, 285.9126, 151.2564, 404329873.0]
73 ['Jan 2010', 1428694.0, 2699586.0, 286.8155, 151.7905, 409771519.0]
74 ['Feb 2010', 1436855.0, 2712437.0, 284.8722, 150.9049, 409320081.0]
75 ['Mar 2010', 1461313.0, 2754632.0, 284.923, 151.1496, 416361642.0]
76 ['Apr 2010', 1474062.0, 2775875.0, 282.8609, 150.2065, 416954568.0]
77 ['May 2010', 1487651.0, 2799734.0, 282.4234, 150.0669, 420147438.0]
78 ['Jun 2010', 1501953.0, 2824845.0, 282.3007, 150.0976, 424002338.0]
79 ['Jul 2010', 1521753.0, 2860394.0, 280.8345, 149.4063, 427360812.0]
80 ['Aug 2010', 1528589.0, 2874189.0, 282.4558, 150.2193, 431758799.0]
81 ['Sep 2010', 1540393.0, 2895995.0, 281.9487, 149.9698, 434311727.0]
82 ['Total', 1463135.3333, 2757836.0, 283.9166, 150.6284, 4984900302.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Rhode Island', '', '', '', '', '']
86 ['Oct 2009', 63015.0, 122836.0, 282.6102, 144.9793, 17808683.0]
87 ['Nov 2009', 65378.0, 126870.0, 284.243, 146.4747, 18583242.0]
88 ['Dec 2009', 66664.0, 128766.0, 276.478, 143.1366, 18431128.0]
89 ['Jan 2010', 69176.0, 133214.0, 270.7979, 140.6212, 18732713.0]
90 ['Feb 2010', 71893.0, 138007.0, 271.4218, 141.3938, 19513330.0]
91 ['Mar 2010', 73467.0, 140390.0, 269.6537, 141.1116, 19810652.0]
92 ['Apr 2010', 74813.0, 142351.0, 270.5005, 142.1624, 20236953.0]
93 ['May 2010', 76161.0, 144479.0, 269.7234, 142.1826, 20542407.0]
94 ['Jun 2010', 76965.0, 145361.0, 270.1101, 143.0165, 20789020.0]
95 ['Jul 2010', 77601.0, 146338.0, 268.084, 142.1612, 20803590.0]
96 ['Aug 2010', 78950.0, 148529.0, 266.8901, 141.8644, 21070977.0]
97 ['Sep 2010', 79994.0, 150450.0, 266.2159, 141.5465, 21295677.0]
98 ['Total', 72839.75, 138965.9167, 271.8506, 142.492, 237618372.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['Vermont', '', '', '', '', '']
102 ['Oct 2009', 40844.0, 82770.0, 245.1347, 120.9651, 10012280.0]
103 ['Nov 2009', 41129.0, 83342.0, 240.6329, 118.7515, 9896991.0]
104 ['Dec 2009', 41643.0, 84300.0, 247.058, 122.0432, 10288238.0]
105 ['Jan 2010', 42046.0, 84968.0, 240.7037, 119.111, 10120626.0]
106 ['Feb 2010', 42255.0, 85276.0, 242.5562, 120.1887, 10249214.0]
107 ['Mar 2010', 42601.0, 85825.0, 245.0978, 121.6593, 10441413.0]
108 ['Apr 2010', 42810.0, 86243.0, 244.4628, 121.3484, 10465453.0]
109 ['May 2010', 42946.0, 86418.0, 243.5196, 121.0187, 10458191.0]
110 ['Jun 2010', 42950.0, 86286.0, 244.7917, 121.8483, 10513802.0]
111 ['Jul 2010', 42949.0, 86244.0, 245.1957, 122.106, 10530909.0]
112 ['Aug 2010', 43296.0, 86948.0, 245.5606, 122.2776, 10631792.0]
113 ['Sep 2010', 43743.0, 87838.0, 244.6774, 121.8484, 10702924.0]
114 ['Total', 42434.3333, 85538.1667, 244.1259, 121.1076, 124311833.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['NERO', '', '', '', '', '']
118 ['Oct 2009', 2181098.0, 4136038.0, 274.4222, 144.7138, 598541796.0]
119 ['Nov 2009', 2205468.0, 4184417.0, 272.9361, 143.8556, 601951911.0]
120 ['Dec 2009', 2243937.0, 4254998.0, 274.0579, 144.5285, 614968618.0]
121 ['Jan 2010', 2272800.0, 4305651.0, 272.7366, 143.9679, 619875637.0]
122 ['Feb 2010', 2290116.0, 4333840.0, 272.8762, 144.195, 624918245.0]
123 ['Mar 2010', 2328053.0, 4399150.0, 272.1292, 144.0122, 633531111.0]
124 ['Apr 2010', 2348770.0, 4432313.0, 270.19, 143.179, 634614234.0]
125 ['May 2010', 2371188.0, 4471499.0, 270.3396, 143.3582, 641025991.0]
126 ['Jun 2010', 2393717.0, 4511588.0, 269.9039, 143.2031, 646073589.0]
127 ['Jul 2010', 2423510.0, 4563387.0, 269.4814, 143.1154, 653090793.0]
128 ['Aug 2010', 2439837.0, 4594530.0, 269.9278, 143.34, 658579941.0]
129 ['Sep 2010', 2460593.0, 4632165.0, 269.513, 143.1646, 663161886.0]
130 ['Total', 2329923.9167, 4401631.3333, 271.48, 143.703, 7590333752.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
134 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [530]:
snap_data = {}

########################
#                      #
# NERO                 #
#                      #
########################

for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117]:
        #for the rows that have the state names
        state = row[0]
        if state == 'NERO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [531]:
########################
#                      #
# MARO                 #
#                      #
########################

sheet = book.sheet_by_name('MARO')

In [532]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2010', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Delaware', '', '', '', '', '']
6 ['Oct 2009', 46056.0, 103620.0, 289.9016, 128.8526, 13351708.0]
7 ['Nov 2009', 45810.0, 102870.0, 275.771, 122.8061, 12633068.0]
8 ['Dec 2009', 48356.0, 108510.0, 278.9771, 124.3224, 13490219.0]
9 ['Jan 2010', 48820.0, 109215.0, 282.1701, 126.1324, 13775546.0]
10 ['Feb 2010', 48514.0, 108291.0, 282.5807, 126.5952, 13709121.0]
11 ['Mar 2010', 49476.0, 110245.0, 284.0875, 127.4934, 14055514.0]
12 ['Apr 2010', 50283.0, 111706.0, 283.9912, 127.835, 14279931.0]
13 ['May 2010', 51116.0, 113497.0, 281.334, 126.7053, 14380671.0]
14 ['Jun 2010', 52720.0, 117026.0, 282.2247, 127.1417, 14878887.0]
15 ['Jul 2010', 53669.0, 118883.0, 283.2927, 127.8908, 15204038.0]
16 ['Aug 2010', 54870.0, 121539.0, 281.9128, 127.2724, 15468557.0]
17 ['Sep 2010', 56394.0, 124755.0, 282.4416, 127.6743, 15928012.0]
18 ['Total', 50507.0, 112513.0833, 282.3953, 126.7669, 171155272.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['District of Columbia', '', '', '', '', '']
22 ['Oct 2009', 62206.0, 112778.0, 250.2745, 138.0462, 15568574.0]
23 ['Nov 2009', 62713.0, 113672.0, 249.878, 137.858, 15670599.0]
24 ['Dec 2009', 63253.0, 114375.0, 248.245, 137.2874, 15702243.0]
25 ['Jan 2010', 63666.0, 114818.0, 246.6875, 136.787, 15705606.0]
26 ['Feb 2010', 62950.0, 113374.0, 247.6065, 137.4815, 15586830.0]
27 ['Mar 2010', 64729.0, 116068.0, 246.1224, 137.258, 15931259.0]
28 ['Apr 2010', 65048.0, 116540.0, 242.6113, 135.416, 15781382.0]
29 ['May 2010', 66664.0, 119259.0, 249.492, 139.4623, 16632136.0]
30 ['Jun 2010', 68051.0, 121340.0, 246.777, 138.3997, 16793424.0]
31 ['Jul 2010', 69766.0, 124281.0, 246.4158, 138.3272, 17191442.0]
32 ['Aug 2010', 71020.0, 126651.0, 246.7781, 138.3817, 17526178.0]
33 ['Sep 2010', 72320.0, 128759.0, 246.1786, 138.271, 17803635.0]
34 ['Total', 66032.1667, 118492.9167, 247.2195, 137.7672, 195893308.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Maryland', '', '', '', '', '']
38 ['Oct 2009', 245549.0, 522010.0, 277.7488, 130.6506, 68200945.0]
39 ['Nov 2009', 247928.0, 527111.0, 278.7767, 131.1233, 69116556.0]
40 ['Dec 2009', 252148.0, 535403.0, 278.3325, 131.0807, 70180988.0]
41 ['Jan 2010', 255424.0, 541413.0, 277.0156, 130.6885, 70756445.0]
42 ['Feb 2010', 254519.0, 538394.0, 277.0507, 130.9722, 70514660.0]
43 ['Mar 2010', 260500.0, 549908.0, 277.9703, 131.6789, 72411255.0]
44 ['Apr 2010', 264603.0, 558731.0, 274.8075, 130.1429, 72714899.0]
45 ['May 2010', 267613.0, 565237.0, 275.6075, 130.4871, 73756161.0]
46 ['Jun 2010', 275206.0, 580252.0, 274.0631, 129.9846, 75423817.0]
47 ['Jul 2010', 279977.0, 588726.0, 271.3562, 129.0473, 75973484.0]
48 ['Aug 2010', 290444.0, 606893.0, 272.5612, 130.441, 79163751.0]
49 ['Sep 2010', 295644.0, 616102.0, 269.7932, 129.4635, 79762752.0]
50 ['Total', 265796.25, 560848.3333, 275.2659, 130.4535, 877975713.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['New Jersey', '', '', '', '', '']
54 ['Oct 2009', 276581.0, 569557.0, 288.9297, 140.3063, 79912455.0]
55 ['Nov 2009', 281913.0, 578954.0, 288.2032, 140.3362, 81248226.0]
56 ['Dec 2009', 287923.0, 589609.0, 288.9122, 141.0841, 83184476.0]
57 ['Jan 2010', 291890.0, 597234.0, 285.4936, 139.5311, 83332737.0]
58 ['Feb 2010', 292921.0, 598151.0, 285.5594, 139.8415, 83646333.0]
59 ['Mar 2010', 292679.0, 597486.0, 285.2703, 139.7399, 83492637.0]
60 ['Apr 2010', 302276.0, 616705.0, 281.5269, 137.9895, 85098820.0]
61 ['May 2010', 309422.0, 632297.0, 280.6144, 137.322, 86828277.0]
62 ['Jun 2010', 316054.0, 647262.0, 279.2993, 136.3801, 88273657.0]
63 ['Jul 2010', 326610.0, 669770.0, 278.1767, 135.6515, 90855278.0]
64 ['Aug 2010', 330216.0, 677167.0, 277.7124, 135.4246, 91705093.0]
65 ['Sep 2010', 336693.0, 690075.0, 275.3691, 134.3547, 92714848.0]
66 ['Total', 303764.8333, 622022.25, 282.6454, 138.03, 1030292837.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Pennsylvania', '', '', '', '', '']
70 ['Oct 2009', 698678.0, 1483361.0, 266.2519, 125.4073, 186024370.0]
71 ['Nov 2009', 709073.0, 1508095.0, 263.0202, 123.6663, 186500516.0]
72 ['Dec 2009', 718299.0, 1529044.0, 264.6659, 124.3321, 190109239.0]
73 ['Jan 2010', 729788.0, 1554442.0, 260.7483, 122.4176, 190290997.0]
74 ['Feb 2010', 733932.0, 1564824.0, 260.5924, 122.2227, 191257069.0]
75 ['Mar 2010', 741514.0, 1579534.0, 261.6373, 122.8259, 194007709.0]
76 ['Apr 2010', 747177.0, 1590177.0, 260.297, 122.3058, 194487904.0]
77 ['May 2010', 745158.0, 1587005.0, 262.9234, 123.4524, 195919507.0]
78 ['Jun 2010', 748374.0, 1592282.0, 263.5277, 123.8582, 197217252.0]
79 ['Jul 2010', 764349.0, 1625400.0, 262.858, 123.6097, 200915226.0]
80 ['Aug 2010', 771575.0, 1638967.0, 262.2148, 123.4426, 202318410.0]
81 ['Sep 2010', 774313.0, 1644259.0, 262.8485, 123.7804, 203527005.0]
82 ['Total', 740185.8333, 1574782.5, 262.6114, 123.4337, 2332575204.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Puerto Rico', '', '', '', '', '']
86 [' No data found.', '', '', '', '', '']
87 ['', '', '', '', '', '']
88 ['', '', '', '', '', '']
89 ['Virginia', '', '', '', '', '']
90 ['Oct 2009', 340649.0, 741363.0, 278.309, 127.8802, 94805675.0]
91 ['Nov 2009', 346691.0, 753035.0, 278.9636, 128.4325, 96714166.0]
92 ['Dec 2009', 351911.0, 763163.0, 278.1654, 128.2681, 97889458.0]
93 ['Jan 2010', 356452.0, 771357.0, 277.2665, 128.1277, 98832200.0]
94 ['Feb 2010', 358971.0, 774978.0, 277.7031, 128.6325, 99687342.0]
95 ['Mar 2010', 364187.0, 784523.0, 277.5448, 128.8403, 101078212.0]
96 ['Apr 2010', 366932.0, 790363.0, 276.8871, 128.5469, 101598731.0]
97 ['May 2010', 369375.0, 794734.0, 277.3235, 128.8939, 102436374.0]
98 ['Jun 2010', 373810.0, 802376.0, 276.0084, 128.5865, 103174708.0]
99 ['Jul 2010', 378334.0, 811169.0, 276.5148, 128.9681, 104614947.0]
100 ['Aug 2010', 383528.0, 820549.0, 276.6099, 129.2886, 106087632.0]
101 ['Sep 2010', 387061.0, 826277.0, 275.3493, 128.9846, 106576972.0]
102 ['Total', 364825.0833, 786157.25, 277.1868, 128.6316, 1213496417.0]
103 ['', '', '', '', '', '']
104 ['', '', '', '', '', '']
105 ['Virgin Islands', '', '', '', '', '']
106 ['Oct 2009', 7600.0, 19186.0, 451.8225, 178.9769, 3433851.0]
107 ['Nov 2009', 7735.0, 19531.0, 450.5139, 178.4202, 3484725.0]
108 ['Dec 2009', 7949.0, 19903.0, 443.8012, 177.2485, 3527776.0]
109 ['Jan 2010', 7951.0, 19928.0, 441.6556, 176.2146, 3511604.0]
110 ['Feb 2010', 7995.0, 20013.0, 441.2368, 176.2698, 3527688.0]
111 ['Mar 2010', 8063.0, 20122.0, 440.8279, 176.6422, 3554395.0]
112 ['Apr 2010', 8086.0, 20213.0, 437.5744, 175.0471, 3538227.0]
113 ['May 2010', 8240.0, 20509.0, 436.2106, 175.2584, 3594375.0]
114 ['Jun 2010', 8309.0, 20653.0, 435.2875, 175.1225, 3616804.0]
115 ['Jul 2010', 8492.0, 21088.0, 434.0982, 174.8085, 3686362.0]
116 ['Aug 2010', 8560.0, 21272.0, 435.6658, 175.3149, 3729299.0]
117 ['Sep 2010', 8760.0, 21514.0, 431.4604, 175.6806, 3779593.0]
118 ['Total', 8145.0, 20327.6667, 439.7862, 176.2159, 42984699.0]
119 ['', '', '', '', '', '']
120 ['', '', '', '', '', '']
121 ['West Virginia', '', '', '', '', '']
122 ['Oct 2009', 147463.0, 326659.0, 265.5197, 119.863, 39154338.0]
123 ['Nov 2009', 149906.0, 332365.0, 260.4807, 117.4841, 39047615.0]
124 ['Dec 2009', 162769.0, 364573.0, 260.819, 116.4465, 42453253.0]
125 ['Jan 2010', 154615.0, 341424.0, 261.0481, 118.2165, 40361959.0]
126 ['Feb 2010', 153040.0, 337656.0, 264.5143, 119.8891, 40481270.0]
127 ['Mar 2010', 154977.0, 341025.0, 257.6451, 117.0854, 39929065.0]
128 ['Apr 2010', 153819.0, 338100.0, 265.8717, 120.9587, 40896122.0]
129 ['May 2010', 154862.0, 339910.0, 264.7796, 120.6328, 41004292.0]
130 ['Jun 2010', 155918.0, 341647.0, 261.4282, 119.3084, 40761367.0]
131 ['Jul 2010', 155858.0, 340840.0, 262.697, 120.1251, 40943430.0]
132 ['Aug 2010', 157803.0, 345906.0, 263.2465, 120.0936, 41541080.0]
133 ['Sep 2010', 157604.0, 343764.0, 256.1212, 117.4228, 40365730.0]
134 ['Total', 154886.1667, 341155.75, 261.9878, 118.9436, 486939521.0]
135 ['', '', '', '', '', '']
136 ['', '', '', '', '', '']
137 ['MARO', '', '', '', '', '']
138 ['Oct 2009', 1824782.0, 3878534.0, 274.253, 129.0312, 500451916.0]
139 ['Nov 2009', 1851769.0, 3935633.0, 272.3965, 128.1663, 504415471.0]
140 ['Dec 2009', 1892608.0, 4024580.0, 272.9237, 128.3457, 516537652.0]
141 ['Jan 2010', 1908606.0, 4049831.0, 270.6515, 127.5528, 516567094.0]
142 ['Feb 2010', 1912842.0, 4055681.0, 271.0158, 127.8232, 518410313.0]
143 ['Mar 2010', 1936125.0, 4098911.0, 270.8813, 127.9511, 524460046.0]
144 ['Apr 2010', 1958224.0, 4142535.0, 269.8343, 127.5538, 528396016.0]
145 ['May 2010', 1972450.0, 4172448.0, 271.009, 128.1147, 534551793.0]
146 ['Jun 2010', 1998442.0, 4222838.0, 270.2805, 127.9092, 540139916.0]
147 ['Jul 2010', 2037055.0, 4300157.0, 269.6953, 127.7591, 549384207.0]
148 ['Aug 2010', 2068016.0, 4358944.0, 269.6014, 127.9071, 557540000.0]
149 ['Sep 2010', 2088789.0, 4395505.0, 268.3175, 127.5072, 560458547.0]
150 ['Total', 1954142.3333, 4136299.75, 270.8483, 127.9588, 6351312971.0]
151 ['', '', '', '', '', '']
152 ['', '', '', '', '', '']
153 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
154 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [533]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,89,105,121,137]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MARO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,87,102,118,134,150]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [534]:
########################
#                      #
# SERO                 #
#                      #
########################

sheet = book.sheet_by_name('SERO')

In [535]:
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2010', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Alabama', '', '', '', '', '']
6 ['Oct 2009', 323655.0, 767453.0, 302.8964, 127.7393, 98033944.0]
7 ['Nov 2009', 328905.0, 777672.0, 299.7862, 126.7902, 98601182.0]
8 ['Dec 2009', 335354.0, 791335.0, 298.118, 126.3372, 99975051.0]
9 ['Jan 2010', 336719.0, 791477.0, 297.2598, 126.4636, 100093017.0]
10 ['Feb 2010', 337954.0, 791430.0, 297.5008, 127.0379, 100541600.0]
11 ['Mar 2010', 342048.0, 798652.0, 295.896, 126.7268, 101210647.0]
12 ['Apr 2010', 344417.0, 802670.0, 294.5326, 126.3808, 101442050.0]
13 ['May 2010', 347616.0, 808070.0, 295.3225, 127.042, 102658836.0]
14 ['Jun 2010', 351478.0, 816400.0, 293.9517, 126.5526, 103317546.0]
15 ['Jul 2010', 356489.0, 826277.0, 294.9209, 127.2407, 105136047.0]
16 ['Aug 2010', 363602.0, 839921.0, 294.0505, 127.2945, 106917358.0]
17 ['Sep 2010', 369218.0, 849785.0, 292.7577, 127.1986, 108091430.0]
18 ['Total', 344787.9167, 805095.1667, 296.3219, 126.902, 1226018708.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Florida', '', '', '', '', '']
22 ['Oct 2009', 1231226.0, 2382421.0, 273.377, 141.2802, 336588876.0]
23 ['Nov 2009', 1258772.0, 2430767.0, 271.0006, 140.3376, 341127932.0]
24 ['Dec 2009', 1296324.0, 2490034.0, 270.3633, 140.7525, 350478479.0]
25 ['Jan 2010', 1305942.0, 2497511.0, 272.8057, 142.6494, 356268436.0]
26 ['Feb 2010', 1323665.0, 2523454.0, 269.9449, 141.5982, 357316553.0]
27 ['Mar 2010', 1350674.0, 2564690.0, 268.8116, 141.5675, 363076837.0]
28 ['Apr 2010', 1369200.0, 2590665.0, 266.2721, 140.7282, 364579693.0]
29 ['May 2010', 1396335.0, 2637425.0, 266.2646, 140.9688, 371794630.0]
30 ['Jun 2010', 1422837.0, 2681377.0, 265.9753, 141.1363, 378439516.0]
31 ['Jul 2010', 1461340.0, 2749224.0, 266.4701, 141.6412, 389403371.0]
32 ['Aug 2010', 1493682.0, 2809636.0, 267.5525, 142.2385, 399638299.0]
33 ['Sep 2010', 1536762.0, 2881019.0, 265.6429, 141.6964, 408229911.0]
34 ['Total', 1370563.25, 2603185.25, 268.5601, 141.3954, 4416942533.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Georgia', '', '', '', '', '']
38 ['Oct 2009', 624308.0, 1477543.0, 317.7845, 134.2739, 198395434.0]
39 ['Nov 2009', 637514.0, 1506811.0, 317.3134, 134.2515, 202291711.0]
40 ['Dec 2009', 650006.0, 1533637.0, 316.0503, 133.9526, 205434595.0]
41 ['Jan 2010', 658911.0, 1548158.0, 313.6394, 133.488, 206660477.0]
42 ['Feb 2010', 666887.0, 1562209.0, 314.2088, 134.1317, 209541735.0]
43 ['Mar 2010', 677505.0, 1582642.0, 312.4115, 133.7386, 211660325.0]
44 ['Apr 2010', 682254.0, 1597957.0, 313.2979, 133.7638, 213748752.0]
45 ['May 2010', 695065.0, 1614920.0, 312.7163, 134.5938, 217358183.0]
46 ['Jun 2010', 705737.0, 1635928.0, 310.1425, 133.795, 218879033.0]
47 ['Jul 2010', 716749.0, 1657782.0, 311.3901, 134.6308, 223188542.0]
48 ['Aug 2010', 729473.0, 1681376.0, 313.067, 135.8256, 228373941.0]
49 ['Sep 2010', 736978.0, 1693976.0, 311.5925, 135.5608, 229636799.0]
50 ['Total', 681782.25, 1591078.25, 313.5372, 134.3517, 2565169527.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Kentucky', '', '', '', '', '']
54 ['Oct 2009', 339291.0, 752244.0, 281.8709, 127.1346, 95636264.0]
55 ['Nov 2009', 342028.0, 757651.0, 278.8024, 125.8604, 95358240.0]
56 ['Dec 2009', 345797.0, 764669.0, 288.7415, 130.574, 99845928.0]
57 ['Jan 2010', 349316.0, 770753.0, 278.5977, 126.2643, 97318623.0]
58 ['Feb 2010', 348872.0, 768927.0, 279.0344, 126.6015, 97347291.0]
59 ['Mar 2010', 352782.0, 776550.0, 278.4184, 126.4838, 98220984.0]
60 ['Apr 2010', 352487.0, 776062.0, 278.5569, 126.5204, 98187675.0]
61 ['May 2010', 354087.0, 778968.0, 278.9814, 126.8136, 98783701.0]
62 ['Jun 2010', 358121.0, 787147.0, 277.1413, 126.0884, 99250122.0]
63 ['Jul 2010', 361832.0, 794818.0, 280.038, 127.4842, 101326709.0]
64 ['Aug 2010', 366838.0, 805040.0, 280.8579, 127.9804, 103029335.0]
65 ['Sep 2010', 367268.0, 804538.0, 277.6892, 126.7639, 101986366.0]
66 ['Total', 353226.5833, 778113.9167, 279.8702, 127.0477, 1186291238.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Mississippi', '', '', '', '', '']
70 ['Oct 2009', 241164.0, 563402.0, 285.1557, 122.0608, 68769293.0]
71 ['Nov 2009', 243594.0, 569352.0, 284.6997, 121.8071, 69351140.0]
72 ['Dec 2009', 245662.0, 573545.0, 287.9334, 123.3282, 70734298.0]
73 ['Jan 2010', 244376.0, 569700.0, 282.8232, 121.3186, 69115214.0]
74 ['Feb 2010', 243433.0, 566261.0, 283.6921, 121.9579, 69060010.0]
75 ['Mar 2010', 243869.0, 566216.0, 283.1798, 121.9654, 69058781.0]
76 ['Apr 2010', 244804.0, 567724.0, 282.9417, 122.0052, 69265270.0]
77 ['May 2010', 246752.0, 571542.0, 289.7941, 125.1129, 71507264.0]
78 ['Jun 2010', 249677.0, 578040.0, 283.0053, 122.2405, 70659926.0]
79 ['Jul 2010', 253399.0, 586090.0, 283.9898, 122.7844, 71962731.0]
80 ['Aug 2010', 257647.0, 594788.0, 283.7997, 122.9348, 73120143.0]
81 ['Sep 2010', 260991.0, 601432.0, 283.3004, 122.938, 73938852.0]
82 ['Total', 247947.3333, 575674.3333, 284.517, 122.5437, 846542922.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['North Carolina', '', '', '', '', '']
86 ['Oct 2009', 568496.0, 1266757.0, 286.5449, 128.5958, 162899637.0]
87 ['Nov 2009', 578307.0, 1285157.0, 286.2374, 128.8038, 165533083.0]
88 ['Dec 2009', 587490.0, 1302121.0, 286.7981, 129.3974, 168491045.0]
89 ['Jan 2010', 594846.0, 1313610.0, 283.9947, 128.6022, 168933092.0]
90 ['Feb 2010', 598210.0, 1317368.0, 284.6862, 129.2745, 170302113.0]
91 ['Mar 2010', 603708.0, 1327754.0, 283.2036, 128.7681, 170972303.0]
92 ['Apr 2010', 607451.0, 1334545.0, 282.3728, 128.5289, 171527654.0]
93 ['May 2010', 612060.0, 1341997.0, 282.412, 128.8029, 172853078.0]
94 ['Jun 2010', 619543.0, 1356607.0, 282.045, 128.8059, 174739014.0]
95 ['Jul 2010', 635000.0, 1393165.0, 280.4915, 127.8471, 178112081.0]
96 ['Aug 2010', 657424.0, 1442650.0, 278.0918, 126.7281, 182824225.0]
97 ['Sep 2010', 673366.0, 1476207.0, 274.6502, 125.2806, 184940073.0]
98 ['Total', 611325.0833, 1346494.8333, 282.4639, 128.2421, 2072127398.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['South Carolina', '', '', '', '', '']
102 ['Oct 2009', 338670.0, 761506.0, 295.3399, 131.3486, 100022754.0]
103 ['Nov 2009', 343966.0, 771540.0, 293.6702, 130.9233, 101012577.0]
104 ['Dec 2009', 348116.0, 778371.0, 292.1851, 130.6758, 101714292.0]
105 ['Jan 2010', 352056.0, 784615.0, 290.7323, 130.4513, 102354068.0]
106 ['Feb 2010', 353229.0, 785735.0, 291.6845, 131.1274, 103031423.0]
107 ['Mar 2010', 357160.0, 792087.0, 291.4674, 131.4256, 104100494.0]
108 ['Apr 2010', 360568.0, 798227.0, 290.1763, 131.0758, 104628280.0]
109 ['May 2010', 362825.0, 801412.0, 289.3496, 130.9979, 104983286.0]
110 ['Jun 2010', 367502.0, 810620.0, 289.1587, 131.0927, 106266394.0]
111 ['Jul 2010', 372154.0, 818691.0, 290.0985, 131.8707, 107961332.0]
112 ['Aug 2010', 377783.0, 829862.0, 291.2636, 132.5937, 110034439.0]
113 ['Sep 2010', 380042.0, 832651.0, 289.939, 132.3352, 110189013.0]
114 ['Total', 359505.9167, 797109.75, 291.2095, 131.3389, 1256298352.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['Tennessee', '', '', '', '', '']
118 ['Oct 2009', 547740.0, 1181440.0, 290.893, 134.864, 159333754.0]
119 ['Nov 2009', 550849.0, 1185791.0, 285.6355, 132.6895, 157342006.0]
120 ['Dec 2009', 561024.0, 1205219.0, 287.1376, 133.6612, 161091074.0]
121 ['Jan 2010', 563971.0, 1208288.0, 286.7381, 133.8356, 161711991.0]
122 ['Feb 2010', 562936.0, 1202604.0, 286.1969, 133.9681, 161110514.0]
123 ['Mar 2010', 574300.0, 1224909.0, 285.551, 133.8809, 163991952.0]
124 ['Apr 2010', 574519.0, 1225308.0, 284.8724, 133.5702, 163664579.0]
125 ['May 2010', 575412.0, 1225284.0, 285.8308, 134.2305, 164470474.0]
126 ['Jun 2010', 588190.0, 1249367.0, 282.4923, 132.9947, 166159128.0]
127 ['Jul 2010', 590079.0, 1251862.0, 285.7207, 134.6776, 168597757.0]
128 ['Aug 2010', 595566.0, 1260726.0, 282.9521, 133.6664, 168516655.0]
129 ['Sep 2010', 600111.0, 1267478.0, 283.4771, 134.2175, 170117697.0]
130 ['Total', 573724.75, 1224023.0, 285.5765, 133.8556, 1966107581.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['SERO', '', '', '', '', '']
134 ['Oct 2009', 4214550.0, 9152766.0, 289.3974, 133.2581, 1219679956.0]
135 ['Nov 2009', 4283935.0, 9284741.0, 287.2634, 132.542, 1230617871.0]
136 ['Dec 2009', 4369773.0, 9438931.0, 287.833, 133.2529, 1257764762.0]
137 ['Jan 2010', 4406137.0, 9484112.0, 286.5219, 133.1126, 1262454918.0]
138 ['Feb 2010', 4435186.0, 9517988.0, 285.9522, 133.2478, 1268251239.0]
139 ['Mar 2010', 4502046.0, 9633500.0, 284.8243, 133.1076, 1282292323.0]
140 ['Apr 2010', 4535700.0, 9693158.0, 283.7586, 132.7786, 1287043953.0]
141 ['May 2010', 4590152.0, 9779618.0, 284.1757, 133.3804, 1304409452.0]
142 ['Jun 2010', 4663085.0, 9915486.0, 282.5835, 132.8942, 1317710679.0]
143 ['Jul 2010', 4747042.0, 10077909.0, 283.4794, 133.5285, 1345688570.0]
144 ['Aug 2010', 4842015.0, 10263999.0, 283.447, 133.7154, 1372454395.0]
145 ['Sep 2010', 4924736.0, 10407086.0, 281.6659, 133.2871, 1387130141.0]
146 ['Total', 4542863.0833, 9720774.5, 284.9799, 133.1812, 15535498259.0]
147 ['', '', '', '', '', '']
148 ['', '', '', '', '', '']
149 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
150 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [536]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117, 133]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SERO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114, 130,146]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [537]:
########################
#                      #
# MWRO                 #
#                      #
########################

sheet = book.sheet_by_name('MWRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2010', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Illinois', '', '', '', '', '']
6 ['Oct 2009', 739304.0, 1579720.0, 302.9864, 141.7967, 223999030.0]
7 ['Nov 2009', 737443.0, 1569325.0, 296.982, 139.5551, 219007276.0]
8 ['Dec 2009', 760630.0, 1624175.0, 303.2111, 141.9991, 230631457.0]
9 ['Jan 2010', 755937.0, 1609560.0, 300.3129, 141.0433, 227017660.0]
10 ['Feb 2010', 756341.0, 1607496.0, 300.7242, 141.4934, 227450044.0]
11 ['Mar 2010', 765758.0, 1622744.0, 301.1321, 142.1015, 230594300.0]
12 ['Apr 2010', 769309.0, 1625404.0, 298.0561, 141.0709, 229297262.0]
13 ['May 2010', 780523.0, 1646813.0, 297.5881, 141.0448, 232274364.0]
14 ['Jun 2010', 786162.0, 1654898.0, 294.9397, 140.1116, 231870379.0]
15 ['Jul 2010', 795746.0, 1674410.0, 293.998, 139.7195, 233947712.0]
16 ['Aug 2010', 803812.0, 1695069.0, 293.8393, 139.3404, 236191568.0]
17 ['Sep 2010', 849263.0, 1839051.0, 308.7299, 142.5696, 262192840.0]
18 ['Total', 775019.0, 1645722.0833, 299.3985, 140.9956, 2784473892.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Indiana', '', '', '', '', '']
22 ['Oct 2009', 329544.0, 774776.0, 312.5715, 132.9495, 103006069.0]
23 ['Nov 2009', 332333.0, 781420.0, 309.3878, 131.5807, 102819770.0]
24 ['Dec 2009', 338287.0, 794209.0, 311.2177, 132.5607, 105280892.0]
25 ['Jan 2010', 341456.0, 800959.0, 308.3804, 131.4653, 105298343.0]
26 ['Feb 2010', 342960.0, 804477.0, 308.4896, 131.5135, 105799587.0]
27 ['Mar 2010', 346813.0, 810986.0, 308.0803, 131.7486, 106846262.0]
28 ['Apr 2010', 345446.0, 805969.0, 306.1895, 131.2357, 105771929.0]
29 ['May 2010', 349641.0, 814069.0, 305.7847, 131.3339, 106914876.0]
30 ['Jun 2010', 352598.0, 823818.0, 310.7226, 132.9908, 109560174.0]
31 ['Jul 2010', 359968.0, 839080.0, 310.8376, 133.3503, 111891576.0]
32 ['Aug 2010', 366057.0, 853086.0, 311.7302, 133.7626, 114111021.0]
33 ['Sep 2010', 368913.0, 857992.0, 308.8117, 132.7806, 113924654.0]
34 ['Total', 347834.6667, 813403.4167, 309.3484, 132.2863, 1291225153.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Michigan', '', '', '', '', '']
38 ['Oct 2009', 790220.0, 1650505.0, 270.7709, 129.6382, 213968560.0]
39 ['Nov 2009', 805575.0, 1679746.0, 271.0631, 129.9968, 218361680.0]
40 ['Dec 2009', 816056.0, 1696692.0, 275.0089, 132.2707, 224422695.0]
41 ['Jan 2010', 837028.0, 1735139.0, 265.8753, 128.2578, 222545033.0]
42 ['Feb 2010', 848429.0, 1747094.0, 259.4224, 125.9815, 220101487.0]
43 ['Mar 2010', 864712.0, 1775174.0, 274.3647, 133.6469, 237246419.0]
44 ['Apr 2010', 877126.0, 1796909.0, 270.5476, 132.0625, 237304344.0]
45 ['May 2010', 884072.0, 1805981.0, 273.0154, 133.6478, 241365310.0]
46 ['Jun 2010', 894013.0, 1822418.0, 272.1487, 133.5064, 243304486.0]
47 ['Jul 2010', 907118.0, 1844919.0, 272.0447, 133.7601, 246776610.0]
48 ['Aug 2010', 926340.0, 1877087.0, 270.8746, 133.6763, 250921991.0]
49 ['Sep 2010', 935410.0, 1884751.0, 269.8759, 133.9406, 252444616.0]
50 ['Total', 865508.25, 1776367.9167, 270.4349, 131.7653, 2808763231.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Minnesota', '', '', '', '', '']
54 ['Oct 2009', 196312.0, 401429.0, 250.6022, 122.5527, 49196211.0]
55 ['Nov 2009', 198301.0, 406313.0, 251.2443, 122.6197, 49821996.0]
56 ['Dec 2009', 202109.0, 414137.0, 249.2592, 121.6446, 50377532.0]
57 ['Jan 2010', 203944.0, 418390.0, 248.683, 121.2204, 50717406.0]
58 ['Feb 2010', 205535.0, 421081.0, 248.2558, 121.1768, 51025258.0]
59 ['Mar 2010', 209909.0, 430419.0, 250.0421, 121.9419, 52486095.0]
60 ['Apr 2010', 211289.0, 434243.0, 249.3329, 121.3175, 52681293.0]
61 ['May 2010', 213425.0, 438209.0, 247.9857, 120.7788, 52926345.0]
62 ['Jun 2010', 216313.0, 443834.0, 245.8157, 119.8041, 53173128.0]
63 ['Jul 2010', 217852.0, 447540.0, 246.9493, 120.2091, 53798402.0]
64 ['Aug 2010', 220476.0, 452603.0, 246.7145, 120.1818, 54394633.0]
65 ['Sep 2010', 222321.0, 455951.0, 244.1897, 119.0665, 54288495.0]
66 ['Total', 209815.5, 430345.75, 248.189, 121.0048, 624886794.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Ohio', '', '', '', '', '']
70 ['Oct 2009', 703403.0, 1519305.0, 307.2983, 142.272, 216154550.0]
71 ['Nov 2009', 715315.0, 1542230.0, 302.6764, 140.3869, 216508960.0]
72 ['Dec 2009', 731783.0, 1576682.0, 305.88, 141.9676, 223837799.0]
73 ['Jan 2010', 734901.0, 1579716.0, 305.46, 142.1033, 224482828.0]
74 ['Feb 2010', 736638.0, 1580984.0, 305.8861, 142.5235, 225327308.0]
75 ['Mar 2010', 749188.0, 1604132.0, 302.9864, 141.5057, 226993811.0]
76 ['Apr 2010', 754362.0, 1611878.0, 302.5677, 141.6023, 228245577.0]
77 ['May 2010', 759443.0, 1620244.0, 301.8716, 141.4937, 229254253.0]
78 ['Jun 2010', 772109.0, 1646418.0, 300.7858, 141.0574, 232239404.0]
79 ['Jul 2010', 776734.0, 1652927.0, 303.4775, 142.6084, 235721288.0]
80 ['Aug 2010', 786702.0, 1670671.0, 301.6585, 142.0479, 237315372.0]
81 ['Sep 2010', 795008.0, 1683877.0, 298.8756, 141.108, 237608510.0]
82 ['Total', 751298.8333, 1607422.0, 303.2182, 141.7223, 2733689660.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Wisconsin', '', '', '', '', '']
86 ['Oct 2009', 266080.0, 641985.0, 277.4884, 115.0091, 73834101.0]
87 ['Nov 2009', 287858.0, 662030.0, 256.4139, 111.4916, 73810781.0]
88 ['Dec 2009', 305216.0, 687313.0, 276.4429, 122.7604, 84374811.0]
89 ['Jan 2010', 313083.0, 702674.0, 259.165, 115.4734, 81140169.0]
90 ['Feb 2010', 317600.0, 712201.0, 255.032, 113.7294, 80998177.0]
91 ['Mar 2010', 320932.0, 720416.0, 257.8744, 114.8783, 82760153.0]
92 ['Apr 2010', 322013.0, 724949.0, 261.2322, 116.036, 84120175.0]
93 ['May 2010', 322929.0, 728149.0, 251.9613, 111.7431, 81365601.0]
94 ['Jun 2010', 327267.0, 735334.0, 260.403, 115.8947, 85221317.0]
95 ['Jul 2010', 335024.0, 747492.0, 278.6058, 124.8704, 93339632.0]
96 ['Aug 2010', 341128.0, 757728.0, 265.2579, 119.4187, 90486881.0]
97 ['Sep 2010', 345053.0, 762287.0, 258.0597, 116.812, 89044272.0]
98 ['Total', 317015.25, 715213.1667, 262.9989, 116.5732, 1000496070.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['MWRO', '', '', '', '', '']
102 ['Oct 2009', 3024863.0, 6567720.0, 290.9747, 134.0128, 880158521.0]
103 ['Nov 2009', 3076825.0, 6641064.0, 286.1165, 132.5586, 880330463.0]
104 ['Dec 2009', 3154081.0, 6793208.0, 291.3448, 135.2712, 918925186.0]
105 ['Jan 2010', 3186349.0, 6846438.0, 285.9704, 133.0913, 911201439.0]
106 ['Feb 2010', 3207503.0, 6873333.0, 283.9286, 132.4979, 910701861.0]
107 ['Mar 2010', 3257312.0, 6963871.0, 287.6381, 134.5411, 936927040.0]
108 ['Apr 2010', 3279545.0, 6999352.0, 285.8386, 133.9296, 937420580.0]
109 ['May 2010', 3310033.0, 7053465.0, 285.224, 133.8492, 944100749.0]
110 ['Jun 2010', 3348462.0, 7126720.0, 285.3157, 134.0545, 955368888.0]
111 ['Jul 2010', 3392442.0, 7206368.0, 287.5437, 135.3629, 975475220.0]
112 ['Aug 2010', 3444515.0, 7306244.0, 285.5036, 134.6001, 983421466.0]
113 ['Sep 2010', 3515968.0, 7483909.0, 287.1196, 134.8899, 1009503387.0]
114 ['Total', 3266491.5, 6988474.3333, 286.8402, 134.0724, 11243534800.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
118 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [538]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MWRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [539]:
########################
#                      #
# SWRO                 #
#                      #
########################

sheet = book.sheet_by_name('SWRO ')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2010', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Arkansas', '', '', '', '', '']
6 ['Oct 2009', 189358.0, 450947.0, 294.2607, 123.5636, 55720613.0]
7 ['Nov 2009', 191463.0, 455393.0, 291.8309, 122.6958, 55874812.0]
8 ['Dec 2009', 195332.0, 464267.0, 291.5162, 122.6502, 56942448.0]
9 ['Jan 2010', 194848.0, 462706.0, 289.8937, 122.0758, 56485199.0]
10 ['Feb 2010', 194996.0, 460754.0, 290.1715, 122.8037, 56582273.0]
11 ['Mar 2010', 196376.0, 464237.0, 289.2043, 122.3358, 56792789.0]
12 ['Apr 2010', 197320.0, 464451.0, 287.5043, 122.1449, 56730341.0]
13 ['May 2010', 198419.0, 466729.0, 286.8949, 121.9667, 56925394.0]
14 ['Jun 2010', 200423.0, 471211.0, 288.4902, 122.7052, 57820062.0]
15 ['Jul 2010', 202124.0, 475025.0, 288.4292, 122.7271, 58298454.0]
16 ['Aug 2010', 204806.0, 480144.0, 287.3266, 122.5595, 58846210.0]
17 ['Sep 2010', 206026.0, 483309.0, 288.2259, 122.8655, 59382022.0]
18 ['Total', 197624.25, 466597.75, 289.4384, 122.5896, 686400617.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Louisiana', '', '', '', '', '']
22 ['Oct 2009', 337711.0, 798740.0, 307.9417, 130.1992, 103995292.0]
23 ['Nov 2009', 339727.0, 802409.0, 305.158, 129.199, 103670401.0]
24 ['Dec 2009', 346880.0, 817671.0, 307.3686, 130.3948, 106620019.0]
25 ['Jan 2010', 345423.0, 811696.0, 303.557, 129.1808, 104855569.0]
26 ['Feb 2010', 345543.0, 810457.0, 305.0258, 130.0495, 105399525.0]
27 ['Mar 2010', 347494.0, 811430.0, 300.2779, 128.5937, 104344782.0]
28 ['Apr 2010', 351753.0, 821300.0, 300.4039, 128.6594, 105667962.0]
29 ['May 2010', 356652.0, 831060.0, 303.1135, 130.0821, 108106037.0]
30 ['Jun 2010', 359005.0, 833950.0, 300.644, 129.4235, 107932709.0]
31 ['Jul 2010', 367096.0, 851744.0, 302.836, 130.5203, 111169880.0]
32 ['Aug 2010', 370314.0, 856446.0, 301.4053, 130.323, 111614613.0]
33 ['Sep 2010', 374339.0, 864112.0, 301.3894, 130.5639, 112821808.0]
34 ['Total', 353494.75, 825917.9167, 303.2102, 129.7747, 1286198597.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['New Mexico', '', '', '', '', '']
38 ['Oct 2009', 137556.0, 329583.0, 303.9017, 126.8375, 41803499.0]
39 ['Nov 2009', 140116.0, 334537.0, 302.7613, 126.8072, 42421707.0]
40 ['Dec 2009', 142174.0, 339203.0, 302.386, 126.7425, 42991427.0]
41 ['Jan 2010', 144118.0, 342290.0, 298.9708, 125.8789, 43087072.0]
42 ['Feb 2010', 146081.0, 346141.0, 303.499, 128.0849, 44335443.0]
43 ['Mar 2010', 147259.0, 347652.0, 297.9224, 126.1945, 43871756.0]
44 ['Apr 2010', 150001.0, 353748.0, 296.5829, 125.7611, 44487738.0]
45 ['May 2010', 153337.0, 361450.0, 297.6204, 126.2587, 45636220.0]
46 ['Jun 2010', 157218.0, 370334.0, 295.9371, 125.6342, 46526633.0]
47 ['Jul 2010', 160942.0, 378805.0, 296.7283, 126.0703, 47756050.0]
48 ['Aug 2010', 165089.0, 387966.0, 299.2902, 127.3553, 49409512.0]
49 ['Sep 2010', 165659.0, 390154.0, 298.6819, 126.82, 49479346.0]
50 ['Total', 150795.8333, 356821.9167, 299.415, 126.5352, 541806403.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Oklahoma', '', '', '', '', '']
54 ['Oct 2009', 234430.0, 549785.0, 302.0507, 128.7954, 70809756.0]
55 ['Nov 2009', 243588.0, 563360.0, 294.6047, 127.3824, 71762164.0]
56 ['Dec 2009', 243143.0, 568612.0, 301.7046, 129.0113, 73357362.0]
57 ['Jan 2010', 244728.0, 570296.0, 298.7719, 128.2104, 73117856.0]
58 ['Feb 2010', 246176.0, 572738.0, 300.8793, 129.3249, 74069265.0]
59 ['Mar 2010', 249373.0, 578566.0, 297.9049, 128.4027, 74289439.0]
60 ['Apr 2010', 252410.0, 584755.0, 297.3812, 128.3649, 75061993.0]
61 ['May 2010', 253955.0, 587871.0, 298.2105, 128.8243, 75732057.0]
62 ['Jun 2010', 255872.0, 590924.0, 297.088, 128.64, 76016492.0]
63 ['Jul 2010', 260308.0, 601111.0, 298.4171, 129.228, 77680357.0]
64 ['Aug 2010', 264096.0, 608349.0, 297.4817, 129.1425, 78563716.0]
65 ['Sep 2010', 266895.0, 613531.0, 296.7275, 129.0808, 79195091.0]
66 ['Total', 251247.8333, 582491.5, 298.3958, 128.708, 899655548.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Texas', '', '', '', '', '']
70 ['Oct 2009', 1258971.0, 3175751.0, 335.2013, 132.8847, 422008666.0]
71 ['Nov 2009', 1277757.0, 3228061.0, 332.8934, 131.7685, 425356855.0]
72 ['Dec 2009', 1310466.0, 3311850.0, 331.4905, 131.1675, 434406992.0]
73 ['Jan 2010', 1365433.0, 3459408.0, 322.4777, 127.2824, 440321722.0]
74 ['Feb 2010', 1373771.0, 3482601.0, 323.6053, 127.6516, 444559550.0]
75 ['Mar 2010', 1408013.0, 3563572.0, 323.3407, 127.7561, 455267957.0]
76 ['Apr 2010', 1426662.0, 3609264.0, 319.2837, 126.2058, 455509875.0]
77 ['May 2010', 1450114.0, 3664965.0, 318.5622, 126.0453, 461951435.0]
78 ['Jun 2010', 1474625.0, 3721663.0, 317.7289, 125.8929, 468531020.0]
79 ['Jul 2010', 1493958.0, 3760275.0, 317.4676, 126.1299, 474283196.0]
80 ['Aug 2010', 1514042.0, 3803719.0, 318.0066, 126.5801, 481475309.0]
81 ['Sep 2010', 1531180.0, 3837839.0, 315.9164, 126.0409, 483724837.0]
82 ['Total', 1407082.6667, 3551580.6667, 322.6177, 127.8163, 5447397414.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['SWRO', '', '', '', '', '']
86 ['Oct 2009', 2158026.0, 5304806.0, 321.7467, 130.8884, 694337826.0]
87 ['Nov 2009', 2192651.0, 5383760.0, 318.8314, 129.8509, 699085939.0]
88 ['Dec 2009', 2237995.0, 5501603.0, 319.1778, 129.8382, 714318248.0]
89 ['Jan 2010', 2294550.0, 5646396.0, 312.8576, 127.1373, 717867418.0]
90 ['Feb 2010', 2306567.0, 5672691.0, 314.2966, 127.7958, 724946056.0]
91 ['Mar 2010', 2348515.0, 5765457.0, 312.7792, 127.4082, 734566723.0]
92 ['Apr 2010', 2378146.0, 5833518.0, 310.0978, 126.4174, 737457909.0]
93 ['May 2010', 2412477.0, 5912075.0, 310.2003, 126.5801, 748351143.0]
94 ['Jun 2010', 2447143.0, 5988082.0, 309.2696, 126.3889, 756826916.0]
95 ['Jul 2010', 2484428.0, 6066960.0, 309.6036, 126.7831, 769187937.0]
96 ['Aug 2010', 2518347.0, 6136624.0, 309.691, 127.0909, 779909360.0]
97 ['Sep 2010', 2544099.0, 6188945.0, 308.4012, 126.7749, 784603104.0]
98 ['Total', 2360245.3333, 5783409.75, 312.8721, 127.685, 8861458579.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
102 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [540]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85]:
        #for the rows that have the state names
        state = row[0]
        if state == 'SWRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [541]:
########################
#                      #
# MPRO                 #
#                      #
########################
sheet = book.sheet_by_name('MPRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2010', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Colorado', '', '', '', '', '']
6 ['Oct 2009', 161463.0, 371389.0, 323.1717, 140.5003, 52180273.0]
7 ['Nov 2009', 164963.0, 379956.0, 323.061, 140.2613, 53293104.0]
8 ['Dec 2009', 169691.0, 390656.0, 323.2605, 140.4161, 54854393.0]
9 ['Jan 2010', 171933.0, 395580.0, 320.922, 139.484, 55177083.0]
10 ['Feb 2010', 173361.0, 398862.0, 327.7329, 142.4455, 56816095.0]
11 ['Mar 2010', 177596.0, 407731.0, 332.8216, 144.9676, 59107776.0]
12 ['Apr 2010', 179103.0, 411245.0, 329.2953, 143.4128, 58977782.0]
13 ['May 2010', 180396.0, 413805.0, 327.2042, 142.6429, 59026325.0]
14 ['Jun 2010', 182250.0, 417989.0, 325.3381, 141.8527, 59292870.0]
15 ['Jul 2010', 183440.0, 419737.0, 322.7506, 141.0535, 59205370.0]
16 ['Aug 2010', 185567.0, 424314.0, 323.6355, 141.5369, 60056067.0]
17 ['Sep 2010', 185707.0, 424878.0, 321.5939, 140.5633, 59722241.0]
18 ['Total', 176289.1667, 404678.5, 325.0859, 141.6164, 687709379.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['Iowa', '', '', '', '', '']
22 ['Oct 2009', 148976.0, 324758.0, 280.3182, 128.5902, 41760683.0]
23 ['Nov 2009', 150300.0, 327486.0, 279.0403, 128.0658, 41939757.0]
24 ['Dec 2009', 152274.0, 331335.0, 279.139, 128.2859, 42505605.0]
25 ['Jan 2010', 153794.0, 334991.0, 276.3545, 126.874, 42501657.0]
26 ['Feb 2010', 154770.0, 337169.0, 278.7207, 127.9406, 43137601.0]
27 ['Mar 2010', 156528.0, 340595.0, 278.5559, 128.0165, 43601791.0]
28 ['Apr 2010', 157422.0, 342517.0, 279.9347, 128.6589, 44067877.0]
29 ['May 2010', 158731.0, 344477.0, 280.0914, 129.0629, 44459194.0]
30 ['Jun 2010', 159680.0, 346551.0, 279.1777, 128.6365, 44579102.0]
31 ['Jul 2010', 161149.0, 349609.0, 280.6128, 129.3458, 45220468.0]
32 ['Aug 2010', 162265.0, 351992.0, 287.2332, 132.4118, 46607895.0]
33 ['Sep 2010', 162461.0, 352164.0, 281.5302, 129.8761, 45737680.0]
34 ['Total', 156529.1667, 340303.6667, 280.0965, 128.8357, 526119310.0]
35 ['', '', '', '', '', '']
36 ['', '', '', '', '', '']
37 ['Kansas', '', '', '', '', '']
38 ['Oct 2009', 114251.0, 252255.0, 274.0673, 124.1302, 31312465.0]
39 ['Nov 2009', 115550.0, 254669.0, 272.6824, 123.7231, 31508450.0]
40 ['Dec 2009', 116377.0, 256321.0, 275.5621, 125.113, 32069093.0]
41 ['Jan 2010', 119119.0, 262622.0, 271.774, 123.2701, 32373445.0]
42 ['Feb 2010', 120142.0, 264227.0, 273.3124, 124.2731, 32836302.0]
43 ['Mar 2010', 121262.0, 266189.0, 272.0648, 123.9387, 32991123.0]
44 ['Apr 2010', 122155.0, 267840.0, 272.6202, 124.3351, 33301920.0]
45 ['May 2010', 124397.0, 272550.0, 271.6875, 124.0034, 33797116.0]
46 ['Jun 2010', 126427.0, 276349.0, 270.9359, 123.9506, 34253619.0]
47 ['Jul 2010', 129447.0, 282968.0, 271.6515, 124.2701, 35164470.0]
48 ['Aug 2010', 132455.0, 289399.0, 273.2202, 125.0501, 36189375.0]
49 ['Sep 2010', 133738.0, 291126.0, 275.4124, 126.5195, 36833105.0]
50 ['Total', 122943.3333, 269709.5833, 272.9106, 124.4025, 402630483.0]
51 ['', '', '', '', '', '']
52 ['', '', '', '', '', '']
53 ['Missouri', '', '', '', '', '']
54 ['Oct 2009', 392484.0, 870143.0, 277.0457, 124.9634, 108736007.0]
55 ['Nov 2009', 396190.0, 877846.0, 279.4977, 126.1431, 110734213.0]
56 ['Dec 2009', 401304.0, 888501.0, 277.6401, 125.4001, 111418072.0]
57 ['Jan 2010', 404237.0, 894320.0, 271.652, 122.788, 109811780.0]
58 ['Feb 2010', 404902.0, 894754.0, 277.5441, 125.5967, 112378158.0]
59 ['Mar 2010', 409270.0, 903934.0, 284.8705, 128.9795, 116588938.0]
60 ['Apr 2010', 408775.0, 901319.0, 275.6809, 125.0295, 112691445.0]
61 ['May 2010', 409735.0, 902145.0, 276.5411, 125.599, 113308549.0]
62 ['Jun 2010', 413240.0, 909139.0, 277.1138, 125.9593, 114514526.0]
63 ['Jul 2010', 418317.0, 918839.0, 276.4954, 125.8792, 115662719.0]
64 ['Aug 2010', 422415.0, 927068.0, 275.5155, 125.5376, 116381883.0]
65 ['Sep 2010', 423734.0, 928183.0, 281.0129, 128.288, 119074703.0]
66 ['Total', 408716.9167, 901349.25, 277.5558, 125.8577, 1361300993.0]
67 ['', '', '', '', '', '']
68 ['', '', '', '', '', '']
69 ['Montana', '', '', '', '', '']
70 ['Oct 2009', 46693.0, 104542.0, 289.4827, 129.2955, 13516814.0]
71 ['Nov 2009', 47610.0, 106343.0, 289.3634, 129.5487, 13776593.0]
72 ['Dec 2009', 48600.0, 108617.0, 289.705, 129.6267, 14079662.0]
73 ['Jan 2010', 49668.0, 110811.0, 288.1297, 129.1462, 14310824.0]
74 ['Feb 2010', 50590.0, 112487.0, 289.2896, 130.1054, 14635161.0]
75 ['Mar 2010', 51417.0, 114406.0, 289.3942, 130.0612, 14879782.0]
76 ['Apr 2010', 52099.0, 115798.0, 286.6745, 128.9785, 14935454.0]
77 ['May 2010', 52528.0, 116368.0, 286.2267, 129.2014, 15034914.0]
78 ['Jun 2010', 53029.0, 117291.0, 285.9102, 129.2642, 15161531.0]
79 ['Jul 2010', 53436.0, 118174.0, 287.337, 129.9282, 15354140.0]
80 ['Aug 2010', 53922.0, 118958.0, 286.3544, 129.8004, 15440801.0]
81 ['Sep 2010', 54186.0, 119039.0, 284.5818, 129.5403, 15420351.0]
82 ['Total', 51148.1667, 113569.5, 287.6382, 129.5433, 176546027.0]
83 ['', '', '', '', '', '']
84 ['', '', '', '', '', '']
85 ['Nebraska', '', '', '', '', '']
86 ['Oct 2009', 65663.0, 152007.0, 285.8917, 123.4977, 18772508.0]
87 ['Nov 2009', 66723.0, 154674.0, 281.1971, 121.3023, 18762316.0]
88 ['Dec 2009', 68114.0, 157922.0, 284.0665, 122.5219, 19348906.0]
89 ['Jan 2010', 69502.0, 161001.0, 282.549, 121.9726, 19637718.0]
90 ['Feb 2010', 70265.0, 162419.0, 280.9054, 121.5241, 19737818.0]
91 ['Mar 2010', 70530.0, 163320.0, 278.8204, 120.409, 19665203.0]
92 ['Apr 2010', 71585.0, 165177.0, 282.4843, 122.4241, 20221642.0]
93 ['May 2010', 71843.0, 165536.0, 278.2662, 120.7682, 19991478.0]
94 ['Jun 2010', 71894.0, 165345.0, 275.1021, 119.6177, 19778188.0]
95 ['Jul 2010', 72978.0, 167568.0, 281.6087, 122.6442, 20551239.0]
96 ['Aug 2010', 73672.0, 169445.0, 277.99, 120.8657, 20480081.0]
97 ['Sep 2010', 73730.0, 169385.0, 279.8058, 121.794, 20630083.0]
98 ['Total', 70541.5833, 162816.5833, 280.6585, 121.5976, 237577180.0]
99 ['', '', '', '', '', '']
100 ['', '', '', '', '', '']
101 ['North Dakota', '', '', '', '', '']
102 ['Oct 2009', 26160.0, 57681.0, 292.9516, 132.862, 7663614.0]
103 ['Nov 2009', 26418.0, 58174.0, 291.8233, 132.5229, 7709389.0]
104 ['Dec 2009', 26709.0, 58796.0, 290.8119, 132.1059, 7767296.0]
105 ['Jan 2010', 26960.0, 59360.0, 289.4704, 131.4711, 7804123.0]
106 ['Feb 2010', 27161.0, 59591.0, 291.8014, 133.0003, 7925619.0]
107 ['Mar 2010', 27488.0, 60297.0, 290.1278, 132.2625, 7975033.0]
108 ['Apr 2010', 27551.0, 60473.0, 292.3553, 133.1946, 8054680.0]
109 ['May 2010', 27493.0, 60414.0, 290.6487, 132.2674, 7990804.0]
110 ['Jun 2010', 27624.0, 60774.0, 290.0205, 131.8249, 8011526.0]
111 ['Jul 2010', 27602.0, 60822.0, 291.039, 132.0782, 8033259.0]
112 ['Aug 2010', 27737.0, 61049.0, 289.5185, 131.5398, 8030375.0]
113 ['Sep 2010', 27878.0, 61229.0, 288.7207, 131.4566, 8048957.0]
114 ['Total', 27231.75, 59888.3333, 290.7595, 132.2109, 95014675.0]
115 ['', '', '', '', '', '']
116 ['', '', '', '', '', '']
117 ['South Dakota', '', '', '', '', '']
118 ['Oct 2009', 37072.0, 88601.0, 319.5139, 133.6895, 11845019.0]
119 ['Nov 2009', 37917.0, 90510.0, 316.964, 132.7845, 12018324.0]
120 ['Dec 2009', 38458.0, 91728.0, 318.2186, 133.4168, 12238052.0]
121 ['Jan 2010', 39289.0, 93681.0, 329.1819, 138.0561, 12933229.0]
122 ['Feb 2010', 39732.0, 94378.0, 318.7499, 134.1899, 12664572.0]
123 ['Mar 2010', 40302.0, 95742.0, 317.9522, 133.84, 12814111.0]
124 ['Apr 2010', 40635.0, 96571.0, 317.8039, 133.7251, 12913962.0]
125 ['May 2010', 40803.0, 96931.0, 317.9133, 133.8253, 12971816.0]
126 ['Jun 2010', 41145.0, 97918.0, 319.345, 134.1883, 13139448.0]
127 ['Jul 2010', 41518.0, 99001.0, 317.617, 133.1989, 13186822.0]
128 ['Aug 2010', 41729.0, 99467.0, 316.8646, 132.933, 13222442.0]
129 ['Sep 2010', 42046.0, 99504.0, 312.2213, 131.9309, 13127657.0]
130 ['Total', 40053.8333, 95336.0, 318.4786, 133.8035, 153075454.0]
131 ['', '', '', '', '', '']
132 ['', '', '', '', '', '']
133 ['Utah', '', '', '', '', '']
134 ['Oct 2009', 88616.0, 220130.0, 323.7385, 130.3249, 28688410.0]
135 ['Nov 2009', 87071.0, 214761.0, 335.2781, 135.9325, 29193002.0]
136 ['Dec 2009', 87858.0, 216119.0, 340.1658, 138.2863, 29886290.0]
137 ['Jan 2010', 93541.0, 232939.0, 318.9076, 128.0633, 29830934.0]
138 ['Feb 2010', 98675.0, 247325.0, 307.0013, 122.484, 30293350.0]
139 ['Mar 2010', 102018.0, 255120.0, 302.5894, 121.0002, 30869568.0]
140 ['Apr 2010', 103755.0, 260723.0, 297.9247, 118.5595, 30911176.0]
141 ['May 2010', 104075.0, 260660.0, 299.7587, 119.6861, 31197386.0]
142 ['Jun 2010', 107318.0, 268573.0, 297.1674, 118.7439, 31891410.0]
143 ['Jul 2010', 104701.0, 262628.0, 293.5623, 117.0335, 30736266.0]
144 ['Aug 2010', 104662.0, 260065.0, 301.138, 121.1916, 31517706.0]
145 ['Sep 2010', 103364.0, 269819.0, 308.5016, 118.1828, 31887958.0]
146 ['Total', 98804.5, 247405.1667, 309.4524, 123.5839, 366903456.0]
147 ['', '', '', '', '', '']
148 ['', '', '', '', '', '']
149 ['Wyoming', '', '', '', '', '']
150 ['Oct 2009', 13003.0, 31540.0, 297.7651, 122.7596, 3871839.0]
151 ['Nov 2009', 13360.0, 32332.0, 297.8041, 123.0565, 3978663.0]
152 ['Dec 2009', 13743.0, 33304.0, 302.1668, 124.6901, 4152678.0]
153 ['Jan 2010', 14246.0, 34494.0, 299.8846, 123.8521, 4272156.0]
154 ['Feb 2010', 14637.0, 35422.0, 299.6958, 123.8396, 4386648.0]
155 ['Mar 2010', 15136.0, 36526.0, 300.9394, 124.7062, 4555019.0]
156 ['Apr 2010', 15086.0, 36226.0, 295.9455, 123.2439, 4464634.0]
157 ['May 2010', 14885.0, 35700.0, 295.6106, 123.2539, 4400164.0]
158 ['Jun 2010', 14892.0, 35574.0, 293.6532, 122.9292, 4373084.0]
159 ['Jul 2010', 14815.0, 35319.0, 295.8256, 124.0878, 4382657.0]
160 ['Aug 2010', 14883.0, 35536.0, 293.8907, 123.0858, 4373976.0]
161 ['Sep 2010', 14986.0, 35615.0, 297.8354, 125.3225, 4463361.0]
162 ['Total', 14472.6667, 34799.0, 297.5429, 123.7461, 51674879.0]
163 ['', '', '', '', '', '']
164 ['', '', '', '', '', '']
165 ['MPRO', '', '', '', '', '']
166 ['Oct 2009', 1094381.0, 2473046.0, 290.8929, 128.7269, 318347632.0]
167 ['Nov 2009', 1106102.0, 2496751.0, 291.9385, 129.3336, 322913811.0]
168 ['Dec 2009', 1123128.0, 2533299.0, 292.3265, 129.6018, 328320047.0]
169 ['Jan 2010', 1142289.0, 2579799.0, 287.7144, 127.3948, 328652949.0]
170 ['Feb 2010', 1154235.0, 2606634.0, 290.0721, 128.4459, 334811324.0]
171 ['Mar 2010', 1171547.0, 2643860.0, 292.8165, 129.7528, 343048344.0]
172 ['Apr 2010', 1178166.0, 2657889.0, 289.0429, 128.1245, 340540572.0]
173 ['May 2010', 1184886.0, 2668586.0, 288.7854, 128.2244, 342177746.0]
174 ['Jun 2010', 1197499.0, 2695503.0, 288.0965, 127.9892, 344995304.0]
175 ['Jul 2010', 1207403.0, 2714665.0, 287.8057, 128.0075, 347497410.0]
176 ['Aug 2010', 1219307.0, 2737293.0, 288.9351, 128.704, 352300601.0]
177 ['Sep 2010', 1221830.0, 2750942.0, 290.5037, 129.0271, 354946096.0]
178 ['Total', 1166731.0833, 2629855.5833, 289.8806, 128.605, 4058551836.0]
179 ['', '', '', '', '', '']
180 ['', '', '', '', '', '']
181 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
182 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [542]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,37,53,69,85,101,117, 133, 149,165]:
        #for the rows that have the state names
        state = row[0]
        if state == 'MPRO':
            break
        else:
            continue         
    if i in [18,34,50,66,82,98,114, 130,146, 162, 178]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [543]:

########################
#                      #
# WRO                  #
#                      #
########################
sheet = book.sheet_by_name('WRO')
for i in range(sheet.nrows):
    print(i,sheet.row_values(i))

0 ['National Data Bank Version 8.2 - Supplemental Nutrition Assistance Program', '', '', '', '', '01/15/2015']
1 ['SNAP Monthly State Participation and Benefit Summary, Fiscal Year 2010', '', '', '', '', '']
2 ['Fiscal Year and Month', 'Participation 1/', '', 'Benefit', '', '']
3 ['', 'Household', 'Persons', 'Per Household', 'Per Person', 'Cost']
4 ['', '----------------- Number -----------------', '', '------------------------------------------------------------------- Dollars -------------------------------------------------------------------', '', '']
5 ['Alaska', '', '', '', '', '']
6 ['Oct 2009', 23734.0, 58834.0, 424.2791, 171.1568, 10069840.0]
7 ['Nov 2009', 27705.0, 69048.0, 430.3503, 172.6749, 11922855.0]
8 ['Dec 2009', 28379.0, 71510.0, 442.8649, 175.7525, 12568063.0]
9 ['Jan 2010', 29815.0, 75215.0, 439.7756, 174.3257, 13111909.0]
10 ['Feb 2010', 30223.0, 76488.0, 445.3565, 175.9754, 13460009.0]
11 ['Mar 2010', 31252.0, 78850.0, 441.9454, 175.164, 13811678.0]
12 ['Apr 2010', 32165.0, 80996.0, 437.9753, 173.928, 14087475.0]
13 ['May 2010', 32307.0, 81226.0, 436.3934, 173.572, 14098563.0]
14 ['Jun 2010', 32390.0, 81102.0, 433.2032, 173.0099, 14031452.0]
15 ['Jul 2010', 32419.0, 81606.0, 438.5933, 174.2366, 14218756.0]
16 ['Aug 2010', 32376.0, 81271.0, 434.6424, 173.1489, 14071981.0]
17 ['Sep 2010', 32526.0, 81196.0, 429.2381, 171.9469, 13961397.0]
18 ['Total', 30440.9167, 76445.1667, 436.4027, 173.7781, 159413978.0]
19 ['', '', '', '', '', '']
20 ['', '', '', '', '', '']
21 ['American Samoa', '', '', '', '', '']
22 [' No data found.', '', '', '', '', '']
23 ['', '', '', '', '', '']
24 ['', '', '', '', '', '']
25 ['Arizona', '', '', '', '', '']
26 ['Oct 2009', 413284.0, 972162.0, 313.0937, 133.1019, 129396619.0]
27 ['Nov 2009', 420349.0, 986276.0, 310.7335, 132.4341, 130616533.0]
28 ['Dec 2009', 429370.0, 1004476.0, 312.2533, 133.4748, 134072203.0]
29 ['Jan 2010', 431481.0, 1005810.0, 304.1206, 130.4643, 131222267.0]
30 ['Feb 2010', 432606.0, 1006005.0, 298.1888, 128.2282, 128998244.0]
31 ['Mar 2010', 439328.0, 1017100.0, 296.6154, 128.1206, 130311471.0]
32 ['Apr 2010', 441537.0, 1020648.0, 295.038, 127.6348, 130270208.0]
33 ['May 2010', 446370.0, 1031075.0, 296.938, 128.5495, 132544197.0]
34 ['Jun 2010', 450310.0, 1037367.0, 296.26, 128.6033, 133408820.0]
35 ['Jul 2010', 454358.0, 1044940.0, 297.414, 129.3207, 135132414.0]
36 ['Aug 2010', 456910.0, 1047779.0, 297.8323, 129.8772, 136082571.0]
37 ['Sep 2010', 456467.0, 1044410.0, 297.1665, 129.8788, 135646702.0]
38 ['Total', 439364.1667, 1018170.6667, 301.1363, 129.9473, 1587702249.0]
39 ['', '', '', '', '', '']
40 ['', '', '', '', '', '']
41 ['California', '', '', '', '', '']
42 ['Oct 2009', 1281901.0, 3011359.0, 345.622, 147.1273, 443053129.0]
43 ['Nov 2009', 1295212.0, 3041650.0, 343.3819, 146.2208, 444752382.0]
44 ['Dec 2009', 1327580.0, 3112043.0, 344.6869, 147.0415, 457599485.0]
45 ['Jan 2010', 1343392.0, 3145373.0, 343.1797, 146.5724, 461024806.0]
46 ['Feb 2010', 1360840.0, 3185154.0, 342.7908, 146.4555, 466483380.0]
47 ['Mar 2010', 1388492.0, 3232550.0, 342.361, 147.0559, 475365545.0]
48 ['Apr 2010', 1398983.0, 3254744.0, 340.2846, 146.2642, 476052433.0]
49 ['May 2010', 1413573.0, 3285959.0, 340.133, 146.3204, 480802761.0]
50 ['Jun 2010', 1434223.0, 3323895.0, 337.271, 145.5286, 483721774.0]
51 ['Jul 2010', 1461495.0, 3376982.0, 338.5, 146.4965, 494716051.0]
52 ['Aug 2010', 1485484.0, 3425892.0, 337.5815, 146.3771, 501471965.0]
53 ['Sep 2010', 1505136.0, 3466974.0, 336.7191, 146.1817, 506808073.0]
54 ['Total', 1391359.25, 3238547.9167, 340.9048, 146.461, 5691851784.0]
55 ['', '', '', '', '', '']
56 ['', '', '', '', '', '']
57 ['Guam', '', '', '', '', '']
58 ['Oct 2009', 10665.0, 34119.0, 721.4653, 225.5174, 7694427.0]
59 ['Nov 2009', 10869.0, 34810.0, 718.5825, 224.3687, 7810273.0]
60 ['Dec 2009', 11379.0, 36467.0, 695.7019, 217.0837, 7916392.0]
61 ['Jan 2010', 11504.0, 36838.0, 690.8293, 215.7365, 7947300.0]
62 ['Feb 2010', 11556.0, 36920.0, 693.2365, 216.9838, 8011041.0]
63 ['Mar 2010', 11629.0, 37153.0, 691.3912, 216.4075, 8040188.0]
64 ['Apr 2010', 11627.0, 37044.0, 693.7212, 217.7383, 8065896.0]
65 ['May 2010', 11729.0, 37293.0, 692.6759, 217.8531, 8124396.0]
66 ['Jun 2010', 11832.0, 37432.0, 696.8311, 220.2635, 8244905.0]
67 ['Jul 2010', 11960.0, 37833.0, 684.1527, 216.2785, 8182466.0]
68 ['Aug 2010', 12091.0, 38292.0, 685.6536, 216.5005, 8290238.0]
69 ['Sep 2010', 12303.0, 38908.0, 680.1254, 215.0607, 8367583.0]
70 ['Total', 11595.3333, 36925.75, 694.9283, 218.2197, 96695105.0]
71 ['', '', '', '', '', '']
72 ['', '', '', '', '', '']
73 ['Hawaii', '', '', '', '', '']
74 ['Oct 2009', 65114.0, 129536.0, 427.1713, 214.7266, 27814831.0]
75 ['Nov 2009', 66017.0, 131361.0, 429.4632, 215.8317, 28351873.0]
76 ['Dec 2009', 67278.0, 134021.0, 430.3662, 216.0421, 28954176.0]
77 ['Jan 2010', 67650.0, 134685.0, 426.5319, 214.2397, 28854880.0]
78 ['Feb 2010', 68093.0, 135511.0, 429.29, 215.7142, 29231645.0]
79 ['Mar 2010', 68812.0, 136594.0, 429.4297, 216.3339, 29549918.0]
80 ['Apr 2010', 69617.0, 138384.0, 429.5766, 216.1076, 29905836.0]
81 ['May 2010', 70394.0, 139816.0, 428.8707, 215.9261, 30189927.0]
82 ['Jun 2010', 71077.0, 141293.0, 429.5877, 216.1027, 30533803.0]
83 ['Jul 2010', 72363.0, 144006.0, 431.0295, 216.5923, 31190590.0]
84 ['Aug 2010', 72953.0, 145534.0, 432.4418, 216.7736, 31547923.0]
85 ['Sep 2010', 73450.0, 147250.0, 435.9353, 217.4496, 32019451.0]
86 ['Total', 69401.5, 138165.9167, 430.0398, 216.0113, 358144853.0]
87 ['', '', '', '', '', '']
88 ['', '', '', '', '', '']
89 ['Idaho', '', '', '', '', '']
90 ['Oct 2009', 64513.0, 162436.0, 329.3966, 130.823, 21250362.0]
91 ['Nov 2009', 67627.0, 170962.0, 314.3222, 124.3356, 21256665.0]
92 ['Dec 2009', 71636.0, 180576.0, 321.3687, 127.4896, 23021567.0]
93 ['Jan 2010', 74849.0, 187692.0, 317.1221, 126.464, 23736274.0]
94 ['Feb 2010', 76880.0, 191703.0, 320.3982, 128.4915, 24632215.0]
95 ['Mar 2010', 78738.0, 195699.0, 319.9231, 128.7186, 25190105.0]
96 ['Apr 2010', 80732.0, 199181.0, 318.0553, 128.9141, 25677240.0]
97 ['May 2010', 81740.0, 201228.0, 318.9583, 129.5628, 26071654.0]
98 ['Jun 2010', 83317.0, 204204.0, 316.5902, 129.1715, 26377347.0]
99 ['Jul 2010', 85323.0, 208458.0, 315.6139, 129.1825, 26929121.0]
100 ['Aug 2010', 86931.0, 211883.0, 316.5556, 129.8759, 27518491.0]
101 ['Sep 2010', 88252.0, 214378.0, 316.0379, 130.1018, 27890973.0]
102 ['Total', 78378.1667, 194033.3333, 318.4901, 128.6514, 299552014.0]
103 ['', '', '', '', '', '']
104 ['', '', '', '', '', '']
105 ['Nevada', '', '', '', '', '']
106 ['Oct 2009', 115400.0, 248437.0, 266.9938, 124.0197, 30811084.0]
107 ['Nov 2009', 117965.0, 254376.0, 265.4124, 123.083, 31309373.0]
108 ['Dec 2009', 119919.0, 259196.0, 270.6746, 125.2297, 32459029.0]
109 ['Jan 2010', 121385.0, 262500.0, 266.2894, 123.1373, 32323534.0]
110 ['Feb 2010', 123136.0, 266276.0, 266.2516, 123.1247, 32785152.0]
111 ['Mar 2010', 126198.0, 272425.0, 269.4927, 124.8396, 34009440.0]
112 ['Apr 2010', 128377.0, 276523.0, 268.3188, 124.5681, 34445958.0]
113 ['May 2010', 131615.0, 283683.0, 267.5901, 124.1487, 35218874.0]
114 ['Jun 2010', 134936.0, 290842.0, 266.8951, 123.8259, 36013759.0]
115 ['Jul 2010', 138861.0, 299168.0, 270.3307, 125.476, 37538393.0]
116 ['Aug 2010', 143693.0, 309586.0, 268.0357, 124.4076, 38514861.0]
117 ['Sep 2010', 146266.0, 314253.0, 267.7786, 124.635, 39166912.0]
118 ['Total', 128979.25, 278105.4167, 267.8702, 124.2324, 414596369.0]
119 ['', '', '', '', '', '']
120 ['', '', '', '', '', '']
121 ['Oregon', '', '', '', '', '']
122 ['Oct 2009', 349378.0, 661945.0, 237.3317, 125.2649, 82918465.0]
123 ['Nov 2009', 354962.0, 672344.0, 237.3851, 125.3268, 84262707.0]
124 ['Dec 2009', 359343.0, 681285.0, 240.6742, 126.9433, 86484599.0]
125 ['Jan 2010', 368489.0, 701149.0, 236.2389, 124.1554, 87051430.0]
126 ['Feb 2010', 370179.0, 701920.0, 238.6936, 125.8824, 88359361.0]
127 ['Mar 2010', 371863.0, 702681.0, 239.2407, 126.6076, 88964768.0]
128 ['Apr 2010', 375496.0, 708235.0, 238.5068, 126.4529, 89558365.0]
129 ['May 2010', 378824.0, 713218.0, 238.2439, 126.5426, 90252489.0]
130 ['Jun 2010', 382947.0, 719675.0, 237.3652, 126.3046, 90898297.0]
131 ['Jul 2010', 386508.0, 725327.0, 237.6787, 126.6528, 91864713.0]
132 ['Aug 2010', 392176.0, 733683.0, 237.0267, 126.698, 92956164.0]
133 ['Sep 2010', 395662.0, 738957.0, 235.9608, 126.3412, 93360737.0]
134 ['Total', 373818.9167, 705034.9167, 237.8451, 126.1087, 1066932095.0]
135 ['', '', '', '', '', '']
136 ['', '', '', '', '', '']
137 ['Washington', '', '', '', '', '']
138 ['Oct 2009', 431777.0, 881080.0, 245.6283, 120.3712, 106056652.0]
139 ['Nov 2009', 439498.0, 897113.0, 244.1159, 119.593, 107288462.0]
140 ['Dec 2009', 450032.0, 953096.0, 246.2115, 116.2559, 110803039.0]
141 ['Jan 2010', 458709.0, 969639.0, 243.9087, 115.3863, 111883099.0]
142 ['Feb 2010', 462941.0, 928849.0, 245.5, 122.3579, 113651998.0]
143 ['Mar 2010', 472155.0, 942453.0, 244.5491, 122.5155, 115465093.0]
144 ['Apr 2010', 479400.0, 956159.0, 243.3695, 122.0208, 116671315.0]
145 ['May 2010', 486811.0, 970402.0, 242.7522, 121.7788, 118174436.0]
146 ['Jun 2010', 494192.0, 979660.0, 241.3161, 121.7325, 119256489.0]
147 ['Jul 2010', 500290.0, 988703.0, 241.7791, 122.3417, 120959641.0]
148 ['Aug 2010', 507296.0, 998372.0, 241.2706, 122.5952, 122395620.0]
149 ['Sep 2010', 513308.0, 1006518.0, 241.5317, 123.1773, 123980140.0]
150 ['Total', 474700.75, 956003.6667, 243.414, 120.8665, 1386585984.0]
151 ['', '', '', '', '', '']
152 ['', '', '', '', '', '']
153 ['Outlying Areas', '', '', '', '', '']
154 [' No data found.', '', '', '', '', '']
155 ['', '', '', '', '', '']
156 ['', '', '', '', '', '']
157 ['WRO', '', '', '', '', '']
158 ['Oct 2009', 2755766.0, 6159908.0, 311.7338, 139.4608, 859065409.0]
159 ['Nov 2009', 2800204.0, 6257940.0, 309.8243, 138.6353, 867571123.0]
160 ['Dec 2009', 2864916.0, 6432670.0, 312.0086, 138.9592, 893878553.0]
161 ['Jan 2010', 2907274.0, 6518901.0, 308.5899, 137.6237, 897155499.0]
162 ['Feb 2010', 2936454.0, 6528826.0, 308.4036, 138.7099, 905613045.0]
163 ['Mar 2010', 2988467.0, 6615505.0, 308.0871, 139.1743, 920708206.0]
164 ['Apr 2010', 3017934.0, 6671914.0, 306.4132, 138.6011, 924734726.0]
165 ['May 2010', 3053363.0, 6743900.0, 306.3761, 138.7146, 935477297.0]
166 ['Jun 2010', 3095224.0, 6815470.0, 304.4971, 138.2864, 942486646.0]
167 ['Jul 2010', 3143577.0, 6907023.0, 305.6175, 139.095, 960732145.0]
168 ['Aug 2010', 3189910.0, 6992292.0, 304.9772, 139.1317, 972849814.0]
169 ['Sep 2010', 3223370.0, 7052844.0, 304.4025, 139.1215, 981201968.0]
170 ['Total', 2998038.25, 6641432.75, 307.4642, 138.7938, 11061474431.0]
171 ['', '', '', '', '', '']
172 ['', '', '', '', '', '']
173 ['1. FNS-388 data. Totals are averaged.', '', '', '', '', '']
174 ['ALL DATA SUBJECT TO REVISION', '', '', '', '', '']

In [544]:
for i in range(5, sheet.nrows):#Start at 7 b/c data starts here
    
    #RULES: 
    
    row = sheet.row_values(i)
    
    if i in [5,21,25,41,57,73,89,105,121,137,153,157]:
        #for the rows that have the state names
        state = row[0]
        if state == 'WRO':
            break
        else:
            continue         
    if i in [18,23,38,54,70,86,102,118,134,150,155,170]:
        
        snap_data[state] = {
        'household_participation': row[1],
        'individual_participation': row[2],
        'total_cost' : row[5],
        'cost_by_household' : row[3],
        'cost_by_individual': row[4],
        }

In [545]:
pprint.pprint(snap_data)

{'Alabama': {'cost_by_household': 296.3219,
             'cost_by_individual': 126.902,
             'household_participation': 344787.9167,
             'individual_participation': 805095.1667,
             'total_cost': 1226018708.0},
 'Alaska': {'cost_by_household': 436.4027,
            'cost_by_individual': 173.7781,
            'household_participation': 30440.9167,
            'individual_participation': 76445.1667,
            'total_cost': 159413978.0},
 'American Samoa': {'cost_by_household': '',
                    'cost_by_individual': '',
                    'household_participation': '',
                    'individual_participation': '',
                    'total_cost': ''},
 'Arizona': {'cost_by_household': 301.1363,
             'cost_by_individual': 129.9473,
             'household_participation': 439364.1667,
             'individual_participation': 1018170.6667,
             'total_cost': 1587702249.0},
 'Arkansas': {'cost_by_household': 289.4384,
              'cost_by_individual': 122.5896,
              'household_participation': 197624.25,
              'individual_participation': 466597.75,
              'total_cost': 686400617.0},
 'California': {'cost_by_household': 340.9048,
                'cost_by_individual': 146.461,
                'household_participation': 1391359.25,
                'individual_participation': 3238547.9167,
                'total_cost': 5691851784.0},
 'Colorado': {'cost_by_household': 325.0859,
              'cost_by_individual': 141.6164,
              'household_participation': 176289.1667,
              'individual_participation': 404678.5,
              'total_cost': 687709379.0},
 'Connecticut': {'cost_by_household': 263.0662,
                 'cost_by_individual': 141.2637,
                 'household_participation': 180462.9167,
                 'individual_participation': 336064.4167,
                 'total_cost': 569684382.0},
 'Delaware': {'cost_by_household': 282.3953,
              'cost_by_individual': 126.7669,
              'household_participation': 50507.0,
              'individual_participation': 112513.0833,
              'total_cost': 171155272.0},
 'District of Columbia': {'cost_by_household': 247.2195,
                          'cost_by_individual': 137.7672,
                          'household_participation': 66032.1667,
                          'individual_participation': 118492.9167,
                          'total_cost': 195893308.0},
 'Florida': {'cost_by_household': 268.5601,
             'cost_by_individual': 141.3954,
             'household_participation': 1370563.25,
             'individual_participation': 2603185.25,
             'total_cost': 4416942533.0},
 'Georgia': {'cost_by_household': 313.5372,
             'cost_by_individual': 134.3517,
             'household_participation': 681782.25,
             'individual_participation': 1591078.25,
             'total_cost': 2565169527.0},
 'Guam': {'cost_by_household': 694.9283,
          'cost_by_individual': 218.2197,
          'household_participation': 11595.3333,
          'individual_participation': 36925.75,
          'total_cost': 96695105.0},
 'Hawaii': {'cost_by_household': 430.0398,
            'cost_by_individual': 216.0113,
            'household_participation': 69401.5,
            'individual_participation': 138165.9167,
            'total_cost': 358144853.0},
 'Idaho': {'cost_by_household': 318.4901,
           'cost_by_individual': 128.6514,
           'household_participation': 78378.1667,
           'individual_participation': 194033.3333,
           'total_cost': 299552014.0},
 'Illinois': {'cost_by_household': 299.3985,
              'cost_by_individual': 140.9956,
              'household_participation': 775019.0,
              'individual_participation': 1645722.0833,
              'total_cost': 2784473892.0},
 'Indiana': {'cost_by_household': 309.3484,
             'cost_by_individual': 132.2863,
             'household_participation': 347834.6667,
             'individual_participation': 813403.4167,
             'total_cost': 1291225153.0},
 'Iowa': {'cost_by_household': 280.0965,
          'cost_by_individual': 128.8357,
          'household_participation': 156529.1667,
          'individual_participation': 340303.6667,
          'total_cost': 526119310.0},
 'Kansas': {'cost_by_household': 272.9106,
            'cost_by_individual': 124.4025,
            'household_participation': 122943.3333,
            'individual_participation': 269709.5833,
            'total_cost': 402630483.0},
 'Kentucky': {'cost_by_household': 279.8702,
              'cost_by_individual': 127.0477,
              'household_participation': 353226.5833,
              'individual_participation': 778113.9167,
              'total_cost': 1186291238.0},
 'Louisiana': {'cost_by_household': 303.2102,
               'cost_by_individual': 129.7747,
               'household_participation': 353494.75,
               'individual_participation': 825917.9167,
               'total_cost': 1286198597.0},
 'Maine': {'cost_by_household': 259.8253,
           'cost_by_individual': 129.1718,
           'household_participation': 114210.5,
           'individual_participation': 229731.0,
           'total_cost': 356097335.0},
 'Maryland': {'cost_by_household': 275.2659,
              'cost_by_individual': 130.4535,
              'household_participation': 265796.25,
              'individual_participation': 560848.3333,
              'total_cost': 877975713.0},
 'Massachusetts': {'cost_by_household': 238.5418,
                   'cost_by_individual': 129.6974,
                   'household_participation': 407303.8333,
                   'individual_participation': 749120.5,
                   'total_cost': 1165907744.0},
 'Michigan': {'cost_by_household': 270.4349,
              'cost_by_individual': 131.7653,
              'household_participation': 865508.25,
              'individual_participation': 1776367.9167,
              'total_cost': 2808763231.0},
 'Minnesota': {'cost_by_household': 248.189,
               'cost_by_individual': 121.0048,
               'household_participation': 209815.5,
               'individual_participation': 430345.75,
               'total_cost': 624886794.0},
 'Mississippi': {'cost_by_household': 284.517,
                 'cost_by_individual': 122.5437,
                 'household_participation': 247947.3333,
                 'individual_participation': 575674.3333,
                 'total_cost': 846542922.0},
 'Missouri': {'cost_by_household': 277.5558,
              'cost_by_individual': 125.8577,
              'household_participation': 408716.9167,
              'individual_participation': 901349.25,
              'total_cost': 1361300993.0},
 'Montana': {'cost_by_household': 287.6382,
             'cost_by_individual': 129.5433,
             'household_participation': 51148.1667,
             'individual_participation': 113569.5,
             'total_cost': 176546027.0},
 'Nebraska': {'cost_by_household': 280.6585,
              'cost_by_individual': 121.5976,
              'household_participation': 70541.5833,
              'individual_participation': 162816.5833,
              'total_cost': 237577180.0},
 'Nevada': {'cost_by_household': 267.8702,
            'cost_by_individual': 124.2324,
            'household_participation': 128979.25,
            'individual_participation': 278105.4167,
            'total_cost': 414596369.0},
 'New Hampshire': {'cost_by_household': 255.3866,
                   'cost_by_individual': 121.2082,
                   'household_participation': 49537.25,
                   'individual_participation': 104375.3333,
                   'total_cost': 151813784.0},
 'New Jersey': {'cost_by_household': 282.6454,
                'cost_by_individual': 138.03,
                'household_participation': 303764.8333,
                'individual_participation': 622022.25,
                'total_cost': 1030292837.0},
 'New Mexico': {'cost_by_household': 299.415,
                'cost_by_individual': 126.5352,
                'household_participation': 150795.8333,
                'individual_participation': 356821.9167,
                'total_cost': 541806403.0},
 'New York': {'cost_by_household': 283.9166,
              'cost_by_individual': 150.6284,
              'household_participation': 1463135.3333,
              'individual_participation': 2757836.0,
              'total_cost': 4984900302.0},
 'North Carolina': {'cost_by_household': 282.4639,
                    'cost_by_individual': 128.2421,
                    'household_participation': 611325.0833,
                    'individual_participation': 1346494.8333,
                    'total_cost': 2072127398.0},
 'North Dakota': {'cost_by_household': 290.7595,
                  'cost_by_individual': 132.2109,
                  'household_participation': 27231.75,
                  'individual_participation': 59888.3333,
                  'total_cost': 95014675.0},
 'Ohio': {'cost_by_household': 303.2182,
          'cost_by_individual': 141.7223,
          'household_participation': 751298.8333,
          'individual_participation': 1607422.0,
          'total_cost': 2733689660.0},
 'Oklahoma': {'cost_by_household': 298.3958,
              'cost_by_individual': 128.708,
              'household_participation': 251247.8333,
              'individual_participation': 582491.5,
              'total_cost': 899655548.0},
 'Oregon': {'cost_by_household': 237.8451,
            'cost_by_individual': 126.1087,
            'household_participation': 373818.9167,
            'individual_participation': 705034.9167,
            'total_cost': 1066932095.0},
 'Outlying Areas': {'cost_by_household': '',
                    'cost_by_individual': '',
                    'household_participation': '',
                    'individual_participation': '',
                    'total_cost': ''},
 'Pennsylvania': {'cost_by_household': 262.6114,
                  'cost_by_individual': 123.4337,
                  'household_participation': 740185.8333,
                  'individual_participation': 1574782.5,
                  'total_cost': 2332575204.0},
 'Puerto Rico': {'cost_by_household': '',
                 'cost_by_individual': '',
                 'household_participation': '',
                 'individual_participation': '',
                 'total_cost': ''},
 'Rhode Island': {'cost_by_household': 271.8506,
                  'cost_by_individual': 142.492,
                  'household_participation': 72839.75,
                  'individual_participation': 138965.9167,
                  'total_cost': 237618372.0},
 'South Carolina': {'cost_by_household': 291.2095,
                    'cost_by_individual': 131.3389,
                    'household_participation': 359505.9167,
                    'individual_participation': 797109.75,
                    'total_cost': 1256298352.0},
 'South Dakota': {'cost_by_household': 318.4786,
                  'cost_by_individual': 133.8035,
                  'household_participation': 40053.8333,
                  'individual_participation': 95336.0,
                  'total_cost': 153075454.0},
 'Tennessee': {'cost_by_household': 285.5765,
               'cost_by_individual': 133.8556,
               'household_participation': 573724.75,
               'individual_participation': 1224023.0,
               'total_cost': 1966107581.0},
 'Texas': {'cost_by_household': 322.6177,
           'cost_by_individual': 127.8163,
           'household_participation': 1407082.6667,
           'individual_participation': 3551580.6667,
           'total_cost': 5447397414.0},
 'Utah': {'cost_by_household': 309.4524,
          'cost_by_individual': 123.5839,
          'household_participation': 98804.5,
          'individual_participation': 247405.1667,
          'total_cost': 366903456.0},
 'Vermont': {'cost_by_household': 244.1259,
             'cost_by_individual': 121.1076,
             'household_participation': 42434.3333,
             'individual_participation': 85538.1667,
             'total_cost': 124311833.0},
 'Virgin Islands': {'cost_by_household': 439.7862,
                    'cost_by_individual': 176.2159,
                    'household_participation': 8145.0,
                    'individual_participation': 20327.6667,
                    'total_cost': 42984699.0},
 'Virginia': {'cost_by_household': 277.1868,
              'cost_by_individual': 128.6316,
              'household_participation': 364825.0833,
              'individual_participation': 786157.25,
              'total_cost': 1213496417.0},
 'Washington': {'cost_by_household': 243.414,
                'cost_by_individual': 120.8665,
                'household_participation': 474700.75,
                'individual_participation': 956003.6667,
                'total_cost': 1386585984.0},
 'West Virginia': {'cost_by_household': 261.9878,
                   'cost_by_individual': 118.9436,
                   'household_participation': 154886.1667,
                   'individual_participation': 341155.75,
                   'total_cost': 486939521.0},
 'Wisconsin': {'cost_by_household': 262.9989,
               'cost_by_individual': 116.5732,
               'household_participation': 317015.25,
               'individual_participation': 715213.1667,
               'total_cost': 1000496070.0},
 'Wyoming': {'cost_by_household': 297.5429,
             'cost_by_individual': 123.7461,
             'household_participation': 14472.6667,
             'individual_participation': 34799.0,
             'total_cost': 51674879.0}}

In [546]:
snap_data_2010 = pd.DataFrame.from_dict(snap_data, orient = "index")

In [547]:
pd.DataFrame.to_csv(snap_data_2010,'SNAP/SNAP DFs/snap_2010_df.csv')